/* $Id$ */

/* .top is made by the Makefile before building anything */
include(".top")

/* when overriding, ld.so doesn't know where to find libraries */
/* this is even more true if we want to move the binaries or */
/* clean.. */

if defined("pm3_version") 
      	/* Polytechnique de Montreal Modula-3 */
	option("shared_lib","")
	option("optimization","T")
else
 if defined("CM3_VERSION")
      	/* Critical Mass Modula-3 */
% see http://www.elegosoft.com/cm3/doc/help/cm3/cm3.html
%     build_standalone()
 else 
	/* SRC Modula-3 */
	m3_option ("-X2@-static@")
 end
end

/* these are the packages that are part of this distribution */

override("prsparse",TOP)
override("magic",TOP)
override("magicextras",TOP)
override("cit_common",TOP)
override("cit_util",TOP)
override("bdd",TOP)
override("cptr",TOP)
override("bool",TOP)
override("sop",TOP)
override("boxes",TOP)
override("simplegrid",TOP)
override("router",TOP)
override("term",TOP)
override("m3-3",TOP)
override("klay",TOP)
override("paneman",TOP)
override("parserlib",TOP & "/parserlib")
override("ktoklib",TOP & "/parserlib")
override("cit_parse",TOP)
override("drawcontext",TOP)
override("dcpane",TOP & "/drawcontext")
override("tasks",TOP)
override("matrix",TOP)
override("layout",TOP)
override("minimize",TOP)
override("convex",TOP)
override("splines",TOP)
override("integrate",TOP)
override("softmax",TOP)
override("pattern",TOP)
override("gatematrix",TOP)
override("angbrmacro",TOP)
override("defmacro",TOP)
override("colc",TOP)
override("tree",TOP)
override("magandspice",TOP & "/mika/vconv/mag")
override("celldb",TOP)
override("sysiphus_parse",TOP & "/sysiphus")
override("sysiphus_lib",TOP & "/sysiphus")
override("finlib",TOP & "/calarm")
override("keylib",TOP & "/calarm")
override("matcher",TOP)
override("optree",TOP)
override("operators", TOP)
override("rsa",TOP)
override("tuple",TOP & "/verif")
override("ld2layout", TOP)
override("gdsII", TOP)
override("voronoi", TOP)
override("color", TOP)
override("mst", TOP)
override("ld", TOP)
override("ld_parse", TOP & "/ld")
override("cast", TOP)
override("cs2", TOP & "/cs2")
override("pro", TOP)
override("gnuplot", TOP)
override("rdwr", TOP)
override("commandrw", TOP)
override("m3curses", TOP)
override("xmlparse", TOP)
override("stabletable", TOP)

override("anova", TOP & "/calarm")
override("wavelets", TOP & "/calarm")
override("htmltable", TOP & "/calarm")
override("postgresql", TOP & "/calarm")
override("twslib", TOP & "/calarm")
override("regresslib", TOP & "/calarm")
override("regressparsing", TOP & "/calarm/regress")
override("traderulelib", TOP & "/calarm")
override("smarttraderule", TOP & "/calarm")
override("fasthf", TOP & "/calarm")
override("fastrw", TOP & "/calarm")
override("sx", TOP & "/calarm")
override("hftrading", TOP & "/calarm")
override("m3gen", TOP & "/calarm")
override("readline", TOP & "/calarm")
override("excelrtd", TOP & "/calarm")
override("mktsim", TOP & "/calarm")
override("gnuplotter", TOP & "/calarm/anova")

% FIX stuff...
override("fixcommon", TOP & "/calarm/fix")
override("fix40", TOP & "/calarm/fix")
override("fix41", TOP & "/calarm/fix")
override("fix42", TOP & "/calarm/fix")
override("fix43", TOP & "/calarm/fix")
override("fix44", TOP & "/calarm/fix")

%override("testtrade2", TOP & "/calarm/twslib")  % broken up into the following libraries...
override("twslogger", TOP & "/calarm/twslib")
override("inventory", TOP & "/calarm/twslib/testtrade2")
override("tradecore", TOP & "/calarm/twslib/testtrade2")
override("fixmonitor", TOP & "/calarm/twslib/testtrade2")
override("twsmonitor", TOP & "/calarm/twslib/testtrade2")
override("tradingstrategy", TOP & "/calarm/twslib/testtrade2")
