import ("libm3")
import ("cit_util")
import ("parseparams")
import ("voronoi")

module ("VSeq")
table ("VSeqRef", "VSeq", "Refany")
module ("Triangle")
mkSet("Triangle","Triangle")
mkSetDef("Triangle","Triangle")
table("TriangleRef","Triangle","Refany")
sequence("Triangle","Triangle")

implementation ("VPlot")

program ("vplot")
