import ("libm3")
import ("cit_util")
import ("spicelib")
import ("tracelib")

Interface ("Transition")
Sequence ("Transition", "Transition")
Module ("TransitionFinder")

Table("TextTransitionSeq", "Text", "TransitionSeq")
Table("CardTransitionSeq", "Cardinal", "TransitionSeq")

Module ("CheckDir")
Interface ("CheckMode")

implementation ("Main")

program ("spicetiming")


