import ("libm3")
import ("cit_util")
import ("spicelib")
import ("tracelib")
import ("metalib")

Module ("CheckDir")
Interface ("CheckMode")
Module ("MarginScenario")

Module ("MarginMeasurement")
Array_sort ("MarginMeasurement", "MarginMeasurement")
Sequence ("MarginMeasurement", "MarginMeasurement")
Module ("MarginDump")

Table("CheckDirRef", "CheckDir", "Refany")
MkSet("CheckDir", "CheckDir")
MkSetDef("CheckDir", "CheckDir")

implementation ("Main")

program ("spicetiming")


