import ("libm3")
import ("cit_util")
import ("spicelib")
import ("tracelib")
import ("metalib")
import ("techc")

implementation ("LowTemp")

interface ("Simulation")
sequence ("Simulation", "Simulation")

program ("lowtemp")


