# Extract AFL checks

#Clock
    clock mby_primary_clock
    clock mby_secondary_clock

#Reset expression
    reset mby_primary_reset
    reset mby_secondary_reset

set_prove_per_property_time_limit 10s
set_prove_per_property_time_limit_factor 2
set_prove_time_limit 5m
set_engine_mode {Hp Ht Bm J Q3 L R B N}

check_afl -extract

# Export AFL checks to FPV (in order to be proved)
check_afl -export

# Prove properties generated by AFL
foreach task [task -list] {
  prove -bg -task $task
}
