import ("libm3")
import ("cit_util")
import ("spicelib")
import ("tracelib")
import ("regression")
import ("ctlib")
import ("spicecompress")
import ("mscheme")
import ("modula3scheme")
import ("sstubgen")
import ("minimize")
import ("integrate")

implementation ("PowerAnal")

Table        ("TextTextLR", "Text", "TextLongRealTbl")
Sorted_table ("TextTextLR", "Text", "TextLongRealTbl")

Sorted_table ("TextLongReal", "Text", "LongrealType")

Table        ("TextSortedTextLR", "Text", "SortedTextLongRealTbl")
Sorted_table ("TextSortedTextLR", "Text", "SortedTextLongRealTbl")

Table        ("TextTextSeq", "Text", "TextSeq")
Sorted_table ("TextTextSeq", "Text", "TextSeq")

program ("poweranal")
