# FocalPoint SDK Top-Level Makefile

# Do not use make's built-in rules 
MAKEFLAGS += -r

# Default platform is the FocalPoint 2000 series EP
ifeq ($(PLATFORM),)
 PLATFORM:=fm2224ep
endif

# Include the makefile fragment that builds the core SDK
include ../build/Makefile.core
