import ("libm3")
import ("cit_util")
import ("parseparams")
import ("simpletoken")

%if defined("CM3_VERSION")
%        m3_optimize("T")
%end

implementation ("Main")

interface ("BnfDefs")
module ("BnfTokenizer")
interface ("BnfTokenizer")

module ("Bnf")

table ("TextBnf", "Text", "Bnf")
sequence ("Bnf", "Bnf")

table ("CharText", "Char", "Text")
module ("CharNames")

program ("bnfgrammar")


