
expression=
		primary | binary_expression;


binary_expression=
		(expression, "+", expression)
        ;

primary=
	       "field",
	        [expression, [":", expression]]
                ;
                
