import ("libm3")
import ("cit_util")
import ("parseparams")
import ("spicelib")
import ("spicebuilderlib")

genMain("TcamAndrew", "TcamSimulation")
genMain("TcamSDG64", "TcamSimulationSDG64")

implementation ("Main")

program ("spicebuilder")
