import ("libm3")
import ("cit_util")
import ("parseparams")
import ("mscheme")
import ("mysql")
import ("modula3scheme")
import ("sstubgen")
import ("htmltable")

SchemeStubs ("TextWr")
SchemeStubs ("FileWr")
SchemeStubs ("Wr")
SchemeStubs ("FileRd")
SchemeStubs ("Rd")
SchemeStubs ("SchemeEnvironment")
SchemeStubs ("Fmt")
SchemeStubs ("Database")
%SchemeStubs ("MySQL")  % pulls in UNTRACED stuff, won't work 

ExportSchemeStubs("testhtml")
importSchemeStubs()

implementation ("Main")

program ("testhtml")


