% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("cit_util")
import ("parseparams")
import ("tracelib")
import ("mscheme")
import ("schemagraph")
import ("modula3scheme")
import ("sstubgen")
import ("newuoa")
import ("cobyla")
import ("normaldev")

implementation ("Main")

program ("exampleprog")
