import ("libm3")
import ("cit_util")
import ("parseparams")
import ("spicelib")
import ("arithcode")
import ("regression")
import ("unsaferdwr")
import ("rep16")
import ("spicecompress")
import ("gds2cast")

module ("Tr0")
module ("DataBlock")

interface ("MyRegEx")

list ("RegEx", "MyRegEx")

%implementation ("ConvertTrace")

Module ("FsdbComms")
Module ("Fsdb")
module ("NameControl")

Module ("TraceFile")
Module ("FileNamer")
Module ("TempReader")

Table("TextCardSeq", "Text", "CardSeq")

Module ("TempDataRep")

Table ("TextCardSet", "Text", "CardSet")
Table ("CardTextSet", "Cardinal", "TextSet")

% spicecompress library below here

m3_optimize("T")

sequence ("CardPair", "CardPair")

Interface ("ArithConstants")

Module ("ZtraceFile")
Module ("ZtraceNodeHeader")
Sequence ("ZtraceNodeHeader", "ZtraceNodeHeader")

% names handling:

Sequence ("TextSeq", "TextSeq")

library ("ctlib")
