import ("libm3")
import ("cit_util")
import ("parseparams")
import ("spicelib")
import ("arithcode")
import ("regression")
import ("tracelib")

%m3_optimize("T")

module ("UnsafeWriter")
module ("UnsafeReader")
module ("Tr0")
module ("DataBlock")

c_source("transfer")

interface("TransferC")

interface ("MyRegEx")

list ("RegEx", "MyRegEx")

%implementation ("ConvertTrace")

module ("Fsdb")
module ("NameControl")

Module ("TraceFile")
Module ("FileNamer")
Module ("TempReader")

Table("TextCardSeq", "Text", "CardSeq")

module ("TempDataRep")

% spicecompress library below here

m3_optimize("T")

Module ("SpiceCompress")
Module ("Wavelet")
Module ("SparseLR")
Array_sort ("Sparse", "SparseLR")

sequence ("CardPair", "CardPair")

Interface ("PolySegment")
Sequence ("PolySegment", "PolySegment")

Interface ("PolySegment16")
Sequence ("PolySegment16", "PolySegment16")

Module ("Rep16")
Module ("Rep16Stream")
Module ("PolySegment16Serial")

Table("TripleRef", "IntTriple", "Refany")

Interface ("ArithConstants")

library ("ctlib")
