// Autogenerated Jamon proxy
// /nfs/site/disks/wdisk.53/kedunckl/p4wd/reg-main-1/shared/java/src/./com/fulcrummicro/hw/verification/lib/constants/TemplateVerilog.jamon

package com.fulcrummicro.hw.verification.lib.constants;

// 2, 1
import java.util.Collection;
// 3, 1
import com.fulcrummicro.util.misc.Utility;
// 4, 1
import com.fulcrummicro.hw.verification.lib.constants.*;

@org.jamon.annotations.Template(
  signature = "5E06D9EB43FFFB5EC7E08EDD52C9C529",
  requiredArguments = {
    @org.jamon.annotations.Argument(name = "cells", type = "Collection<ConstantsCell>")})
public class TemplateVerilog
  extends org.jamon.AbstractTemplateProxy
{
  
  public TemplateVerilog(org.jamon.TemplateManager p_manager)
  {
     super(p_manager);
  }
  
  protected TemplateVerilog(String p_path)
  {
    super(p_path);
  }
  
  public TemplateVerilog()
  {
     super("/com/fulcrummicro/hw/verification/lib/constants/TemplateVerilog");
  }
  
  public interface Intf
    extends org.jamon.AbstractTemplateProxy.Intf
  {
    
    void renderNoFlush(final java.io.Writer jamonWriter) throws java.io.IOException;
    
  }
  public static class ImplData
    extends org.jamon.AbstractTemplateProxy.ImplData
  {
    // 7, 1
    public void setCells(Collection<ConstantsCell> cells)
    {
      // 7, 1
      m_cells = cells;
    }
    public Collection<ConstantsCell> getCells()
    {
      return m_cells;
    }
    private Collection<ConstantsCell> m_cells;
  }
  @Override
  protected org.jamon.AbstractTemplateProxy.ImplData makeImplData()
  {
    return new ImplData();
  }
  @Override public ImplData getImplData()
  {
    return (ImplData) super.getImplData();
  }
  
  
  @Override
  public org.jamon.AbstractTemplateImpl constructImpl(Class<? extends org.jamon.AbstractTemplateImpl> p_class){
    try
    {
      return p_class
        .getConstructor(new Class [] { org.jamon.TemplateManager.class, ImplData.class })
        .newInstance(new Object [] { getTemplateManager(), getImplData()});
    }
    catch (RuntimeException e)
    {
      throw e;
    }
    catch (Exception e)
    {
      throw new RuntimeException(e);
    }
  }
  
  @Override
  protected org.jamon.AbstractTemplateImpl constructImpl(){
    return new TemplateVerilogImpl(getTemplateManager(), getImplData());
  }
  public org.jamon.Renderer makeRenderer(final Collection<ConstantsCell> cells)
  {
    return new org.jamon.AbstractRenderer() {
      @Override
      public void renderTo(final java.io.Writer jamonWriter)
        throws java.io.IOException
      {
        render(jamonWriter, cells);
      }
    };
  }
  
  public void render(final java.io.Writer jamonWriter, final Collection<ConstantsCell> cells)
    throws java.io.IOException
  {
    renderNoFlush(jamonWriter, cells);
    jamonWriter.flush();
  }
  public void renderNoFlush(final java.io.Writer jamonWriter, final Collection<ConstantsCell> cells)
    throws java.io.IOException
  {
    ImplData implData = getImplData();
    implData.setCells(cells);
    Intf instance = (Intf) getTemplateManager().constructImpl(this);
    instance.renderNoFlush(jamonWriter);
    reset();
  }
  
  
}
