% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("minimize")
import ("csv")
import ("cit_util")

interface ("Measurement")
sequence ("Measurement", "Measurement")

implementation ("Main")

program ("modelopt")

