/* $Id$ */

/* 
   Copyright (c) Generation Capital Ltd., 2008.  All rights reserved.

   Author: Mika Nystrom <mika@alum.mit.edu>
*/


if defined("pm3_version")
	option("optimization","") 
else 
	m3_optimize("T")
end


import ("libm3")
import ("m3core")
import ("cit_util")
import ("scheme-lib")

Module("Scheme")
Module("SchemeProfiler")

Interface("SchemeClass")

Module("SchemePair")

Module("SchemeUtils")
implementation("SchemeUtilsFormat")

interface("SchemePrimitives")

Module("SchemeProcedure")
interface("SchemeProcedureClass")

Module("SchemeClosure")
Interface("SchemeClosureClass")

Module("SchemeMacro")

Module("SchemePrimitive")

Module("SchemeEnvironment")
interface("SchemeEnvironmentClass")
Interface("SchemeEnvironmentSuper")

Module("SchemeNavigatorEnvironment")

Module("SchemeInputPort")
Interface("SchemeInputPortClass")

Interface("SchemeObject")

Module("SchemeBoolean")

Module("SchemeLongReal")

Module("SchemeChar")

Module("SchemeSymbol")

Module("SchemeString")

Interface("SchemeVector")

Module("SchemeContinuation")

template ("sgenerics")

Module("SchemeAtRun")

Netobj("SchemeEnvironment", "Public")

Module("SchemeUnixDeps")
module("SchemeProfilerSysDep")

c_source("schemeUnixDeps")

library ("mscheme")





