import ("libm3")
import ("cit_util")

m3_optimize("T")

Module ("FreqTable")
Module ("ArithCode")
Interface ("ArithCoder")
Module ("ArithCallback")
Module ("ArithProbability")

%implementation ("TestMain")

Interface ("ArithBits")

library ("arithcode")
