% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("cit_util")

m3_optimize("T")

Module ("FreqTable")
Module ("ArithCode")
Interface ("ArithCoder")
Module ("ArithCallback")
Module ("ArithProbability")

%implementation ("TestMain")

Interface ("ArithBits")

library ("arithcode")
