% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("wm_support")

Interface("Byte")
Sequence("Byte","Byte")

Module ("NetTypes")

Module ("RdNet")
Module ("WrNet")
Module ("StructField")

Interface ("NetError")
Interface ("NetContext")

Module("ServerPacket")
implementation("ServerPacketDbg")

library ("wm_net")
