% Imports
import( "libm3" )

% Core types
module( "DepGraph" )
module( "Node" )
module( "Spec" )

% Wrapper types
module( "MyREFANY" )
module( "MyCARDINAL" )
interface( "MyBOOLEAN" )

% Lists
module( "REFANYList" )
module( "CARDINALList" )

% Tables
module( "NextCharTbl" )
module( "StyleRulesTbl" )
module( "SymbolTbl" )
module( "TypeUseTbl" )

% Main program
implementation( "Main" )
program( "test" )
