% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import("parserlib")
import("cit_util")
import("bdd")
import("parseparams")

module ("Gate")
list ("Gate", "Gate")

module ("GateExpr")
implementation ("Main")
module ("Aliases")

Token("gate")
Lexer("gate", "gate")
Parser("gate", "gate")

Table("TextGateExpr", "Text", "GateExpr")

Table("TextGate", "Text", "Gate")

Extended("gateLexStd")
Extended("gateParseStd")

Module ("Edge")
Sequence ("Edge", "Edge")

Interface("RegExIntf")
List("RegEx", "RegExIntf")

program("geneqs")
