% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("cit_util")
import ("spicelib")
import ("tracelib")
import ("metalib")
import ("techc")

module ("SpeedSample")
sequence ("SpeedSample", "SpeedSample")
array_sort("SpeedSample", "SpeedSample")

implementation ("RingOsc")

program ("ringosc")


