import ("libm3")
import ("cit_util")
import ("parseparams")

Module ("Dims")
Interface ("Sim")
Interface ("ProbeMode")
Module ("Assertion")
List ("Assertion","Assertion")

Module ("SpiceFormat")
Interface ("SpiceFileFormat")

Module ("SpiceObject")
Interface ("SpiceObjectParse")
Sequence ("SpiceObject","SpiceObject")
Interface ("SpiceCircuit")
List ("SpiceCircuit","SpiceCircuit")
Table ("TextSpiceCircuit", "Text", "SpiceCircuit")

MkSet("SpiceObject", "SpiceObject")
MkSetDef("SpiceObject", "SpiceObject")
Table("SpiceObjectRef", "SpiceObject", "Refany")
Table("TextSpiceObjectSet", "Text", "SpiceObjectSet")

library ("spicelib")
