#!/usr/intel/pkgs/perl/5.20.1/bin/perl
#--------------------------------------------------------------------------------
# INTEL CONFIDENTIAL
#
# Copyright (June 2005)2 (May 2008)3 Intel Corporation All Rights Reserved.
# The source code contained or described herein and all documents related to the
# source code ("Material") are owned by Intel Corporation or its suppliers or
# licensors. Title to the Material remains with Intel Corporation or its
# suppliers and licensors. The Material contains trade secrets and proprietary
# and confidential information of Intel or its suppliers and licensors. The
# Material is protected by worldwide copyright and trade secret laws and treaty
# provisions. No part of the Material may be used, copied, reproduced, modified,
# published, uploaded, posted, transmitted, distributed, or disclosed in any way
# without Intels prior express written permission.
#
# No license under any patent, copyright, trade secret or other intellectual
# property right is granted to or conferred upon you by disclosure or delivery
# of the Materials, either expressly, by implication, inducement, estoppel or
# otherwise. Any license under such intellectual property rights must be express
# and approved by Intel in writing.
#
#--------------------------------------------------------------------------------
use strict;
use warnings;
use Data::Dumper;
use Getopt::Long;
use Cwd;
use File::Basename;
use File::chdir;
use File::Spec;

#############################################################################
# Globals / options

my %options;
my $debug = 0;

my $date = `date`; chomp $date;
my $name = basename($0);

sub myinfo {
   my ($info) = @_;
   $info = "$name: $info";
   print "-I- $info\n";
}

sub mywarn {
   my ($warn) = @_;
   $warn = "$name: $warn";
   print "-W- $warn\n";
}

#############################################################################
# Custom "die" routine

sub mydie {
   my ($error) = @_;
   $error = "$name: $error";
   confess($error) if $debug;
   die($error);
}

#############################################################################

sub usage {
   print "$name: usage: \n";
   exit (0);
}

#############################################################################

sub create_hdl_spec {
   my ($filename_rtl, $filename_ral, $model_root, $dir)  = @_;

   my $cmd = "cd $model_root; find $dir -name rtlgen_pkg\\*.vh | grep output/sverilog";
   my $vfiles = `$cmd`;

   $cmd = "cd $model_root; find $dir -name \\*.vh | grep output/sverilog";
   $vfiles .= `$cmd`;

   $cmd = "cd $model_root; find $dir -name \\*.sv | grep output/sverilog";
   $vfiles .= `$cmd`;

   $cmd = "cd $model_root; find $dir -name \\*.sv | grep output/genpg";
   $vfiles .= `$cmd`;

   $vfiles =~ s#(.*)\n#   \"$1\",\n#g;
   chomp $vfiles;

   $cmd = "cd $model_root; find $dir -type d -name output -print";
   my $incdirs = `$cmd`;

   $cmd = "cd $model_root; find $dir -type d -name sverilog -print";
   $incdirs .= `$cmd`;

   $incdirs =~ s#(.*)\n#   \"$1\",\n#g;
   chomp $incdirs;

   ## HDLSpec for RTL files

   if (open(my $fh, ">", $filename_rtl )) {
     print $fh "## Auto-generated by $name\n";
     print $fh "\$hdl_spec = {\n";
     print $fh "   -vlog_files => [\n";
     print $fh $vfiles;
     print $fh "\n   ],\n";
     print $fh "   -vlog_incdirs => [\n";
     print $fh $incdirs;
     print $fh "\n   ],\n";
     print $fh "};\n";
     close $fh;
   } else {
      mydie "Couldn't create HDL file: $!";
   }

   ## HDLSpec for RAL files

   $cmd = "cd $model_root; find $dir -type d -name ovm -print";
   $incdirs = `$cmd`;

   $incdirs =~ s#(.*)\n#   \"$1\",\n#g;
   chomp $incdirs;

   if (open(my $fh, ">", $filename_ral )) {
     print $fh "## Auto-generated by $name\n";
     print $fh "\$hdl_spec = {\n";
     print $fh "   -vlog_incdirs => [\n";
     print $fh $incdirs;
     print $fh "\n   ],\n";
     print $fh "};\n";
     close $fh;
   } else {
      mydie "Couldn't create HDL file: $!";
   }

}

Getopt::Long::Configure("pass_through","no_ignore_case", "prefix_pattern=(--|-)");

my @optionSpec = (
  'filename_rtl=s',
  'filename_ral=s',
  'dir=s',
  'model_root=s',
  'help|h',
  'debug|d'
);

GetOptions (\%options, @optionSpec );
$debug = $options{debug} if (defined $options{debug});

usage() if ( defined $options{help} );
create_hdl_spec ($options{filename_rtl}, $options{filename_ral}, $options{model_root}, $options{dir});
