#! /bin/sh -p

#
# Copyright 2000 Asynchronous Digital Design.  All rights reserved.
#
# $Id$
#
# author: Jesse Rosenstock
#

#
# wrapper for convenient use of iosim
#   handles setting of CLASSPATH and LD_LIBRARY_PATH
#

if [ $# -lt 2 ]; then
    echo "Usage: $0 module [modules ...]  csimfile"
    exit 1
fi

CLASSPATH=$HOME/jars/jcast.jar:${IOSIM_CLASSPATH}:.
export CLASSPATH
LD_LIBRARY_PATH=/usr/intel/jars/native:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

exec /usr/intel/bin/java -Diosim.class.path="${IOSIM_CLASSPATH}:." -Xmx256M com.avlsi.tools.iosim.IOSIM "$@"
