#! /bin/zsh

# -d option to use original classpath
if [ x"$1" = x-d ]; then
    shift
else
    CLASSPATH=$HOME/jars/antlr.jar:$HOME/jars/jcast.jar
    export CLASSPATH
fi

if [ $# -lt 2 ]; then
    echo "Usage: $0 cast_file cast_cell [more]"
    exit 1
fi

CASTFILE=`cast_which $1`
if [ x"$CASTFILE" = x ]; then
    echo "Couldn't find $1"
    exit 2
fi
shift

# make cast file that instantiates cell, until we can do this in java
tmp_cast=`mktemp /tmp/jlvs.XXXXXX`
cat $CASTFILE > $tmp_cast
echo "$1 __lvs_instance__;" >> $tmp_cast

/usr/intel/bin/java -Xmx256M -DHOME="$HOME" \
    com.avlsi.tools.lvs.PrsToNet "$tmp_cast" $*
lvs_status=$?

rm -f $tmp_cast

exit $lvs_status
