% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("metalib")

m3_optimize("T")

Module("Arith")
Module("ArithP")
Module("ArithR")
Module("ArithRep")
Module("ArithOps")

Table("ArithRef", "Arith", "Refany")

Table("NodePairLongReal", "NodePair", "LongrealType")
Table("NodePairLongRealPair", "NodePair", "LongRealPair")

Module("PRS")
Interface("PRSClass")
Module("PRSimulate")
Module("Scenario")

Interface("TimingModel")
Module("Transition")
KeyPair("Transition", "Transition", "Transition")
List("Transition","Transition")
%Module("Example") % changed interpolation model, broke code
Module("Circuit")

Table("TransitionPred", "TransitionPair", "Boolean")

library ("arith")
