* source

vsrc_victim li0 0 pwl(0.0ns	 0
+ 'start+0*halfcycle-halfrise'           0
+ 'start+0*halfcycle+halfrise'           vtrue
+ 'start+1*halfcycle-halfrise'           vtrue
+ 'start+1*halfcycle+halfrise'           0
+ 'start+2*halfcycle-halfrise'           0
+ 'start+2*halfcycle+halfrise'           vtrue
+ 'start+3*halfcycle-halfrise'           vtrue
+ 'start+3*halfcycle+halfrise'           0
+ 'start+4*halfcycle-halfrise'           0
+ 'start+4*halfcycle+halfrise'           vtrue
+ 'start+5*halfcycle-halfrise'           vtrue
+ 'start+5*halfcycle+halfrise'           0
+ 'start+6*halfcycle-halfrise'           0
+ 'start+6*halfcycle+halfrise'           vtrue
+ 'start+7*halfcycle-halfrise'           vtrue
+ 'start+7*halfcycle+halfrise'           0
+ 'start+8*halfcycle-halfrise'           0
+ 'start+8*halfcycle+halfrise'           vtrue
+ 'start+9*halfcycle-halfrise'           vtrue
+ 'start+9*halfcycle+halfrise'           0
+ 'start+10*halfcycle-halfrise'           0
+ 'start+10*halfcycle+halfrise'           vtrue
+ 'start+11*halfcycle-halfrise'           vtrue
+ 'start+11*halfcycle+halfrise'           0
+ 'start+12*halfcycle-halfrise'           0
+ 'start+12*halfcycle+halfrise'           vtrue
+ 'start+13*halfcycle-halfrise'           vtrue
+ 'start+13*halfcycle+halfrise'           0
+ 'start+14*halfcycle-halfrise'           0
+ 'start+14*halfcycle+halfrise'           vtrue
+ 'start+15*halfcycle-halfrise'           vtrue
+ 'start+15*halfcycle+halfrise'           0
+ 'start+16*halfcycle-halfrise'           0
+ 'start+16*halfcycle+halfrise'           vtrue
+ 'start+17*halfcycle-halfrise'           vtrue
+ 'start+17*halfcycle+halfrise'           0
+ 'start+18*halfcycle-halfrise'           0
+ 'start+18*halfcycle+halfrise'           vtrue
+ 'start+19*halfcycle-halfrise'           vtrue
+ 'start+19*halfcycle+halfrise'           0
+ 'start+20*halfcycle-halfrise'           0
+ 'start+20*halfcycle+halfrise'           vtrue
+ 'start+21*halfcycle-halfrise'           vtrue
+ 'start+21*halfcycle+halfrise'           0
+ 'start+22*halfcycle-halfrise'           0
+ 'start+22*halfcycle+halfrise'           vtrue
+ 'start+23*halfcycle-halfrise'           vtrue
+ 'start+23*halfcycle+halfrise'           0
+ 'start+24*halfcycle-halfrise'           0
+ 'start+24*halfcycle+halfrise'           vtrue
+ 'start+25*halfcycle-halfrise'           vtrue
+ 'start+25*halfcycle+halfrise'           0
+ 'start+26*halfcycle-halfrise'           0
+ 'start+26*halfcycle+halfrise'           vtrue
+ 'start+27*halfcycle-halfrise'           vtrue
+ 'start+27*halfcycle+halfrise'           0
+ 'start+28*halfcycle-halfrise'           0
+ 'start+28*halfcycle+halfrise'           vtrue
+ 'start+29*halfcycle-halfrise'           vtrue
+ 'start+29*halfcycle+halfrise'           0
+ 'start+30*halfcycle-halfrise'           0
+ 'start+30*halfcycle+halfrise'           vtrue
+ 'start+31*halfcycle-halfrise'           vtrue
+ 'start+31*halfcycle+halfrise'           0
+ 'start+32*halfcycle-halfrise'           0
+ 'start+32*halfcycle+halfrise'           vtrue
+ 'start+33*halfcycle-halfrise'           vtrue
+ 'start+33*halfcycle+halfrise'           0
+ 'start+34*halfcycle-halfrise'           0
+ 'start+34*halfcycle+halfrise'           vtrue
+ 'start+35*halfcycle-halfrise'           vtrue
+ 'start+35*halfcycle+halfrise'           0
+ 'start+36*halfcycle-halfrise'           0
+ 'start+36*halfcycle+halfrise'           vtrue
+ 'start+37*halfcycle-halfrise'           vtrue
+ 'start+37*halfcycle+halfrise'           0
+ 'start+38*halfcycle-halfrise'           0
+ 'start+38*halfcycle+halfrise'           vtrue
+ 'start+39*halfcycle-halfrise'           vtrue
+ 'start+39*halfcycle+halfrise'           0
+ 'start+40*halfcycle-halfrise'           0
+ 'start+40*halfcycle+halfrise'           vtrue
+ 'start+41*halfcycle-halfrise'           vtrue
+ 'start+41*halfcycle+halfrise'           0
+ 'start+42*halfcycle-halfrise'           0
+ 'start+42*halfcycle+halfrise'           vtrue
+ 'start+43*halfcycle-halfrise'           vtrue
+ 'start+43*halfcycle+halfrise'           0
+ 'start+44*halfcycle-halfrise'           0
+ 'start+44*halfcycle+halfrise'           vtrue
+ 'start+45*halfcycle-halfrise'           vtrue
+ 'start+45*halfcycle+halfrise'           0
+ 'start+46*halfcycle-halfrise'           0
+ 'start+46*halfcycle+halfrise'           vtrue
+ 'start+47*halfcycle-halfrise'           vtrue
+ 'start+47*halfcycle+halfrise'           0
+ 'start+48*halfcycle-halfrise'           0
+ 'start+48*halfcycle+halfrise'           vtrue
+ 'start+49*halfcycle-halfrise'           vtrue
+ 'start+49*halfcycle+halfrise'           0
+ 'start+50*halfcycle-halfrise'           0
+ 'start+50*halfcycle+halfrise'           vtrue
+ 'start+51*halfcycle-halfrise'           vtrue
+ 'start+51*halfcycle+halfrise'           0
+ 'start+52*halfcycle-halfrise'           0
+ 'start+52*halfcycle+halfrise'           vtrue
+ 'start+53*halfcycle-halfrise'           vtrue
+ 'start+53*halfcycle+halfrise'           0
+ 'start+54*halfcycle-halfrise'           0
+ 'start+54*halfcycle+halfrise'           vtrue
+ 'start+55*halfcycle-halfrise'           vtrue
+ 'start+55*halfcycle+halfrise'           0
+ 'start+56*halfcycle-halfrise'           0
+ 'start+56*halfcycle+halfrise'           vtrue
+ 'start+57*halfcycle-halfrise'           vtrue
+ 'start+57*halfcycle+halfrise'           0
+ 'start+58*halfcycle-halfrise'           0
+ 'start+58*halfcycle+halfrise'           vtrue
+ 'start+59*halfcycle-halfrise'           vtrue
+ 'start+59*halfcycle+halfrise'           0
+ 'start+60*halfcycle-halfrise'           0
+ 'start+60*halfcycle+halfrise'           vtrue
+ 'start+61*halfcycle-halfrise'           vtrue
+ 'start+61*halfcycle+halfrise'           0
+ 'start+62*halfcycle-halfrise'           0
+ 'start+62*halfcycle+halfrise'           vtrue
+ 'start+63*halfcycle-halfrise'           vtrue
+ 'start+63*halfcycle+halfrise'           0
+ 'start+64*halfcycle-halfrise'           0
+ 'start+64*halfcycle+halfrise'           vtrue
+ 'start+65*halfcycle-halfrise'           vtrue
+ 'start+65*halfcycle+halfrise'           0
+ 'start+66*halfcycle-halfrise'           0
+ 'start+66*halfcycle+halfrise'           vtrue
+ 'start+67*halfcycle-halfrise'           vtrue
+ 'start+67*halfcycle+halfrise'           0
+ 'start+68*halfcycle-halfrise'           0
+ 'start+68*halfcycle+halfrise'           vtrue
+ 'start+69*halfcycle-halfrise'           vtrue
+ 'start+69*halfcycle+halfrise'           0
+ 'start+70*halfcycle-halfrise'           0
+ 'start+70*halfcycle+halfrise'           vtrue
+ 'start+71*halfcycle-halfrise'           vtrue
+ 'start+71*halfcycle+halfrise'           0
+ 'start+72*halfcycle-halfrise'           0
+ 'start+72*halfcycle+halfrise'           vtrue
+ 'start+73*halfcycle-halfrise'           vtrue
+ 'start+73*halfcycle+halfrise'           0
+ 'start+74*halfcycle-halfrise'           0
+ 'start+74*halfcycle+halfrise'           vtrue
+ 'start+75*halfcycle-halfrise'           vtrue
+ 'start+75*halfcycle+halfrise'           0
+ 'start+76*halfcycle-halfrise'           0
+ 'start+76*halfcycle+halfrise'           vtrue
+ 'start+77*halfcycle-halfrise'           vtrue
+ 'start+77*halfcycle+halfrise'           0
+ 'start+78*halfcycle-halfrise'           0
+ 'start+78*halfcycle+halfrise'           vtrue
+ 'start+79*halfcycle-halfrise'           vtrue
+ 'start+79*halfcycle+halfrise'           0
+ 'start+80*halfcycle-halfrise'           0
+ 'start+80*halfcycle+halfrise'           vtrue
+ 'start+81*halfcycle-halfrise'           vtrue
+ 'start+81*halfcycle+halfrise'           0
+ 'start+82*halfcycle-halfrise'           0
+ 'start+82*halfcycle+halfrise'           vtrue
+ 'start+83*halfcycle-halfrise'           vtrue
+ 'start+83*halfcycle+halfrise'           0
+ 'start+84*halfcycle-halfrise'           0
+ 'start+84*halfcycle+halfrise'           vtrue
+ 'start+85*halfcycle-halfrise'           vtrue
+ 'start+85*halfcycle+halfrise'           0
+ 'start+86*halfcycle-halfrise'           0
+ 'start+86*halfcycle+halfrise'           vtrue
+ 'start+87*halfcycle-halfrise'           vtrue
+ 'start+87*halfcycle+halfrise'           0
+ 'start+88*halfcycle-halfrise'           0
+ 'start+88*halfcycle+halfrise'           vtrue
+ 'start+89*halfcycle-halfrise'           vtrue
+ 'start+89*halfcycle+halfrise'           0
+ 'start+90*halfcycle-halfrise'           0
+ 'start+90*halfcycle+halfrise'           vtrue
+ 'start+91*halfcycle-halfrise'           vtrue
+ 'start+91*halfcycle+halfrise'           0
+ 'start+92*halfcycle-halfrise'           0
+ 'start+92*halfcycle+halfrise'           vtrue
+ 'start+93*halfcycle-halfrise'           vtrue
+ 'start+93*halfcycle+halfrise'           0
+ 'start+94*halfcycle-halfrise'           0
+ 'start+94*halfcycle+halfrise'           vtrue
+ 'start+95*halfcycle-halfrise'           vtrue
+ 'start+95*halfcycle+halfrise'           0
+ 'start+96*halfcycle-halfrise'           0
+ 'start+96*halfcycle+halfrise'           vtrue
+ 'start+97*halfcycle-halfrise'           vtrue
+ 'start+97*halfcycle+halfrise'           0
+ 'start+98*halfcycle-halfrise'           0
+ 'start+98*halfcycle+halfrise'           vtrue
+ 'start+99*halfcycle-halfrise'           vtrue
+ 'start+99*halfcycle+halfrise'           0
+ 'start+100*halfcycle-halfrise'           0
+ 'start+100*halfcycle+halfrise'           vtrue
+ 'start+101*halfcycle-halfrise'           vtrue
+ 'start+101*halfcycle+halfrise'           0
+ 'start+102*halfcycle-halfrise'           0
+ 'start+102*halfcycle+halfrise'           vtrue
+ 'start+103*halfcycle-halfrise'           vtrue
+ 'start+103*halfcycle+halfrise'           0
+ 'start+104*halfcycle-halfrise'           0
+ 'start+104*halfcycle+halfrise'           vtrue
+ 'start+105*halfcycle-halfrise'           vtrue
+ 'start+105*halfcycle+halfrise'           0
+ 'start+106*halfcycle-halfrise'           0
+ 'start+106*halfcycle+halfrise'           vtrue
+ 'start+107*halfcycle-halfrise'           vtrue
+ 'start+107*halfcycle+halfrise'           0
+ 'start+108*halfcycle-halfrise'           0
+ 'start+108*halfcycle+halfrise'           vtrue
+ 'start+109*halfcycle-halfrise'           vtrue
+ 'start+109*halfcycle+halfrise'           0
+ 'start+110*halfcycle-halfrise'           0
+ 'start+110*halfcycle+halfrise'           vtrue
+ 'start+111*halfcycle-halfrise'           vtrue
+ 'start+111*halfcycle+halfrise'           0
+ 'start+112*halfcycle-halfrise'           0
+ 'start+112*halfcycle+halfrise'           vtrue
+ 'start+113*halfcycle-halfrise'           vtrue
+ 'start+113*halfcycle+halfrise'           0
+ 'start+114*halfcycle-halfrise'           0
+ 'start+114*halfcycle+halfrise'           vtrue
+ 'start+115*halfcycle-halfrise'           vtrue
+ 'start+115*halfcycle+halfrise'           0
+ 'start+116*halfcycle-halfrise'           0
+ 'start+116*halfcycle+halfrise'           vtrue
+ 'start+117*halfcycle-halfrise'           vtrue
+ 'start+117*halfcycle+halfrise'           0
+ 'start+118*halfcycle-halfrise'           0
+ 'start+118*halfcycle+halfrise'           vtrue
+ 'start+119*halfcycle-halfrise'           vtrue
+ 'start+119*halfcycle+halfrise'           0
+ 'start+120*halfcycle-halfrise'           0
+ 'start+120*halfcycle+halfrise'           vtrue
+ 'start+121*halfcycle-halfrise'           vtrue
+ 'start+121*halfcycle+halfrise'           0
+ 'start+122*halfcycle-halfrise'           0
+ 'start+122*halfcycle+halfrise'           vtrue
+ 'start+123*halfcycle-halfrise'           vtrue
+ 'start+123*halfcycle+halfrise'           0
+ 'start+124*halfcycle-halfrise'           0
+ 'start+124*halfcycle+halfrise'           vtrue
+ 'start+125*halfcycle-halfrise'           vtrue
+ 'start+125*halfcycle+halfrise'           0
+ 'start+126*halfcycle-halfrise'           0
+ 'start+126*halfcycle+halfrise'           vtrue
+ 'start+127*halfcycle-halfrise'           vtrue
+ 'start+127*halfcycle+halfrise'           0
+ 'start+128*halfcycle-halfrise'           0
+ 'start+128*halfcycle+halfrise'           vtrue
+ 'start+129*halfcycle-halfrise'           vtrue
+ 'start+129*halfcycle+halfrise'           0
+ 'start+130*halfcycle-halfrise'           0
+ 'start+130*halfcycle+halfrise'           vtrue
+ 'start+131*halfcycle-halfrise'           vtrue
+ 'start+131*halfcycle+halfrise'           0
+ 'start+132*halfcycle-halfrise'           0
+ 'start+132*halfcycle+halfrise'           vtrue
+ 'start+133*halfcycle-halfrise'           vtrue
+ 'start+133*halfcycle+halfrise'           0
+ 'start+134*halfcycle-halfrise'           0
+ 'start+134*halfcycle+halfrise'           vtrue
+ 'start+135*halfcycle-halfrise'           vtrue
+ 'start+135*halfcycle+halfrise'           0
+ 'start+136*halfcycle-halfrise'           0
+ 'start+136*halfcycle+halfrise'           vtrue
+ 'start+137*halfcycle-halfrise'           vtrue
+ 'start+137*halfcycle+halfrise'           0
+ 'start+138*halfcycle-halfrise'           0
+ 'start+138*halfcycle+halfrise'           vtrue
+ 'start+139*halfcycle-halfrise'           vtrue
+ 'start+139*halfcycle+halfrise'           0
+ 'start+140*halfcycle-halfrise'           0
+ 'start+140*halfcycle+halfrise'           vtrue
+ 'start+141*halfcycle-halfrise'           vtrue
+ 'start+141*halfcycle+halfrise'           0
+ 'start+142*halfcycle-halfrise'           0
+ 'start+142*halfcycle+halfrise'           vtrue
+ 'start+143*halfcycle-halfrise'           vtrue
+ 'start+143*halfcycle+halfrise'           0
+ 'start+144*halfcycle-halfrise'           0
+ 'start+144*halfcycle+halfrise'           vtrue
+ 'start+145*halfcycle-halfrise'           vtrue
+ 'start+145*halfcycle+halfrise'           0
+ 'start+146*halfcycle-halfrise'           0
+ 'start+146*halfcycle+halfrise'           vtrue
+ 'start+147*halfcycle-halfrise'           vtrue
+ 'start+147*halfcycle+halfrise'           0
+ 'start+148*halfcycle-halfrise'           0
+ 'start+148*halfcycle+halfrise'           vtrue
+ 'start+149*halfcycle-halfrise'           vtrue
+ 'start+149*halfcycle+halfrise'           0
+ 'start+150*halfcycle-halfrise'           0
+ 'start+150*halfcycle+halfrise'           vtrue
+ 'start+151*halfcycle-halfrise'           vtrue
+ 'start+151*halfcycle+halfrise'           0
+ 'start+152*halfcycle-halfrise'           0
+ 'start+152*halfcycle+halfrise'           vtrue
+ 'start+153*halfcycle-halfrise'           vtrue
+ 'start+153*halfcycle+halfrise'           0
+ 'start+154*halfcycle-halfrise'           0
+ 'start+154*halfcycle+halfrise'           vtrue
+ 'start+155*halfcycle-halfrise'           vtrue
+ 'start+155*halfcycle+halfrise'           0
+ 'start+156*halfcycle-halfrise'           0
+ 'start+156*halfcycle+halfrise'           vtrue
+ 'start+157*halfcycle-halfrise'           vtrue
+ 'start+157*halfcycle+halfrise'           0
+ 'start+158*halfcycle-halfrise'           0
+ 'start+158*halfcycle+halfrise'           vtrue
+ 'start+159*halfcycle-halfrise'           vtrue
+ 'start+159*halfcycle+halfrise'           0
+ 'start+160*halfcycle-halfrise'           0
+ 'start+160*halfcycle+halfrise'           vtrue
+ 'start+161*halfcycle-halfrise'           vtrue
+ 'start+161*halfcycle+halfrise'           0
+ 'start+162*halfcycle-halfrise'           0
+ 'start+162*halfcycle+halfrise'           vtrue
+ 'start+163*halfcycle-halfrise'           vtrue
+ 'start+163*halfcycle+halfrise'           0
+ 'start+164*halfcycle-halfrise'           0
+ 'start+164*halfcycle+halfrise'           vtrue
+ 'start+165*halfcycle-halfrise'           vtrue
+ 'start+165*halfcycle+halfrise'           0
+ 'start+166*halfcycle-halfrise'           0
+ 'start+166*halfcycle+halfrise'           vtrue
+ 'start+167*halfcycle-halfrise'           vtrue
+ 'start+167*halfcycle+halfrise'           0
+ 'start+168*halfcycle-halfrise'           0
+ 'start+168*halfcycle+halfrise'           vtrue
+ 'start+169*halfcycle-halfrise'           vtrue
+ 'start+169*halfcycle+halfrise'           0
+ 'start+170*halfcycle-halfrise'           0
+ 'start+170*halfcycle+halfrise'           vtrue
+ 'start+171*halfcycle-halfrise'           vtrue
+ 'start+171*halfcycle+halfrise'           0
+ 'start+172*halfcycle-halfrise'           0
+ 'start+172*halfcycle+halfrise'           vtrue
+ 'start+173*halfcycle-halfrise'           vtrue
+ 'start+173*halfcycle+halfrise'           0
+ 'start+174*halfcycle-halfrise'           0
+ 'start+174*halfcycle+halfrise'           vtrue
+ 'start+175*halfcycle-halfrise'           vtrue
+ 'start+175*halfcycle+halfrise'           0
+ 'start+176*halfcycle-halfrise'           0
+ 'start+176*halfcycle+halfrise'           vtrue
+ 'start+177*halfcycle-halfrise'           vtrue
+ 'start+177*halfcycle+halfrise'           0
+ 'start+178*halfcycle-halfrise'           0
+ 'start+178*halfcycle+halfrise'           vtrue
+ 'start+179*halfcycle-halfrise'           vtrue
+ 'start+179*halfcycle+halfrise'           0
+ 'start+180*halfcycle-halfrise'           0
+ 'start+180*halfcycle+halfrise'           vtrue
+ 'start+181*halfcycle-halfrise'           vtrue
+ 'start+181*halfcycle+halfrise'           0
+ 'start+182*halfcycle-halfrise'           0
+ 'start+182*halfcycle+halfrise'           vtrue
+ 'start+183*halfcycle-halfrise'           vtrue
+ 'start+183*halfcycle+halfrise'           0
+ 'start+184*halfcycle-halfrise'           0
+ 'start+184*halfcycle+halfrise'           vtrue
+ 'start+185*halfcycle-halfrise'           vtrue
+ 'start+185*halfcycle+halfrise'           0
+ 'start+186*halfcycle-halfrise'           0
+ 'start+186*halfcycle+halfrise'           vtrue
+ 'start+187*halfcycle-halfrise'           vtrue
+ 'start+187*halfcycle+halfrise'           0
+ 'start+188*halfcycle-halfrise'           0
+ 'start+188*halfcycle+halfrise'           vtrue
+ 'start+189*halfcycle-halfrise'           vtrue
+ 'start+189*halfcycle+halfrise'           0
+ 'start+190*halfcycle-halfrise'           0
+ 'start+190*halfcycle+halfrise'           vtrue
+ 'start+191*halfcycle-halfrise'           vtrue
+ 'start+191*halfcycle+halfrise'           0
+ 'start+192*halfcycle-halfrise'           0
+ 'start+192*halfcycle+halfrise'           vtrue
+ 'start+193*halfcycle-halfrise'           vtrue
+ 'start+193*halfcycle+halfrise'           0
+ 'start+194*halfcycle-halfrise'           0
+ 'start+194*halfcycle+halfrise'           vtrue
+ 'start+195*halfcycle-halfrise'           vtrue
+ 'start+195*halfcycle+halfrise'           0
+ 'start+196*halfcycle-halfrise'           0
+ 'start+196*halfcycle+halfrise'           vtrue
+ 'start+197*halfcycle-halfrise'           vtrue
+ 'start+197*halfcycle+halfrise'           0
+ 'start+198*halfcycle-halfrise'           0
+ 'start+198*halfcycle+halfrise'           vtrue
+ 'start+199*halfcycle-halfrise'           vtrue
+ 'start+199*halfcycle+halfrise'           0
+ 'start+200*halfcycle-halfrise'           0
+ 'start+200*halfcycle+halfrise'           vtrue
+ 'start+201*halfcycle-halfrise'           vtrue
+ 'start+201*halfcycle+halfrise'           0
+ 'start+202*halfcycle-halfrise'           0
+ 'start+202*halfcycle+halfrise'           vtrue
+ 'start+203*halfcycle-halfrise'           vtrue
+ 'start+203*halfcycle+halfrise'           0
+ 'start+204*halfcycle-halfrise'           0
+ 'start+204*halfcycle+halfrise'           vtrue
+ 'start+205*halfcycle-halfrise'           vtrue
+ 'start+205*halfcycle+halfrise'           0
+ 'start+206*halfcycle-halfrise'           0
+ 'start+206*halfcycle+halfrise'           vtrue
+ 'start+207*halfcycle-halfrise'           vtrue
+ 'start+207*halfcycle+halfrise'           0
+ 'start+208*halfcycle-halfrise'           0
+ 'start+208*halfcycle+halfrise'           vtrue
+ 'start+209*halfcycle-halfrise'           vtrue
+ 'start+209*halfcycle+halfrise'           0
+ 'start+210*halfcycle-halfrise'           0
+ 'start+210*halfcycle+halfrise'           vtrue
+ 'start+211*halfcycle-halfrise'           vtrue
+ 'start+211*halfcycle+halfrise'           0
+ 'start+212*halfcycle-halfrise'           0
+ 'start+212*halfcycle+halfrise'           vtrue
+ 'start+213*halfcycle-halfrise'           vtrue
+ 'start+213*halfcycle+halfrise'           0
+ 'start+214*halfcycle-halfrise'           0
+ 'start+214*halfcycle+halfrise'           vtrue
+ 'start+215*halfcycle-halfrise'           vtrue
+ 'start+215*halfcycle+halfrise'           0
+ 'start+216*halfcycle-halfrise'           0
+ 'start+216*halfcycle+halfrise'           vtrue
+ 'start+217*halfcycle-halfrise'           vtrue
+ 'start+217*halfcycle+halfrise'           0
+ 'start+218*halfcycle-halfrise'           0
+ 'start+218*halfcycle+halfrise'           vtrue
+ 'start+219*halfcycle-halfrise'           vtrue
+ 'start+219*halfcycle+halfrise'           0
+ 'start+220*halfcycle-halfrise'           0
+ 'start+220*halfcycle+halfrise'           vtrue
+ 'start+221*halfcycle-halfrise'           vtrue
+ 'start+221*halfcycle+halfrise'           0
+ 'start+222*halfcycle-halfrise'           0
+ 'start+222*halfcycle+halfrise'           vtrue
+ 'start+223*halfcycle-halfrise'           vtrue
+ 'start+223*halfcycle+halfrise'           0
+ 'start+224*halfcycle-halfrise'           0
+ 'start+224*halfcycle+halfrise'           vtrue
+ 'start+225*halfcycle-halfrise'           vtrue
+ 'start+225*halfcycle+halfrise'           0
+ 'start+226*halfcycle-halfrise'           0
+ 'start+226*halfcycle+halfrise'           vtrue
+ 'start+227*halfcycle-halfrise'           vtrue
+ 'start+227*halfcycle+halfrise'           0
+ 'start+228*halfcycle-halfrise'           0
+ 'start+228*halfcycle+halfrise'           vtrue
+ 'start+229*halfcycle-halfrise'           vtrue
+ 'start+229*halfcycle+halfrise'           0
+ 'start+230*halfcycle-halfrise'           0
+ 'start+230*halfcycle+halfrise'           vtrue
+ 'start+231*halfcycle-halfrise'           vtrue
+ 'start+231*halfcycle+halfrise'           0
+ 'start+232*halfcycle-halfrise'           0
+ 'start+232*halfcycle+halfrise'           vtrue
+ 'start+233*halfcycle-halfrise'           vtrue
+ 'start+233*halfcycle+halfrise'           0
+ 'start+234*halfcycle-halfrise'           0
+ 'start+234*halfcycle+halfrise'           vtrue
+ 'start+235*halfcycle-halfrise'           vtrue
+ 'start+235*halfcycle+halfrise'           0
+ 'start+236*halfcycle-halfrise'           0
+ 'start+236*halfcycle+halfrise'           vtrue
+ 'start+237*halfcycle-halfrise'           vtrue
+ 'start+237*halfcycle+halfrise'           0
+ 'start+238*halfcycle-halfrise'           0
+ 'start+238*halfcycle+halfrise'           vtrue
+ 'start+239*halfcycle-halfrise'           vtrue
+ 'start+239*halfcycle+halfrise'           0
+ 'start+240*halfcycle-halfrise'           0
+ 'start+240*halfcycle+halfrise'           vtrue
+ 'start+241*halfcycle-halfrise'           vtrue
+ 'start+241*halfcycle+halfrise'           0
+ 'start+242*halfcycle-halfrise'           0
+ 'start+242*halfcycle+halfrise'           vtrue
+ 'start+243*halfcycle-halfrise'           vtrue
+ 'start+243*halfcycle+halfrise'           0
+ 'start+244*halfcycle-halfrise'           0
+ 'start+244*halfcycle+halfrise'           vtrue
+ 'start+245*halfcycle-halfrise'           vtrue
+ 'start+245*halfcycle+halfrise'           0
+ 'start+246*halfcycle-halfrise'           0
+ 'start+246*halfcycle+halfrise'           vtrue
+ 'start+247*halfcycle-halfrise'           vtrue
+ 'start+247*halfcycle+halfrise'           0
+ 'start+248*halfcycle-halfrise'           0
+ 'start+248*halfcycle+halfrise'           vtrue
+ 'start+249*halfcycle-halfrise'           vtrue
+ 'start+249*halfcycle+halfrise'           0
+ 'start+250*halfcycle-halfrise'           0
+ 'start+250*halfcycle+halfrise'           vtrue
+ 'start+251*halfcycle-halfrise'           vtrue
+ 'start+251*halfcycle+halfrise'           0
+ 'start+252*halfcycle-halfrise'           0
+ 'start+252*halfcycle+halfrise'           vtrue
+ 'start+253*halfcycle-halfrise'           vtrue
+ 'start+253*halfcycle+halfrise'           0
+ 'start+254*halfcycle-halfrise'           0
+ 'start+254*halfcycle+halfrise'           vtrue
+ 'start+255*halfcycle-halfrise'           vtrue
+ 'start+255*halfcycle+halfrise'           0
+ 'start+256*halfcycle-halfrise'           0
+ 'start+256*halfcycle+halfrise'           vtrue
+ 'start+257*halfcycle-halfrise'           vtrue
+ 'start+257*halfcycle+halfrise'           0
+ 'start+258*halfcycle-halfrise'           0
+ 'start+258*halfcycle+halfrise'           vtrue
+ 'start+259*halfcycle-halfrise'           vtrue
+ 'start+259*halfcycle+halfrise'           0
+ 'start+260*halfcycle-halfrise'           0
+ 'start+260*halfcycle+halfrise'           vtrue
+ 'start+261*halfcycle-halfrise'           vtrue
+ 'start+261*halfcycle+halfrise'           0
+ 'start+262*halfcycle-halfrise'           0
+ 'start+262*halfcycle+halfrise'           vtrue
+ 'start+263*halfcycle-halfrise'           vtrue
+ 'start+263*halfcycle+halfrise'           0
+ 'start+264*halfcycle-halfrise'           0
+ 'start+264*halfcycle+halfrise'           vtrue
+ 'start+265*halfcycle-halfrise'           vtrue
+ 'start+265*halfcycle+halfrise'           0
+ 'start+266*halfcycle-halfrise'           0
+ 'start+266*halfcycle+halfrise'           vtrue
+ 'start+267*halfcycle-halfrise'           vtrue
+ 'start+267*halfcycle+halfrise'           0
+ 'start+268*halfcycle-halfrise'           0
+ 'start+268*halfcycle+halfrise'           vtrue
+ 'start+269*halfcycle-halfrise'           vtrue
+ 'start+269*halfcycle+halfrise'           0
+ 'start+270*halfcycle-halfrise'           0
+ 'start+270*halfcycle+halfrise'           vtrue
+ 'start+271*halfcycle-halfrise'           vtrue
+ 'start+271*halfcycle+halfrise'           0
+ 'start+272*halfcycle-halfrise'           0
+ 'start+272*halfcycle+halfrise'           vtrue
+ 'start+273*halfcycle-halfrise'           vtrue
+ 'start+273*halfcycle+halfrise'           0
+ 'start+274*halfcycle-halfrise'           0
+ 'start+274*halfcycle+halfrise'           vtrue
+ 'start+275*halfcycle-halfrise'           vtrue
+ 'start+275*halfcycle+halfrise'           0
+ 'start+276*halfcycle-halfrise'           0
+ 'start+276*halfcycle+halfrise'           vtrue
+ 'start+277*halfcycle-halfrise'           vtrue
+ 'start+277*halfcycle+halfrise'           0
+ 'start+278*halfcycle-halfrise'           0
+ 'start+278*halfcycle+halfrise'           vtrue
+ 'start+279*halfcycle-halfrise'           vtrue
+ 'start+279*halfcycle+halfrise'           0
+ 'start+280*halfcycle-halfrise'           0
+ 'start+280*halfcycle+halfrise'           vtrue
+ 'start+281*halfcycle-halfrise'           vtrue
+ 'start+281*halfcycle+halfrise'           0
+ 'start+282*halfcycle-halfrise'           0
+ 'start+282*halfcycle+halfrise'           vtrue
+ 'start+283*halfcycle-halfrise'           vtrue
+ 'start+283*halfcycle+halfrise'           0
+ 'start+284*halfcycle-halfrise'           0
+ 'start+284*halfcycle+halfrise'           vtrue
+ 'start+285*halfcycle-halfrise'           vtrue
+ 'start+285*halfcycle+halfrise'           0
+ 'start+286*halfcycle-halfrise'           0
+ 'start+286*halfcycle+halfrise'           vtrue
+ 'start+287*halfcycle-halfrise'           vtrue
+ 'start+287*halfcycle+halfrise'           0
+ 'start+288*halfcycle-halfrise'           0
+ 'start+288*halfcycle+halfrise'           vtrue
+ 'start+289*halfcycle-halfrise'           vtrue
+ 'start+289*halfcycle+halfrise'           0
+ 'start+290*halfcycle-halfrise'           0
+ 'start+290*halfcycle+halfrise'           vtrue
+ 'start+291*halfcycle-halfrise'           vtrue
+ 'start+291*halfcycle+halfrise'           0
+ 'start+292*halfcycle-halfrise'           0
+ 'start+292*halfcycle+halfrise'           vtrue
+ 'start+293*halfcycle-halfrise'           vtrue
+ 'start+293*halfcycle+halfrise'           0
+ 'start+294*halfcycle-halfrise'           0
+ 'start+294*halfcycle+halfrise'           vtrue
+ 'start+295*halfcycle-halfrise'           vtrue
+ 'start+295*halfcycle+halfrise'           0
+ 'start+296*halfcycle-halfrise'           0
+ 'start+296*halfcycle+halfrise'           vtrue
+ 'start+297*halfcycle-halfrise'           vtrue
+ 'start+297*halfcycle+halfrise'           0
+ 'start+298*halfcycle-halfrise'           0
+ 'start+298*halfcycle+halfrise'           vtrue
+ 'start+299*halfcycle-halfrise'           vtrue
+ 'start+299*halfcycle+halfrise'           0
+ 'start+300*halfcycle-halfrise'           0
+ 'start+300*halfcycle+halfrise'           vtrue
+ 'start+301*halfcycle-halfrise'           vtrue
+ 'start+301*halfcycle+halfrise'           0
+ 'start+302*halfcycle-halfrise'           0
+ 'start+302*halfcycle+halfrise'           vtrue
+ 'start+303*halfcycle-halfrise'           vtrue
+ 'start+303*halfcycle+halfrise'           0
+ 'start+304*halfcycle-halfrise'           0
+ 'start+304*halfcycle+halfrise'           vtrue
+ 'start+305*halfcycle-halfrise'           vtrue
+ 'start+305*halfcycle+halfrise'           0
+ 'start+306*halfcycle-halfrise'           0
+ 'start+306*halfcycle+halfrise'           vtrue
+ 'start+307*halfcycle-halfrise'           vtrue
+ 'start+307*halfcycle+halfrise'           0
+ 'start+308*halfcycle-halfrise'           0
+ 'start+308*halfcycle+halfrise'           vtrue
+ 'start+309*halfcycle-halfrise'           vtrue
+ 'start+309*halfcycle+halfrise'           0
+ 'start+310*halfcycle-halfrise'           0
+ 'start+310*halfcycle+halfrise'           vtrue
+ 'start+311*halfcycle-halfrise'           vtrue
+ 'start+311*halfcycle+halfrise'           0
+ 'start+312*halfcycle-halfrise'           0
+ 'start+312*halfcycle+halfrise'           vtrue
+ 'start+313*halfcycle-halfrise'           vtrue
+ 'start+313*halfcycle+halfrise'           0
+ 'start+314*halfcycle-halfrise'           0
+ 'start+314*halfcycle+halfrise'           vtrue
+ 'start+315*halfcycle-halfrise'           vtrue
+ 'start+315*halfcycle+halfrise'           0
+ 'start+316*halfcycle-halfrise'           0
+ 'start+316*halfcycle+halfrise'           vtrue
+ 'start+317*halfcycle-halfrise'           vtrue
+ 'start+317*halfcycle+halfrise'           0
+ 'start+318*halfcycle-halfrise'           0
+ 'start+318*halfcycle+halfrise'           vtrue
+ 'start+319*halfcycle-halfrise'           vtrue
+ 'start+319*halfcycle+halfrise'           0
+ 'start+320*halfcycle-halfrise'           0
+ 'start+320*halfcycle+halfrise'           vtrue
+ 'start+321*halfcycle-halfrise'           vtrue
+ 'start+321*halfcycle+halfrise'           0
+ 'start+322*halfcycle-halfrise'           0
+ 'start+322*halfcycle+halfrise'           vtrue
+ 'start+323*halfcycle-halfrise'           vtrue
+ 'start+323*halfcycle+halfrise'           0
+ 'start+324*halfcycle-halfrise'           0
+ 'start+324*halfcycle+halfrise'           vtrue
+ 'start+325*halfcycle-halfrise'           vtrue
+ 'start+325*halfcycle+halfrise'           0
+ 'start+326*halfcycle-halfrise'           0
+ 'start+326*halfcycle+halfrise'           vtrue
+ 'start+327*halfcycle-halfrise'           vtrue
+ 'start+327*halfcycle+halfrise'           0
+ 'start+328*halfcycle-halfrise'           0
+ 'start+328*halfcycle+halfrise'           vtrue
+ 'start+329*halfcycle-halfrise'           vtrue
+ 'start+329*halfcycle+halfrise'           0
+ 'start+330*halfcycle-halfrise'           0
+ 'start+330*halfcycle+halfrise'           vtrue
+ 'start+331*halfcycle-halfrise'           vtrue
+ 'start+331*halfcycle+halfrise'           0
+ 'start+332*halfcycle-halfrise'           0
+ 'start+332*halfcycle+halfrise'           vtrue
+ 'start+333*halfcycle-halfrise'           vtrue
+ 'start+333*halfcycle+halfrise'           0
+ 'start+334*halfcycle-halfrise'           0
+ 'start+334*halfcycle+halfrise'           vtrue
+ 'start+335*halfcycle-halfrise'           vtrue
+ 'start+335*halfcycle+halfrise'           0
+ 'start+336*halfcycle-halfrise'           0
+ 'start+336*halfcycle+halfrise'           vtrue
+ 'start+337*halfcycle-halfrise'           vtrue
+ 'start+337*halfcycle+halfrise'           0
+ 'start+338*halfcycle-halfrise'           0
+ 'start+338*halfcycle+halfrise'           vtrue
+ 'start+339*halfcycle-halfrise'           vtrue
+ 'start+339*halfcycle+halfrise'           0
+ 'start+340*halfcycle-halfrise'           0
+ 'start+340*halfcycle+halfrise'           vtrue
+ 'start+341*halfcycle-halfrise'           vtrue
+ 'start+341*halfcycle+halfrise'           0
+ 'start+342*halfcycle-halfrise'           0
+ 'start+342*halfcycle+halfrise'           vtrue
+ 'start+343*halfcycle-halfrise'           vtrue
+ 'start+343*halfcycle+halfrise'           0
+ 'start+344*halfcycle-halfrise'           0
+ 'start+344*halfcycle+halfrise'           vtrue
+ 'start+345*halfcycle-halfrise'           vtrue
+ 'start+345*halfcycle+halfrise'           0
+ 'start+346*halfcycle-halfrise'           0
+ 'start+346*halfcycle+halfrise'           vtrue
+ 'start+347*halfcycle-halfrise'           vtrue
+ 'start+347*halfcycle+halfrise'           0
+ 'start+348*halfcycle-halfrise'           0
+ 'start+348*halfcycle+halfrise'           vtrue
+ 'start+349*halfcycle-halfrise'           vtrue
+ 'start+349*halfcycle+halfrise'           0
+ 'start+350*halfcycle-halfrise'           0
+ 'start+350*halfcycle+halfrise'           vtrue
+ 'start+351*halfcycle-halfrise'           vtrue
+ 'start+351*halfcycle+halfrise'           0
+ 'start+352*halfcycle-halfrise'           0
+ 'start+352*halfcycle+halfrise'           vtrue
+ 'start+353*halfcycle-halfrise'           vtrue
+ 'start+353*halfcycle+halfrise'           0
+ 'start+354*halfcycle-halfrise'           0
+ 'start+354*halfcycle+halfrise'           vtrue
+ 'start+355*halfcycle-halfrise'           vtrue
+ 'start+355*halfcycle+halfrise'           0
+ 'start+356*halfcycle-halfrise'           0
+ 'start+356*halfcycle+halfrise'           vtrue
+ 'start+357*halfcycle-halfrise'           vtrue
+ 'start+357*halfcycle+halfrise'           0
+ 'start+358*halfcycle-halfrise'           0
+ 'start+358*halfcycle+halfrise'           vtrue
+ 'start+359*halfcycle-halfrise'           vtrue
+ 'start+359*halfcycle+halfrise'           0
+ 'start+360*halfcycle-halfrise'           0
+ 'start+360*halfcycle+halfrise'           vtrue
+ 'start+361*halfcycle-halfrise'           vtrue
+ 'start+361*halfcycle+halfrise'           0
+ 'start+362*halfcycle-halfrise'           0
+ 'start+362*halfcycle+halfrise'           vtrue
+ 'start+363*halfcycle-halfrise'           vtrue
+ 'start+363*halfcycle+halfrise'           0
+ 'start+364*halfcycle-halfrise'           0
+ 'start+364*halfcycle+halfrise'           vtrue
+ 'start+365*halfcycle-halfrise'           vtrue
+ 'start+365*halfcycle+halfrise'           0
+ 'start+366*halfcycle-halfrise'           0
+ 'start+366*halfcycle+halfrise'           vtrue
+ 'start+367*halfcycle-halfrise'           vtrue
+ 'start+367*halfcycle+halfrise'           0
+ 'start+368*halfcycle-halfrise'           0
+ 'start+368*halfcycle+halfrise'           vtrue
+ 'start+369*halfcycle-halfrise'           vtrue
+ 'start+369*halfcycle+halfrise'           0
+ 'start+370*halfcycle-halfrise'           0
+ 'start+370*halfcycle+halfrise'           vtrue
+ 'start+371*halfcycle-halfrise'           vtrue
+ 'start+371*halfcycle+halfrise'           0
+ 'start+372*halfcycle-halfrise'           0
+ 'start+372*halfcycle+halfrise'           vtrue
+ 'start+373*halfcycle-halfrise'           vtrue
+ 'start+373*halfcycle+halfrise'           0
+ 'start+374*halfcycle-halfrise'           0
+ 'start+374*halfcycle+halfrise'           vtrue
+ 'start+375*halfcycle-halfrise'           vtrue
+ 'start+375*halfcycle+halfrise'           0
+ 'start+376*halfcycle-halfrise'           0
+ 'start+376*halfcycle+halfrise'           vtrue
+ 'start+377*halfcycle-halfrise'           vtrue
+ 'start+377*halfcycle+halfrise'           0
+ 'start+378*halfcycle-halfrise'           0
+ 'start+378*halfcycle+halfrise'           vtrue
+ 'start+379*halfcycle-halfrise'           vtrue
+ 'start+379*halfcycle+halfrise'           0
+ 'start+380*halfcycle-halfrise'           0
+ 'start+380*halfcycle+halfrise'           vtrue
+ 'start+381*halfcycle-halfrise'           vtrue
+ 'start+381*halfcycle+halfrise'           0
+ 'start+382*halfcycle-halfrise'           0
+ 'start+382*halfcycle+halfrise'           vtrue
+ 'start+383*halfcycle-halfrise'           vtrue
+ 'start+383*halfcycle+halfrise'           0
+ 'start+384*halfcycle-halfrise'           0
+ 'start+384*halfcycle+halfrise'           vtrue
+ 'start+385*halfcycle-halfrise'           vtrue
+ 'start+385*halfcycle+halfrise'           0
+ 'start+386*halfcycle-halfrise'           0
+ 'start+386*halfcycle+halfrise'           vtrue
+ 'start+387*halfcycle-halfrise'           vtrue
+ 'start+387*halfcycle+halfrise'           0
+ 'start+388*halfcycle-halfrise'           0
+ 'start+388*halfcycle+halfrise'           vtrue
+ 'start+389*halfcycle-halfrise'           vtrue
+ 'start+389*halfcycle+halfrise'           0
+ 'start+390*halfcycle-halfrise'           0
+ 'start+390*halfcycle+halfrise'           vtrue
+ 'start+391*halfcycle-halfrise'           vtrue
+ 'start+391*halfcycle+halfrise'           0
+ 'start+392*halfcycle-halfrise'           0
+ 'start+392*halfcycle+halfrise'           vtrue
+ 'start+393*halfcycle-halfrise'           vtrue
+ 'start+393*halfcycle+halfrise'           0
+ 'start+394*halfcycle-halfrise'           0
+ 'start+394*halfcycle+halfrise'           vtrue
+ 'start+395*halfcycle-halfrise'           vtrue
+ 'start+395*halfcycle+halfrise'           0
+ 'start+396*halfcycle-halfrise'           0
+ 'start+396*halfcycle+halfrise'           vtrue
+ 'start+397*halfcycle-halfrise'           vtrue
+ 'start+397*halfcycle+halfrise'           0
+ 'start+398*halfcycle-halfrise'           0
+ 'start+398*halfcycle+halfrise'           vtrue
+ 'start+399*halfcycle-halfrise'           vtrue
+ 'start+399*halfcycle+halfrise'           0
+)
