% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

/* $Id$ */

%import ("regresslib")
import ("htmltable")
import ("cit_util")

implementation("Main")

program("cgidb")
