.TH AUTO 1 
.UC 4
.SH NAME
auto \- size and layout production rules
.SH SYNOPSIS
.B auto
.I seed
[
.I args
]

.SH DESCRIPTION
Auto is a multifunction CAD tool for asynchronous circuit design.  It
has two primary functions: optimizing the widths of production rules
and generating unwired layout for production rules.  It also provides
some related functions like estimating the wiring cost of connecting
nodes in layout, and minimizing the number of transistors used in 1 of
N logic networks.

.SH "FILE FORMATS"
Auto understands several file formats.  These formats and related
tools are summarized below:

.TP 1.0i
.B .auto
Auto's own flattened PRS format.  Each auto file corresponds to a mag
file of the same base name.  They can be initially generated with the
script "make_auto file.cast CELLNAME".  Some additional directives
beginning with an @ may be added at the end of the file.  The most
common is "@ypitch(#)" to specify the bitpitch for layout.

.TP 1.0i
.B .prs
Another version of auto's flattened PRS format, used only for library
cells.  Library cells are created for common operators and subcircuits
which can be matched to a user circuit and stretched to the correct
transistor widths.  In a prs file for auto, additional directives
beginning with an @ are allowed at the end of the file.

.TP 1.0i
.B .mag
Magic's layout format.  Necessary to indicate instances and labels
when sizing or estimating wiring loads from Magic.

.TP 1.0i
.B .instances
A file describing the type, name, and bounding box of every cell.  Usually
obtained from Cadence by (DumpCellHierarchy CellView FileName).  Needed for
sizing or load estimites from Cadence.

.TP 1.0i
.B .connect
A simple file summarizing the connections which are supposed to exist
in the digital circuit (but do not yet exist in the layout).  Generate
with "cflat -connect file.cast > file.connect".

.TP 1.0i
.B .cap
Specify extra load (in fF) on specified nodes in a circuit.  Format is
"node load".  Can be generated from extracted capacitance by "ext2sim
file.ext; capacitances < file.sim > file.cap"

.TP 1.0i
.B .aspcap
A list of capacitors, generated by auto to give an estimate of wiring
capacitance for analog simulation by aspice.  Must be included by the
asp file.

.TP 1.0i
.B .in
The usual extension for a command script for auto.

.SH "BASIC USAGE"
Auto has dozens of functions invoked via a command line interface.
Full documentation of the commands is not written.  However, the most
common uses of auto have been incorporated into c-shell scripts and in
files.  These operations are summarized below.  In all cases, file
extensions are implicit.

.TP 1.0i
.B auto_place \fIfile\fR
Generate unwired operators and place them.  Reads in file.auto.  Tries
to match subcircuits to library cells.  Stretches library cells to
specified widths.  Anything left over is implemented with stacks of
transistors.  Then auto attempts to minimize wiring cost, reduce area,
and avoid illegal overlaps.  Finally, auto overwrites file.mag with
the result.  Directives to specify @ypitch and to pass through magic
commands are very useful.

.TP 1.0i
.B auto_layout \fIfile\fR
Same as auto_place, except placement is unoptimized but quick.

.TP 1.0i
.B auto_replace \fIseed\fR \fIfile\fR
Takes the resulting file.mag of auto_place or auto_layout and
file.auto to redo the placement of the layout using a different random
seed.  User can also edit the operators by hand first.

.TP 1.0i
.B auto_matchcircuit \fIcircuit\fR \fIsubcircuit\fP \fIlayout\fP
Reads circuit.auto, matches any circuit fragments described by
subcircuit.prs and subcircuit.mag, then generates layout.mag with the
result.  Useful for creating a library cell on-the-fly for replicating
identical parts of a cell after doing complicated wiring.

.TP 1.0i
.B auto_size \fIfile\fR \fIdelay\fR
.TP 1.0i
.B auto_relax \fIfile\fR \fIdelay\fR
.TP 1.0i
.B auto_sweep \fIfile\fR \fImindelay\fR \fImaxdelay\fR \fItolerance\fR
Do transistor sizing.  Requires file.connect and file.cells to
describe heirarchy.  Requires file.mag (unwired) to estimate wiring
capacitance.  User may create file.cap to specify extra capacitance.
Delay is used to set the typical delay of a transition, in seconds
(usually around 0.1e-9).  Auto_size reads in, sizes, and writes out
all auto files mentioned in the file.cells.  Process is
non-destructive except for the sizes of each PRS.  If an auto file is
not writable, auto assumes its transistor widths should remain fixed.
Auto_relax is a quicker, less optimal algorithm.  Auto_sweep performs
a binary tree search for best Ett of auto_size.

.TP 1.0i
.B auto_aspcap \fIfile\fR
Estimate wiring capacitance for analog simulation.  Requires file.mag
and file.connect.  Pipe the output into file.aspcap and include it in
the asp file for aspice.

.TP 1.0i
.B auto_espresso \fIinfile\fR \fIoutfile\fR
Do Karnaugh-Cube like minimization of 1ofN logic.  Reads infile.auto
and writes simplified logic to outfile.auto.  Only precharge logic
rules should be optimized, since this algorithm does not work for
weak-condition rules or completion trees.  Specify @exclhi() or
@excllo() directives for all inputs to the logic.

.SH "SEARCH PATH"

The default search path is ".:$AUTO_PATH".  Common scripts and the
layout library reside in $CAST_HOME/lib/auto.  User files should be
found through $AUTO_PATH.  Any output mag or auto files will be put in
the same directory as the original auto file.

.SH "SEE ALSO"
capacitances\|(1), aspice\|(1), magic\|(1), magic\|(5), ext2aspice\|(1)

.SH AUTHOR
Andrew Lines, ADD INC, 1999.

.SH BUGS
Error reporting is poor.  Integration with other tools is awkward.
Auto is a work in progress, and may change frequently.
