#!/usr/intel/bin/perl -w 

# Usage: rte [options]
# 
# Regression Test Engine wrapper. Invokes server.sh and specified/default
# number of client.sh process.

# find relevant packaged tools and libraries
BEGIN {
    $package_root = $0;
    my $exe = $package_root;
    $exe =~ s:.*/::;
    if (! ($package_root =~ m:^/:)) {
        my $pwd = `pwd`;
        chomp $pwd;
        $package_root = $pwd;
        $package_root .= "/$0";
        $package_root =~ s:$exe$::;
        $package_root =~ s://:/:g;
        chdir $package_root;
        $package_root = `pwd`;
        chomp $package_root;
        chdir $pwd;
    }
    else {
        $package_root =~ s:/bin/$exe::;
    }
    @INC = ("$package_root/lib/perl", @INC);
}


# report wrapper usage
sub usage() {
    my $usage = <<EOF;
USAGE: rte [args]
    --cell=[${cell}]|--module=[${module}]|--cell-list=[${cell_list}]
      (Cell, module, or cell list to verify; cell list is a text file with one
       fully qualified cell name per line, a line starting with # is treated
       as a comment)
    --cast-path=[${cast_path}]		(cast-path for cell implementation)
    --device-path=[${device_path}]	(device-path for java classes)
    --digital-delay=[${digital_d}]      (When specified use this for gate delays)
    --estimated-delay=[${estimated_d}]  (Estimated delay value)
    --measured-delay=[${measured_d}]    (Measured Delay value)
    --dataset=[${dataset}]              (Dataset for measured delay)
    --cycle-count=[$cycle_count]         (Override default cycle_count, iff >0)
    --cycle-time=[$cycle_time]           (Override default cycle_time, iff >0)
    --use-measured-delay=[${umd}]       (use measured delay in all sims)
    --enable-file-cache=[${file_cache}]	(Enable CAST file caching)
    --output-dir=[${directory}]	(Output for html results)
    --cell-prefix=[${cell_prefix}]      (Test <prefix>.<fqcn> if specified)
    --walltime=[${walltime}]	(Walltime for Server/Clients in whole hours)
    --no-recurse=[$no_recurse]          (Enable recursion into passed cells)
    --verbose=[${verbose}]		(Enable verbosity)
    --max-heap-size=[${max_heap_size}]	(Java Heap size)
    --client-max-heap-size=[${client_max_heap_size}]	(Client Java Heap size)
    --server-max-heap-size=[${server_max_heap_size}]	(Server Java Heap size)
    --help=[${help}]			(Get Server/Client and this help message)
    --version=[${version}]		(Get the version of the client/server)
    --qsub=[${qsub}]			(Run jobs with Sun Grid Engine)    
    --qsub-mem=[${qsub_mem}]		(Memory requested from queuing system)
    --qsubarch=[${qsub_arch}]		(requested architecture)
    --jobs=[$serverLimit]               (Number of Parallel qsub jobs to run)

    RTE Executed on $arch platform
EOF
    die "${usage}";
}

# default varibales

$cell = "";
$module = "";
$cell_list = "";
$cast_path = "";
$walltime  = "48";
$device_path = "";
$file_cache = 1;
$digital_d = "off";
$estimated_d = "off";
$measured_d = "off";
$dataset = "0";
$cycle_count = "0";
$cycle_time = "0";
$umd = "off";
$directory = `pwd`;
chomp $directory;
$cell_prefix = "";
$serverLimit = 4;
$no_recurse = 0;
$qsub = 1;
$qsub_mem = "";
$verbose = 0;
$help = 0;
$version = 0;
$max_heap_size="1500M";
$client_max_heap_size="";
$server_max_heap_size="";
$qsub_arch="lx*";
$sge_arch = "x86_64";
chomp $sge_arch;
$qsub_tool = "qb";
$arch = "";

$arch=`uname -s`;
chomp $arch;
$arch .= '-';
$arch .= `uname -m`;
chomp $arch;

# get optional command line arguments
while (defined $ARGV[0] && $ARGV[0] =~ /^--(.*)/) {
    ($flag, $value) = split("=",$1);
    if    ($flag eq "cell")             { $cell = $value; }
    elsif ($flag eq "module")           { $module = $value; }
    elsif ($flag eq "cell-list")        { $cell_list = $value; }
    elsif ($flag eq "cast-path")        { $cast_path = $value; }
    elsif ($flag eq "device-path")      { $device_path = $value; }
    elsif ($flag eq "digital-delay")    { $digital_d = $value; }
    elsif ($flag eq "estimated-delay")  { $estimated_d = $value; }    
    elsif ($flag eq "use-measured-delay") { $umd = $value; }
    elsif ($flag eq "measured-delay")   { $measured_d = $value; }
    elsif ($flag eq "dataset")          { $dataset = $value; }
    elsif ($flag eq "cycle-count")      { $cycle_count = $value; }
    elsif ($flag eq "cycle-time")      { $cycle_time = $value; }    
    elsif ($flag eq "enable-file-cache"){ $file_cache = $value; }
    elsif ($flag eq "output-dir")       { $directory = $value; }
    elsif ($flag eq "cell-prefix")      { $cell_prefix = $value; }
    elsif ($flag eq "walltime")         { $walltime = $value; } 
    elsif ($flag eq "jobs")             { $serverLimit = $value; }
    elsif ($flag eq "no-recurse")       { $no_recurse = $value; }
    elsif ($flag eq "verbose")          { $verbose = 1; }
    elsif ($flag eq "version")          { $version = 1; }
    elsif ($flag eq "help")             { $help = 1; }
    elsif ($flag eq "qsub")             { $qsub = $value; } 
    elsif ($flag eq "qsub-mem")         { $qsub_mem = $value; } 
    elsif ($flag eq "qsubarch")         { $qsub_arch = $value; } 
    elsif ($flag eq "max-heap-size")    { $max_heap_size = $value; } 
    elsif ($flag eq "client-max-heap-size") { $client_max_heap_size = $value; } 
    elsif ($flag eq "server-max-heap-size") { $server_max_heap_size = $value; } 
    else {  die "ERROR: argument --${flag}=${value} not recognized.\n"; }
    shift @ARGV;
}

$client_max_heap_size = $max_heap_size if ($client_max_heap_size eq "");
$server_max_heap_size = $max_heap_size if ($server_max_heap_size eq "");
$qsub_mem = $client_max_heap_size if ($qsub_mem eq "");

if($help != 0){
    `$package_root/bin/server --help`;
    `$package_root/bin/client --help`;
    usage();
    exit;
}

if($version != 0){
    `$package_root/bin/server --version`;
    `$package_root/bin/client --version`;
    exit;
}

# check for required arguments
if("$cell" eq "" && $module eq "" && $cell_list eq ""){print "ERROR: --cell, --module, or --cell-list not specified.\n"; usage();}
if("$cast_path" eq ""){print "ERROR: cast_path option missing.\n"; usage();}

$setup_cmds = "";
$setup_cmds = $setup_cmds." cp $package_root/share/html/examples.html $directory";
$setup_cmds = $setup_cmds."; cp $package_root/share/html/test-info.html $directory";
$setup_cmds = $setup_cmds."; cp $package_root/share/html/help-doc.html $directory";
$setup_cmds = $setup_cmds."; cp $package_root/share/html/logo.png $directory";
$setup_cmds = $setup_cmds."; cp $package_root/share/html/stylesheet.css $directory";

# construct client command
if($cell_list ne "") {
    $server = "$package_root/bin/server --cell-list=\"$cell_list\" "
} elsif ($cell ne ""){
    $server = "$package_root/bin/server --cell=\"$cell\" "
    }
else {
    $server = "$package_root/bin/server --module=$module "
}
$server .= " "
    ."--cast-path=$cast_path --server-limit=$serverLimit --work-dir=$directory "
    ."--cell-prefix=$cell_prefix "
    ."--max-heap-size=$server_max_heap_size --walltime=$walltime --no-recurse=$no_recurse ";

# construct server command
my $name = `hostname`;
chomp($name);
$client = "$package_root/bin/client --cast-path=$cast_path "
    ."--server=$name --hostname=`hostname` --dataset=$dataset "
    ."--digital-delay=$digital_d --use-measured-delay=$umd "
    ."--estimated-delay=$estimated_d --measured-delay=$measured_d "
    ."--cycle-count=$cycle_count --cycle-time=$cycle_time "
    ."--max-heap-size=$client_max_heap_size --enable-file-cache=$file_cache " ."--device-path=$device_path --base-dir=$directory ";

if($verbose != 0){
    $server = $server." --script-verbose";
    $client = $client." --script-verbose";
}

# create script to be run on local host or submitted to qsub
`rm -rf "$directory/modules/"`;
`rm -rf "$directory/logs/"`;
`rm -rf "$directory/hier/"`;
`rm -rf "$directory/scripts/"`;
`mkdir -p "$directory/modules/"`;
`mkdir -p "$directory/logs/"`;
`mkdir -p "$directory/hier/"`;
`mkdir -p "$directory/scripts/"`;
`$setup_cmds`;

$log = "$directory/logs/";
$do = "$directory/scripts/rte_client";

open  OUT, ">$do" or die "Can't open $do for writing.\n";
print OUT "#!/bin/sh\n";
chmod(0755,$do);

# start and monitor server 
open(RTESERVER, "$server |") or die "FATAL: RTEServer failed to start.\n";

# echo every message
while(<RTESERVER>){
    if($_ =~ /Server Running at port (\d+)/){
	print $_;
        print OUT "$client --port=$1\n";
        close OUT;
	if($qsub != 0) {
	    print "Starting $serverLimit clients using qsub on $arch\n";
	    for($i=0; $i < $serverLimit; $i++){
	       `$qsub_tool -V -e $log -o $log -l h_rt=$walltime:00:00,a=$qsub_arch,mem=$qsub_mem -cwd $do`;
	    }
	}
	else {
	    print "Starting $serverLimit clients on localhost\n";
	    for($i=0; $i < $serverLimit; $i++){
		`$do &> $log/localhost-$i.log `;
	    }
	}
    }
    else {print $_; }
}
