% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("set")
import ("parseparams")
import ("cit_util")

sorted_table("CardRef", "Cardinal", "Refany")

module("NumberedObject")
array_sort("NumberedObject", "NumberedObject")

interface("TaggedToken")
sequence("TaggedToken", "TaggedToken")

implementation("Main")

program ("timing")
