#!/usr/intel/bin/perl -w

# Compares cells.debug files for all cells, given a field to compare.
# Filters out differences less than a specified threshold, in percent.

@ARGV==4 or die "USAGE: percent_threshold field cells1.debug cells2.debug\n";
my $r = $ARGV[0];
my $f = $ARGV[1];
my $a = $ARGV[2];
my $b = $ARGV[3];
print "Comparing $a to $b\n  on $f with $r% threshold\n";
$r=$r*0.01;

# parse cells.debug into hash tables
my %a_sizes = read_cells($a);
my %b_sizes = read_cells($b);

# compare all cells and all half-operator sizes
foreach my $cell (sort keys %a_sizes) {
    print "CELL $cell\n";
    my $as = $a_sizes{$cell};
    my $bs = $b_sizes{$cell};
    foreach my $ho (sort keys %{$as}) {
        my $av = $as->{$ho};
        my $bv = $bs->{$ho};
        if (defined($av) && defined($bv)) {
            $ba = $bv/$av;
            if ($ba>(1+$r) || $ba<1/(1+$r)) {
                print "  $ho a=$av b=$bv ratio=$ba\n";
            }
        }
    }
}

# reads cells.debug into hash table
sub read_cells {
    my $file = shift;
    my %sizes;
    my %cell_sizes;
    my $cell;
    open IN, "<$file" or die "ERROR: can't read $file\n";
    while (my $line = <IN>) {
        if ($line =~ /^CELL (.*) {/) {
            if (defined $cell)  {
                my %sizes2 = %sizes;
                $cell_sizes{$cell} = \%sizes2;
            }
            $cell = $1;
            %sizes = ();
        } elsif ($line =~ /^  ($f) = (.*)u/ ) {
            $sizes{$1} = $2;
        }
    }
    if (defined $cell) {
        my %sizes2 = %sizes;
        $cell_sizes{$cell} = \%sizes2;
    }
    close IN;
    return %cell_sizes;
}
