import( "libm3" )

% TCAM
module( "Tcam" )

% WCM Group
module( "WCMTcamBlock" )
module( "WCM" )
module( "WCMTest" )
interface( "WCMConstants" )

% Top Level Test
implementation( "Main" )
program( "testall" )
