% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import( "libm3" )

% TCAM
module( "Tcam" )

% WCM Group
module( "WCMTcamBlock" )
module( "WCM" )
module( "WCMTest" )
interface( "WCMConstants" )

% Top Level Test
implementation( "Main" )
program( "testall" )
