import ("libm3")
import ("cit_util")
import ("parseparams")
import ("trie")

module ("DefFormat")
module ("DefLexer")

interface ("ParseProc")
interface ("ParseProcRec")
interface ("ParseError")

trie("DefParse", "Char", "ParseProcRec")

interface ("DefPoint")
sequence  ("DefPoint", "DefPoint")

implementation ("Main")

program ("testdef")
