% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("cit_util")
import ("spicelib")
import ("m3readline")

Table("TextTextSet", "Text", "TextSet")

Module ("TextCard")
Array_sort ("TextCard", "TextCard")

Module ("SpiceInstance")

MkSet("SpiceInstance", "SpiceInstance")
MkSetDef("SpiceInstance", "SpiceInstance")
Table("SpiceInstanceRef", "SpiceInstance", "Refany")

Table("TextSpiceInstanceSet", "Text", "SpiceInstanceSet")

Module ("FlatUI")

Module ("SpiceFlat")

library ("spiceflat")
