#!/bin/sh -x

LIBROOT=/p/cth/rtl/cad/x86-64_linux44/synopsys/verdi3
#VERSION=R-2020.12
VERSION=T-2022.06

INCLUDE_DIR=${LIBROOT}/${VERSION}/share/FsdbReader/
LIB_DIR=${LIBROOT}/${VERSION}/share/FsdbReader/linux64/
SO_DIR=${LIBROOT}/${VERSION}/share/FsdbReader/linux64/

#g++ -g -o read_analog -I ${INCLUDE_DIR} read_analog.cpp -L ${LIB_DIR} -lnffr -lnsys -ldl -lz -Wl,-rpath=${SO_DIR}

#g++ -g -o read_mix -I ${INCLUDE_DIR} read_mix.cpp -L ${LIB_DIR} -lnffr -lnsys -ldl -lz -Wl,-rpath=${SO_DIR}

g++ -g -o read_nanosim -I ${INCLUDE_DIR} read_nanosim.cpp -L ${LIB_DIR} -lnffr -lnsys -ldl -lz -Wl,-rpath=${SO_DIR}

g++ -g -o nanosimrd -I ${INCLUDE_DIR} nanosimrd.cpp -L ${LIB_DIR} -lnffr -lnsys -ldl -lz -Wl,-rpath=${SO_DIR}

