/*m3_option("-g")*/
/*m3_option("-X2@-pg@")*/
/*m3_option("-Z")*/
/*remove_m3_option("-O")*/
module(Debug)

module(BDD)
implementation(BDDImpl)
module(BDDTripleHash)
module(BDDPair)
interface(BDDPrivate)

generic_module(ProcTable)

import("libm3")
implementation(BDDTest)

program(bddtest)
