/* $Id$ */
m3_option("-g")
m3_option("-times")
/*m3_option("-X2@-pg@")*/
/*m3_option("-Z")*/
/*remove_m3_option("-O")*/
import("cit_util")

Module("BDD")
List("BDD","BDD")
Interface("BDDDepends")
implementation("BDDImpl")
module("BDDTripleHash")
module("BDDPair")
interface("BDDPrivate")

generic_module("ProcTable")

Table ("BDDRef", "BDD", "Refany")
MkSet ("BDD", "BDD")
MkSetDef ("BDD", "BDD")


import("libm3")
library("bdd")
