///------------------------------------------------------------------------------
///                                                                              
///  INTEL CONFIDENTIAL                                                          
///                                                                              
///  Copyright 2018 Intel Corporation All Rights Reserved.                 
///                                                                              
///  The source code contained or described herein and all documents related     
///  to the source code ("Material") are owned by Intel Corporation or its    
///  suppliers or licensors. Title to the Material remains with Intel            
///  Corporation or its suppliers and licensors. The Material contains trade     
///  secrets and proprietary and confidential information of Intel or its        
///  suppliers and licensors. The Material is protected by worldwide copyright   
///  and trade secret laws and treaty provisions. No part of the Material may    
///  be used, copied, reproduced, modified, published, uploaded, posted,         
///  transmitted, distributed, or disclosed in any way without Intel's prior     
///  express written permission.                                                 
///                                                                              
///  No license under any patent, copyright, trade secret or other intellectual  
///  property right is granted to or conferred upon you by disclosure or         
///  delivery of the Materials, either expressly, by implication, inducement,    
///  estoppel or otherwise. Any license under such intellectual property rights  
///  must be express and approved by Intel in writing.                           
///                                                                              
///------------------------------------------------------------------------------
///  Auto-generated by ngen. please do not hand edit
///------------------------------------------------------------------------------
// -- Author       : Copy from Steve Olson <steve.olson.com> 
// -- Project Name : MBY 
// -- Description  : gpm memory wrapper netlist. 
// ------------------------------------------------------------------- 

module mby_gpm_gen_mem (
input i_reset, 
mby_gpm_mem_if.pod_ptr_mem   mem_pod_ptr_0_if, 
mby_gpm_mem_if.pod_ptr_mem   mem_pod_ptr_1_if, 
mby_gpm_mem_if.pod_ptr_mem   mem_pod_ptr_2_if, 
mby_gpm_mem_if.pod_ptr_mem   mem_pod_ptr_3_if, 
mby_gpm_mem_if.pointers_mem  mem_pointers_0_if, 
mby_gpm_mem_if.pointers_mem  mem_pointers_1_if, 
mby_gpm_mem_if.pointers_mem  mem_pointers_2_if, 
mby_gpm_mem_if.pointers_mem  mem_pointers_3_if, 
mby_gpm_mem_if.pointers_mem  mem_pointers_4_if, 
mby_gpm_mem_if.pointers_mem  mem_pointers_5_if, 
mby_gpm_mem_if.pointers_mem  mem_pointers_6_if, 
mby_gpm_mem_if.pointers_mem  mem_pointers_7_if, 
//Input List
input                   cclk,                                     
input                   fary_enblfloat_sram,                      
input                   fary_ensleep_sram,                        
input           [19:0]  fary_ffuse_data_misc_sram,                
input            [1:0]  fary_fwen_sram,                           
input                   fary_pwren_b_sram,                        
input                   fary_stm_enable,                          
input                   fary_stm_hilo,                            
input                   fary_wakeup_sram,                         
input                   fdfx_lbist_test_mode,                     
input                   fscan_byprst_b,                           
input                   fscan_mode,                               
input           [11:0]  fscan_ram_awt_mode,                       
input           [11:0]  fscan_ram_awt_ren,                        
input           [11:0]  fscan_ram_awt_wen,                        
input           [11:0]  fscan_ram_bypsel,                         
input                   fscan_ram_init_en,                        
input                   fscan_ram_init_val,                       
input           [11:0]  fscan_ram_odis_b,                         
input                   fscan_ram_rddis_b,                        
input                   fscan_ram_wrdis_b,                        
input                   fscan_rstbypen,                           
input                   mclk,                                     

//Output List
output                  aary_pwren_b_sram                         
);

logic   [37:0] gpm_mem_pod_ptr_0_from_mem;     
logic   [56:0] gpm_mem_pod_ptr_0_to_mem;       
logic   [37:0] gpm_mem_pod_ptr_1_from_mem;     
logic   [56:0] gpm_mem_pod_ptr_1_to_mem;       
logic   [37:0] gpm_mem_pod_ptr_2_from_mem;     
logic   [56:0] gpm_mem_pod_ptr_2_to_mem;       
logic   [37:0] gpm_mem_pod_ptr_3_from_mem;     
logic   [56:0] gpm_mem_pod_ptr_3_to_mem;       
logic [2352:0] gpm_mem_pointers_0_from_mem;    
logic [2385:0] gpm_mem_pointers_0_to_mem;      
logic [2352:0] gpm_mem_pointers_1_from_mem;    
logic [2385:0] gpm_mem_pointers_1_to_mem;      
logic [2352:0] gpm_mem_pointers_2_from_mem;    
logic [2385:0] gpm_mem_pointers_2_to_mem;      
logic [2352:0] gpm_mem_pointers_3_from_mem;    
logic [2385:0] gpm_mem_pointers_3_to_mem;      
logic [2352:0] gpm_mem_pointers_4_from_mem;    
logic [2385:0] gpm_mem_pointers_4_to_mem;      
logic [2352:0] gpm_mem_pointers_5_from_mem;    
logic [2385:0] gpm_mem_pointers_5_to_mem;      
logic [2352:0] gpm_mem_pointers_6_from_mem;    
logic [2385:0] gpm_mem_pointers_6_to_mem;      
logic [2352:0] gpm_mem_pointers_7_from_mem;    
logic [2385:0] gpm_mem_pointers_7_to_mem;      
logic          mem_pod_ptr_0_if;               
logic          mem_pod_ptr_1_if;               
logic          mem_pod_ptr_2_if;               
logic          mem_pod_ptr_3_if;               
logic          mem_pointers_0_if;              
logic          mem_pointers_1_if;              
logic          mem_pointers_2_if;              
logic          mem_pointers_3_if;              
logic          mem_pointers_4_if;              
logic          mem_pointers_5_if;              
logic          mem_pointers_6_if;              
logic          mem_pointers_7_if;              
logic reset_n; 
assign reset_n = !i_reset;


// module gpm_shells_wrapper    from gpm_shells_wrapper using gpm_shells_wrapper.map 
gpm_shells_wrapper    gpm_shells_wrapper(
/* input  logic           */ .GPM_ECC_COR_ERR_reg_sel       (1'b0),                                    
/* input  logic           */ .GPM_ECC_UNCOR_ERR_reg_sel     (1'b0),                                    
/* input  logic           */ .MEM_POD_PTR_0_CFG_reg_sel     (1'b0),                                    
/* input  logic           */ .MEM_POD_PTR_0_STATUS_reg_sel  (1'b0),                                    
/* input  logic           */ .MEM_POD_PTR_1_CFG_reg_sel     (1'b0),                                    
/* input  logic           */ .MEM_POD_PTR_1_STATUS_reg_sel  (1'b0),                                    
/* input  logic           */ .MEM_POD_PTR_2_CFG_reg_sel     (1'b0),                                    
/* input  logic           */ .MEM_POD_PTR_2_STATUS_reg_sel  (1'b0),                                    
/* input  logic           */ .MEM_POD_PTR_3_CFG_reg_sel     (1'b0),                                    
/* input  logic           */ .MEM_POD_PTR_3_STATUS_reg_sel  (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_0_CFG_reg_sel    (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_0_STATUS_reg_sel (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_1_CFG_reg_sel    (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_1_STATUS_reg_sel (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_2_CFG_reg_sel    (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_2_STATUS_reg_sel (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_3_CFG_reg_sel    (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_3_STATUS_reg_sel (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_4_CFG_reg_sel    (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_4_STATUS_reg_sel (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_5_CFG_reg_sel    (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_5_STATUS_reg_sel (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_6_CFG_reg_sel    (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_6_STATUS_reg_sel (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_7_CFG_reg_sel    (1'b0),                                    
/* input  logic           */ .MEM_POINTERS_7_STATUS_reg_sel (1'b0),                                    
/* input  logic           */ .clk                           (mclk),                                    
/* input  logic    [37:0] */ .gpm_mem_pod_ptr_0_from_mem    (gpm_mem_pod_ptr_0_from_mem),              
/* input  logic    [37:0] */ .gpm_mem_pod_ptr_1_from_mem    (gpm_mem_pod_ptr_1_from_mem),              
/* input  logic    [37:0] */ .gpm_mem_pod_ptr_2_from_mem    (gpm_mem_pod_ptr_2_from_mem),              
/* input  logic    [37:0] */ .gpm_mem_pod_ptr_3_from_mem    (gpm_mem_pod_ptr_3_from_mem),              
/* input  logic  [2352:0] */ .gpm_mem_pointers_0_from_mem   (gpm_mem_pointers_0_from_mem),             
/* input  logic  [2352:0] */ .gpm_mem_pointers_1_from_mem   (gpm_mem_pointers_1_from_mem),             
/* input  logic  [2352:0] */ .gpm_mem_pointers_2_from_mem   (gpm_mem_pointers_2_from_mem),             
/* input  logic  [2352:0] */ .gpm_mem_pointers_3_from_mem   (gpm_mem_pointers_3_from_mem),             
/* input  logic  [2352:0] */ .gpm_mem_pointers_4_from_mem   (gpm_mem_pointers_4_from_mem),             
/* input  logic  [2352:0] */ .gpm_mem_pointers_5_from_mem   (gpm_mem_pointers_5_from_mem),             
/* input  logic  [2352:0] */ .gpm_mem_pointers_6_from_mem   (gpm_mem_pointers_6_from_mem),             
/* input  logic  [2352:0] */ .gpm_mem_pointers_7_from_mem   (gpm_mem_pointers_7_from_mem),             
/* Interface .adr         */ .mem_pod_ptr_0_adr             (mem_pod_ptr_0_if.adr),                    
/* input  logic           */ .mem_pointers_3_mem_ls_enter   (1'b0),                                    
/* Interface .rd_en       */ .mem_pointers_3_rd_en          (mem_pointers_3_if.rd_en),                 
/* Interface .wr_bwe      */ .mem_pointers_3_wr_bwe         (mem_pointers_3_if.wr_bwe),                
/* Interface .wr_data     */ .mem_pointers_3_wr_data        (mem_pointers_3_if.wr_data),               
/* input  logic           */ .mem_pod_ptr_0_mem_ls_enter    (1'b0),                                    
/* Interface .rd_en       */ .mem_pod_ptr_0_rd_en           (mem_pod_ptr_0_if.rd_en),                  
/* Interface .wr_data     */ .mem_pod_ptr_0_wr_data         (mem_pod_ptr_0_if.wr_data),                
/* Interface .wr_en       */ .mem_pod_ptr_0_wr_en           (mem_pod_ptr_0_if.wr_en),                  
/* Interface .adr         */ .mem_pod_ptr_1_adr             (mem_pod_ptr_1_if.adr),                    
/* input  logic           */ .mem_pod_ptr_1_mem_ls_enter    (1'b0),                                    
/* Interface .rd_en       */ .mem_pod_ptr_1_rd_en           (mem_pod_ptr_1_if.rd_en),                  
/* Interface .wr_data     */ .mem_pod_ptr_1_wr_data         (mem_pod_ptr_1_if.wr_data),                
/* Interface .wr_en       */ .mem_pod_ptr_1_wr_en           (mem_pod_ptr_1_if.wr_en),                  
/* Interface .adr         */ .mem_pod_ptr_2_adr             (mem_pod_ptr_2_if.adr),                    
/* input  logic           */ .mem_pod_ptr_2_mem_ls_enter    (1'b0),                                    
/* Interface .rd_en       */ .mem_pod_ptr_2_rd_en           (mem_pod_ptr_2_if.rd_en),                  
/* Interface .wr_data     */ .mem_pod_ptr_2_wr_data         (mem_pod_ptr_2_if.wr_data),                
/* Interface .wr_en       */ .mem_pod_ptr_2_wr_en           (mem_pod_ptr_2_if.wr_en),                  
/* Interface .adr         */ .mem_pod_ptr_3_adr             (mem_pod_ptr_3_if.adr),                    
/* input  logic           */ .mem_pod_ptr_3_mem_ls_enter    (1'b0),                                    
/* Interface .rd_en       */ .mem_pod_ptr_3_rd_en           (mem_pod_ptr_3_if.rd_en),                  
/* Interface .wr_data     */ .mem_pod_ptr_3_wr_data         (mem_pod_ptr_3_if.wr_data),                
/* Interface .wr_en       */ .mem_pod_ptr_3_wr_en           (mem_pod_ptr_3_if.wr_en),                  
/* Interface .adr         */ .mem_pointers_0_adr            (mem_pointers_0_if.adr),                   
/* input  logic           */ .mem_pointers_0_mem_ls_enter   (1'b0),                                    
/* Interface .rd_en       */ .mem_pointers_0_rd_en          (mem_pointers_0_if.rd_en),                 
/* Interface .wr_bwe      */ .mem_pointers_0_wr_bwe         (mem_pointers_0_if.wr_bwe),                
/* Interface .wr_data     */ .mem_pointers_0_wr_data        (mem_pointers_0_if.wr_data),               
/* Interface .wr_en       */ .mem_pointers_0_wr_en          (mem_pointers_0_if.wr_en),                 
/* Interface .adr         */ .mem_pointers_1_adr            (mem_pointers_1_if.adr),                   
/* input  logic           */ .mem_pointers_1_mem_ls_enter   (1'b0),                                    
/* Interface .rd_en       */ .mem_pointers_1_rd_en          (mem_pointers_1_if.rd_en),                 
/* Interface .wr_bwe      */ .mem_pointers_1_wr_bwe         (mem_pointers_1_if.wr_bwe),                
/* Interface .wr_data     */ .mem_pointers_1_wr_data        (mem_pointers_1_if.wr_data),               
/* Interface .wr_en       */ .mem_pointers_1_wr_en          (mem_pointers_1_if.wr_en),                 
/* Interface .adr         */ .mem_pointers_2_adr            (mem_pointers_2_if.adr),                   
/* input  logic           */ .mem_pointers_2_mem_ls_enter   (1'b0),                                    
/* Interface .rd_en       */ .mem_pointers_2_rd_en          (mem_pointers_2_if.rd_en),                 
/* Interface .wr_bwe      */ .mem_pointers_2_wr_bwe         (mem_pointers_2_if.wr_bwe),                
/* Interface .wr_data     */ .mem_pointers_2_wr_data        (mem_pointers_2_if.wr_data),               
/* Interface .wr_en       */ .mem_pointers_2_wr_en          (mem_pointers_2_if.wr_en),                 
/* Interface .adr         */ .mem_pointers_3_adr            (mem_pointers_3_if.adr),                   
/* Interface .wr_en       */ .mem_pointers_3_wr_en          (mem_pointers_3_if.wr_en),                 
/* Interface .adr         */ .mem_pointers_4_adr            (mem_pointers_4_if.adr),                   
/* input  logic           */ .mem_pointers_4_mem_ls_enter   (1'b0),                                    
/* Interface .rd_en       */ .mem_pointers_4_rd_en          (mem_pointers_4_if.rd_en),                 
/* Interface .wr_bwe      */ .mem_pointers_4_wr_bwe         (mem_pointers_4_if.wr_bwe),                
/* Interface .wr_data     */ .mem_pointers_4_wr_data        (mem_pointers_4_if.wr_data),               
/* Interface .wr_en       */ .mem_pointers_4_wr_en          (mem_pointers_4_if.wr_en),                 
/* Interface .adr         */ .mem_pointers_5_adr            (mem_pointers_5_if.adr),                   
/* input  logic           */ .mem_pointers_5_mem_ls_enter   (1'b0),                                    
/* Interface .rd_en       */ .mem_pointers_5_rd_en          (mem_pointers_5_if.rd_en),                 
/* Interface .wr_bwe      */ .mem_pointers_5_wr_bwe         (mem_pointers_5_if.wr_bwe),                
/* Interface .wr_data     */ .mem_pointers_5_wr_data        (mem_pointers_5_if.wr_data),               
/* Interface .wr_en       */ .mem_pointers_5_wr_en          (mem_pointers_5_if.wr_en),                 
/* Interface .adr         */ .mem_pointers_6_adr            (mem_pointers_6_if.adr),                   
/* input  logic           */ .mem_pointers_6_mem_ls_enter   (1'b0),                                    
/* Interface .rd_en       */ .mem_pointers_6_rd_en          (mem_pointers_6_if.rd_en),                 
/* Interface .wr_bwe      */ .mem_pointers_6_wr_bwe         (mem_pointers_6_if.wr_bwe),                
/* Interface .wr_data     */ .mem_pointers_6_wr_data        (mem_pointers_6_if.wr_data),               
/* Interface .wr_en       */ .mem_pointers_6_wr_en          (mem_pointers_6_if.wr_en),                 
/* Interface .adr         */ .mem_pointers_7_adr            (mem_pointers_7_if.adr),                   
/* input  logic           */ .mem_pointers_7_mem_ls_enter   (1'b0),                                    
/* Interface .rd_en       */ .mem_pointers_7_rd_en          (mem_pointers_7_if.rd_en),                 
/* Interface .wr_bwe      */ .mem_pointers_7_wr_bwe         (mem_pointers_7_if.wr_bwe),                
/* Interface .wr_data     */ .mem_pointers_7_wr_data        (mem_pointers_7_if.wr_data),               
/* Interface .wr_en       */ .mem_pointers_7_wr_en          (mem_pointers_7_if.wr_en),                 
/* input  logic           */ .reset_n                       (reset_n),                                 
/* input  logic           */ .unified_regs_rd               (1'b1),                                    
/* input  logic    [31:0] */ .unified_regs_wr_data          ('h0),                                     
/* Interface .rd_valid    */ .mem_pointers_7_rd_valid       (mem_pointers_7_if.rd_valid),              
/* output logic           */ .unified_regs_ack              (),                                        
/* output logic    [31:0] */ .unified_regs_rd_data          (),                                        
/* output logic           */ .gpm_ecc_int                   (),                                        
/* output logic           */ .gpm_init_done                 (),                                        
/* output logic    [56:0] */ .gpm_mem_pod_ptr_0_to_mem      (gpm_mem_pod_ptr_0_to_mem),                
/* output logic    [56:0] */ .gpm_mem_pod_ptr_1_to_mem      (gpm_mem_pod_ptr_1_to_mem),                
/* output logic    [56:0] */ .gpm_mem_pod_ptr_2_to_mem      (gpm_mem_pod_ptr_2_to_mem),                
/* output logic    [56:0] */ .gpm_mem_pod_ptr_3_to_mem      (gpm_mem_pod_ptr_3_to_mem),                
/* output logic  [2385:0] */ .gpm_mem_pointers_0_to_mem     (gpm_mem_pointers_0_to_mem),               
/* output logic  [2385:0] */ .gpm_mem_pointers_1_to_mem     (gpm_mem_pointers_1_to_mem),               
/* output logic  [2385:0] */ .gpm_mem_pointers_2_to_mem     (gpm_mem_pointers_2_to_mem),               
/* output logic  [2385:0] */ .gpm_mem_pointers_3_to_mem     (gpm_mem_pointers_3_to_mem),               
/* output logic  [2385:0] */ .gpm_mem_pointers_4_to_mem     (gpm_mem_pointers_4_to_mem),               
/* output logic  [2385:0] */ .gpm_mem_pointers_5_to_mem     (gpm_mem_pointers_5_to_mem),               
/* output logic  [2385:0] */ .gpm_mem_pointers_6_to_mem     (gpm_mem_pointers_6_to_mem),               
/* output logic  [2385:0] */ .gpm_mem_pointers_7_to_mem     (gpm_mem_pointers_7_to_mem),               
/* output logic           */ .mem_pod_ptr_0_ecc_uncor_err   (),                                        
/* output logic           */ .mem_pod_ptr_0_init_done       (),                                        
/* Interface .rd_data     */ .mem_pod_ptr_0_rd_data         (mem_pod_ptr_0_if.rd_data),                
/* Interface .rd_valid    */ .mem_pod_ptr_0_rd_valid        (mem_pod_ptr_0_if.rd_valid),               
/* output logic           */ .mem_pod_ptr_1_ecc_uncor_err   (),                                        
/* output logic           */ .mem_pod_ptr_1_init_done       (),                                        
/* Interface .rd_data     */ .mem_pod_ptr_1_rd_data         (mem_pod_ptr_1_if.rd_data),                
/* Interface .rd_valid    */ .mem_pod_ptr_1_rd_valid        (mem_pod_ptr_1_if.rd_valid),               
/* output logic           */ .mem_pod_ptr_2_ecc_uncor_err   (),                                        
/* output logic           */ .mem_pod_ptr_2_init_done       (),                                        
/* Interface .rd_data     */ .mem_pod_ptr_2_rd_data         (mem_pod_ptr_2_if.rd_data),                
/* Interface .rd_valid    */ .mem_pod_ptr_2_rd_valid        (mem_pod_ptr_2_if.rd_valid),               
/* output logic           */ .mem_pod_ptr_3_ecc_uncor_err   (),                                        
/* output logic           */ .mem_pod_ptr_3_init_done       (),                                        
/* Interface .rd_data     */ .mem_pod_ptr_3_rd_data         (mem_pod_ptr_3_if.rd_data),                
/* Interface .rd_valid    */ .mem_pod_ptr_3_rd_valid        (mem_pod_ptr_3_if.rd_valid),               
/* output logic           */ .mem_pointers_0_ecc_uncor_err  (),                                        
/* output logic           */ .mem_pointers_0_init_done      (),                                        
/* Interface .rd_data     */ .mem_pointers_0_rd_data        (mem_pointers_0_if.rd_data),               
/* Interface .rd_valid    */ .mem_pointers_0_rd_valid       (mem_pointers_0_if.rd_valid),              
/* output logic           */ .mem_pointers_1_ecc_uncor_err  (),                                        
/* output logic           */ .mem_pointers_1_init_done      (),                                        
/* Interface .rd_data     */ .mem_pointers_1_rd_data        (mem_pointers_1_if.rd_data),               
/* Interface .rd_valid    */ .mem_pointers_1_rd_valid       (mem_pointers_1_if.rd_valid),              
/* output logic           */ .mem_pointers_2_ecc_uncor_err  (),                                        
/* output logic           */ .mem_pointers_2_init_done      (),                                        
/* Interface .rd_data     */ .mem_pointers_2_rd_data        (mem_pointers_2_if.rd_data),               
/* Interface .rd_valid    */ .mem_pointers_2_rd_valid       (mem_pointers_2_if.rd_valid),              
/* output logic           */ .mem_pointers_3_ecc_uncor_err  (),                                        
/* output logic           */ .mem_pointers_3_init_done      (),                                        
/* Interface .rd_data     */ .mem_pointers_3_rd_data        (mem_pointers_3_if.rd_data),               
/* Interface .rd_valid    */ .mem_pointers_3_rd_valid       (mem_pointers_3_if.rd_valid),              
/* output logic           */ .mem_pointers_4_ecc_uncor_err  (),                                        
/* output logic           */ .mem_pointers_4_init_done      (),                                        
/* Interface .rd_data     */ .mem_pointers_4_rd_data        (mem_pointers_4_if.rd_data),               
/* Interface .rd_valid    */ .mem_pointers_4_rd_valid       (mem_pointers_4_if.rd_valid),              
/* output logic           */ .mem_pointers_5_ecc_uncor_err  (),                                        
/* output logic           */ .mem_pointers_5_init_done      (),                                        
/* Interface .rd_data     */ .mem_pointers_5_rd_data        (mem_pointers_5_if.rd_data),               
/* Interface .rd_valid    */ .mem_pointers_5_rd_valid       (mem_pointers_5_if.rd_valid),              
/* output logic           */ .mem_pointers_6_ecc_uncor_err  (),                                        
/* output logic           */ .mem_pointers_6_init_done      (),                                        
/* Interface .rd_data     */ .mem_pointers_6_rd_data        (mem_pointers_6_if.rd_data),               
/* Interface .rd_valid    */ .mem_pointers_6_rd_valid       (mem_pointers_6_if.rd_valid),              
/* output logic           */ .mem_pointers_7_ecc_uncor_err  (),                                        
/* output logic           */ .mem_pointers_7_init_done      (),                                        
/* Interface .rd_data     */ .mem_pointers_7_rd_data        (mem_pointers_7_if.rd_data));               
// End of module gpm_shells_wrapper from gpm_shells_wrapper


// module gpm_sram_mems    from gpm_sram_mems using gpm_sram_mems.map 
gpm_sram_mems    gpm_sram_mems(
/* input  logic           */ .fary_ensleep_sram                  (fary_ensleep_sram),                       
/* input  logic           */ .car_raw_lan_power_good_with_byprst (1'b1),                                    
/* input  logic           */ .fary_enblfloat_sram                (fary_enblfloat_sram),                     
/* input  logic    [19:0] */ .fary_ffuse_data_misc_sram          (fary_ffuse_data_misc_sram),               
/* input  logic     [1:0] */ .fary_fwen_sram                     (fary_fwen_sram),                          
/* input  logic           */ .cclk                               (cclk),                                    
/* input  logic           */ .fary_pwren_b_sram                  (fary_pwren_b_sram),                       
/* input  logic           */ .fary_stm_enable                    (fary_stm_enable),                         
/* input  logic           */ .fary_stm_hilo                      (fary_stm_hilo),                           
/* input  logic           */ .fary_wakeup_sram                   (fary_wakeup_sram),                        
/* input  logic           */ .fdfx_lbist_test_mode               (fdfx_lbist_test_mode),                    
/* input  logic           */ .fscan_byprst_b                     (fscan_byprst_b),                          
/* input  logic           */ .fscan_mode                         (fscan_mode),                              
/* input  logic    [11:0] */ .fscan_ram_awt_mode                 (fscan_ram_awt_mode),                      
/* input  logic    [11:0] */ .fscan_ram_awt_ren                  (fscan_ram_awt_ren),                       
/* input  logic    [11:0] */ .fscan_ram_awt_wen                  (fscan_ram_awt_wen),                       
/* input  logic    [11:0] */ .fscan_ram_bypsel                   (fscan_ram_bypsel),                        
/* input  logic           */ .fscan_ram_init_en                  (fscan_ram_init_en),                       
/* input  logic           */ .fscan_ram_init_val                 (fscan_ram_init_val),                      
/* input  logic    [11:0] */ .fscan_ram_odis_b                   (fscan_ram_odis_b),                        
/* input  logic           */ .fscan_ram_rddis_b                  (fscan_ram_rddis_b),                       
/* input  logic           */ .fscan_ram_wrdis_b                  (fscan_ram_wrdis_b),                       
/* input  logic           */ .fscan_rstbypen                     (fscan_rstbypen),                          
/* input  logic    [56:0] */ .gpm_mem_pod_ptr_0_to_mem           (gpm_mem_pod_ptr_0_to_mem),                
/* input  logic    [56:0] */ .gpm_mem_pod_ptr_1_to_mem           (gpm_mem_pod_ptr_1_to_mem),                
/* input  logic    [56:0] */ .gpm_mem_pod_ptr_2_to_mem           (gpm_mem_pod_ptr_2_to_mem),                
/* input  logic    [56:0] */ .gpm_mem_pod_ptr_3_to_mem           (gpm_mem_pod_ptr_3_to_mem),                
/* input  logic  [2385:0] */ .gpm_mem_pointers_0_to_mem          (gpm_mem_pointers_0_to_mem),               
/* input  logic  [2385:0] */ .gpm_mem_pointers_1_to_mem          (gpm_mem_pointers_1_to_mem),               
/* input  logic  [2385:0] */ .gpm_mem_pointers_2_to_mem          (gpm_mem_pointers_2_to_mem),               
/* input  logic  [2385:0] */ .gpm_mem_pointers_3_to_mem          (gpm_mem_pointers_3_to_mem),               
/* input  logic  [2385:0] */ .gpm_mem_pointers_4_to_mem          (gpm_mem_pointers_4_to_mem),               
/* input  logic  [2385:0] */ .gpm_mem_pointers_5_to_mem          (gpm_mem_pointers_5_to_mem),               
/* input  logic  [2385:0] */ .gpm_mem_pointers_6_to_mem          (gpm_mem_pointers_6_to_mem),               
/* input  logic  [2385:0] */ .gpm_mem_pointers_7_to_mem          (gpm_mem_pointers_7_to_mem),               
/* output logic           */ .aary_pwren_b_sram                  (aary_pwren_b_sram),                       
/* output logic    [37:0] */ .gpm_mem_pod_ptr_0_from_mem         (gpm_mem_pod_ptr_0_from_mem),              
/* output logic    [37:0] */ .gpm_mem_pod_ptr_1_from_mem         (gpm_mem_pod_ptr_1_from_mem),              
/* output logic    [37:0] */ .gpm_mem_pod_ptr_2_from_mem         (gpm_mem_pod_ptr_2_from_mem),              
/* output logic    [37:0] */ .gpm_mem_pod_ptr_3_from_mem         (gpm_mem_pod_ptr_3_from_mem),              
/* output logic  [2352:0] */ .gpm_mem_pointers_0_from_mem        (gpm_mem_pointers_0_from_mem),             
/* output logic  [2352:0] */ .gpm_mem_pointers_1_from_mem        (gpm_mem_pointers_1_from_mem),             
/* output logic  [2352:0] */ .gpm_mem_pointers_2_from_mem        (gpm_mem_pointers_2_from_mem),             
/* output logic  [2352:0] */ .gpm_mem_pointers_3_from_mem        (gpm_mem_pointers_3_from_mem),             
/* output logic  [2352:0] */ .gpm_mem_pointers_4_from_mem        (gpm_mem_pointers_4_from_mem),             
/* output logic  [2352:0] */ .gpm_mem_pointers_5_from_mem        (gpm_mem_pointers_5_from_mem),             
/* output logic  [2352:0] */ .gpm_mem_pointers_6_from_mem        (gpm_mem_pointers_6_from_mem),             
/* output logic  [2352:0] */ .gpm_mem_pointers_7_from_mem        (gpm_mem_pointers_7_from_mem));             
// End of module gpm_sram_mems from gpm_sram_mems

endmodule // mby_gpm_gen_mem
