% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

/* $Id: m3makefile,v 1.1 2008/01/22 01:52:17 mika Exp $ */

import ("matrix")

implementation ("Main")

program ("test_mul")