import ("libm3")
import ("cit_util")
import ("parseparams")

Module ("BraceParse")
implementation ("Main")

module("OpenCharArray")

interface ("CellRec")

openarrayTable("CellRec", "OpenCharArray", "CellRec")

%library ("braceparse")
program ("testbrace")


