import ("libm3")
import ("cit_util")
import ("parseparams")

_exec(["../makekeywords/AMD64_LINUX/makekeywords","../src/key.words","NetKeywords"])

derived_interface("NetKeywords",HIDDEN)

Module ("BraceParse")
implementation ("Main")

module("OpenCharArray")

module ("CellRec")

openarrayTable("CellRec", "OpenCharArray", "CellRec")
openarrayTable("CharsAtom", "OpenCharArray", "Atom")


%library ("braceparse")

module("Subcell")
list ("Subcell", "Subcell")
sequence ("Subcell", "Subcell")
module ("MosInfo")

table ("MosInfoCard", "MosInfo", "CardPair")
table ("AtomCell", "Atom", "CellRec")

table ("AtomMosInfoCardTbl", "Atom", "MosInfoCardTbl")

openarrayTable ("OpenCharArrayRef", "OpenCharArray", "Refany")

program ("testbrace")


