
CPPFILES_COMPILER     := $(GCXX)
CPPFILES_PREPROCESSOR := $(CPPFILES_COMPILER) -E

CPPFILES_PROJECT_INCLUDE_DIRS := $(CURR_TARGET_DIR)/ $(CURR_PROJECT_DIR)/ $(JAVAFILES_JDK_ROOT)/include/ $(CURR_PROJECT_DIR)/transrecord/include

CPPFILES_PROJECT_INCLUDE_DIRS := $(CPPFILES_PROJECT_INCLUDE_DIRS) $(JAVAFILES_JNI_INCLUDE_DIR)
