% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import("cit_util")
import("mscheme")
import("sstubgen")
import("modula3scheme")
import("parseparams")
import("parseliberty")
import("ctlib")

implementation ("Main")

program ("libertyqc")
