import ("libm3")
import ("cit_util")
import ("parseparams")
import ("spicelib")
import ("spicebuilderlib")
import ("lambbuilderlib")

genMain("Lamb", "LambSimulation")

implementation ("Main")

program ("lambbuilder")
