% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("cit_util")
import ("spicelib")
import ("tracelib")
import ("regression")
import ("ctlib")
import ("spicecompress")
import ("mscheme")
import ("modula3scheme")
import ("sstubgen")
import ("minimize")
import ("integrate")

implementation ("TestTrans")

program ("testtrans")
