/* $Id: m3makefile,v 1.4 2011/02/13 22:54:48 mika Exp $ */

% we should do this all through cm3cfg

import_sys_lib("READLINE")

if equal(TARGET, "LINUXLIBC6")
        import_lib ("readline","/usr/lib")
end

if equal(TARGET, "PPC_DARWIN")
	import_lib ("ncurses","/usr/lib")
end

import ("libm3")

c_source ("program")

C_program("readlinefe")
