/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Readline_Keymap_Entry */

#ifndef _Included_Readline_Keymap_Entry
#define _Included_Readline_Keymap_Entry
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
