% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

/* $Id: m3makefile,v 1.1 2005/04/20 00:08:50 mika Exp $ */

import("libm3")
import("cit_util")
import("matrix")

implementation("Main")

program("x")
