/* $Id$ */
import("cit_common")
template("generics")
Interface("DblRefany")
Module("Debug")
Module("TextUtils")
implementation("TextUtilsFmt")
Generic_module("OpenArrayTable")
Generic_module("DblTable")
Generic_module("BrandedSet")
template("brandedset")
Generic_module("KeyPair")
template("keypair")
Module("SIsuffix")
table("Suffix", "Char", "SIsuffix")
template("dbltable")

KeyPair("Int", "Integer", "Integer")
List("IntPair", "IntPair")

Module("RTBrand")

Module("ToRefany")

gmodule("Ref")
gmodule("ArrayRef")
Gmodule("ToRefany")
Interface("ToRefanyClass")
table("ToRefany","Integer","ToRefanyClass")


/* this is a dumb hack.  to ensure that initialization code gets run,
   you MUST import xToRefany in ToRefanyPrivate (or in some other 
   module that does get run). */

implementation("ToRefanyPrivate")
template("to_refany")
ord_to_refany("Int", "Integer")
ord_to_refany("Bool", "Boolean")
ord_to_refany("Char", "Char")
ord_to_refany("Real", "RealType")
ord_to_refany("Longreal", "LongrealType")

/* new stuff */
MkSet("IntPair", "IntPair")
MkSetDef("IntPair", "IntPair")
Table("IntPairRef", "IntPair", "Refany")

/* used to be in ktoklib */
Module("TextSubs")
module("TextSubsClause")
list("TextSubsClause", "TextSubsClause")
table("TextSubsClauseList", "Char", "TextSubsClauseList")


Library("cit_util")



