/* $Id$ */

m3_option("-X2@-pg@")
m3_option("-g")
remove_m3_option("-O")
m3_option("-times")
import ("libm3")
Module("TextReader")
Module("Debug")
Module("TextUtils")
implementation("TextUtilsFmt")
Generic_module("OpenArrayTable")
Generic_module("DblTable")
Generic_interface("BrandedSet")
Module("SIsuffix")
table("Suffix", "Char", "SIsuffix")
template("dbltable")
Library("cit_util")

