import ("libm3")
import ("cit_util")
import ("parserlib")

Token("rdl")
Lexer("rdl","rdl")
Parser("rdl","rdl")

extended("rdlLexExt")
extended("rdlParseExt")

%library("rdlparse")

derived_interface ("RdlPredefProperty", VISIBLE)
derived_interface ("RdlPropertyModifier", VISIBLE)
derived_interface ("RdlPropertyComponent", VISIBLE)
derived_interface ("RdlPropertyRvalueKeyword", VISIBLE)
derived_interface ("RdlComponentDefType", VISIBLE)
derived_interface ("RdlOrigin",VISIBLE)

interface ("RdlRootElem")
interface ("RdlComponentDef")
interface ("RdlEnumDef")
interface ("RdlComponentDefClass")
interface ("RdlPropertyComponentDisjunction")

implementation ("Main")

program ("parserdl")
