import("cit_util")
import("mscheme")
import("sstubgen")
import("modula3scheme")
import("parseparams")
import("parseliberty")
import("ctlib")
import("techc")

implementation ("Main")

program ("libertyscale")
