(load "parts/pe_top.scm")

( define mymax 500 )
( define alu_add_op 0 )
( define alu_sub_op 1 )
( define alu_mult_op 2 )
( define alu_div_op 3 )

; Original ALU Tests
( define ( fibonacci_alu_add x )
	( let ( ( max_index mymax ) )
		( let loop ( ( xn 1 ) ( xnminus1 0 ) ( index 0 ) )
			( if ( = index max_index )
				xn
				( loop ( alu xn xnminus1 alu_add_op ) xn ( + index 1 ) )
			)
		)
	)
)

( define ( fibonacci_alu_sub x )
	( let ( ( max_index mymax ) )
		( let loop ( ( xn 1 ) ( xnminus1 0 ) ( index 0 ) )
			( if ( = index max_index )
				xn
				( loop ( alu xn xnminus1 alu_sub_op ) xn ( + index 1 ) )
			)
		)
	)
)

( define ( fibonacci_alu_mult x )
	( let ( ( max_index mymax ) )
		( let loop ( ( xn 1 ) ( xnminus1 3 ) ( index 0 ) )
			( if ( = index max_index )
				xn
				( loop ( alu xn xnminus1 alu_mult_op ) xnminus1 ( + index 1 ) )
			)
		)
	)
)

( define ( fibonacci_alu_div x )
	( let ( ( max_index mymax ) )
		( let loop ( ( xn ( expt 3 500 ) ) ( xnminus1 3 ) ( index 0 ) )
			( if ( = index max_index )
				xn
				( loop ( alu xn xnminus1 alu_div_op ) xnminus1 ( + index 1 ) )
			)
		)
	)
)

; PE ALU Tests
( define ( fibonacci_pe_add x )
	( let ( ( max_index mymax ) )
		( let loop ( ( xn 1 ) ( xnminus1 0 ) ( index 0 ) )
			( if ( = index max_index )
				xn
				( loop ( add_alu xn xnminus1 ) xn ( + index 1 ) )
			)
		)
	)
)

( define ( fibonacci_pe_sub x )
	( let ( ( max_index mymax ) )
		( let loop ( ( xn 1 ) ( xnminus1 0 ) ( index 0 ) )
			( if ( = index max_index )
				xn
				( loop ( sub_alu xn xnminus1 ) xn ( + index 1 ) )
			)
		)
	)
)

( define ( fibonacci_pe_mult x )
	( let ( ( max_index mymax ) )
		( let loop ( ( xn 1 ) ( xnminus1 3 ) ( index 0 ) )
			( if ( = index max_index )
				xn
				( loop ( mult_alu xn xnminus1 ) xnminus1 ( + index 1 ) )
			)
		)
	)
)

( define ( fibonacci_pe_div x )
	( let ( ( max_index mymax ) )
		( let loop ( ( xn ( expt 3 500 ) ) ( xnminus1 3 ) ( index 0 ) )
			( if ( = index max_index )
				xn
				( loop ( div_alu xn xnminus1 ) xnminus1 ( + index 1 ) )
			)
		)
	)
)
( define ( fibonacci_speed_test x )
	( let ( ( alu_time1 0 )
		( alu_time2 0 )
		( pe_time1 0 )
		( pe_time2 0 )
		( maxtestiter 100000 )
		( add_result 0 )
		( add_result_pe 0 )
		( sub_result 0 )
		( sub_result_pe 0 )
		( mult_result 0 )
		( mult_result_pe 0 )
		( div_result 0 )
		( div_result_pe 0 )
	      )
		; Old ALU - add
		( set! alu_time1 ( current-time ) )
		( let loop ( ( index 0 ) )
			( fibonacci_alu_add 1 )
			( if ( not ( = maxtestiter index ) )
				( loop ( + index 1 ) )
			)
		)
		( set! alu_time2 ( current-time ) )
		( set! add_result ( fibonacci_alu_add 1 ) )

		; PE ALU - add
		( set! pe_time1 ( current-time ) )
		( let loop ( ( index 0 ) )
			( fibonacci_pe_add 1 )
			( if ( not ( = maxtestiter index ) )
				( loop ( + index 1 ) )
			)
		)
		( set! pe_time2 ( current-time ) )
		( set! add_result_pe ( fibonacci_pe_add 1 ) )
		( if ( = add_result add_result_pe )
			( let ( )
				( display "Add results match!" )
				( newline )
			)
			( let ( )
				( display "Add results mismatch!" )
				( newline )
			)
		)
		( display "ALU add Time: " )
		( display ( - alu_time2 alu_time1 ) )
		( newline )
		( display "PE add Time: " )
		( display ( - pe_time2 pe_time1 ) )
		( newline )

		; Old ALU - sub
		( set! alu_time1 ( current-time ) )
		( let loop ( ( index 0 ) )
			( fibonacci_alu_sub 1 )
			( if ( not ( = maxtestiter index ) )
				( loop ( + index 1 ) )
			)
		)
		( set! alu_time2 ( current-time ) )
		( set! sub_result ( fibonacci_alu_sub 1 ) )

		; PE ALU - sub
		( set! pe_time1 ( current-time ) )
		( let loop ( ( index 0 ) )
			( fibonacci_pe_sub 1 )
			( if ( not ( = maxtestiter index ) )
				( loop ( + index 1 ) )
			)
		)
		( set! pe_time2 ( current-time ) )
		( set! sub_result_pe ( fibonacci_pe_sub 1 ) )
		( if ( = sub_result sub_result_pe )
			( let ( )
				( display "Sub results match!" )
				( newline )
			)
			( let ( )
				( display "Sub results mismatch!" )
				( newline )
			)
		)
		( display "ALU sub Time: " )
		( display ( - alu_time2 alu_time1 ) )
		( newline )
		( display "PE sub Time: " )
		( display ( - pe_time2 pe_time1 ) )
		( newline )

		; Old ALU - mult
		( set! alu_time1 ( current-time ) )
		( let loop ( ( index 0 ) )
			( fibonacci_alu_mult 1 )
			( if ( not ( = maxtestiter index ) )
				( loop ( + index 1 ) )
			)
		)
		( set! alu_time2 ( current-time ) )
		( set! mult_result ( fibonacci_alu_mult 1 ) )

		; PE ALU - mult
		( set! pe_time1 ( current-time ) )
		( let loop ( ( index 0 ) )
			( fibonacci_pe_mult 1 )
			( if ( not ( = maxtestiter index ) )
				( loop ( + index 1 ) )
			)
		)
		( set! pe_time2 ( current-time ) )
		( set! mult_result_pe ( fibonacci_pe_mult 1 ) )
		( if ( = mult_result mult_result_pe )
			( let ( )
				( display "Mult results match!" )
				( newline )
			)
			( let ( )
				( display "Mult results mismatch!" )
				( newline )
			)
		)
		( display "ALU mult Time: " )
		( display ( - alu_time2 alu_time1 ) )
		( newline )
		( display "PE mult Time: " )
		( display ( - pe_time2 pe_time1 ) )
		( newline )

		; Old ALU - div
		( set! alu_time1 ( current-time ) )
			( let loop ( ( index 0 ) )
				( fibonacci_alu_div 1 )
				( if ( not ( = maxtestiter index ) )
					( loop ( + index 1 ) )
				)
			)
		( set! alu_time2 ( current-time ) )
		( set! div_result ( fibonacci_alu_div 1 ) )

		; PE ALU - div
		( set! pe_time1 ( current-time ) )
		( let loop ( ( index 0 ) )
			( fibonacci_pe_div 1 )
			( if ( not ( = maxtestiter index ) )
				( loop ( + index 1 ) )
			)
		)
		( set! pe_time2 ( current-time ) )
		( set! div_result_pe ( fibonacci_pe_div 1 ) )
		( if ( = div_result div_result_pe )
			( let ( )
				( display "Div results match!" )
				( newline )
			)
			( let ( )
				( display "Div results mismatch!" )
				( newline )
			)
		)
		( display "ALU div Time: " )
		( display ( - alu_time2 alu_time1 ) )
		( newline )
		( display "PE div Time: " )
		( display ( - pe_time2 pe_time1 ) )
		( newline )
	)
)
( fibonacci_speed_test 1 )
( exit )
