
import("libm3")
import("cit_util")


% system header glue

h_source("termios")
interface("Termios")
Interface("TermHooks")


% terminal interfaces

Module("Term")
Module("TermIO")
implementation("TermObject")


% command line utilities

Module("Cooker")
Module("CommandLoop")
Gmodule("CommandLoop")
implementation("CommandLoopDefaultCommand")
Interface("BrandedCommand")
Table("TextCommand", "Text", "BrandedCommand")
Module("ScalarVar")

library("term")
