PROGFILES_VARS_CHANGED_STACK :=$(PROGFILES_VARS_CHANGED) $(PROGFILES_VARS_CHANGED_STACK)
PROGFILES_VARS_CHANGED :=0

PROGFILES_PROGFILES_CUSTOM_MK := $(wildcard $(CURR_PROJECT_DIR)/progfiles-custom.mk)
ifneq ("$(strip $(PROGFILES_PROGFILES_CUSTOM_MK))","")

PROGFILES_LINKER_TEMP := $(PROGFILES_LINKER)

PROGFILES_PROJECT_LIB_DIRS_TEMP := $(PROGFILES_PROJECT_LIB_DIRS)

PROGFILES_PROJECT_LIBS_TEMP := $(PROGFILES_PROJECT_LIBS)

PROGFILES_PROJECT_LINK_FLAGS_TEMP := $(PROGFILES_PROJECT_LINK_FLAGS)

-include $(CURR_PROJECT_DIR)/progfiles-custom.mk

ifneq ("$(strip $(PROGFILES_LINKER_TEMP))","$(strip $(PROGFILES_LINKER))")
PROGFILES_VARS_CHANGED :=1
else
ifneq ("$(strip $(PROGFILES_PROJECT_LIB_DIRS_TEMP))","$(strip $(PROGFILES_PROJECT_LIB_DIRS))")
PROGFILES_VARS_CHANGED :=1
else
ifneq ("$(strip $(PROGFILES_PROJECT_LIBS_TEMP))","$(strip $(PROGFILES_PROJECT_LIBS))")
PROGFILES_VARS_CHANGED :=1
else
ifneq ("$(strip $(PROGFILES_PROJECT_LINK_FLAGS_TEMP))","$(strip $(PROGFILES_PROJECT_LINK_FLAGS))")
PROGFILES_VARS_CHANGED :=1
endif
endif
endif
endif


ifeq ($(PROGFILES_VARS_CHANGED),1)

PUSH_SCOPED_VAR_VAR_NAME := PROGFILES_LINKER
include $(BUILD_SYSTEM_ROOT)/include-functions/pushscopedvar.mk

PUSH_SCOPED_VAR_VAR_NAME := PROGFILES_PROJECT_LIB_DIRS
include $(BUILD_SYSTEM_ROOT)/include-functions/pushscopedvar.mk

PUSH_SCOPED_VAR_VAR_NAME := PROGFILES_PROJECT_LIBS
include $(BUILD_SYSTEM_ROOT)/include-functions/pushscopedvar.mk

PUSH_SCOPED_VAR_VAR_NAME := PROGFILES_PROJECT_LINK_FLAGS
include $(BUILD_SYSTEM_ROOT)/include-functions/pushscopedvar.mk

endif

endif

PROGFILES_LIB_DIRS := $(PROGFILES_PROJECT_LIB_DIRS) $(SYSTEM_LIB_DIRS)

PROGFILES_LIB_PATH_SWITCHES := $(foreach dir, $(PROGFILES_LIB_DIRS), -L$(dir) )

PROGFILES_LIBRARIES := $(PROGFILES_PROJECT_LIBS) $(SYSTEM_LIBS)

PROGFILES_LIB_SWITCHES := $(foreach lib, $(PROGFILES_LIBRARIES), -l$(lib) )

PROGFILES_LD_PREFIX := $(PROGFILES_LINKER) $(PROGFILES_LIB_PATH_SWITCHES) $(PROGFILES_PROJECT_LINK_FLAGS)

PROGFILES_LD_POSTFIX := $(PROGFILES_LIB_SWITCHES)

PROGFILES_LD := $(PROGFILES_LD_PREFIX) $(PROGFILES_LD_POSTFIX)

PROGFILES_LOCAL_LD-$(CURR_TARGET_DIR) := $(PROGFILES_LD)

PROGFILES_LOCAL_LD_PREFIX-$(CURR_TARGET_DIR) := $(PROGFILES_LD_PREFIX)

PROGFILES_LOCAL_LD_POSTFIX-$(CURR_TARGET_DIR) := $(PROGFILES_LD_POSTFIX)
