(define ffu-enums
  `((enum mby-classifier-act1
          u8
          ((m3 MbyClassifierAct1))
          (
           (drop           0)
           (trap           1)
           (log            2)
           (no-route               3)
           (rx-mirror              4)
           (capt-time              5)
           (tx-tag0                6)
           (tx-tag1                7)
           (trigger0               8)
           (trigger1               9)
           (trigger2               10)
           (trigger3               11)
           (trigger4               12)
           (trigger5               13)
           (trigger6               14)
           (trigger7               15)
           (scenario0              16)
           (scenario1              17)
           (scenario2              18)
           (scenario3              19)
           (scenario4              20)
           (scenario5              21)
           (learn          22)
           (copy-otr-vpri          23)

           ))
    
    (enum mby-classifier-act4
          u8
          ((m3 MbyClassifierAct4))
          (
           (dscp-ctrl              0)
           (ttl-ctrl               1)
           (tc-ctrl                2)
           (ecn-ctrl               3)
           (vid-low                4)
           (vid-mid                5)
           (vid-high               6)
           (vpri-low               7)
           (dscp-low               8)
           (dscp-high              9)
           (tc             10)
           (vpri-high              11)
           (hash-profile-ecmp-0            12)
           (hash-profile-ecmp-1            13)
           (hash-profile-mod-0             14)
           (hash-profile-mod-1             15)
           (meta0-low              16)
           (meta0-high             17)
           (meta1-low              18)
           (meta1-high             19)
           (meta2-low              20)
           (meta2-high             21)
           (mpls-pop               22)

           ))

    (enum mby-classifier-act24
          u8
          ((m3 MbyClassifierAct24))
          (
           (policer0               0)
           (policer1               1)
           (policer2               2)
           (policer3               3)
           (fwd            4)
           (mod-idx                5)
           (remap0         6)
           (remap1         7)
           (remap2         8)
           (remap3         9)
           (remap4         10)
           (remap5         11)
           (remap6         12)
           (remap7         13)
           ))
    )
  )

(compile! ffu-enums)
