import ("libm3")
import ("parseparams")
import ("wm_support")
import ("wm_net")
import ("hlp")

module ("ModelServer")
interface ("ModelServerClass")
module("MsIosf")
%interface ("MsIosf")
module ("HlpModelServer")

module ("DataPusher")
table ("IntDataPusher", "Integer", "DataPusher")

implementation ("Main")

program ("modelserver")
