import ("libm3")
import ("parseparams")
import ("wm_support")
import ("wm_net")
import ("hlp")
import ("mby")
import ("mscheme")
import ("modula3scheme")
import ("netobj")
import ("sstubgen")

_exec(["../../structgen/AMD64_LINUX/structgen","../../wm_net/src/structgen_shared.scm","../../wm_net/src/structgen_m3.scm","../../wm_net/src/structs_m3.scm", "../src/actionsets.scm", "../src/enums.scm", "../src/ffu_enums.scm", "../src/mapper_constants.scm", "../src/parser_constants.scm", "exit"])
include ("../AMD64_LINUX/derived.m3m")

module ("ModelServer")

%module ("HlpModelServer")
% NO -- CANT PULL THIS IN HERE!  The reason is that this will pull in
% the entire register def of HLP into the Scheme name mangling, which
% is too big for us to handle (at least with any speed).
%
% Instead, if we want to get at the HLP regs from Scheme,
% we have to do so in some roundabout way.  (not as yet defined)
% ... more to come ...
%

interface ("ModelServerClass")
module("MsIosf")
%interface ("MsIosf")
module ("HlpModelServer")

module ("DataPusher")
table ("IntDataPusher", "Integer", "DataPusher")
table ("CardByte", "Cardinal", "Byte")

module ("HlpModel")
module ("MbyModel")

Generic_module("BaseModelServer")
module("MbyModelServer")

interface("BaseModelStage")
module("Metadata")
Generic_module("ModelStage")
module ("ModelStageResult")
interface ("ModelStageResultClass")


interface ("MbyTypes")
interface ("MbyMeta")
interface ("MbyParserTypes")
%interface ("MbyParserSizes")
interface ("MbyMacToParserMeta")
interface ("MbyParserToMapperMeta")
interface ("MbyParserToModifierMeta")
interface ("MbyParserInfo")
interface ("MbyMapperToClassifierMeta")
interface ("MbyFfuTypes")

module ("MbyParserStage")
module ("MbyParserStageModel")
interface ("MbyParserMeta")

%interface ("MbyMapperSizes")
module ("MbyMapperStage")
module ("MbyMapperStageModel")
module ("MbyDoRealignKeys")

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% just testing stuff
module ("HlpRepStageModel")
module ("HlpRepStage")

SchemeStubs ("ModelServer")

ExportSchemeStubs("model_server")
importSchemeStubs()              % import ALL scheme stubs

implementation ("Main")

program ("modelserver")
