SYSTEM_CC = SYSTEM_CC & " -std=gnu99"

h_source ("mby_common")
c_source ("mby_common")

h_source ("mby_parser")
c_source ("mby_parser")

h_source ("mby_mapper")
c_source ("mby_mapper")

c_source ("mby_model_basic")

h_source ("fm_bitfield")
c_source ("fm_bitfield")

h_source ("fm_defs")
h_source ("fm_types")

library ("mby_c_model")
