/* $Id: m3makefile,v 1.2 2009/04/24 07:36:44 mika Exp $ */



if defined("pm3_version")
	option("optimization","") 
end


import("libm3")
import("cit_util")
import("mscheme")
import("modula3scheme")
import("schemesig")
import("m3readline")
import("schemereadline")

implementation("Main")

program("mscheme-doc")
