/* $Id$ */

import ("libm3")
import ("mscheme")
%import ("finlib")
import ("rdwr")
import ("tz")

Generic_module("SchemeAutoTbl")
template ("schemeautotbl")

Interface("SchemeJailBreak")

Module ("SchemeM3TableOps")

Module("M3toSTextString")

Module("M3toSRefany")
SchemeAutoTbl("TextRef", "TextRefTbl", "M3toSTextString", "M3toSRefany")

KeyPair("CardAtom", "Cardinal", "Atom")

table("CARef", "CardAtomPair", "Refany")

Table("AtomCard", "Atom", "Cardinal")

Module("SchemeM3")
Module("SchemeCommandRunner")

Module("SchemeModula3Types")

Module("SchemeApply")

Module("SchemeProcedureStubs")

library ("modula3scheme")
