import ("libm3")
import ("tcp")
import ("udp")
import ("cit_util")

module ("UdpDatagram")
sequence ("UdpDatagram", "UdpDatagram")
module ("UdpAdapter")
module ("ReorderUdpAdapter")

implementation ("Main")

program ("udptest")
