import ("libm3")
import ("parseparams")
import ("cit_util")
import ("tracelib")

interface ("TechConfig")
interface ("TechProcess")
module ("TechSimulate")

interface ("N5TechProcess")
interface ("N3TechProcess")
interface ("N3ETechProcess")

interface ("P1276p4TechProcess")
interface ("P1276p4_g1m_TechProcess") % this is the 4nm lib in the 3nm proc
interface ("P1276p4_aml1_TechProcess") % Andrew's extracted 2-fin
interface ("P1276p4_aml2_TechProcess") % Andrew's extracted 2-fin
interface ("P1278p3TechProcess")

interface ("TechTechs")
interface ("TechProgress")

module ("Watchdog")
module ("TechKill")
module ("TechConvert")
module ("TechMeasure")

Module ("TechSetup")
Interface ("TechTemplate")

Module ("TechLookup")

module ("SimWatcher")

implementation ("Main")

program ("techc")
library ("techc")
