


CFILES_VARS_CHANGED_STACK :=$(CFILES_VARS_CHANGED) $(CFILES_VARS_CHANGED_STACK)
CFILES_VARS_CHANGED :=0


CFILES_CFILES_CUSTOM_MK := $(wildcard $(CURR_PROJECT_DIR)/cfiles-custom.mk)

ifneq ("$(strip $(CFILES_CFILES_CUSTOM_MK))","")

CFILES_COMPILER_TEMP               := $(CFILES_COMPILER)
CFILES_PREPROCESSOR_TEMP           := $(CFILES_PREPROCESSOR)
CFILES_PRE_PROCESSOR_DEFINES_TEMP  := $(CFILES_PRE_PROCESSOR_DEFINES)
CFILES_PROJECT_INCLUDE_DIRS_TEMP   := $(CFILES_PROJECT_INCLUDE_DIRS)
CFILES_GENERATED_INCLUDE_DIRS_TEMP := $(CFILES_GENERATED_INCLUDE_DIRS)
CFILES_C_COMPILE_FLAGS_TEMP        := $(CFILES_C_COMPILE_FLAGS)

-include $(CURR_PROJECT_DIR)/cfiles-custom.mk 


ifneq ("$(strip $(CFILES_COMPILER_TEMP))","$(strip $(CFILES_COMPILER))")
CFILES_VARS_CHANGED :=1
else
ifneq ("$(strip $(CFILES_PREPROCESSOR_TEMP))","$(strip $(CFILES_PREPROCESSOR))")
CFILES_VARS_CHANGED :=1
else
ifneq ("$(strip $(CFILES_PRE_PROCESSOR_DEFINES_TEMP))","$(strip $(CFILES_PRE_PROCESSOR_DEFINES))")
CFILES_VARS_CHANGED :=1
else
ifneq ("$(strip $(CFILES_PROJECT_INCLUDE_DIRS_TEMP))","$(strip $(CFILES_PROJECT_INCLUDE_DIRS))")
CFILES_VARS_CHANGED :=1
else
ifneq ("$(strip $(CFILES_GENERATED_INCLUDE_DIRS_TEMP))","$(strip $(CFILES_GENERATED_INCLUDE_DIRS))")
CFILES_VARS_CHANGED :=1
else
ifneq ("$(strip $(CFILES_C_COMPILE_FLAGS_TEMP))","$(strip $(CFILES_C_COMPILE_FLAGS))")
CFILES_VARS_CHANGED :=1
endif
endif
endif
endif
endif
endif

ifeq ($(CFILES_VARS_CHANGED),1)

PUSH_SCOPED_VAR_VAR_NAME := CFILES_COMPILER
include $(BUILD)/include-functions/pushscopedvar.mk

PUSH_SCOPED_VAR_VAR_NAME := CFILES_PREPROCESSOR
include $(BUILD)/include-functions/pushscopedvar.mk

PUSH_SCOPED_VAR_VAR_NAME := CFILES_PRE_PROCESSOR_DEFINES
include $(BUILD)/include-functions/pushscopedvar.mk

PUSH_SCOPED_VAR_VAR_NAME := CFILES_PROJECT_INCLUDE_DIRS
include $(BUILD)/include-functions/pushscopedvar.mk

PUSH_SCOPED_VAR_VAR_NAME := CFILES_GENERATED_INCLUDE_DIRS
include $(BUILD)/include-functions/pushscopedvar.mk

PUSH_SCOPED_VAR_VAR_NAME := CFILES_C_COMPILE_FLAGS
include $(BUILD)/include-functions/pushscopedvar.mk

endif

endif


CURR_TARGET_C_FILES     := $(wildcard $(CURR_PROJECT_DIR)/*.c )
ifneq ("$(strip $(CURR_TARGET_C_FILES))","")

CFILES_CURR_INCLUDE_DIRS          := $(CFILES_PROJECT_INCLUDE_DIRS) $(SYSTEM_INCLUDE_DIRS) $(CFILES_GENERATED_INCLUDE_DIRS)
CFILES_CURR_INCLUDE_PATH_SWITCHES := $(foreach dir, $(CFILES_CURR_INCLUDE_DIRS),-I$(dir))

CFILES_CURR_PRE_PROCESSOR_DEFINES          := $(CFILES_PRE_PROCESSOR_DEFINES)      \
                                              $(SYSTEM_DEFINES) 
CFILES_CURR_PRE_PROCESSOR_DEFINES_SWITCHES := $(foreach def,$(CFILES_CURR_PRE_PROCESSOR_DEFINES),-D$(def))

CFILES_CURR_CC    := $(CFILES_COMPILER) $(CFILES_C_COMPILE_FLAGS) $(CFILES_CURR_INCLUDE_PATH_SWITCHES) $(CFILES_CURR_PRE_PROCESSOR_DEFINES_SWITCHES)
CFILES_CURR_PRECC := $(CFILES_PREPROCESSOR) $(CFILES_CURR_INCLUDE_PATH_SWITCHES) \
                     $(CFILES_CURR_PRE_PROCESSOR_DEFINES_SWITCHES) -DFULCRUM_EXCLUDED_GENERATED_INCLUDES


CURR_TARGET_DEPS        := $(patsubst $(CURR_PROJECT_DIR)/%.c, $(CURR_TARGET_DIR)/%.d, $(CURR_TARGET_C_FILES) ) $(CURR_TARGET_DEPS)


CFILES_C_OBJS         := $(patsubst $(CURR_PROJECT_DIR)/%.c, $(CURR_TARGET_DIR)/%.o, $(CURR_TARGET_C_FILES) )

LIBFILES_TARGET_LD_OBJS     :=  $(CFILES_C_OBJS) $(LIBFILES_TARGET_LD_OBJS)

CURR_INTERMEDIATE_FILES := $(CFILES_C_OBJS) $(CURR_INTERMEDIATE_FILES)

CFILES_LOCAL_CC-$(CURR_TARGET_DIR) := $(CFILES_CURR_CC)

$(CURR_TARGET_DIR)/%.o: $(CURR_PROJECT_DIR)/%.c
	$(CFILES_LOCAL_CC-$(strip $(@D))) -c -o $@ $<

CFILES_LOCAL_PRECC-$(CURR_TARGET_DIR) := $(CFILES_CURR_PRECC)

$(CURR_TARGET_DEPS): $(foreach dir, $(CFILES_GENERATED_INCLUDE_DIRS), $(dir)/.sometimesmakesucks)

$(CURR_TARGET_DIR)/%.d: $(CURR_PROJECT_DIR)/%.c
	$(CFILES_LOCAL_PRECC-$(strip $(@D))) -MM -MG $< | $(GNUSED) -e "s/.*\.o\:/$(subst /,\/,$(@D)/$(*F)).o:/" >$@


endif
