#!/usr/intel/bin/perl -w

# find relevant packaged tools and libraries
BEGIN {
    $lve_root = $0;
    $lve_root =~ s:/[^/]*$::;
    $lve_root =~ s:/[^/]*$::;
    @INC = ("$lve_root/lib/perl", @INC);
}
use LveStatus;

# pick bound to look for
my $report_nodes = 0;
if (@ARGV && $ARGV[0] eq "--nodes") { $report_nodes = 1; shift; }
@ARGV == 2 or die "USAGE: find_bumps [--nodes] max_ok_bump cc\n";
my $bump_bound = $ARGV[0];
my $cc = $ARGV[1];

# find all bumps of greater than bump_bound
open IN, "find . -noleaf -name alint.raw|" or die "ERROR: can't find alint.raw\n";
my %cells = ();
my %nodes = ();
while (my $file = <IN>) {
    my @raw = get_lines("$file");
    foreach my $line (sort @raw) {
        my ($status, $task, $cell, $path, %results) = parse_raw_line($line);
        if (defined $results{bump_up} && defined $results{bump_dn}) {
            my ($bump_dn) = split("@",$results{bump_dn});
            my ($bump_up) = split("@",$results{bump_up});
            if ($results{cc} != $cc) { next; }
            if ($bump_up>$bump_bound || $bump_dn>$bump_bound) {
                $cells{$cell}=1;
                my $bump = $bump_up>$bump_dn ? $bump_up : $bump_dn;
                if (!defined($nodes{"$cell/$results{node}"}) ||
                    $bump > $nodes{"$cell/$results{node}"}) {
                    $nodes{"$cell/$results{node}"} = $bump;
                }
            }
        }
    }
}
close IN;

# print all cells with bumps
if ($report_nodes) {
    foreach my $node (sort keys %nodes) {
        print "$node $nodes{$node}\n";
    }
} else {
    foreach my $cell (sort keys %cells) {
        print "$cell\n";
    }
}
