import ("libm3")
import ("cit_util")
import ("parseparams")
import ("spicelib")
import ("ctlib")

implementation ("SisLaunch")
interface ("SisTask")

module ("FileMonitor")

sequence ("SisTask", "SisTask")
program ("sislaunch")
