(
(gmp_randinit void gmp_randstate_t gmp_randalg_t ...)
(gmp_randinit_default void gmp_randstate_t)
(gmp_randinit_lc_2exp void gmp_randstate_t mpz_srcptr unsigned-long-int mp_bitcnt_t)
(gmp_randinit_lc_2exp_size int gmp_randstate_t mp_bitcnt_t)
(gmp_randinit_mt void gmp_randstate_t)
(gmp_randinit_set void gmp_randstate_t const-__gmp_randstate_struct-*)
(gmp_randseed void gmp_randstate_t mpz_srcptr)
(gmp_randseed_ui void gmp_randstate_t unsigned-long-int)
(gmp_randclear void gmp_randstate_t)
(gmp_urandomb_ui unsigned-long gmp_randstate_t unsigned-long)
(gmp_urandomm_ui unsigned-long gmp_randstate_t unsigned-long)
(gmp_asprintf int char-** const-char-* ...)
(gmp_fprintf int FILE-* const-char-* ...)
(gmp_obstack_printf int struct-obstack-* const-char-* ...)
(gmp_obstack_vprintf int struct-obstack-* const-char-* va_list)
(gmp_printf int const-char-* ...)
(gmp_snprintf int char-* size_t const-char-* ...)
(gmp_sprintf int char-* const-char-* ...)
(gmp_vasprintf int char-** const-char-* va_list)
(gmp_vfprintf int FILE-* const-char-* va_list)
(gmp_vprintf int const-char-* va_list)
(gmp_vsnprintf int char-* size_t const-char-* va_list)
(gmp_vsprintf int char-* const-char-* va_list)
(gmp_fscanf int FILE-* const-char-* ...)
(gmp_scanf int const-char-* ...)
(gmp_sscanf int const-char-* const-char-* ...)
(gmp_vfscanf int FILE-* const-char-* va_list)
(gmp_vscanf int const-char-* va_list)
(gmp_vsscanf int const-char-* const-char-* va_list)
(_mpz_realloc void-* mpz_ptr mp_size_t)
(mpz_abs void mpz_ptr mpz_srcptr)
(mpz_add void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_add_ui void mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_addmul void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_addmul_ui void mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_and void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_array_init void mpz_ptr mp_size_t mp_size_t)
(mpz_bin_ui void mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_bin_uiui void mpz_ptr unsigned-long-int unsigned-long-int)
(mpz_cdiv_q void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_cdiv_q_2exp void mpz_ptr mpz_srcptr mp_bitcnt_t)
(mpz_cdiv_q_ui unsigned-long-int mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_cdiv_qr void mpz_ptr mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_cdiv_qr_ui unsigned-long-int mpz_ptr mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_cdiv_r void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_cdiv_r_2exp void mpz_ptr mpz_srcptr mp_bitcnt_t)
(mpz_cdiv_r_ui unsigned-long-int mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_cdiv_ui unsigned-long-int mpz_srcptr unsigned-long-int)
(mpz_clear void mpz_ptr)
(mpz_clears void mpz_ptr ...)
(mpz_clrbit void mpz_ptr mp_bitcnt_t)
(mpz_cmp int mpz_srcptr mpz_srcptr)
(mpz_cmp_d int mpz_srcptr double)
(_mpz_cmp_si int mpz_srcptr signed-long-int)
(_mpz_cmp_ui int mpz_srcptr unsigned-long-int)
(mpz_cmpabs int mpz_srcptr mpz_srcptr)
(mpz_cmpabs_d int mpz_srcptr double)
(mpz_cmpabs_ui int mpz_srcptr unsigned-long-int)
(mpz_com void mpz_ptr mpz_srcptr)
(mpz_combit void mpz_ptr mp_bitcnt_t)
(mpz_congruent_p int mpz_srcptr mpz_srcptr mpz_srcptr)
(mpz_congruent_2exp_p int mpz_srcptr mpz_srcptr mp_bitcnt_t)
(mpz_congruent_ui_p int mpz_srcptr unsigned-long unsigned-long)
(mpz_divexact void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_divexact_ui void mpz_ptr mpz_srcptr unsigned-long)
(mpz_divisible_p int mpz_srcptr mpz_srcptr)
(mpz_divisible_ui_p int mpz_srcptr unsigned-long)
(mpz_divisible_2exp_p int mpz_srcptr mp_bitcnt_t)
(mpz_dump void mpz_srcptr)
(mpz_export void-* void-* size_t-* int size_t int size_t mpz_srcptr)
(mpz_fac_ui void mpz_ptr unsigned-long-int)
(mpz_2fac_ui void mpz_ptr unsigned-long-int)
(mpz_mfac_uiui void mpz_ptr unsigned-long-int unsigned-long-int)
(mpz_primorial_ui void mpz_ptr unsigned-long-int)
(mpz_fdiv_q void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_fdiv_q_2exp void mpz_ptr mpz_srcptr mp_bitcnt_t)
(mpz_fdiv_q_ui unsigned-long-int mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_fdiv_qr void mpz_ptr mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_fdiv_qr_ui unsigned-long-int mpz_ptr mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_fdiv_r void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_fdiv_r_2exp void mpz_ptr mpz_srcptr mp_bitcnt_t)
(mpz_fdiv_r_ui unsigned-long-int mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_fdiv_ui unsigned-long-int mpz_srcptr unsigned-long-int)
(mpz_fib_ui void mpz_ptr unsigned-long-int)
(mpz_fib2_ui void mpz_ptr mpz_ptr unsigned-long-int)
(mpz_fits_sint_p int mpz_srcptr)
(mpz_fits_slong_p int mpz_srcptr)
(mpz_fits_sshort_p int mpz_srcptr)
(mpz_fits_uint_p int mpz_srcptr)
(mpz_fits_ulong_p int mpz_srcptr)
(mpz_fits_ushort_p int mpz_srcptr)
(mpz_gcd void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_gcd_ui unsigned-long-int mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_gcdext void mpz_ptr mpz_ptr mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_get_d double mpz_srcptr)
(mpz_get_d_2exp double signed-long-int-* mpz_srcptr)
(mpz_get_si /*-signed-*/-long-int mpz_srcptr)
(mpz_get_str char-* char-* int mpz_srcptr)
(mpz_get_ui unsigned-long-int mpz_srcptr)
(mpz_getlimbn mp_limb_t mpz_srcptr mp_size_t)
(mpz_hamdist mp_bitcnt_t mpz_srcptr mpz_srcptr)
(mpz_import void mpz_ptr size_t int size_t int size_t const-void-*)
(mpz_init void mpz_ptr)
(mpz_init2 void mpz_ptr mp_bitcnt_t)
(mpz_inits void mpz_ptr ...)
(mpz_init_set void mpz_ptr mpz_srcptr)
(mpz_init_set_d void mpz_ptr double)
(mpz_init_set_si void mpz_ptr signed-long-int)
(mpz_init_set_str int mpz_ptr const-char-* int)
(mpz_init_set_ui void mpz_ptr unsigned-long-int)
(mpz_inp_raw size_t mpz_ptr FILE-*)
(mpz_inp_str size_t mpz_ptr FILE-* int)
(mpz_invert int mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_ior void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_jacobi int mpz_srcptr mpz_srcptr)
(mpz_kronecker_si int mpz_srcptr long)
(mpz_kronecker_ui int mpz_srcptr unsigned-long)
(mpz_si_kronecker int long mpz_srcptr)
(mpz_ui_kronecker int unsigned-long mpz_srcptr)
(mpz_lcm void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_lcm_ui void mpz_ptr mpz_srcptr unsigned-long)
(mpz_lucnum_ui void mpz_ptr unsigned-long-int)
(mpz_lucnum2_ui void mpz_ptr mpz_ptr unsigned-long-int)
(mpz_millerrabin int mpz_srcptr int)
(mpz_mod void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_mul void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_mul_2exp void mpz_ptr mpz_srcptr mp_bitcnt_t)
(mpz_mul_si void mpz_ptr mpz_srcptr long-int)
(mpz_mul_ui void mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_neg void mpz_ptr mpz_srcptr)
(mpz_nextprime void mpz_ptr mpz_srcptr)
(mpz_out_raw size_t FILE-* mpz_srcptr)
(mpz_out_str size_t FILE-* int mpz_srcptr)
(mpz_perfect_power_p int mpz_srcptr)
(mpz_perfect_square_p int mpz_srcptr)
(mpz_popcount mp_bitcnt_t mpz_srcptr)
(mpz_pow_ui void mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_powm void mpz_ptr mpz_srcptr mpz_srcptr mpz_srcptr)
(mpz_powm_sec void mpz_ptr mpz_srcptr mpz_srcptr mpz_srcptr)
(mpz_powm_ui void mpz_ptr mpz_srcptr unsigned-long-int mpz_srcptr)
(mpz_probab_prime_p int mpz_srcptr int)
(mpz_random void mpz_ptr mp_size_t)
(mpz_random2 void mpz_ptr mp_size_t)
(mpz_realloc2 void mpz_ptr mp_bitcnt_t)
(mpz_remove mp_bitcnt_t mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_root int mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_rootrem void mpz_ptr mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_rrandomb void mpz_ptr gmp_randstate_t mp_bitcnt_t)
(mpz_scan0 mp_bitcnt_t mpz_srcptr mp_bitcnt_t)
(mpz_scan1 mp_bitcnt_t mpz_srcptr mp_bitcnt_t)
(mpz_set void mpz_ptr mpz_srcptr)
(mpz_set_d void mpz_ptr double)
(mpz_set_f void mpz_ptr mpf_srcptr)
(mpz_set_q void mpz_ptr mpq_srcptr)
(mpz_set_si void mpz_ptr signed-long-int)
(mpz_set_str int mpz_ptr const-char-* int)
(mpz_set_ui void mpz_ptr unsigned-long-int)
(mpz_setbit void mpz_ptr mp_bitcnt_t)
(mpz_size size_t mpz_srcptr)
(mpz_sizeinbase size_t mpz_srcptr int)
(mpz_sqrt void mpz_ptr mpz_srcptr)
(mpz_sqrtrem void mpz_ptr mpz_ptr mpz_srcptr)
(mpz_sub void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_sub_ui void mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_ui_sub void mpz_ptr unsigned-long-int mpz_srcptr)
(mpz_submul void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_submul_ui void mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_swap void mpz_ptr mpz_ptr)
(mpz_tdiv_ui unsigned-long-int mpz_srcptr unsigned-long-int)
(mpz_tdiv_q void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_tdiv_q_2exp void mpz_ptr mpz_srcptr mp_bitcnt_t)
(mpz_tdiv_q_ui unsigned-long-int mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_tdiv_qr void mpz_ptr mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_tdiv_qr_ui unsigned-long-int mpz_ptr mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_tdiv_r void mpz_ptr mpz_srcptr mpz_srcptr)
(mpz_tdiv_r_2exp void mpz_ptr mpz_srcptr mp_bitcnt_t)
(mpz_tdiv_r_ui unsigned-long-int mpz_ptr mpz_srcptr unsigned-long-int)
(mpz_tstbit int mpz_srcptr mp_bitcnt_t)
(mpz_ui_pow_ui void mpz_ptr unsigned-long-int unsigned-long-int)
(mpz_urandomb void mpz_ptr gmp_randstate_t mp_bitcnt_t)
(mpz_urandomm void mpz_ptr gmp_randstate_t mpz_srcptr)
(mpz_xor void mpz_ptr mpz_srcptr mpz_srcptr)
(mpq_abs void mpq_ptr mpq_srcptr)
(mpq_add void mpq_ptr mpq_srcptr mpq_srcptr)
(mpq_canonicalize void mpq_ptr)
(mpq_clear void mpq_ptr)
(mpq_clears void mpq_ptr ...)
(mpq_cmp int mpq_srcptr mpq_srcptr)
(_mpq_cmp_si int mpq_srcptr long unsigned-long)
(_mpq_cmp_ui int mpq_srcptr unsigned-long-int unsigned-long-int)
(mpq_div void mpq_ptr mpq_srcptr mpq_srcptr)
(mpq_div_2exp void mpq_ptr mpq_srcptr mp_bitcnt_t)
(mpq_equal int mpq_srcptr mpq_srcptr)
(mpq_get_num void mpz_ptr mpq_srcptr)
(mpq_get_den void mpz_ptr mpq_srcptr)
(mpq_get_d double mpq_srcptr)
(mpq_get_str char-* char-* int mpq_srcptr)
(mpq_init void mpq_ptr)
(mpq_inits void mpq_ptr ...)
(mpq_inp_str size_t mpq_ptr FILE-* int)
(mpq_inv void mpq_ptr mpq_srcptr)
(mpq_mul void mpq_ptr mpq_srcptr mpq_srcptr)
(mpq_mul_2exp void mpq_ptr mpq_srcptr mp_bitcnt_t)
(mpq_neg void mpq_ptr mpq_srcptr)
(mpq_out_str size_t FILE-* int mpq_srcptr)
(mpq_set void mpq_ptr mpq_srcptr)
(mpq_set_d void mpq_ptr double)
(mpq_set_den void mpq_ptr mpz_srcptr)
(mpq_set_f void mpq_ptr mpf_srcptr)
(mpq_set_num void mpq_ptr mpz_srcptr)
(mpq_set_si void mpq_ptr signed-long-int unsigned-long-int)
(mpq_set_str int mpq_ptr const-char-* int)
(mpq_set_ui void mpq_ptr unsigned-long-int unsigned-long-int)
(mpq_set_z void mpq_ptr mpz_srcptr)
(mpq_sub void mpq_ptr mpq_srcptr mpq_srcptr)
(mpq_swap void mpq_ptr mpq_ptr)
(mpf_abs void mpf_ptr mpf_srcptr)
(mpf_add void mpf_ptr mpf_srcptr mpf_srcptr)
(mpf_add_ui void mpf_ptr mpf_srcptr unsigned-long-int)
(mpf_ceil void mpf_ptr mpf_srcptr)
(mpf_clear void mpf_ptr)
(mpf_clears void mpf_ptr ...)
(mpf_cmp int mpf_srcptr mpf_srcptr)
(mpf_cmp_d int mpf_srcptr double)
(mpf_cmp_si int mpf_srcptr signed-long-int)
(mpf_cmp_ui int mpf_srcptr unsigned-long-int)
(mpf_div void mpf_ptr mpf_srcptr mpf_srcptr)
(mpf_div_2exp void mpf_ptr mpf_srcptr mp_bitcnt_t)
(mpf_div_ui void mpf_ptr mpf_srcptr unsigned-long-int)
(mpf_dump void mpf_srcptr)
(mpf_eq int mpf_srcptr mpf_srcptr mp_bitcnt_t)
(mpf_fits_sint_p int mpf_srcptr)
(mpf_fits_slong_p int mpf_srcptr)
(mpf_fits_sshort_p int mpf_srcptr)
(mpf_fits_uint_p int mpf_srcptr)
(mpf_fits_ulong_p int mpf_srcptr)
(mpf_fits_ushort_p int mpf_srcptr)
(mpf_floor void mpf_ptr mpf_srcptr)
(mpf_get_d double mpf_srcptr)
(mpf_get_d_2exp double signed-long-int-* mpf_srcptr)
(mpf_get_default_prec mp_bitcnt_t void)
(mpf_get_prec mp_bitcnt_t mpf_srcptr)
(mpf_get_si long mpf_srcptr)
(mpf_get_str char-* char-* mp_exp_t-* int size_t mpf_srcptr)
(mpf_get_ui unsigned-long mpf_srcptr)
(mpf_init void mpf_ptr)
(mpf_init2 void mpf_ptr mp_bitcnt_t)
(mpf_inits void mpf_ptr ...)
(mpf_init_set void mpf_ptr mpf_srcptr)
(mpf_init_set_d void mpf_ptr double)
(mpf_init_set_si void mpf_ptr signed-long-int)
(mpf_init_set_str int mpf_ptr const-char-* int)
(mpf_init_set_ui void mpf_ptr unsigned-long-int)
(mpf_inp_str size_t mpf_ptr FILE-* int)
(mpf_integer_p int mpf_srcptr)
(mpf_mul void mpf_ptr mpf_srcptr mpf_srcptr)
(mpf_mul_2exp void mpf_ptr mpf_srcptr mp_bitcnt_t)
(mpf_mul_ui void mpf_ptr mpf_srcptr unsigned-long-int)
(mpf_neg void mpf_ptr mpf_srcptr)
(mpf_out_str size_t FILE-* int size_t mpf_srcptr)
(mpf_pow_ui void mpf_ptr mpf_srcptr unsigned-long-int)
(mpf_random2 void mpf_ptr mp_size_t mp_exp_t)
(mpf_reldiff void mpf_ptr mpf_srcptr mpf_srcptr)
(mpf_set void mpf_ptr mpf_srcptr)
(mpf_set_d void mpf_ptr double)
(mpf_set_default_prec void mp_bitcnt_t)
(mpf_set_prec void mpf_ptr mp_bitcnt_t)
(mpf_set_prec_raw void mpf_ptr mp_bitcnt_t)
(mpf_set_q void mpf_ptr mpq_srcptr)
(mpf_set_si void mpf_ptr signed-long-int)
(mpf_set_str int mpf_ptr const-char-* int)
(mpf_set_ui void mpf_ptr unsigned-long-int)
(mpf_set_z void mpf_ptr mpz_srcptr)
(mpf_size size_t mpf_srcptr)
(mpf_sqrt void mpf_ptr mpf_srcptr)
(mpf_sqrt_ui void mpf_ptr unsigned-long-int)
(mpf_sub void mpf_ptr mpf_srcptr mpf_srcptr)
(mpf_sub_ui void mpf_ptr mpf_srcptr unsigned-long-int)
(mpf_swap void mpf_ptr mpf_ptr)
(mpf_trunc void mpf_ptr mpf_srcptr)
(mpf_ui_div void mpf_ptr unsigned-long-int mpf_srcptr)
(mpf_ui_sub void mpf_ptr unsigned-long-int mpf_srcptr)
(mpf_urandomb void mpf_t gmp_randstate_t mp_bitcnt_t)
(mpn_add mp_limb_t mp_ptr mp_srcptr mp_size_t mp_srcptr mp_size_t)
(mpn_add_1 mp_limb_t mp_ptr mp_srcptr mp_size_t mp_limb_t)
(mpn_add_n mp_limb_t mp_ptr mp_srcptr mp_srcptr mp_size_t)
(mpn_addmul_1 mp_limb_t mp_ptr mp_srcptr mp_size_t mp_limb_t)
(mpn_cmp int mp_srcptr mp_srcptr mp_size_t)
(mpn_divexact_by3c mp_limb_t mp_ptr mp_srcptr mp_size_t mp_limb_t)
(mpn_divrem mp_limb_t mp_ptr mp_size_t mp_ptr mp_size_t mp_srcptr mp_size_t)
(mpn_divrem_1 mp_limb_t mp_ptr mp_size_t mp_srcptr mp_size_t mp_limb_t)
(mpn_divrem_2 mp_limb_t mp_ptr mp_size_t mp_ptr mp_size_t mp_srcptr)
(mpn_div_qr_2 mp_limb_t mp_ptr mp_ptr mp_srcptr mp_size_t mp_srcptr)
(mpn_gcd mp_size_t mp_ptr mp_ptr mp_size_t mp_ptr mp_size_t)
(mpn_gcd_1 mp_limb_t mp_srcptr mp_size_t mp_limb_t)
(mpn_gcdext_1 mp_limb_t mp_limb_signed_t-* mp_limb_signed_t-* mp_limb_t mp_limb_t)
(mpn_gcdext mp_size_t mp_ptr mp_ptr mp_size_t-* mp_ptr mp_size_t mp_ptr mp_size_t)
(mpn_get_str size_t unsigned-char-* int mp_ptr mp_size_t)
(mpn_hamdist mp_bitcnt_t mp_srcptr mp_srcptr mp_size_t)
(mpn_lshift mp_limb_t mp_ptr mp_srcptr mp_size_t unsigned-int)
(mpn_mod_1 mp_limb_t mp_srcptr mp_size_t mp_limb_t)
(mpn_mul mp_limb_t mp_ptr mp_srcptr mp_size_t mp_srcptr mp_size_t)
(mpn_mul_1 mp_limb_t mp_ptr mp_srcptr mp_size_t mp_limb_t)
(mpn_mul_n void mp_ptr mp_srcptr mp_srcptr mp_size_t)
(mpn_sqr void mp_ptr mp_srcptr mp_size_t)
(mpn_neg mp_limb_t mp_ptr mp_srcptr mp_size_t)
(mpn_com void mp_ptr mp_srcptr mp_size_t)
(mpn_perfect_square_p int mp_srcptr mp_size_t)
(mpn_perfect_power_p int mp_srcptr mp_size_t)
(mpn_popcount mp_bitcnt_t mp_srcptr mp_size_t)
(mpn_pow_1 mp_size_t mp_ptr mp_srcptr mp_size_t mp_limb_t mp_ptr)
(mpn_preinv_mod_1 mp_limb_t mp_srcptr mp_size_t mp_limb_t mp_limb_t)
(mpn_random void mp_ptr mp_size_t)
(mpn_random2 void mp_ptr mp_size_t)
(mpn_rshift mp_limb_t mp_ptr mp_srcptr mp_size_t unsigned-int)
(mpn_scan0 mp_bitcnt_t mp_srcptr mp_bitcnt_t)
(mpn_scan1 mp_bitcnt_t mp_srcptr mp_bitcnt_t)
(mpn_set_str mp_size_t mp_ptr const-unsigned-char-* size_t int)
(mpn_sqrtrem mp_size_t mp_ptr mp_ptr mp_srcptr mp_size_t)
(mpn_sub mp_limb_t mp_ptr mp_srcptr mp_size_t mp_srcptr mp_size_t)
(mpn_sub_1 mp_limb_t mp_ptr mp_srcptr mp_size_t mp_limb_t)
(mpn_sub_n mp_limb_t mp_ptr mp_srcptr mp_srcptr mp_size_t)
(mpn_submul_1 mp_limb_t mp_ptr mp_srcptr mp_size_t mp_limb_t)
(mpn_tdiv_qr void mp_ptr mp_ptr mp_size_t mp_srcptr mp_size_t mp_srcptr mp_size_t)
(mpn_and_n void mp_ptr mp_srcptr mp_srcptr mp_size_t)
(mpn_andn_n void mp_ptr mp_srcptr mp_srcptr mp_size_t)
(mpn_nand_n void mp_ptr mp_srcptr mp_srcptr mp_size_t)
(mpn_ior_n void mp_ptr mp_srcptr mp_srcptr mp_size_t)
(mpn_iorn_n void mp_ptr mp_srcptr mp_srcptr mp_size_t)
(mpn_nior_n void mp_ptr mp_srcptr mp_srcptr mp_size_t)
(mpn_xor_n void mp_ptr mp_srcptr mp_srcptr mp_size_t)
(mpn_xnor_n void mp_ptr mp_srcptr mp_srcptr mp_size_t)
(mpn_copyi void mp_ptr mp_srcptr mp_size_t)
(mpn_copyd void mp_ptr mp_srcptr mp_size_t)
(mpn_zero void mp_ptr mp_size_t)
)
