1 0
# Copyright 2002 Fulcrum Microsystems.  All rights reserved.
# $Id: //depot/sw/main/cad/external-tools-integration/cadence/virtuoso/nano.package#1 $
# $DateTime: 2005/11/07 14:51:55 $
# $Author: aubrey $

<<DOC
 Fulcrum Cadence Enviornment that many layout engineer use.
DOC

# SKILL
install/share/bin/gen_autoload          skill/gen_autoload                    775 p
share/skill/layout/fulcrum_setup/AlignCells.il skill/layout/fulcrum_setup/AlignCells.il 664 p
share/skill/layout/fulcrum_setup/AlignCellsDataPath.il skill/layout/fulcrum_setup/AlignCellsDataPath.il 664 p
share/skill/layout/fulcrum_setup/AlignCellsNonOverlap.il skill/layout/fulcrum_setup/AlignCellsNonOverlap.il 664 p
share/skill/layout/fulcrum_setup/AnalysisLayout.il skill/layout/fulcrum_setup/AnalysisLayout.il 664 p
share/skill/layout/fulcrum_setup/CompactCells.il skill/layout/fulcrum_setup/CompactCells.il 664 p
share/skill/layout/fulcrum_setup/DrawIO.il skill/layout/fulcrum_setup/DrawIO.il 664 p
share/skill/layout/fulcrum_setup/DrawWellPlugs.il skill/layout/fulcrum_setup/DrawWellPlugs.il 664 p
share/skill/layout/fulcrum_setup/ExtraBasicSkills.il skill/layout/fulcrum_setup/ExtraBasicSkills.il 664 p
share/skill/layout/fulcrum_setup/FloorplanCells.il skill/layout/fulcrum_setup/FloorplanCells.il 664 p
share/skill/layout/fulcrum_setup/Floorplanner.il skill/layout/fulcrum_setup/Floorplanner.il 664 p
share/skill/layout/fulcrum_setup/GetOverlaps.il skill/layout/fulcrum_setup/GetOverlaps.il 664 p
share/skill/layout/fulcrum_setup/GlobalHiliteStack.il skill/layout/fulcrum_setup/GlobalHiliteStack.il 664 p
share/skill/layout/fulcrum_setup/IO.input.x6 skill/layout/fulcrum_setup/IO.input.x6 664 p
share/skill/layout/fulcrum_setup/IO.input.x6.alias skill/layout/fulcrum_setup/IO.input.x6.alias 664 p
share/skill/layout/fulcrum_setup/IO.map.x6 skill/layout/fulcrum_setup/IO.map.x6 664 p
share/skill/layout/fulcrum_setup/M_Floorplan.il skill/layout/fulcrum_setup/M_Floorplan.il 664 p
share/skill/layout/fulcrum_setup/M_Main.il skill/layout/fulcrum_setup/M_Main.il 664 p
share/skill/layout/fulcrum_setup/M_Verify.il skill/layout/fulcrum_setup/M_Verify.il 664 p
share/skill/layout/fulcrum_setup/ManageWindows.il skill/layout/fulcrum_setup/ManageWindows.il 664 p
share/skill/layout/fulcrum_setup/MapConnectivity.il skill/layout/fulcrum_setup/MapConnectivity.il 664 p
share/skill/layout/fulcrum_setup/MoveToSnap.il skill/layout/fulcrum_setup/MoveToSnap.il 664 p
share/skill/layout/fulcrum_setup/PathFinder.il skill/layout/fulcrum_setup/PathFinder.il 664 p
share/skill/layout/fulcrum_setup/SelectSameMaster.il skill/layout/fulcrum_setup/SelectSameMaster.il 664 p
share/skill/layout/fulcrum_setup/SetDeleteViewLevels.il skill/layout/fulcrum_setup/SetDeleteViewLevels.il 664 p
share/skill/layout/fulcrum_setup/SetSnapping.il skill/layout/fulcrum_setup/SetSnapping.il 664 p
share/skill/layout/fulcrum_setup/ShowName.il skill/layout/fulcrum_setup/ShowName.il 664 p
share/skill/layout/fulcrum_setup/StandardBindKeys.il skill/layout/fulcrum_setup/StandardBindKeys.il 664 p
share/skill/layout/fulcrum_setup/TR_ChangeInstName.il skill/layout/fulcrum_setup/TR_ChangeInstName.il 664 p
share/skill/layout/fulcrum_setup/TR_CountNets.il skill/layout/fulcrum_setup/TR_CountNets.il 664 p
share/skill/layout/fulcrum_setup/TR_CrawFish.il skill/layout/fulcrum_setup/TR_CrawFish.il 664 p
share/skill/layout/fulcrum_setup/TR_DrawIO.il skill/layout/fulcrum_setup/TR_DrawIO.il 664 p
share/skill/layout/fulcrum_setup/TR_DrawIO_Globals_x6.il skill/layout/fulcrum_setup/TR_DrawIO_Globals_x6.il 664 p
share/skill/layout/fulcrum_setup/TR_DrawPins.il skill/layout/fulcrum_setup/TR_DrawPins.il 664 p
share/skill/layout/fulcrum_setup/TR_ExtendConnDepth.il skill/layout/fulcrum_setup/TR_ExtendConnDepth.il 664 p
share/skill/layout/fulcrum_setup/TR_FindInstance.il skill/layout/fulcrum_setup/TR_FindInstance.il 664 p
share/skill/layout/fulcrum_setup/TR_FloorplanArray.il skill/layout/fulcrum_setup/TR_FloorplanArray.il 664 p
share/skill/layout/fulcrum_setup/TR_Floorplanner.il skill/layout/fulcrum_setup/TR_Floorplanner.il 664 p
share/skill/layout/fulcrum_setup/TR_GenerateBindingFile.il skill/layout/fulcrum_setup/TR_GenerateBindingFile.il 664 p
share/skill/layout/fulcrum_setup/TR_GetManhattanDistance.il skill/layout/fulcrum_setup/TR_GetManhattanDistance.il 664 p
share/skill/layout/fulcrum_setup/TR_HiLiteLabels.il skill/layout/fulcrum_setup/TR_HiLiteLabels.il 664 p
share/skill/layout/fulcrum_setup/TR_MoveAndSnap.il skill/layout/fulcrum_setup/TR_MoveAndSnap.il 664 p
share/skill/layout/fulcrum_setup/TrackRouter.il skill/layout/fulcrum_setup/TrackRouter.il 664 p
share/skill/layout/fulcrum_setup/trZoom.il skill/layout/fulcrum_setup/trZoom.il 664 p
share/skill/layout/fulcrum_setup/FL_Overlap.il skill/layout/fulcrum_setup/FL_Overlap.il 664 p
share/skill/layout/fulcrum_setup/FulcrumLoad.il skill/layout/fulcrum_setup/FulcrumLoad.il 664 p

