#!/usr/intel/bin/zsh -x

# runme_final : final steps of Harry's runme script

# ALLOW 64GB 

TOP=$WARD

cell_list=$TOP/$RECHAR_CELL_LIST_FN

source $TOP/$RECHAR_ENV_ZSH 

cd $WARD/$RECHAR_SIS_WORKDIR 

###################################################################

# Post-process libs to create all the metal variants, and also to update
# operating condition and comments.

echo "===========================     POSTPROCESS `date`    ==========================="
pwd


$TOP/scripts/run_postprocess */*/models/liberty/liberty*.lib

# Compile .lib to .ldb
echo "===========================     COMPILE-LDBS `date`     ==========================="
pwd
$TOP/scripts/compile_ldb */*/models/liberty/${techlib}*.lib

# Create NDMs
echo "===========================     CREATE-NDMS `date`    ==========================="
pwd

mkdir -p $WARD/${RECHAR_SIS_WORKDIR}/ndms
cd $WARD/${RECHAR_SIS_WORKDIR}/ndms
cp $WARD/${RECHAR_SIS_WORKDIR}/*/*/models/liberty/${techlib}*.{lib,ldb} .
$TOP/scripts/gen_ndms $bundles

# Bundle new collateral

echo "===========================     REBUNDLE `date`    ==========================="
pwd

mkdir -p $WARD/${RECHAR_SIS_WORKDIR}/bundles
cd $WARD/${RECHAR_SIS_WORKDIR}/bundles
$TOP/scripts/rebundle $WARD/${RECHAR_SIS_WORKDIR}/ndms $bundles

echo "**********  $0 done at `date`"
