#!/usr/intel/bin/perl -w

@ARGV==2 or die "USAGE: find_drc cell LAYOUT_ERRORS\n";
my $cell = $ARGV[0];
my $file = $ARGV[1];
my $radius = 0.2;
my @boxes;
if ($cell =~ /^core_neuro_neuron_NEURON/ || $cell =~ /^core_neuro_dumb_DUMB_NEURON/ ) {
    @boxes = ("3.36:-478.8:420:-57.456", "30.24:-478.8:420:-3.192");
} elsif ($cell =~ /^chip_n1_io_IO/ ) {
    @boxes = ("-50.4:-95.76:50.4:0");
} elsif ($cell =~ /^chip_n1_test0_TEST0/ ) {
    @boxes = ("0:-319.2:305.76:0","305.76:-95.76:369.6:0","305.76:-319.2:420:-150.024");
} elsif ($cell =~ /^chip_n1_test1_TEST1/ ) {
    @boxes = ("-50.4:-319.2:62.16:-150.024","0:-95.76:62.16:0","62.16:-319.2:369.6:0");
} elsif ($cell =~ /^chip_n1_testm_TESTM/ ) {
    @boxes = ("-420:-319.2:420:0")
} elsif ($cell eq "neuro_top" || $cell =~ /^chip_n1_N1/) {
    @boxes = ("0:0:1270.08:1244.88");
}
my $shrink_x = 0.1;
my $shrink_y = 0.1;

my $num=0;
my $err="";
my %errors;
open IN, "<$file" or die;
while (my $line = <IN>) {
    if ($line =~ /^(\S+): /) { $err = $1; }
    elsif ($line =~ /^(\S+)\s+\((\S+),\s*(\S+)\)/ ) {
        if ($1 eq $cell) {
            my $x = $2;
            my $y = $3;
            my $found = 1;
            if (@boxes>0) { $found = 0; }
            foreach my $box (@boxes) {
                if (in_box($x,$y,$box)) { $found=1; }
            }
            unless ($found) { next; }
            $num++;
            $found = 0;
            foreach my $key (keys %errors) {
                my ($kx, $ky) = split(":",$key);
                if (abs($x-$kx)<$radius && abs($y-$ky)<$radius) {
                    $errors{$key} .= " $err";
                    $found = 1;
                    next;
                }
            }
            unless ($found) { $errors{"$x:$y"} = $err; }
        }
    }
}
close IN;
print "; $num total DRC errors\n\n";

# report errors by layer
foreach my $layer ("M0", "V0", "M1", "V1", "M2", "V2", "M3", "V3", "M4", "V4", "M5", "V5", "M6", "V6",
                   "M7", "V7", "M8", "V8", "M9", "V9", "TM1", "TV1", "other") {
    print "; $layer\n";
    foreach my $key (sort keys %errors) {
        my ($x, $y) = split(":",$key);
        my $err = $errors{$key};
        if (get_layer($err) eq "$layer") {
            printf "(GoToLocation $x $y 2000) ; $err\n";
        }
    }
    print "\n";
}

sub get_layer {
    my ($errors) = (@_);
    my $layer = "";
    foreach my $field (split(" ",$errors)) {
        if ($field =~ /(\S+)_/) {
            if ($layer eq "") { $layer = $1; }
            elsif ($layer ne $1) { $layer = "other"; }
        }
    }
    return $layer;        
}

sub in_box {
    my ($x,$y,$box) = @_;
    my ($x0,$y0,$x1,$y1) = split(":",$box);
    $x0 += $shrink_x;
    $x1 -= $shrink_x;
    $y0 += $shrink_y;
    $y1 -= $shrink_y;
    return ($x>=$x0 && $x<=$x1 && $y>=$y0 && $y<$y1);
}
