DEFAULTS_MK_TEMPL := $(BUILD_SYSTEM_ROOT)/defaults.mk.tmpl
DEFAULTS_MK_GEN_SCRIPT := $(BUILD_SYSTEM_ROOT)/defaults.mk.gen
DEFAULTS_MK_GEN_CMD := $(DEFAULTS_MK_GEN_SCRIPT) $(GNUSED) $(DEFAULTS_MK_TEMPL)
