import ("libm3")
import ("cit_util")
import ("spicelib")
import ("tracelib")
import ("regression")
import ("ctlib")
import ("spicecompress")

implementation ("SpiceUncompress")

program ("spiceuncompress")
