wire("$GND","GND")
wire("$Vdd","Vdd")
wire("$_RESET","_RESET")
define "standard.channel.e1of2.0"("0", "1", "e") {
  exclcc("0","1","e")
  exclhi("0","1")
  wire("0","d[0]")
  wire("1","d[1]")
}
excllo("_d.0","_d.1")
excllo("_s.0","_s.1")
wire("GND","reset.GND")
wire("Reset","reset.Reset")
wire("Vdd","reset.Vdd")
wire("_RESET","reset._RESET")
wire("_Reset","reset._Reset")
wire("abe","a.e","b.e")
wire("_d.0","_d.d[0]")
wire("_d.1","_d.d[1]")
wire("_s.0","_s.d[0]")
wire("_s.1","_s.d[1]")
"standard.channel.e1of2.0" "a"("a.0", "a.1", "abe")
"standard.channel.e1of2.0" "b"("b.0", "b.1", "abe")
"standard.channel.e1of2.0" "c"("c.0", "c.1", "c.e")
"standard.channel.e1of2.0" "d"("d.0", "d.1", "d.e")
"standard.channel.e1of2.0" "s"("s.0", "s.1", "s.e")
