// Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
// SPDX-License-Identifier: Apache-2.0

// Code autogenerated via MPGEN. Do not edit.
interface egr_tqu_mem_if (); 

import egr_tqu_mem_pkg::*;

egr_tqu_epl_eop_fifo_addr_t    egr_tqu_epl_eop_fifo_rd_adr       [EGR_TQU_EPL_EOP_FIFO_INST ];
egr_tqu_epl_eop_fifo_addr_t    egr_tqu_epl_eop_fifo_wr_adr       [EGR_TQU_EPL_EOP_FIFO_INST ];
egr_tqu_epl_eop_fifo_data_t    egr_tqu_epl_eop_fifo_rd_data      [EGR_TQU_EPL_EOP_FIFO_INST ];
egr_tqu_epl_eop_fifo_data_t    egr_tqu_epl_eop_fifo_wr_data      [EGR_TQU_EPL_EOP_FIFO_INST ];
logic                        egr_tqu_epl_eop_fifo_rd_en        [EGR_TQU_EPL_EOP_FIFO_INST ];
logic                        egr_tqu_epl_eop_fifo_wr_en        [EGR_TQU_EPL_EOP_FIFO_INST ];
logic                        egr_tqu_epl_eop_fifo_rd_valid     [EGR_TQU_EPL_EOP_FIFO_INST ];

egr_tqu_epl_pktid_fifo_addr_t    egr_tqu_epl_pktid_fifo_rd_adr       [EGR_TQU_EPL_PKTID_FIFO_INST ];
egr_tqu_epl_pktid_fifo_addr_t    egr_tqu_epl_pktid_fifo_wr_adr       [EGR_TQU_EPL_PKTID_FIFO_INST ];
egr_tqu_epl_pktid_fifo_data_t    egr_tqu_epl_pktid_fifo_rd_data      [EGR_TQU_EPL_PKTID_FIFO_INST ];
egr_tqu_epl_pktid_fifo_data_t    egr_tqu_epl_pktid_fifo_wr_data      [EGR_TQU_EPL_PKTID_FIFO_INST ];
logic                        egr_tqu_epl_pktid_fifo_rd_en        [EGR_TQU_EPL_PKTID_FIFO_INST ];
logic                        egr_tqu_epl_pktid_fifo_wr_en        [EGR_TQU_EPL_PKTID_FIFO_INST ];
logic                        egr_tqu_epl_pktid_fifo_rd_valid     [EGR_TQU_EPL_PKTID_FIFO_INST ];

egr_tqu_epl_smp_tb_addr_t    egr_tqu_epl_smp_tb_adr           [EGR_TQU_EPL_SMP_TB_INST ];
egr_tqu_epl_smp_tb_data_t    egr_tqu_epl_smp_tb_wr_data       [EGR_TQU_EPL_SMP_TB_INST ];
egr_tqu_epl_smp_tb_data_t    egr_tqu_epl_smp_tb_rd_data       [EGR_TQU_EPL_SMP_TB_INST ];
logic                        egr_tqu_epl_smp_tb_rd_en        [EGR_TQU_EPL_SMP_TB_INST ];
logic                        egr_tqu_epl_smp_tb_wr_en        [EGR_TQU_EPL_SMP_TB_INST ];
logic                        egr_tqu_epl_smp_tb_rd_valid     [EGR_TQU_EPL_SMP_TB_INST ];

egr_tqu_epl_sop_fifo_addr_t    egr_tqu_epl_sop_fifo_rd_adr       [EGR_TQU_EPL_SOP_FIFO_INST ];
egr_tqu_epl_sop_fifo_addr_t    egr_tqu_epl_sop_fifo_wr_adr       [EGR_TQU_EPL_SOP_FIFO_INST ];
egr_tqu_epl_sop_fifo_data_t    egr_tqu_epl_sop_fifo_rd_data      [EGR_TQU_EPL_SOP_FIFO_INST ];
egr_tqu_epl_sop_fifo_data_t    egr_tqu_epl_sop_fifo_wr_data      [EGR_TQU_EPL_SOP_FIFO_INST ];
logic                        egr_tqu_epl_sop_fifo_rd_en        [EGR_TQU_EPL_SOP_FIFO_INST ];
logic                        egr_tqu_epl_sop_fifo_wr_en        [EGR_TQU_EPL_SOP_FIFO_INST ];
logic                        egr_tqu_epl_sop_fifo_rd_valid     [EGR_TQU_EPL_SOP_FIFO_INST ];

egr_tqu_smp_rob_ptr_bank_addr_t    egr_tqu_smp_rob_ptr_bank_rd_adr       [EGR_TQU_SMP_ROB_PTR_BANK_INST ];
egr_tqu_smp_rob_ptr_bank_addr_t    egr_tqu_smp_rob_ptr_bank_wr_adr       [EGR_TQU_SMP_ROB_PTR_BANK_INST ];
egr_tqu_smp_rob_ptr_bank_data_t    egr_tqu_smp_rob_ptr_bank_rd_data      [EGR_TQU_SMP_ROB_PTR_BANK_INST ];
egr_tqu_smp_rob_ptr_bank_data_t    egr_tqu_smp_rob_ptr_bank_wr_data      [EGR_TQU_SMP_ROB_PTR_BANK_INST ];
logic                        egr_tqu_smp_rob_ptr_bank_rd_en        [EGR_TQU_SMP_ROB_PTR_BANK_INST ];
logic                        egr_tqu_smp_rob_ptr_bank_wr_en        [EGR_TQU_SMP_ROB_PTR_BANK_INST ];
logic                        egr_tqu_smp_rob_ptr_bank_rd_valid     [EGR_TQU_SMP_ROB_PTR_BANK_INST ];

modport egr_tqu_epl_eop_fifo(
    output egr_tqu_epl_eop_fifo_rd_adr   ,
    output egr_tqu_epl_eop_fifo_wr_adr   ,
    output egr_tqu_epl_eop_fifo_rd_en    ,
    output egr_tqu_epl_eop_fifo_wr_data  ,
    output egr_tqu_epl_eop_fifo_wr_en    ,
    input  egr_tqu_epl_eop_fifo_rd_data  ,
    input  egr_tqu_epl_eop_fifo_rd_valid  
);
modport egr_tqu_epl_pktid_fifo(
    output egr_tqu_epl_pktid_fifo_rd_adr   ,
    output egr_tqu_epl_pktid_fifo_wr_adr   ,
    output egr_tqu_epl_pktid_fifo_rd_en    ,
    output egr_tqu_epl_pktid_fifo_wr_data  ,
    output egr_tqu_epl_pktid_fifo_wr_en    ,
    input  egr_tqu_epl_pktid_fifo_rd_data  ,
    input  egr_tqu_epl_pktid_fifo_rd_valid  
);
modport egr_tqu_epl_smp_tb(
    output egr_tqu_epl_smp_tb_adr      ,
    output egr_tqu_epl_smp_tb_rd_en    ,
    output egr_tqu_epl_smp_tb_wr_data  ,
    output egr_tqu_epl_smp_tb_wr_en    ,
    input  egr_tqu_epl_smp_tb_rd_data  ,
    input  egr_tqu_epl_smp_tb_rd_valid  
);
modport egr_tqu_epl_sop_fifo(
    output egr_tqu_epl_sop_fifo_rd_adr   ,
    output egr_tqu_epl_sop_fifo_wr_adr   ,
    output egr_tqu_epl_sop_fifo_rd_en    ,
    output egr_tqu_epl_sop_fifo_wr_data  ,
    output egr_tqu_epl_sop_fifo_wr_en    ,
    input  egr_tqu_epl_sop_fifo_rd_data  ,
    input  egr_tqu_epl_sop_fifo_rd_valid  
);
modport egr_tqu_smp_rob_ptr_bank(
    output egr_tqu_smp_rob_ptr_bank_rd_adr   ,
    output egr_tqu_smp_rob_ptr_bank_wr_adr   ,
    output egr_tqu_smp_rob_ptr_bank_rd_en    ,
    output egr_tqu_smp_rob_ptr_bank_wr_data  ,
    output egr_tqu_smp_rob_ptr_bank_wr_en    ,
    input  egr_tqu_smp_rob_ptr_bank_rd_data  ,
    input  egr_tqu_smp_rob_ptr_bank_rd_valid  
);

modport mem(
            input  egr_tqu_epl_eop_fifo_rd_adr   ,
            input  egr_tqu_epl_eop_fifo_wr_adr   ,
            input  egr_tqu_epl_eop_fifo_rd_en    ,
            input  egr_tqu_epl_eop_fifo_wr_data  ,
            input  egr_tqu_epl_eop_fifo_wr_en    ,
            output egr_tqu_epl_eop_fifo_rd_data  ,
            output egr_tqu_epl_eop_fifo_rd_valid ,

            input  egr_tqu_epl_pktid_fifo_rd_adr   ,
            input  egr_tqu_epl_pktid_fifo_wr_adr   ,
            input  egr_tqu_epl_pktid_fifo_rd_en    ,
            input  egr_tqu_epl_pktid_fifo_wr_data  ,
            input  egr_tqu_epl_pktid_fifo_wr_en    ,
            output egr_tqu_epl_pktid_fifo_rd_data  ,
            output egr_tqu_epl_pktid_fifo_rd_valid ,

            input  egr_tqu_epl_smp_tb_adr      ,
            input  egr_tqu_epl_smp_tb_rd_en    ,
            input  egr_tqu_epl_smp_tb_wr_data  ,
            input  egr_tqu_epl_smp_tb_wr_en    ,
            output egr_tqu_epl_smp_tb_rd_data  ,
            output egr_tqu_epl_smp_tb_rd_valid ,

            input  egr_tqu_epl_sop_fifo_rd_adr   ,
            input  egr_tqu_epl_sop_fifo_wr_adr   ,
            input  egr_tqu_epl_sop_fifo_rd_en    ,
            input  egr_tqu_epl_sop_fifo_wr_data  ,
            input  egr_tqu_epl_sop_fifo_wr_en    ,
            output egr_tqu_epl_sop_fifo_rd_data  ,
            output egr_tqu_epl_sop_fifo_rd_valid ,

            input  egr_tqu_smp_rob_ptr_bank_rd_adr   ,
            input  egr_tqu_smp_rob_ptr_bank_wr_adr   ,
            input  egr_tqu_smp_rob_ptr_bank_rd_en    ,
            input  egr_tqu_smp_rob_ptr_bank_wr_data  ,
            input  egr_tqu_smp_rob_ptr_bank_wr_en    ,
            output egr_tqu_smp_rob_ptr_bank_rd_data  ,
            output egr_tqu_smp_rob_ptr_bank_rd_valid 
);

endinterface:egr_tqu_mem_if
