% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("parseparams")
import ("spicelib")
import ("spiceflat")
import ("m3readline")

implementation ("Main")

program ("spiceflat")
