% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("parseparams")
import ("cit_util")
import ("tracelib")
import ("csv")

table("TextRefSeq", "Text", "RefSeq")

module ("Entry")
array_sort ("Entry", "Entry")

implementation ("Main")

interface ("AreaSpec")
sequence ("AreaSpec", "AreaSpec")

program ("techdigest")
