import ("libm3")
import ("parseparams")
import ("cit_util")
import ("tracelib")
import ("csv")

table("TextRefSeq", "Text", "RefSeq")

module ("Entry")
array_sort ("Entry", "Entry")

implementation ("Main")

program ("techdigest")
