import ("libm3")
import ("cit_util")
import ("matrix")
import ("minimize")


c_source ("calcfc")
c_source ("cobyla")
c_source ("cobylb")
c_source ("main")
c_source ("trstlp")

interface ("COBYLA")

%Module ("NewUOA_M3")
%Module ("NewUOAs")

%implementation("Main")
%program ("testcobyla")
library ("cobyla")
