/* $Id: m3makefile,v 1.6 2009/05/02 03:04:05 mika Exp $ */



if defined("pm3_version")
	option("optimization","") 
end


import("libm3")
import("cit_util")
import("mscheme")
import("modula3scheme")
import("schemesig")
import("m3readline")
import("schemereadline")
import("parseparams")

implementation("Main")

program("mscheme")
