import ("libm3")
import ("cit_util")
import ("svspredict")
import ("newuoa")

implementation ("Main")

Module ("LrArray")

Module ("ReadPmroVmin")
Module ("ReadVmin")

Interface ("DieData")
interface ("ReadStats")

Table ("LrArrayLR", "LrArray", "LongrealType")

program ("svspostsi")

