import ("libm3")
import ("cit_util")
import ("svspredict")
import ("newuoa")

implementation ("Main")

Module ("LrArray")
Module ("ReadDist")
Interface ("DieData")

Table ("LrArrayLR", "LrArray", "LongrealType")

program ("svspostsi")

