#!/bin/bash

echo "installing ftdi library"

if [ -a libftd2xx.so.1.1.12.gz ]
then
	gzip -f -d libftd2xx.so.1.1.12.gz
fi
sudo cp libftd2xx.so.1.1.12 /usr/local/lib
sudo chmod 0755 /usr/local/lib/libftd2xx.so.1.1.12
sudo ln -sf /usr/local/lib/libftd2xx.so.1.1.12 /usr/local/lib/libftd2xx.so



echo "removing ftdi_sio module"

modules=`find /usr/lib/modules/ | grep "ftdi_sio.*\.ko$"`

for module in ${modules}
do
	sudo mv "$module" "${module}.bk"
done



