# -*- mode:Makefile -*-

# Copyright (C) 2018 Intel Corporation

 
SOURCES  = ${C_DIR}/uint.c
SOURCES += ${C_DIR}/fm_alos_debughash.c
SOURCES += ${MAP_DIR}/mby_top_map.c
SOURCES += tst_model_c_write.c

LIB_NAME = model_c_write

include ../make/liball.mk

