import ("libm3")
import ("cit_common")
import ("cit_util")
import ("ctlib")

m3_optimize("T")

Module ("Trace")
Interface ("TraceRep")

module ("TraceUnsafe")

interface ("TraceHeader")
table ("CardTextSeq", "Cardinal", "TextSeq")

Interface ("Transition")
Sequence ("Transition", "Transition")
Module ("TransitionFinder")

Table("TextTransitionSeq", "Text", "TransitionSeq")
Table("CardTransitionSeq", "Cardinal", "TransitionSeq")

Module ("TraceRewriter")
Module ("DistZTrace")

Module ("TraceOp")
Module ("TraceInterpolator")

library ("tracelib")
