import ("libm3")
import ("cit_common")
import ("cit_util")

Module ("Trace")
Interface ("TraceRep")

module ("TraceUnsafe")

interface ("TraceHeader")
table ("CardTextSeq", "Cardinal", "TextSeq")

Interface ("Transition")
Sequence ("Transition", "Transition")
Module ("TransitionFinder")

Table("TextTransitionSeq", "Text", "TransitionSeq")
Table("CardTransitionSeq", "Cardinal", "TransitionSeq")

library ("tracelib")
