# Copyright 2005 Fulcrum Microsystems.  All rights reserved.
# $Id$
# $DateTime$
# $Author$

# directory setup
ARCH     = $(shell echo `uname -s`-`uname -m` | sed "s/ //g")
LIB_DIR  = $(TOP)/lib
BIN_DIR  = $(TOP)/bin/$(ARCH)
MAN_DIR  = $(TOP)/man/man1

# tools setup
CC          = gcc # -pg
AR          = ar ru
INSTALL     = install -m 775
INSTALL_MAN = install -m 664
OPT         = -O3 -Wall -funroll-loops -ffast-math -finline-limit=20000

# architecture dependent setup
ifeq ($(ARCH),Linux-i686)
  CFLAGS = -I$(LIB_DIR) $(OPT) -ggdb -march=pentium3 -DPREFETCH -DSIMD # -I$(SDI2_INCLUDE) -DSST2
  LFLAGS = -lm -lreadline $(LIB_DIR)/castlib.a # $(SDI2_LIB)
endif

ifeq ($(ARCH),Linux-x86_64)
  CFLAGS = -I$(LIB_DIR) $(OPT) -ggdb -march=opteron -m64 -DPREFETCH -DSIMD
  LFLAGS = -lm -lreadline $(LIB_DIR)/castlib.a
endif

# template make rules

all::
	@$(MAKE) --no-print-directory subdirs TARGET=all

all:: $(LIB_TARGETS) $(BIN_TARGETS)

install::
	@$(MAKE) --no-print-directory subdirs TARGET=install

install:: all
	@mkdir -p $(BIN_DIR)
	@mkdir -p $(MAN_DIR)
	@for t in $(INSTALL_TARGETS) "" ; do [ -z "$$t" ] || (echo "Installing $$t" ; $(INSTALL) $$t $(BIN_DIR)) || exit 1 ; done
	@for t in $(MAN_TARGETS) "" ; do [ -z "$$t" ] || (echo "Installing $$t" ; $(INSTALL_MAN) $$t $(MAN_DIR)) || exit 1 ; done

clean::
	@$(MAKE) --no-print-directory subdirs TARGET=clean

clean::
	@rm -f $(wildcard *.o) $(wildcard *.a) $(BIN_TARGETS) $(LIB_TARGETS)

subdirs:
	@for sub in $(SUBDIRS) "" ; do [ -z "$$sub" ] || $(MAKE) -C $$sub $(TARGET) || exit 1 ; done

%.o: %.c
	$(CC) $(CFLAGS) -c $<

%.a:
	$(AR) $@ $^
	ranlib $@

$(BIN_TARGETS): %: %.o
	$(CC) $(CFLAGS) $^ -o $@ $(LFLAGS)
