import("parserlib")
import("cit_util")
import("mscheme")
import("sstubgen")
import("modula3scheme")
import("parseparams")

Token("liberty")
Lexer("liberty", "liberty")
Parser("liberty", "liberty")

Extended("libertyLexStd")
Extended("libertyParseStd")

implementation ("TestParse")

%library ("libertyparse")

Module ("LibertyComponent")
Module ("LibertyDefine")
Module ("LibertyDefineGroup")
Module ("LibertyBoolean")
Module ("LibertyAttrVal")
Module ("LibertyAttrValExpr")
Module ("LibertyExpr")
Module ("LibertyNumber")
Module ("LibertySorI")
Module ("LibertyParamList")
Module ("LibertyHead")
Module ("LibertyComplexAttr")
Module ("LibertySimpleAttr")
Interface ("LibertyStatement")
Module ("LibertyGroup")

Sequence ("LibertyAttrVal", "LibertyAttrVal")
Sequence ("LibertyStatement", "LibertyStatement")

Table    ("LibertyComponentRef", "LibertyComponent", "Refany")
MkSet    ("LibertyComponent", "LibertyComponent")
MkSetDef ("LibertyComponent", "LibertyComponent")
Sequence ("LibertyComponent", "LibertyComponent")

Module ("LibertyComponentSeqBuilder")
Interface ("LibertyComponentChildren")

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

SchemeStubs("LibertyComponent")
SchemeStubs ("LibertyDefine")
SchemeStubs ("LibertyDefineGroup")
SchemeStubs ("LibertyBoolean")
SchemeStubs ("LibertyAttrVal")
SchemeStubs ("LibertyAttrValExpr")
SchemeStubs ("LibertyExpr")
SchemeStubs ("LibertyNumber")
SchemeStubs ("LibertySorI")
SchemeStubs ("LibertyParamList")
SchemeStubs ("LibertyHead")
SchemeStubs ("LibertyComplexAttr")
SchemeStubs ("LibertySimpleAttr")
SchemeStubs ("LibertyStatement")
SchemeStubs ("LibertyGroup")

ExportSchemeStubs ("liberty")
importSchemeStubs()

program("testparse")



