import("parserlib")
import("cit_util")

Token("liberty")
Lexer("liberty", "liberty")
Parser("liberty", "liberty")

Extended("libertyLexStd")

implementation ("TestParse")

%library ("libertyparse")

Interface("LibertyComponent")
Module ("LibertyBoolean")
Module ("LibertyExpr")
Module ("LibertyNumber")
Module ("LibertySorI")

program("testparse")



