/* $Id$ */

import ("libm3")
import ("cit_util")
import ("json")
import ("splines")

Module ("DataPoint")
Interface ("Oscillator")
Interface ("OscillatorTemp")

Sequence("DataPoint", "DataPoint")

Array_sort("DataPoint", "DataPoint")

Module ("P3")
Module ("Triangle3")
List("Triangle3", "Triangle3")

implementation ("Main")

program ("sensor")
