#!/usr/intel/bin/perl -w

my $placements=10;
my $height=1;
my $area="min";

my $lsf =
    "set_architecture_file $ENV{COLLATERAL}/arch/e08/e08.arch\n" .
    "set_rpg_file $ENV{COLLATERAL}/arch/e08/e08_rpg_all.txt\n" .
    "set_tcl_container_file $ENV{COLLATERAL}/arch/e08/e08_container.tcl\n" .
    "set_option layer_file $ENV{COLLATERAL}/arch/e08/e08.layer\n" .
    "set_option fabric e08\n" .
    "set_option use_assumptions yes\n" .
    "set_option upperlayer m2\n" .
    "set_log_level status";

foreach my $cell (@ARGV) {
    my $rundir="${cell}.run";
    system("mkdir -p $rundir");
    system("cd $rundir; $ENV{FULCRUM} cast2cdl " . 
           "--process-dependent-name --cdl-mos-parameters=m " .
           "--cast-path=$ENV{CAST_PATH} --cadence-name " .
           "--cell=$cell --output=hier.cdl; " .
           "$ENV{FULCRUM} inliner " .
           "--cdl=hier.cdl --library=hier.cdl > $cell.flat.cdl; " .
           "$ENV{FULCRUM} cdl2snp " .
           "--length 20e-9 --gridW 34e-9 --maxNmosW 102e-9 --maxPmosW 102e-9 " .
           "$cell $cell.flat.cdl $cell.snp; " .
           "$ENV{LAYGENWARD}/tcl/snp_to_lgf.tcl $cell.snp $cell.lgf");
    my $lgf="$cell.lgf";

    # place
    print "PLACE: $lgf\n";
    open OUT, ">$rundir/place.lsh" or die;
    print OUT <<EOF;
$lsf
set_option placement_result_idx $placements
set_option generate_snp yes
set_option run_hazel_placement_engine 1
set_option max_num_cores 4
set_option placement_effort 1
set_option target_area $area
set_option target_height $height
set_option route no
set_netlist $lgf
run_main
exit
EOF
    system("cd $rundir; $ENV{LAYGENWARD}/bin/laygen_shell -nogui -file place.lsh > place.log");

    # route
    for (my $n=0; $n<$placements; $n++) {
        my $place_lgf = "out/lib_p${n}.lgf";
        next if (!-e "$rundir/$place_lgf");
        print "ROUTE: $rundir/$place_lgf\n";
        system("mkdir $rundir/route.${n}");
        open OUT, ">$rundir/route.${n}/route.lsh" or die;
        print OUT <<EOF;
$lsf
set_option option "Option name=undesired_pattern_report_filename value=undesired_patterns.${n}.txt"
set_option option "Option name=dump_final_rpg_file value=0"
set_option option "Option name=show_invisible_layout value=0"
set_option route yes
set_netlist ../$place_lgf
run_main
exit
EOF
        close OUT;
        system("cd $rundir/route.${n}; $ENV{LAYGENWARD}/bin/laygen_shell -nogui -file route.lsh > route.log");
    }
}
