#!/usr/intel/bin/perl -w
#
# Script to create nominal threshold versions of SPEC files
# according to simple expression matching rules.

while (my $file = shift @ARGV) {
    if ( $file =~ /(.*\/)c([^\.]+)\.cast/ ) {
        my $subtype = $2;
        my $out = "${1}b${2}.cast";
        print "$out\n";
        open IN, "<$file";
        open OUT, ">$out";
        while (my $line = <IN>) {
            chomp($line);
            if ($line =~ /^(.*\")c([^\.]+)(\".*)$/ ) { # remap CAST cell definition
                $line = "${1}b${2}${3}";
            }
            elsif ($line =~ /^(.*vendor\.intel\.e08\..*)c\.(.*)$/ ) { # remap E08 subcells
                $line = "${1}b.${2}";
            }
            elsif ($line =~ /^(.*\s+stack\.\S+\()1(\)\s+.*)$/) { # remap stack
                $line = "${1}2${2}";
            }
            elsif ($line =~ /^(.*\s+gate\.\S+\()1,1(\)\s+.*)$/) { # remap gate
                $line = "${1}2,2${2}";
            }
            elsif ($line =~ /^(.*\S+\.)c([^\.]+)$/) { # remap CAST subcells
                $line = "${1}b${2}";
            }
            elsif ($line =~ /^(.*) N\[1\] (.*)$/) { # rename transistors
                $line = "${1} N[2] ${2}";
            }
            elsif ($line =~ /^(.*) P\[1\] (.*)$/) { # rename transistors
                $line = "${1} P[2] ${2}";
            }
            elsif ($line =~ /^(.*transistor_type\s*=\s*)1(;.*)$/) { # fix directive
                $line = "${1}2${2}";
            }
            print OUT "$line\n";
        }
        close IN;
        close OUT;
        system("p4 -c $ENV{HW_CLIENT} add \"$out\"");
    }
}
