/* $Id: m3makefile,v 1.1 2008/10/14 07:51:11 mika Exp $ */

/* 
   Copyright (c) Generation Capital Ltd., 2008.  All rights reserved.

   Author: Mika Nystrom <mika@alum.mit.edu>
*/
import ("libm3")

Interface("Csighandler")

c_source ("sighandler")

library ("schemesig")
