%char [|@.{};:?()+\-*/,\]\[%]

%const ERROR

%const T_EQ
%token T_mID
%token T_mVNUM
%token T_mNUM
%token T_mSTR
%const T_mINC
%const T_mMOD
%const T_mDREF
%token T_mPROPERTY
%const T_ACCESSWIDTH
%const T_ACTIVEHIGH
%const T_ACTIVELOW
%const T_ADDRESSING
%const T_ADDRMAP
%const T_ALIAS
%const T_ALIGNMENT
%const T_ALL
%const T_ANDED
%const T_ARBITER
%const T_ASYNC
%const T_BIGENDIAN
%const T_BOOLEAN
%const T_BOTHEDGE
%const T_BRIDGE
%const T_CLOCK
%const T_COMPACT
%const T_COMPONENT
%const T_COUNTER
%const T_CPUIF_RESET
%const T_DECR
%const T_DECRSATURATE
%const T_DECRTHRESHOLD
%const T_DECRVALUE
%const T_DECRWIDTH
%const T_DEFAULT
%const T_DESC
%const T_DONTCOMPARE
%const T_DONTTEST
%const T_ENABLE
%const T_ENCODE
%const T_ENUM
%const T_ERREXTBUS
%const T_EXTERNAL
%const T_FALSE
%const T_FIELD
%const T_FIELD_RESET
%const T_FIELDWIDTH
%const T_FULLALIGN
%const T_HALT
%const T_HALTENABLE
%const T_HALTMASK
%const T_HW
%const T_HWCLR
%const T_HWENABLE
%const T_HWMASK
%const T_HWSET
%const T_INCR
%const T_INCRVALUE
%const T_INCRWIDTH
%const T_INTERNAL
%const T_INTR
%const T_LEVEL
%const T_LITTLEENDIAN
%const T_LSB0
%const T_MASK
%const T_MSB0
%const T_NA
%const T_NAME
%const T_NEGEDGE
%const T_NEXT
%const T_NONSTICKY
%const T_NUMBER
%const T_ORED
%const T_OVERFLOW
%const T_POSEDGE
%const T_PRECEDENCE
%const T_PROPERTY
%const T_R
%const T_RCLR
%const T_REF
%const T_REG
%const T_REGALIGN
%const T_REGFILE
%const T_REGWIDTH
%const T_RESET
%const T_RESETSIGNAL
%const T_RSET
%const T_RSVDSET
%const T_RSVDSETX
%const T_RW
%const T_SATURATE
%const T_SHARED
%const T_SHAREDEXTBUS
%const T_SIGNAL
%const T_SIGNALWIDTH
%const T_SINGLEPULSE
%const T_STICKY
%const T_STICKYBIT
%const T_STRING
%const T_SW
%const T_SWACC
%const T_SWMOD
%const T_SWWE
%const T_SWWEL
%const T_SYNC
%const T_THRESHOLD
%const T_TRUE
%const T_TYPE
%const T_UNDERFLOW
%const T_W
%const T_WE
%const T_WEL
%const T_WOCLR
%const T_WOSET
%const T_WR
%const T_XORED
