// Autogenerated Jamon implementation
// C:/Users/mhesseli/Documents/Perforce/rrc-4/reg-main/shared/java/src/./com/fulcrummicro/hw/verification/chip/mgmt/registers/templates/Cast.jamon

package com.fulcrummicro.hw.verification.chip.mgmt.registers.templates;

// 3, 1
import java.util.Collection;
// 4, 1
import com.fulcrummicro.util.misc.Utility;
// 5, 1
import com.fulcrummicro.hw.verification.chip.mgmt.registers.*;
// 6, 1
import com.fulcrummicro.hw.verification.lib.constants.ConstantsEnum;

public class CastImpl
  extends com.fulcrummicro.util.jamon.timestampImpl
  implements com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.Cast.Intf

{
  private final Collection<RegisterBase> bases;
  private final Collection<Register> regs;
  private final String chip;
  protected static com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.Cast.ImplData __jamon_setOptionalArguments(com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.Cast.ImplData p_implData)
  {
    com.fulcrummicro.util.jamon.timestampImpl.__jamon_setOptionalArguments(p_implData);
    return p_implData;
  }
  public CastImpl(org.jamon.TemplateManager p_templateManager, com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.Cast.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    bases = p_implData.getBases();
    regs = p_implData.getRegs();
    chip = p_implData.getChip();
  }
  
  @Override protected void child_render_1(final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 12, 9
    jamonWriter.write("/**\n * INTEL TOP SECRET\n * Copyright ");
    // 15, 14
    {
      // 15, 14
      __jamon_innerUnit__copyright_year(jamonWriter, __jamon__get_Method_Opt_creationYear_default());
    }
    // 15, 35
    jamonWriter.write(" Intel Corporation. All Rights Reserved.\n *\n * THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MODIFY.\n * Last Updated ");
    // 18, 17
    {
      // 18, 17
      __jamon_innerUnit__timestamp(jamonWriter);
    }
    // 18, 33
    jamonWriter.write("\n */\n\nmodule chip.");
    // 21, 13
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(chip), jamonWriter);
    // 21, 23
    jamonWriter.write(".base.registers;\n\ndefine AddressSpace ()() attributes\n  <+ chip.");
    // 24, 11
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(chip), jamonWriter);
    // 24, 21
    jamonWriter.write(".base.constant.MgmtConstants\n{\n\n //  Register_Name                            incremental  absolute  base\n");
    // 28, 1
    for (RegisterBase base : bases )
    {
      // 28, 35
      jamonWriter.write(" int ");
      // 29, 6
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", base.getFullName())), jamonWriter);
      // 29, 54
      jamonWriter.write(" = 0x");
      // 29, 59
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", base.getIncrementalAddress())), jamonWriter);
      // 29, 116
      jamonWriter.write("; // 0x");
      // 30, 7
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", base.getAbsoluteAddress())), jamonWriter);
      // 30, 61
      jamonWriter.write(" ");
      // 30, 62
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(base.getParent().getFullName()), jamonWriter);
      // 30, 98
      jamonWriter.write("\n int ");
      // 31, 6
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", base.getName() + "_SIZE")), jamonWriter);
      // 31, 60
      jamonWriter.write(" = 0x");
      // 31, 65
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", base.getSize())), jamonWriter);
      // 31, 108
      jamonWriter.write(";\n int ");
      // 32, 6
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", base.getName() + "_BUS_STOP_NR")), jamonWriter);
      // 32, 67
      jamonWriter.write(" = ");
      // 32, 70
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(base.getBusStopId()), jamonWriter);
      // 32, 95
      jamonWriter.write(";\n");
    }
    // 33, 8
    jamonWriter.write("\n");
    // 38, 1
    for (Register reg : regs )
    {
      // 39, 1
      String postfix = (reg.getNumEntries() > 1) ? "_BASE" : "_ADDR"; 
      // 40, 1
      String entriesPostfix = (reg.getNumEntries1() > 1) ? "_0" : ""; 
      // 40, 74
      jamonWriter.write(" int ");
      // 41, 6
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + postfix)), jamonWriter);
      // 41, 59
      jamonWriter.write(" = 0x");
      // 42, 4
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getAddressSafe())), jamonWriter);
      // 42, 53
      jamonWriter.write("; // 0x");
      // 43, 7
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getAddressOffset())), jamonWriter);
      // 43, 58
      jamonWriter.write(" ");
      // 43, 59
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getBaseName()), jamonWriter);
      // 43, 82
      jamonWriter.write("\n");
      // 44, 1
      if (reg.getNumEntries() > 1 )
      {
        // 44, 32
        jamonWriter.write(" int ");
        // 45, 6
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_BASE_MASK" + entriesPostfix)), jamonWriter);
        // 45, 81
        jamonWriter.write(" = 0x");
        // 46, 4
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getAddressMatchMask())), jamonWriter);
        // 46, 58
        jamonWriter.write(";\n int ");
        // 47, 6
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_STRIDE" + entriesPostfix)), jamonWriter);
        // 47, 78
        jamonWriter.write(" = 0x");
        // 48, 4
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getEntrySpace())), jamonWriter);
        // 48, 52
        jamonWriter.write(";\n");
      }
      // 50, 1
      if (reg.getNumEntries1() > 1 )
      {
        // 50, 33
        jamonWriter.write(" int ");
        // 51, 6
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_STRIDE_1")), jamonWriter);
        // 51, 63
        jamonWriter.write(" = 0x");
        // 52, 4
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getEntrySpace1())), jamonWriter);
        // 52, 53
        jamonWriter.write(";\n");
      }
      // 54, 1
      if (reg.getNumEntries2() > 1 )
      {
        // 54, 33
        jamonWriter.write(" int ");
        // 55, 6
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_STRIDE_2")), jamonWriter);
        // 55, 63
        jamonWriter.write(" = 0x");
        // 56, 4
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getEntrySpace2())), jamonWriter);
        // 56, 53
        jamonWriter.write(";\n");
      }
      // 57, 7
      jamonWriter.write(" int ");
      // 58, 6
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_BITS")), jamonWriter);
      // 58, 59
      jamonWriter.write(" = ");
      // 58, 62
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getNumberFieldBits()), jamonWriter);
      // 58, 92
      jamonWriter.write(";\n int ");
      // 59, 6
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_IMPL_BITS")), jamonWriter);
      // 59, 64
      jamonWriter.write(" = ");
      // 59, 67
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getImplementationWidth()), jamonWriter);
      // 59, 101
      jamonWriter.write(";\n int ");
      // 60, 6
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_SRAM_BITS")), jamonWriter);
      // 60, 64
      jamonWriter.write(" = ");
      // 60, 67
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getSramWidth()), jamonWriter);
      // 60, 91
      jamonWriter.write(";\n int ");
      // 61, 6
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_WIDTH")), jamonWriter);
      // 61, 60
      jamonWriter.write(" = ");
      // 61, 63
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getEntryWidth()), jamonWriter);
      // 61, 88
      jamonWriter.write(";\n int ");
      // 62, 6
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_ATOMIC_WIDTH")), jamonWriter);
      // 62, 67
      jamonWriter.write(" = ");
      // 62, 70
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getAtomicWidth()), jamonWriter);
      // 62, 96
      jamonWriter.write(";\n");
      // 65, 1
      if (reg.getNumDefaults() == 1 )
      {
        // 65, 34
        jamonWriter.write(" int ");
        // 66, 6
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_DEFAULT")), jamonWriter);
        // 66, 62
        jamonWriter.write(" = 0x");
        // 66, 67
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%x", reg.getDefault(0))), jamonWriter);
        // 66, 111
        jamonWriter.write(";\n");
      }
      // 67, 1
      else
      {
        // 67, 8
        jamonWriter.write(" int ");
        // 68, 6
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
        // 68, 25
        jamonWriter.write("_DEFAULT[0..");
        // 68, 37
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getNumDefaults()-1), jamonWriter);
        // 68, 65
        jamonWriter.write("];\n");
        // 69, 1
        for (int i = 0; i < reg.getNumDefaults(); i++ )
        {
          // 69, 50
          jamonWriter.write("     ");
          // 70, 6
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_DEFAULT[" + i + "]")), jamonWriter);
          // 70, 73
          jamonWriter.write(" = 0x");
          // 70, 78
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%x", reg.getDefault(i))), jamonWriter);
          // 70, 122
          jamonWriter.write(";\n");
        }
      }
      // 75, 1
      if (reg.getNumEntries() > 1 )
      {
        // 75, 32
        jamonWriter.write(" int ");
        // 76, 6
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_ENTRIES" + entriesPostfix)), jamonWriter);
        // 76, 79
        jamonWriter.write(" = ");
        // 76, 82
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getNumEntries()), jamonWriter);
        // 76, 107
        jamonWriter.write(";\n");
      }
      // 78, 1
      if (reg.getNumEntries1() > 1 )
      {
        // 78, 33
        jamonWriter.write(" int ");
        // 79, 6
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_ENTRIES_1")), jamonWriter);
        // 79, 64
        jamonWriter.write(" = ");
        // 79, 67
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getNumEntries1()), jamonWriter);
        // 79, 93
        jamonWriter.write(";\n");
      }
      // 81, 1
      if (reg.getNumEntries2() > 1 )
      {
        // 81, 33
        jamonWriter.write(" int ");
        // 82, 6
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_ENTRIES_2")), jamonWriter);
        // 82, 64
        jamonWriter.write(" = ");
        // 82, 67
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getNumEntries2()), jamonWriter);
        // 82, 93
        jamonWriter.write(";\n");
      }
      // 83, 7
      jamonWriter.write(" int ");
      // 85, 6
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_STRUCT_ID")), jamonWriter);
      // 85, 64
      jamonWriter.write(" = ");
      // 85, 67
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getStructId()), jamonWriter);
      // 85, 90
      jamonWriter.write(";\n");
    }
    // 86, 8
    jamonWriter.write("\n}\n\n");
    // 93, 1
    for (RegisterBase base : bases )
    {
      // 93, 35
      jamonWriter.write("\n");
      // 94, 1
      String camelCaseBaseName = Utility.underscoreToCamelCase(base.getName(), true); 
      // 95, 1
      jamonWriter.write("define ");
      // 95, 8
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(camelCaseBaseName), jamonWriter);
      // 95, 31
      jamonWriter.write("RegisterFields ()() attributes {\n\n");
      // 97, 1
      for (Register reg : base.getRegisters() )
      {
        // 98, 1
        for (RegisterField field : reg.fields.values() )
        {
          // 99, 1
          if (field.len == 1 )
          {
            // 99, 23
            jamonWriter.write("  int ");
            // 100, 7
            org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_b_" + field.desc)), jamonWriter);
            // 100, 71
            jamonWriter.write(" = ");
            // 100, 74
            org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.pos), jamonWriter);
            // 100, 89
            jamonWriter.write(";\n");
          }
          // 101, 1
          else
          {
            // 101, 8
            jamonWriter.write("  int ");
            // 102, 7
            org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_l_" + field.desc)), jamonWriter);
            // 102, 71
            jamonWriter.write(" = ");
            // 102, 74
            org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.pos), jamonWriter);
            // 102, 89
            jamonWriter.write(";\n  int ");
            // 103, 7
            org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_h_" + field.desc)), jamonWriter);
            // 103, 71
            jamonWriter.write(" = ");
            // 103, 74
            org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.pos + field.len - 1), jamonWriter);
            // 103, 105
            jamonWriter.write(";\n  int ");
            // 104, 7
            org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_w_" + field.desc)), jamonWriter);
            // 104, 71
            jamonWriter.write(" = ");
            // 104, 74
            org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.len), jamonWriter);
            // 104, 89
            jamonWriter.write(";\n");
          }
          // 107, 1
          if (field.typedef != null && !base.getEnums().contains(field.typedef) && (field.currentEntry == field.baseEntry) )
          {
            // 107, 117
            org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.typedef.toCast()), jamonWriter);
          }
        }
        // 108, 8
        jamonWriter.write("  int ");
        // 109, 7
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_RW_MASK")), jamonWriter);
        // 109, 63
        jamonWriter.write(" = 0x");
        // 109, 68
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getTypeMask(RegisterType.RW).toHexString()), jamonWriter);
        // 109, 120
        jamonWriter.write(";\n  int ");
        // 110, 7
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_RO_MASK")), jamonWriter);
        // 110, 63
        jamonWriter.write(" = 0x");
        // 110, 68
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getTypeMask(RegisterType.RO).toHexString()), jamonWriter);
        // 110, 120
        jamonWriter.write(";\n  int ");
        // 111, 7
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_CW_MASK")), jamonWriter);
        // 111, 63
        jamonWriter.write(" = 0x");
        // 111, 68
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getTypeMask(RegisterType.CW).toHexString()), jamonWriter);
        // 111, 120
        jamonWriter.write(";\n  int ");
        // 112, 7
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_CW1_MASK")), jamonWriter);
        // 112, 64
        jamonWriter.write(" = 0x");
        // 112, 69
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getTypeMask(RegisterType.CW1).toHexString()), jamonWriter);
        // 112, 122
        jamonWriter.write(";\n  int ");
        // 113, 7
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_WO_MASK")), jamonWriter);
        // 113, 63
        jamonWriter.write(" = 0x");
        // 113, 68
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getTypeMask(RegisterType.WO).toHexString()), jamonWriter);
        // 113, 120
        jamonWriter.write(";\n  int ");
        // 114, 7
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", reg.getName() + "_RV_MASK")), jamonWriter);
        // 114, 63
        jamonWriter.write(" = 0x");
        // 114, 68
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getUnusedOrReservedMask().toHexString()), jamonWriter);
        // 114, 117
        jamonWriter.write(";\n");
      }
      // 117, 1
      for (ConstantsEnum e : base.getEnums() )
      {
        // 117, 43
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(e.toCast()), jamonWriter);
      }
      // 117, 66
      jamonWriter.write("\n  csp {\n");
      // 121, 1
      for (RegisterStruct rs : base.getStructs() )
      {
        // 122, 1
        {
          // 122, 1
          __jamon_innerUnit__structure(jamonWriter, rs );
        }
        // 122, 23
        jamonWriter.write("\n");
      }
      // 124, 1
      for (Register reg : base.getRegisters() )
      {
        // 125, 1
        {
          // 125, 1
          __jamon_innerUnit__structure(jamonWriter, reg );
        }
      }
      // 126, 8
      jamonWriter.write("  }\n}\n");
    }
    // 129, 8
    jamonWriter.write("\n\n");
  }
  
  
  // 132, 1
  private void __jamon_innerUnit__structure(final java.io.Writer jamonWriter, final RegisterStruct rs)
    throws java.io.IOException
  {
    // 133, 34
    jamonWriter.write("    structure ");
    // 134, 15
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(Utility.underscoreToCamelCase(rs.getName(), true)), jamonWriter);
    // 134, 70
    jamonWriter.write(" = (\n");
    // 135, 1
    if (rs.getSortedFields() != null )
    {
      // 136, 1
      if ((rs instanceof Register) && ( ((Register)rs).getImplementationWidth() > ((Register)rs).getNumberFieldBits() ) )
      {
        // 136, 118
        jamonWriter.write("      int(");
        // 137, 11
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(((Register)rs).getImplementationWidth() - ((Register)rs).getNumberFieldBits()), jamonWriter);
        // 137, 94
        jamonWriter.write(") RESERVED_IMPLEMENTATION_BITS;\n");
      }
      // 139, 1
      for (RegisterField field : rs.getSortedFields(true) )
      {
        // 139, 56
        jamonWriter.write("      int(");
        // 140, 11
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.len), jamonWriter);
        // 140, 26
        jamonWriter.write(") ");
        // 140, 28
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.desc), jamonWriter);
        // 140, 44
        if (field.entries>1 )
        {
          // 140, 67
          jamonWriter.write("[");
          // 140, 68
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.baseEntry), jamonWriter);
          // 140, 89
          jamonWriter.write("..");
          // 140, 91
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.entries-1), jamonWriter);
          // 140, 112
          jamonWriter.write("]");
        }
        // 140, 119
        jamonWriter.write(";\n");
      }
    }
    // 142, 1
    else
    {
      // 142, 8
      jamonWriter.write("      // ERROR: field overlap\n");
    }
    // 144, 7
    jamonWriter.write("    );\n");
  }
  
  
}
