// Autogenerated Jamon implementation
// C:/Users/mhesseli/Documents/Perforce/rrc-4/reg-main/shared/java/src/./com/fulcrummicro/hw/verification/chip/mgmt/registers/templates/CastRegMap.jamon

package com.fulcrummicro.hw.verification.chip.mgmt.registers.templates;

// 3, 1
import java.util.Collection;
// 4, 1
import com.fulcrummicro.util.misc.Utility;
// 5, 1
import com.fulcrummicro.hw.verification.chip.mgmt.registers.*;

public class CastRegMapImpl
  extends com.fulcrummicro.util.jamon.timestampImpl
  implements com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.CastRegMap.Intf

{
  private final Collection<RegisterCrossbarPort> crossbarPorts;
  private final Collection<RegisterBase> bases;
  private final Collection<Register> regs;
  private final String chip;
  protected static com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.CastRegMap.ImplData __jamon_setOptionalArguments(com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.CastRegMap.ImplData p_implData)
  {
    com.fulcrummicro.util.jamon.timestampImpl.__jamon_setOptionalArguments(p_implData);
    return p_implData;
  }
  public CastRegMapImpl(org.jamon.TemplateManager p_templateManager, com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.CastRegMap.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    crossbarPorts = p_implData.getCrossbarPorts();
    bases = p_implData.getBases();
    regs = p_implData.getRegs();
    chip = p_implData.getChip();
  }
  
  @Override protected void child_render_1(final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 12, 9
    jamonWriter.write("/**\n * INTEL TOP SECRET\n * Copyright ");
    // 15, 14
    {
      // 15, 14
      __jamon_innerUnit__copyright_year(jamonWriter, __jamon__get_Method_Opt_creationYear_default());
    }
    // 15, 35
    jamonWriter.write(" Intel Corporation. All Rights Reserved.\n *\n * THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MODIFY.\n * Last Updated ");
    // 18, 17
    {
      // 18, 17
      __jamon_innerUnit__timestamp(jamonWriter);
    }
    // 18, 33
    jamonWriter.write("\n */\nmodule chip.");
    // 20, 13
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(chip), jamonWriter);
    // 20, 23
    jamonWriter.write(".base.register_map;\n\nimport chip.");
    // 22, 13
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(chip), jamonWriter);
    // 22, 23
    jamonWriter.write(".base.constant.*;\nimport chip.");
    // 23, 13
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(chip), jamonWriter);
    // 23, 23
    jamonWriter.write(".base.functions.*;\nimport chip.");
    // 24, 13
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(chip), jamonWriter);
    // 24, 23
    jamonWriter.write(".base.registers.*;\n\n/**\n * Functions defined:\n *\n");
    // 29, 1
    for (RegisterCrossbarPort xbPort : crossbarPorts )
    {
      // 30, 1
      if (xbPort.hasBusStops() )
      {
        // 30, 29
        jamonWriter.write(" * ");
        // 31, 4
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(xbPort.getBusStopCspAttributeName()), jamonWriter);
        // 31, 45
        jamonWriter.write("\n");
      }
    }
    // 33, 8
    jamonWriter.write(" *\n * CbpDecoderFunctions\n *\n */\n\ndefine BusFunctions()() attributes {\n  csp {\n    structure DecodedRegister = (\n//FIXME addr using chip_addr for now\n//if changed to block_offset_addr there will be aliasing problems\n//if 2 or more register sets map onto the same bus stop\n      int addr;          // index into structure (in units of register width)\n      int bus_stop_nr;   // target bus stop\n      int num_words;     // number of atomic words in this register\n                         // otherwise one for non-atomic reg\n      int word_nr;       // word offset for current mgmt cycle for atomic reg\n                         // otherwise zero for non-atomic reg\n    );\n  }\n}\n\n");
    // 55, 1
    for (RegisterCrossbarPort xbPort : crossbarPorts )
    {
      // 56, 1
      if (xbPort.hasBusStops() )
      {
        // 56, 29
        jamonWriter.write("//Mgmt linear bus register decode functions\ndefine ");
        // 58, 8
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(xbPort.getBusStopCspAttributeName()), jamonWriter);
        // 58, 49
        jamonWriter.write("()() attributes\n  <+ chip.");
        // 59, 11
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(chip), jamonWriter);
        // 59, 21
        jamonWriter.write(".base.functions.RegisterFunctions\n  <+ chip.");
        // 60, 11
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(chip), jamonWriter);
        // 60, 21
        jamonWriter.write(".base.registers.AddressSpace\n  <+ BusFunctions\n{\n  csp {\n//FIXME dec_reg::addr using chip_addr for now\n//if changed to block_offset_addr there will be aliasing problems\n//if 2 or more register sets map onto the same bus stop\n\n    //decode chip address into bus stop address for MGMT_IN\n    function reg_map(\n      int -chip_addr; //chip level address\n      DecodedRegister +dec_reg) = (\n      int block_addr, i, i0, i1, i2, word;\n      dec_reg::num_words = 1; // default for registers w/ atomic width 1\n      dec_reg::word_nr   = 0; // default for registers w/ atomic width 1\n      dec_reg::addr = chip_addr; //FIXME may want to change to block_addr later\n");
        // 76, 1
        boolean firstBusStop = true; 
        // 76, 39
        jamonWriter.write("      #[");
        // 78, 14
        for (RegisterBusStop busStop : xbPort.getBusStops() )
        {
          // 79, 16
          for (RegisterBase base : busStop.getRegisterBases() )
          {
            // 80, 1
            org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(firstBusStop ? "" : "      []"), jamonWriter);
            // 80, 37
            firstBusStop=false; 
            // 80, 66
            jamonWriter.write("regRange(chip_addr, ");
            // 81, 21
            org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(base.getFullName()), jamonWriter);
            // 81, 45
            jamonWriter.write(", ");
            // 81, 47
            org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(base.getName()), jamonWriter);
            // 81, 67
            jamonWriter.write("_SIZE, block_addr) ->\n");
            // 82, 18
            if (busStop.getStride() > 0 )
            {
              // 82, 49
              jamonWriter.write("        int bus_stop_offset = (chip_addr - ");
              // 83, 44
              org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(base.getFullName()), jamonWriter);
              // 83, 68
              jamonWriter.write(") / ");
              // 83, 72
              org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("0x%x",busStop.getStride())), jamonWriter);
              // 83, 119
              jamonWriter.write(";\n        dec_reg::bus_stop_nr = ");
              // 84, 32
              org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(busStop.getName()), jamonWriter);
              // 84, 55
              jamonWriter.write(" + bus_stop_offset;\n        block_addr = block_addr - ");
              // 85, 35
              org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("0x%x",busStop.getStride())), jamonWriter);
              // 85, 82
              jamonWriter.write(" * bus_stop_offset;\n");
            }
            // 86, 18
            else
            {
              // 86, 25
              jamonWriter.write("        dec_reg::bus_stop_nr = ");
              // 87, 32
              org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(busStop.getName()), jamonWriter);
              // 87, 55
              jamonWriter.write(";\n");
            }
            // 94, 8
            jamonWriter.write("        #[");
            // 96, 1
            boolean firstReg = true; 
            // 97, 18
            for (Register reg : base.getRegisters() )
            {
              // 97, 61
              if (reg.getAlias() == null )
              {
                // 98, 1
                org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(firstReg ? "" : "        []"), jamonWriter);
                // 98, 35
                firstReg=false; 
                // 99, 20
                if (reg.getNumEntries() == 1 )
                {
                  // 99, 77
                  jamonWriter.write("addrMatch(block_addr,\n              ");
                  // 101, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 101, 34
                  jamonWriter.write("_ADDR,\n              ");
                  // 102, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 102, 34
                  jamonWriter.write("_BITS,\n              word) ->\n");
                }
                // 104, 20
                else if (reg.getNumEntries1() == 1 )
                {
                  // 104, 57
                  jamonWriter.write("addrMatch1D(block_addr,\n              ");
                  // 106, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 106, 34
                  jamonWriter.write("_BASE,\n              ");
                  // 107, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 107, 34
                  jamonWriter.write("_ENTRIES,\n              ");
                  // 108, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 108, 34
                  jamonWriter.write("_STRIDE,\n              ");
                  // 109, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 109, 34
                  jamonWriter.write("_BITS,\n              i, word) ->\n");
                }
                // 111, 20
                else if (reg.getNumEntries2() == 1 )
                {
                  // 111, 57
                  jamonWriter.write("addrMatch2D(block_addr,\n              ");
                  // 113, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 113, 34
                  jamonWriter.write("_BASE,\n              ");
                  // 114, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 114, 34
                  jamonWriter.write("_ENTRIES_0,\n              ");
                  // 115, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 115, 34
                  jamonWriter.write("_ENTRIES_1,\n              ");
                  // 116, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 116, 34
                  jamonWriter.write("_STRIDE_0,\n              ");
                  // 117, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 117, 34
                  jamonWriter.write("_STRIDE_1,\n              ");
                  // 118, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 118, 34
                  jamonWriter.write("_BITS,\n              i0, i1, word) ->\n");
                }
                // 120, 20
                else
                {
                  // 120, 27
                  jamonWriter.write("addrMatch3D(block_addr,\n              ");
                  // 122, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 122, 34
                  jamonWriter.write("_BASE,\n              ");
                  // 123, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 123, 34
                  jamonWriter.write("_ENTRIES_0,\n              ");
                  // 124, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 124, 34
                  jamonWriter.write("_ENTRIES_1,\n              ");
                  // 125, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 125, 34
                  jamonWriter.write("_ENTRIES_2,\n              ");
                  // 126, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 126, 34
                  jamonWriter.write("_STRIDE_0,\n              ");
                  // 127, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 127, 34
                  jamonWriter.write("_STRIDE_1,\n              ");
                  // 128, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 128, 34
                  jamonWriter.write("_STRIDE_2,\n              ");
                  // 129, 15
                  org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                  // 129, 34
                  jamonWriter.write("_BITS,\n              i0, i1, i2, word) ->\n");
                }
                // 131, 26
                jamonWriter.write("          dec_reg::num_words   = ");
                // 132, 34
                org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                // 132, 53
                jamonWriter.write("_ATOMIC_WIDTH;\n          dec_reg::word_nr     = word % ");
                // 133, 41
                org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
                // 133, 60
                jamonWriter.write("_ATOMIC_WIDTH;\n");
              }
            }
            // 135, 52
            jamonWriter.write("        ]\n");
          }
        }
        // 138, 42
        jamonWriter.write("      ]\n    );\n  }\n}\n\n");
      }
    }
    // 150, 1
    jamonWriter.write("define CbpDecoderFunctions () () attributes\n  <+ chip.");
    // 151, 11
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(chip), jamonWriter);
    // 151, 21
    jamonWriter.write(".base.constant.MgmtConstants\n  <+ chip.");
    // 152, 11
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(chip), jamonWriter);
    // 152, 21
    jamonWriter.write(".base.registers.AddressSpace\n  <+ chip.");
    // 153, 11
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(chip), jamonWriter);
    // 153, 21
    jamonWriter.write(".base.functions.RegisterFunctions\n  <+ standard.base.functions\n{\n  csp {\n  \t//return the crossbar port number that the chip_addr belongs to\n    function get_cb_port(\n      int -chip_addr; //chip level address\n  \t  int +cb_port //crossbar port\n  \t  ) = (\n  \t  int addr; //unused\n  \t  int cb_offset = 0; //for crossbar ports with non-zero stride\n");
    // 164, 1
    for (RegisterCrossbarPort cbp : crossbarPorts )
    {
      // 164, 50
      jamonWriter.write("\n      // ");
      // 165, 10
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(cbp.getName()), jamonWriter);
      // 165, 29
      jamonWriter.write("\n      [ ");
      // 167, 14
      for (RegisterBase base : cbp.getRegisterBases() )
      {
        // 167, 65
        jamonWriter.write("regRange(chip_addr, ");
        // 167, 85
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(base.getFullName()), jamonWriter);
        // 167, 109
        jamonWriter.write(", ");
        // 167, 111
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(base.getName()), jamonWriter);
        // 167, 131
        jamonWriter.write("_SIZE, addr) ->\n");
        // 168, 16
        if (cbp.getStride() > 0 )
        {
          // 168, 43
          jamonWriter.write("        cb_offset = (chip_addr - ");
          // 169, 34
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(base.getFullName()), jamonWriter);
          // 169, 58
          jamonWriter.write(") / ");
          // 169, 62
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("0x%x",cbp.getStride())), jamonWriter);
          // 169, 105
          jamonWriter.write(";\n        cb_port = ");
          // 170, 19
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(cbp.getName()), jamonWriter);
          // 170, 38
          jamonWriter.write(" + cb_offset\n");
        }
        // 171, 16
        else
        {
          // 171, 23
          jamonWriter.write("        cb_port = ");
          // 172, 19
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(cbp.getName()), jamonWriter);
          // 172, 38
          jamonWriter.write("\n");
        }
        // 173, 22
        jamonWriter.write("      [] ");
      }
      // 175, 38
      jamonWriter.write("else -> assert(false, \"unknown address \"+hex(chip_addr))\n      ];\n");
    }
    // 177, 8
    jamonWriter.write("\n  \t);\n  } \n}\n\n");
  }
  
  
}
