// Autogenerated Jamon proxy
// C:/Users/mhesseli/Documents/Perforce/rrc-4/reg-main/shared/java/src/./com/fulcrummicro/hw/verification/chip/mgmt/registers/templates/CastMgmtTcam.jamon

package com.fulcrummicro.hw.verification.chip.mgmt.registers.templates;

// 6, 1
import java.util.Collection;
// 7, 1
import com.fulcrummicro.util.misc.Utility;
// 8, 1
import com.fulcrummicro.hw.verification.chip.mgmt.registers.*;

@org.jamon.annotations.Template(
  signature = "93D749115F61F4EF34724C9EE85B0917",
  requiredArguments = {
    @org.jamon.annotations.Argument(name = "base", type = "RegisterBase"),
    @org.jamon.annotations.Argument(name = "registers", type = "Collection<Register>"),
    @org.jamon.annotations.Argument(name = "baseNamePrefixCC", type = "String")})
public class CastMgmtTcam
  extends org.jamon.AbstractTemplateProxy
{
  
  public CastMgmtTcam(org.jamon.TemplateManager p_manager)
  {
     super(p_manager);
  }
  
  protected CastMgmtTcam(String p_path)
  {
    super(p_path);
  }
  
  public CastMgmtTcam()
  {
     super("/com/fulcrummicro/hw/verification/chip/mgmt/registers/templates/CastMgmtTcam");
  }
  
  public interface Intf
    extends org.jamon.AbstractTemplateProxy.Intf
  {
    
    void renderNoFlush(final java.io.Writer jamonWriter) throws java.io.IOException;
    
  }
  public static class ImplData
    extends org.jamon.AbstractTemplateProxy.ImplData
  {
    // 11, 1
    public void setBase(RegisterBase base)
    {
      // 11, 1
      m_base = base;
    }
    public RegisterBase getBase()
    {
      return m_base;
    }
    private RegisterBase m_base;
    // 12, 1
    public void setRegisters(Collection<Register> registers)
    {
      // 12, 1
      m_registers = registers;
    }
    public Collection<Register> getRegisters()
    {
      return m_registers;
    }
    private Collection<Register> m_registers;
    // 13, 1
    public void setBaseNamePrefixCC(String baseNamePrefixCC)
    {
      // 13, 1
      m_baseNamePrefixCC = baseNamePrefixCC;
    }
    public String getBaseNamePrefixCC()
    {
      return m_baseNamePrefixCC;
    }
    private String m_baseNamePrefixCC;
  }
  @Override
  protected org.jamon.AbstractTemplateProxy.ImplData makeImplData()
  {
    return new ImplData();
  }
  @Override public ImplData getImplData()
  {
    return (ImplData) super.getImplData();
  }
  
  
  @Override
  public org.jamon.AbstractTemplateImpl constructImpl(Class<? extends org.jamon.AbstractTemplateImpl> p_class){
    try
    {
      return p_class
        .getConstructor(new Class [] { org.jamon.TemplateManager.class, ImplData.class })
        .newInstance(new Object [] { getTemplateManager(), getImplData()});
    }
    catch (RuntimeException e)
    {
      throw e;
    }
    catch (Exception e)
    {
      throw new RuntimeException(e);
    }
  }
  
  @Override
  protected org.jamon.AbstractTemplateImpl constructImpl(){
    return new CastMgmtTcamImpl(getTemplateManager(), getImplData());
  }
  public org.jamon.Renderer makeRenderer(final RegisterBase base, final Collection<Register> registers, final String baseNamePrefixCC)
  {
    return new org.jamon.AbstractRenderer() {
      @Override
      public void renderTo(final java.io.Writer jamonWriter)
        throws java.io.IOException
      {
        render(jamonWriter, base, registers, baseNamePrefixCC);
      }
    };
  }
  
  public void render(final java.io.Writer jamonWriter, final RegisterBase base, final Collection<Register> registers, final String baseNamePrefixCC)
    throws java.io.IOException
  {
    renderNoFlush(jamonWriter, base, registers, baseNamePrefixCC);
    jamonWriter.flush();
  }
  public void renderNoFlush(final java.io.Writer jamonWriter, final RegisterBase base, final Collection<Register> registers, final String baseNamePrefixCC)
    throws java.io.IOException
  {
    ImplData implData = getImplData();
    implData.setBase(base);
    implData.setRegisters(registers);
    implData.setBaseNamePrefixCC(baseNamePrefixCC);
    Intf instance = (Intf) getTemplateManager().constructImpl(this);
    instance.renderNoFlush(jamonWriter);
    reset();
  }
  
  
}
