// Autogenerated Jamon implementation
// C:/Users/mhesseli/Documents/Perforce/rrc-4/reg-main/shared/java/src/./com/fulcrummicro/hw/verification/chip/mgmt/registers/templates/H.jamon

package com.fulcrummicro.hw.verification.chip.mgmt.registers.templates;

// 3, 1
import java.util.Collection;
// 4, 1
import java.util.Iterator;
// 5, 1
import java.util.Set;
// 6, 1
import java.util.TreeSet;
// 7, 1
import com.avlsi.util.text.StringUtil;
// 8, 1
import com.fulcrummicro.util.misc.Utility;
// 9, 1
import com.fulcrummicro.hw.verification.chip.mgmt.registers.Register;
// 10, 1
import com.fulcrummicro.hw.verification.chip.mgmt.registers.RegisterBase;
// 11, 1
import com.fulcrummicro.hw.verification.chip.mgmt.registers.RegisterField;
// 12, 1
import com.fulcrummicro.hw.verification.chip.mgmt.registers.RegisterStruct;
// 13, 1
import com.fulcrummicro.hw.verification.lib.testcase.ResetType.ResetDomain;

public class HImpl
  extends com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.CImpl
  implements com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.H.Intf

{
  private final Collection<RegisterBase> bases;
  private final Collection<Register> regs;
  private final String prefix;
  // 76, 1
  
static int ndims(Register r) {
    return r.getNumDimensions() == 1 && r.getNumEntries() == 1 ?
           0 :
           r.getNumDimensions();
}
static String INDENT = StringUtil.repeatString(" ", 60);

  protected static com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.H.ImplData __jamon_setOptionalArguments(com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.H.ImplData p_implData)
  {
    com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.CImpl.__jamon_setOptionalArguments(p_implData);
    return p_implData;
  }
  public HImpl(org.jamon.TemplateManager p_templateManager, com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.H.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    bases = p_implData.getBases();
    regs = p_implData.getRegs();
    prefix = p_implData.getPrefix();
  }
  
  @Override protected void child_render_2(final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 84, 1
    
String lowerPrefix = Utility.underscoreToCamelCase(prefix, false);

    // 87, 1
    jamonWriter.write("/**\n * INTEL CONFIDENTIAL\n * Copyright ");
    // 89, 14
    {
      // 89, 14
      __jamon_innerUnit__copyright_year(jamonWriter, __jamon__get_Method_Opt_creationYear_default());
    }
    // 89, 35
    jamonWriter.write(" Intel Corporation. All Rights Reserved.\n *\n * THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MODIFY.\n * Last Updated ");
    // 92, 17
    {
      // 92, 17
      __jamon_innerUnit__timestamp(jamonWriter);
    }
    // 92, 33
    jamonWriter.write("\n */\n\n#ifndef __FM_");
    // 95, 14
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix), jamonWriter);
    // 95, 26
    jamonWriter.write("API_REGS_INT_H\n#define __FM_");
    // 96, 14
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix), jamonWriter);
    // 96, 26
    jamonWriter.write("API_REGS_INT_H\n\ntypedef enum\n{\n    ");
    // 103, 5
    {
      // 103, 5
      __jamon_innerUnit__rstdom(jamonWriter, ResetDomain.CHIP.toString(), prefix );
    }
    // 103, 72
    jamonWriter.write(" = 0,\n\n");
    // 105, 1
    
Set<ResetDomain> domains = new TreeSet<ResetDomain>();
for (Register r : regs) {
    domains.addAll(r.getResetType(0).getDomains());
}

    // 111, 1
    for (ResetDomain domain : domains )
    {
      // 111, 38
      jamonWriter.write("    ");
      // 112, 5
      {
        // 112, 5
        __jamon_innerUnit__rstdom(jamonWriter, domain.toString(), prefix );
      }
      // 112, 62
      jamonWriter.write(" = ");
      // 113, 1
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(domain.ordinal()), jamonWriter);
      // 113, 23
      jamonWriter.write(",\n\n");
    }
    // 115, 8
    jamonWriter.write("    ");
    // 116, 5
    {
      // 116, 5
      __jamon_innerUnit__rstdom(jamonWriter, "MAX", prefix );
    }
    // 116, 50
    jamonWriter.write("\n\n} ");
    // 118, 3
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(lowerPrefix), jamonWriter);
    // 118, 20
    jamonWriter.write("_resetDomain;\n\n\n/*      Register Base                            incremental   absolute base */\n");
    // 122, 1
    for (RegisterBase base : bases )
    {
      // 123, 1
      RegisterBase parent = base.getParent();
      // 124, 1
      jamonWriter.write("#define ");
      // 124, 9
      {
        // 124, 9
        __jamon_innerUnit____decl(jamonWriter, base.getFullName() , null);
      }
      // 124, 48
      jamonWriter.write(" (");
      // 125, 1
      {
        // 125, 1
        __jamon_innerUnit__strfaddr(jamonWriter, base.getIncrementalAddress() );
      }
      // 126, 1
      if (parent.getParent() != null )
      {
        // 126, 35
        jamonWriter.write("+ ");
        // 126, 37
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix + parent.getFullName()), jamonWriter);
      }
      // 126, 78
      jamonWriter.write(")\n");
      // 128, 1
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(INDENT), jamonWriter);
      // 128, 13
      jamonWriter.write("/* ");
      // 128, 16
      {
        // 128, 16
        __jamon_innerUnit__strfaddr(jamonWriter, base.getAbsoluteAddress() );
      }
      // 128, 64
      jamonWriter.write(" ");
      // 129, 1
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(parent.getFullName()), jamonWriter);
      // 129, 27
      jamonWriter.write(" */\n#define ");
      // 130, 9
      {
        // 130, 9
        __jamon_innerUnit____decl(jamonWriter, base.getName(), "_SIZE" );
      }
      // 130, 62
      jamonWriter.write(" ");
      // 131, 1
      {
        // 131, 1
        __jamon_innerUnit__strfaddr(jamonWriter, base.getSize() );
      }
      // 131, 38
      jamonWriter.write("\n\n");
    }
    // 133, 8
    jamonWriter.write("\n/*      Register Name                            incremental   absolute base */\n");
    // 136, 1
    for (Register reg : regs )
    {
      // 137, 1
      
int nDims = ndims(reg);
boolean w = reg.getEntryWidth() > 1;

      // 147, 1
      if (nDims == 0 )
      {
        // 147, 19
        jamonWriter.write("#define ");
        // 148, 9
        {
          // 148, 9
          __jamon_innerUnit____decl(jamonWriter, reg.getName(), w ? "(word)" : "()" );
        }
        // 148, 73
        jamonWriter.write(" (");
      }
      // 149, 1
      else if (nDims == 1 )
      {
        // 149, 23
        jamonWriter.write("#define ");
        // 150, 9
        {
          // 150, 9
          __jamon_innerUnit____decl(jamonWriter, reg.getName(), w ? "(index, word)" : "(index)" );
        }
        // 150, 85
        jamonWriter.write(" ((");
        // 151, 2
        {
          // 151, 2
          __jamon_innerUnit__strfaddr(jamonWriter, reg.getEntrySpace() );
        }
        // 151, 44
        jamonWriter.write(") * ((index) - ");
        // 151, 59
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getBaseEntry()), jamonWriter);
        // 151, 83
        jamonWriter.write(") + ");
      }
      // 152, 1
      else if (nDims == 2 )
      {
        // 152, 23
        jamonWriter.write("#define ");
        // 153, 9
        {
          // 153, 9
          __jamon_innerUnit____decl(jamonWriter, reg.getName(), w ? "(index1, index0, word)" : "(index1, index0)" );
        }
        // 153, 103
        jamonWriter.write(" ((");
        // 154, 2
        {
          // 154, 2
          __jamon_innerUnit__strfaddr(jamonWriter, reg.getEntrySpace1() );
        }
        // 154, 45
        jamonWriter.write(") * ((index1) - ");
        // 154, 61
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getBaseEntry1()), jamonWriter);
        // 154, 86
        jamonWriter.write(") + (");
        // 155, 2
        {
          // 155, 2
          __jamon_innerUnit__strfaddr(jamonWriter, reg.getEntrySpace() );
        }
        // 155, 44
        jamonWriter.write(") * ((index0) - ");
        // 155, 60
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getBaseEntry()), jamonWriter);
        // 155, 84
        jamonWriter.write(") + ");
      }
      // 156, 1
      else if (nDims == 3 )
      {
        // 156, 23
        jamonWriter.write("#define ");
        // 157, 9
        {
          // 157, 9
          __jamon_innerUnit____decl(jamonWriter, reg.getName(), w ? "(index2, index1, index0, word)" : "(index2, index1, index0)" );
        }
        // 157, 119
        jamonWriter.write(" ((");
        // 158, 2
        {
          // 158, 2
          __jamon_innerUnit__strfaddr(jamonWriter, reg.getEntrySpace2() );
        }
        // 158, 45
        jamonWriter.write(") * ((index2) - ");
        // 158, 61
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getBaseEntry2()), jamonWriter);
        // 158, 86
        jamonWriter.write(") + (");
        // 159, 2
        {
          // 159, 2
          __jamon_innerUnit__strfaddr(jamonWriter, reg.getEntrySpace1() );
        }
        // 159, 45
        jamonWriter.write(") * ((index1) - ");
        // 159, 61
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getBaseEntry1()), jamonWriter);
        // 159, 86
        jamonWriter.write(") + (");
        // 160, 2
        {
          // 160, 2
          __jamon_innerUnit__strfaddr(jamonWriter, reg.getEntrySpace() );
        }
        // 160, 44
        jamonWriter.write(") * ((index0) - ");
        // 160, 60
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getBaseEntry()), jamonWriter);
        // 160, 84
        jamonWriter.write(") + ");
      }
      // 161, 1
      else
      {
        // 162, 1
        throw new Error(nDims + "-dimensional registers not supported");
      }
      // 164, 1
      if (w )
      {
        // 164, 10
        jamonWriter.write("(word) + ");
      }
      // 164, 25
      jamonWriter.write("(");
      // 165, 2
      {
        // 165, 2
        __jamon_innerUnit__strfaddr(jamonWriter, reg.getAddressOffset() );
      }
      // 165, 47
      jamonWriter.write(") + (");
      // 166, 2
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix + reg.getBaseName()), jamonWriter);
      // 166, 34
      jamonWriter.write("))\n");
      // 167, 1
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(INDENT), jamonWriter);
      // 167, 13
      jamonWriter.write("/* ");
      // 167, 16
      {
        // 167, 16
        __jamon_innerUnit__strfaddr(jamonWriter, reg.getAddress() );
      }
      // 167, 55
      jamonWriter.write(" ");
      // 168, 1
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix + reg.getBaseName()), jamonWriter);
      // 168, 33
      jamonWriter.write(" */\n#define ");
      // 170, 9
      {
        // 170, 9
        __jamon_innerUnit____decl(jamonWriter, reg.getName(), "_WIDTH" );
      }
      // 170, 62
      jamonWriter.write(" ");
      // 171, 1
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getEntryWidth()), jamonWriter);
      // 171, 26
      jamonWriter.write("\n");
      // 173, 1
      if (nDims >= 1 )
      {
        // 173, 19
        jamonWriter.write("#define ");
        // 174, 9
        {
          // 174, 9
          __jamon_innerUnit____decl(jamonWriter, reg.getName(), nDims > 1 ? "_ENTRIES_0" : "_ENTRIES" );
        }
        // 174, 91
        jamonWriter.write(" ");
        // 175, 1
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getNumEntries()), jamonWriter);
        // 175, 26
        jamonWriter.write("\n");
      }
      // 177, 1
      if (nDims >= 2 )
      {
        // 177, 19
        jamonWriter.write("#define ");
        // 178, 9
        {
          // 178, 9
          __jamon_innerUnit____decl(jamonWriter, reg.getName(), "_ENTRIES_1" );
        }
        // 178, 66
        jamonWriter.write(" ");
        // 179, 1
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getNumEntries1()), jamonWriter);
        // 179, 27
        jamonWriter.write("\n");
      }
      // 181, 1
      if (nDims >= 3 )
      {
        // 181, 19
        jamonWriter.write("#define ");
        // 182, 9
        {
          // 182, 9
          __jamon_innerUnit____decl(jamonWriter, reg.getName(), "_ENTRIES_2" );
        }
        // 182, 66
        jamonWriter.write(" ");
        // 183, 1
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getNumEntries2()), jamonWriter);
        // 183, 27
        jamonWriter.write("\n");
      }
      // 184, 7
      jamonWriter.write("\n");
    }
    // 186, 8
    jamonWriter.write("\n/*** Register fields ***/\n");
    // 189, 1
    for (Register reg : regs )
    {
      // 190, 1
      {
        // 190, 1
        __jamon_innerUnit____fields(jamonWriter, reg );
      }
    }
    // 191, 8
    jamonWriter.write("\n/*** Register Structure fields ***/\n");
    // 194, 1
    for (RegisterBase base : bases )
    {
      // 195, 1
      for (RegisterStruct rs : base.getStructs() )
      {
        // 195, 47
        jamonWriter.write("#define ");
        // 196, 9
        {
          // 196, 9
          __jamon_innerUnit____decl(jamonWriter, rs.getName(), "_WIDTH" );
        }
        // 196, 61
        jamonWriter.write(" ");
        // 197, 1
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(rs.getEntryWidth()), jamonWriter);
        // 197, 25
        jamonWriter.write("\n");
        // 198, 1
        {
          // 198, 1
          __jamon_innerUnit____fields(jamonWriter, rs );
        }
      }
    }
    // 200, 8
    jamonWriter.write("#endif  /* __FM_");
    // 201, 17
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix), jamonWriter);
    // 201, 29
    jamonWriter.write("API_REGS_INT_H */\n\n");
  }
  
  
  // 36, 1
  private void __jamon_innerUnit____fields(final java.io.Writer jamonWriter, final RegisterStruct reg)
    throws java.io.IOException
  {
    // 38, 1
    Collection<RegisterField> fields = reg.getSortedFields(false, false, false); 
    // 39, 1
    if (fields == null )
    {
      // 40, 1
      fields = reg.fields.values();
      // 41, 1
      jamonWriter.write("/* WARNING: Fields below from ");
      // 41, 31
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getName()), jamonWriter);
      // 41, 50
      jamonWriter.write(" overlap */\n");
    }
    // 43, 1
    for (RegisterField f : fields )
    {
      // 44, 1
      if (f.len == 1 )
      {
        // 44, 19
        jamonWriter.write("#define ");
        // 45, 9
        {
          // 45, 9
          __jamon_innerUnit____decl(jamonWriter, reg.getName(), "_b_" + f.desc );
        }
        // 45, 68
        jamonWriter.write(" ");
        // 45, 69
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(f.pos), jamonWriter);
        // 45, 80
        jamonWriter.write("\n");
      }
      // 46, 1
      else
      {
        // 46, 8
        jamonWriter.write("#define ");
        // 47, 9
        {
          // 47, 9
          __jamon_innerUnit____decl(jamonWriter, reg.getName(), "_l_" + f.desc );
        }
        // 47, 68
        jamonWriter.write(" ");
        // 47, 69
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(f.pos), jamonWriter);
        // 47, 80
        jamonWriter.write("\n#define ");
        // 48, 9
        {
          // 48, 9
          __jamon_innerUnit____decl(jamonWriter, reg.getName(), "_h_" + f.desc );
        }
        // 48, 68
        jamonWriter.write(" ");
        // 49, 1
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(f.pos + f.len - 1), jamonWriter);
        // 49, 24
        jamonWriter.write("\n");
      }
    }
    // 52, 1
    fields = reg.getSortedFields(false, true, false);
    // 53, 1
    if (fields != null )
    {
      // 54, 1
      for (RegisterField f : fields )
      {
        // 55, 1
        if (f.entries>1 )
        {
          // 55, 20
          jamonWriter.write("#define ");
          // 56, 9
          {
            // 56, 9
            __jamon_innerUnit____decl(jamonWriter, reg.getName(), "_l_" + f.desc );
          }
          // 56, 68
          jamonWriter.write(" ");
          // 56, 69
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(f.pos), jamonWriter);
          // 56, 80
          jamonWriter.write("\n#define ");
          // 57, 9
          {
            // 57, 9
            __jamon_innerUnit____decl(jamonWriter, reg.getName(), "_h_" + f.desc );
          }
          // 57, 68
          jamonWriter.write(" ");
          // 58, 1
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(f.pos + (f.entries * f.len) - 1), jamonWriter);
          // 58, 38
          jamonWriter.write("\n#define ");
          // 59, 9
          {
            // 59, 9
            __jamon_innerUnit____decl(jamonWriter, reg.getName(), "_s_" + f.desc );
          }
          // 59, 68
          jamonWriter.write(" ");
          // 59, 69
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(f.len), jamonWriter);
          // 59, 80
          jamonWriter.write("\n");
        }
      }
    }
    // 62, 7
    jamonWriter.write("\n");
  }
  
  
  // 19, 1
  private void __jamon_innerUnit____decl(final java.io.Writer jamonWriter, final String name, final String suffix)
    throws java.io.IOException
  {
    // 24, 1
    
String s = prefix + name;
if (suffix != null) {
    s += suffix;
}

    // 30, 1
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%-40s", s)), jamonWriter);
  }
  
  
}
