// Autogenerated Jamon implementation
// C:/Users/mhesseli/Documents/Perforce/rrc-4/reg-main/shared/java/src/./com/fulcrummicro/hw/verification/chip/mgmt/registers/templates/Python.jamon

package com.fulcrummicro.hw.verification.chip.mgmt.registers.templates;

// 3, 1
import java.util.Collection;
// 4, 1
import com.fulcrummicro.hw.verification.chip.mgmt.registers.*;

public class PythonImpl
  extends com.fulcrummicro.util.jamon.timestampImpl
  implements com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.Python.Intf

{
  private final Collection<RegisterBase> bases;
  private final Collection<Register> regs;
  private final String prefix;
  protected static com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.Python.ImplData __jamon_setOptionalArguments(com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.Python.ImplData p_implData)
  {
    com.fulcrummicro.util.jamon.timestampImpl.__jamon_setOptionalArguments(p_implData);
    return p_implData;
  }
  public PythonImpl(org.jamon.TemplateManager p_templateManager, com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.Python.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    bases = p_implData.getBases();
    regs = p_implData.getRegs();
    prefix = p_implData.getPrefix();
  }
  
  @Override protected void child_render_1(final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 10, 9
    jamonWriter.write("#!/usr/bin/python\n\"\"\"\nINTEL CONFIDENTIAL\nCopyright ");
    // 14, 11
    {
      // 14, 11
      __jamon_innerUnit__copyright_year(jamonWriter, __jamon__get_Method_Opt_creationYear_default());
    }
    // 14, 32
    jamonWriter.write(" Intel Corporation\nAll Rights Reserved.\n\nTHIS FILE IS AUTOMATICALLY GENERATED - DO NOT MODIFY.\nLast Updated ");
    // 18, 14
    {
      // 18, 14
      __jamon_innerUnit__timestamp(jamonWriter);
    }
    // 18, 30
    jamonWriter.write("\n\"\"\"\n\n# Register_Name                            incremental  absolute  base\n");
    // 22, 1
    for (RegisterBase base : bases )
    {
      // 23, 1
      if (base.getParent().getParent() == null )
      {
        // 24, 1
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+String.format("%-40s", base.getFullName())), jamonWriter);
        // 24, 56
        jamonWriter.write(" = 0x");
        // 24, 61
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", base.getIncrementalAddress())), jamonWriter);
        // 24, 118
        jamonWriter.write("\n");
      }
      // 25, 1
      else
      {
        // 26, 1
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+String.format("%-40s", base.getFullName())), jamonWriter);
        // 26, 56
        jamonWriter.write("  ((0x");
        // 27, 6
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", base.getIncrementalAddress())), jamonWriter);
        // 27, 63
        jamonWriter.write(") + (");
        // 27, 68
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+base.getParent().getFullName()), jamonWriter);
        // 27, 111
        jamonWriter.write("))\n");
      }
      // 28, 7
      jamonWriter.write("                                                # 0x");
      // 29, 53
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", base.getAbsoluteAddress())), jamonWriter);
      // 29, 107
      jamonWriter.write(" ");
      // 29, 108
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(base.getParent().getFullName()), jamonWriter);
      // 29, 144
      jamonWriter.write("\n");
      // 30, 1
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+String.format("%-40s", base.getName() + "_SIZE")), jamonWriter);
      // 30, 62
      jamonWriter.write(" = 0x");
      // 30, 67
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", base.getSize())), jamonWriter);
      // 30, 110
      jamonWriter.write("\n\n");
    }
    // 32, 8
    jamonWriter.write("\n\n\n");
    // 36, 1
    for (Register reg : regs )
    {
      // 37, 1
      boolean w = (reg.getEntryWidth() > 1); 
      // 38, 1
      if (reg.getNumEntries() == 1 )
      {
        // 38, 33
        jamonWriter.write("def ");
        // 39, 5
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+String.format("%-40s", reg.getName() + (w? "(word)" : "()"))), jamonWriter);
        // 39, 78
        jamonWriter.write(":\n    return ((0x");
        // 40, 16
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getAddressOffset())), jamonWriter);
        // 40, 67
        jamonWriter.write(") + (");
        // 40, 72
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+reg.getBaseName()), jamonWriter);
        // 40, 102
        if (w )
        {
          // 40, 111
          jamonWriter.write(" + (word)");
        }
        // 40, 126
        jamonWriter.write("))\n");
      }
      // 41, 1
      else if (reg.getNumEntries1() == 1 )
      {
        // 41, 38
        jamonWriter.write("def ");
        // 42, 5
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+String.format("%-40s", reg.getName() + "(index" + (w? ", word)" : ")"))), jamonWriter);
        // 42, 89
        jamonWriter.write(":\n    return ((0x");
        // 43, 16
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getEntrySpace())), jamonWriter);
        // 43, 64
        jamonWriter.write(") * ((index) - (");
        // 43, 80
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getBaseEntry()), jamonWriter);
        // 43, 104
        jamonWriter.write(")) + (0x");
        // 44, 5
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getAddressOffset())), jamonWriter);
        // 44, 56
        jamonWriter.write(") + (");
        // 44, 61
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+reg.getBaseName()), jamonWriter);
        // 44, 91
        if (w )
        {
          // 44, 100
          jamonWriter.write(" + (word)");
        }
        // 44, 115
        jamonWriter.write("))\n");
      }
      // 45, 1
      else if (reg.getNumEntries2() == 1 )
      {
        // 45, 38
        jamonWriter.write("def ");
        // 46, 5
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+String.format("%-40s", reg.getName() + "(index1, index0" + (w? ", word)" : ")"))), jamonWriter);
        // 46, 98
        jamonWriter.write(":\n    return ((0x");
        // 47, 16
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getEntrySpace1())), jamonWriter);
        // 47, 65
        jamonWriter.write(") * ((index1) - (");
        // 47, 82
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getBaseEntry1()), jamonWriter);
        // 47, 107
        jamonWriter.write(")) + (0x");
        // 48, 5
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getEntrySpace())), jamonWriter);
        // 48, 53
        jamonWriter.write(") * ((index0) - (");
        // 48, 70
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getBaseEntry()), jamonWriter);
        // 48, 94
        jamonWriter.write(")) + (0x");
        // 49, 5
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getAddressOffset())), jamonWriter);
        // 49, 56
        jamonWriter.write(") + (");
        // 49, 61
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+reg.getBaseName()), jamonWriter);
        // 49, 91
        if (w )
        {
          // 49, 100
          jamonWriter.write(" + (word)");
        }
        // 49, 115
        jamonWriter.write("))\n");
      }
      // 50, 1
      else
      {
        // 50, 8
        jamonWriter.write("def ");
        // 51, 5
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+String.format("%-40s", reg.getName() + "(index2, index1, index0" + (w? ", word)" : ")"))), jamonWriter);
        // 51, 106
        jamonWriter.write(":\n    return ((0x");
        // 52, 16
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getEntrySpace2())), jamonWriter);
        // 52, 65
        jamonWriter.write(" ) * ((index2) - (");
        // 52, 83
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getBaseEntry2()), jamonWriter);
        // 52, 108
        jamonWriter.write(")) + (0x");
        // 53, 5
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getEntrySpace1())), jamonWriter);
        // 53, 54
        jamonWriter.write(") * ((index1) - (");
        // 53, 71
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getBaseEntry1()), jamonWriter);
        // 53, 96
        jamonWriter.write(")) + (0x");
        // 54, 5
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getEntrySpace())), jamonWriter);
        // 54, 53
        jamonWriter.write(") * ((index0) - (");
        // 54, 70
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getBaseEntry()), jamonWriter);
        // 54, 94
        jamonWriter.write(")) + (0x");
        // 55, 5
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getAddressOffset())), jamonWriter);
        // 55, 56
        jamonWriter.write(") + (");
        // 55, 61
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+reg.getBaseName()), jamonWriter);
        // 55, 91
        if (w )
        {
          // 55, 100
          jamonWriter.write(" + (word)");
        }
        // 55, 115
        jamonWriter.write("))\n");
      }
      // 56, 7
      jamonWriter.write("                                                # 0x");
      // 57, 53
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%05X", reg.getAddressSafe())), jamonWriter);
      // 57, 102
      jamonWriter.write(" ");
      // 57, 103
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getBaseName()), jamonWriter);
      // 57, 126
      jamonWriter.write("\n");
      // 58, 1
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+String.format("%-40s", reg.getName() + "_WIDTH")), jamonWriter);
      // 58, 62
      jamonWriter.write(" = ");
      // 58, 65
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getEntryWidth()), jamonWriter);
      // 58, 90
      jamonWriter.write("\n");
      // 59, 1
      if (reg.getNumEntries() > 1 )
      {
        // 60, 1
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+String.format("%-40s", reg.getName() + "_ENTRIES" + ((reg.getNumEntries1() > 1)? "_0" : ""))), jamonWriter);
        // 60, 106
        jamonWriter.write(" = ");
        // 60, 109
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getNumEntries()), jamonWriter);
        // 60, 134
        jamonWriter.write("\n\n");
      }
      // 63, 1
      if (reg.getNumEntries1() > 1 )
      {
        // 64, 1
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+String.format("%-40s", reg.getName() + "_ENTRIES_1")), jamonWriter);
        // 64, 66
        jamonWriter.write(" = ");
        // 64, 69
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getNumEntries1()), jamonWriter);
        // 64, 95
        jamonWriter.write("\n\n");
      }
      // 67, 1
      if (reg.getNumEntries1() > 2 )
      {
        // 68, 1
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+String.format("%-40s", reg.getName() + "_ENTRIES_2")), jamonWriter);
        // 68, 66
        jamonWriter.write(" = ");
        // 68, 69
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(reg.getNumEntries2()), jamonWriter);
        // 68, 95
        jamonWriter.write("\n\n");
      }
    }
    // 71, 8
    jamonWriter.write("\n\n\n");
    // 75, 1
    for (Register reg : regs )
    {
      // 76, 1
      for (RegisterField field : reg.fields.values() )
      {
        // 77, 1
        if (field.len == 1 )
        {
          // 78, 1
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+String.format("%-40s", reg.getName() + "_b_" + field.desc)), jamonWriter);
          // 78, 72
          jamonWriter.write(" = ");
          // 78, 75
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.pos), jamonWriter);
          // 78, 90
          jamonWriter.write("\n");
        }
        // 79, 1
        else
        {
          // 80, 1
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+String.format("%-40s", reg.getName() + "_l_" + field.desc)), jamonWriter);
          // 80, 72
          jamonWriter.write(" =  ");
          // 80, 76
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.pos), jamonWriter);
          // 80, 91
          jamonWriter.write("\n");
          // 81, 1
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix+String.format("%-40s", reg.getName() + "_h_" + field.desc)), jamonWriter);
          // 81, 72
          jamonWriter.write(" = ");
          // 81, 75
          org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.pos + field.len - 1), jamonWriter);
          // 81, 106
          jamonWriter.write("\n");
        }
      }
      // 83, 8
      jamonWriter.write("\n");
    }
  }
  
  
}
