// Autogenerated Jamon proxy
// C:/Users/mhesseli/Documents/Perforce/rrc-4/reg-main/shared/java/src/./com/fulcrummicro/hw/verification/chip/mgmt/registers/templates/SdkDebugRegs.jamon

package com.fulcrummicro.hw.verification.chip.mgmt.registers.templates;

// 3, 1
import java.util.Collection;
// 4, 1
import java.util.regex.Pattern;
// 5, 1
import com.fulcrummicro.util.misc.Utility;
// 6, 1
import com.fulcrummicro.hw.verification.chip.mgmt.registers.Register;

@org.jamon.annotations.Template(
  signature = "AE37EC08C01F727701C11D97715D2759",
  inheritanceDepth = 1,
  requiredArguments = {
    @org.jamon.annotations.Argument(name = "regs", type = "Collection<Register>"),
    @org.jamon.annotations.Argument(name = "prefix", type = "String"),
    @org.jamon.annotations.Argument(name = "numPorts", type = "int"),
    @org.jamon.annotations.Argument(name = "numEpls", type = "int"),
    @org.jamon.annotations.Argument(name = "numLanes", type = "int")},
  methods = {
    @org.jamon.annotations.Method(
      name = "timestamp"),
    @org.jamon.annotations.Method(
      name = "copyright_year",
      optionalArguments = {
        @org.jamon.annotations.Argument(name = "creationYear", type = "Integer")})})
public class SdkDebugRegs
  extends com.fulcrummicro.util.jamon.timestamp
{
  
  public SdkDebugRegs(org.jamon.TemplateManager p_manager)
  {
     super(p_manager);
  }
  
  protected SdkDebugRegs(String p_path)
  {
    super(p_path);
  }
  
  public SdkDebugRegs()
  {
     super("/com/fulcrummicro/hw/verification/chip/mgmt/registers/templates/SdkDebugRegs");
  }
  
  public interface Intf
    extends com.fulcrummicro.util.jamon.timestamp.Intf
  {
    
    void renderNoFlush(final java.io.Writer jamonWriter) throws java.io.IOException;
    
  }
  public static class ImplData
    extends com.fulcrummicro.util.jamon.timestamp.ImplData
  {
    // 196, 1
    public void setRegs(Collection<Register> regs)
    {
      // 196, 1
      m_regs = regs;
    }
    public Collection<Register> getRegs()
    {
      return m_regs;
    }
    private Collection<Register> m_regs;
    // 197, 1
    public void setPrefix(String prefix)
    {
      // 197, 1
      m_prefix = prefix;
    }
    public String getPrefix()
    {
      return m_prefix;
    }
    private String m_prefix;
    // 198, 1
    public void setNumPorts(int numPorts)
    {
      // 198, 1
      m_numPorts = numPorts;
    }
    public int getNumPorts()
    {
      return m_numPorts;
    }
    private int m_numPorts;
    // 199, 1
    public void setNumEpls(int numEpls)
    {
      // 199, 1
      m_numEpls = numEpls;
    }
    public int getNumEpls()
    {
      return m_numEpls;
    }
    private int m_numEpls;
    // 200, 1
    public void setNumLanes(int numLanes)
    {
      // 200, 1
      m_numLanes = numLanes;
    }
    public int getNumLanes()
    {
      return m_numLanes;
    }
    private int m_numLanes;
  }
  @Override
  protected org.jamon.AbstractTemplateProxy.ImplData makeImplData()
  {
    return new ImplData();
  }
  @Override public ImplData getImplData()
  {
    return (ImplData) super.getImplData();
  }
  
  
  @Override
  public org.jamon.AbstractTemplateImpl constructImpl(Class<? extends org.jamon.AbstractTemplateImpl> p_class){
    try
    {
      return p_class
        .getConstructor(new Class [] { org.jamon.TemplateManager.class, ImplData.class })
        .newInstance(new Object [] { getTemplateManager(), getImplData()});
    }
    catch (RuntimeException e)
    {
      throw e;
    }
    catch (Exception e)
    {
      throw new RuntimeException(e);
    }
  }
  
  @Override
  protected org.jamon.AbstractTemplateImpl constructImpl(){
    return new SdkDebugRegsImpl(getTemplateManager(), getImplData());
  }
  public org.jamon.Renderer makeRenderer(final Collection<Register> regs, final String prefix, final int numPorts, final int numEpls, final int numLanes)
  {
    return new org.jamon.AbstractRenderer() {
      @Override
      public void renderTo(final java.io.Writer jamonWriter)
        throws java.io.IOException
      {
        render(jamonWriter, regs, prefix, numPorts, numEpls, numLanes);
      }
    };
  }
  
  public void render(final java.io.Writer jamonWriter, final Collection<Register> regs, final String prefix, final int numPorts, final int numEpls, final int numLanes)
    throws java.io.IOException
  {
    renderNoFlush(jamonWriter, regs, prefix, numPorts, numEpls, numLanes);
    jamonWriter.flush();
  }
  public void renderNoFlush(final java.io.Writer jamonWriter, final Collection<Register> regs, final String prefix, final int numPorts, final int numEpls, final int numLanes)
    throws java.io.IOException
  {
    ImplData implData = getImplData();
    implData.setRegs(regs);
    implData.setPrefix(prefix);
    implData.setNumPorts(numPorts);
    implData.setNumEpls(numEpls);
    implData.setNumLanes(numLanes);
    Intf instance = (Intf) getTemplateManager().constructImpl(this);
    instance.renderNoFlush(jamonWriter);
    reset();
  }
  
  public com.fulcrummicro.util.jamon.timestamp.ParentRenderer makeParentRenderer(final Collection<Register> regs, final String prefix, final int numPorts, final int numEpls, final int numLanes)
  {
    return new com.fulcrummicro.util.jamon.timestamp.ParentRenderer() {
      @Override protected void renderChild(final java.io.Writer jamonWriter)
        throws java.io.IOException
      {
        SdkDebugRegs.this.renderNoFlush(jamonWriter, regs, prefix, numPorts, numEpls, numLanes);
      }
    };
  }
  
}
