// Autogenerated Jamon implementation
// C:/Users/mhesseli/Documents/Perforce/rrc-4/reg-main/shared/java/src/./com/fulcrummicro/hw/verification/chip/mgmt/registers/templates/SdkDebugFields.jamon

package com.fulcrummicro.hw.verification.chip.mgmt.registers.templates;

// 3, 1
import java.util.Collection;
// 4, 1
import com.fulcrummicro.util.misc.Utility;
// 5, 1
import com.fulcrummicro.hw.verification.chip.mgmt.registers.Register;
// 6, 1
import com.fulcrummicro.hw.verification.chip.mgmt.registers.RegisterField;

public class SdkDebugFieldsImpl
  extends com.fulcrummicro.util.jamon.timestampImpl
  implements com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.SdkDebugFields.Intf

{
  private final Collection<Register> regs;
  private final String prefix;
  protected static com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.SdkDebugFields.ImplData __jamon_setOptionalArguments(com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.SdkDebugFields.ImplData p_implData)
  {
    com.fulcrummicro.util.jamon.timestampImpl.__jamon_setOptionalArguments(p_implData);
    return p_implData;
  }
  public SdkDebugFieldsImpl(org.jamon.TemplateManager p_templateManager, com.fulcrummicro.hw.verification.chip.mgmt.registers.templates.SdkDebugFields.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    regs = p_implData.getRegs();
    prefix = p_implData.getPrefix();
  }
  
  @Override protected void child_render_1(final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 12, 1
    
String lcPrefix = Utility.underscoreToCamelCase(prefix, false).toLowerCase();
String ucPrefix = Utility.underscoreToCamelCase(prefix, false).toUpperCase();

    // 16, 1
    jamonWriter.write("/* vim:ts=4:sw=4:expandtab\n * (No tabs, indent level is 4 spaces)  */\n/*****************************************************************************\n * File:            ");
    // 19, 21
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(lcPrefix), jamonWriter);
    // 19, 35
    jamonWriter.write("_debug_reg_fields.c\n * Creation Date:   December 11, 2008\n * Last Updated:    ");
    // 21, 21
    {
      // 21, 21
      __jamon_innerUnit__timestamp(jamonWriter);
    }
    // 21, 37
    jamonWriter.write("\n * Description:     Provide debugging functions for accessing register\n *                  fields by name.\n *                  THIS FILE IS AUTO-GENERATED. EDIT THE TEMPLATE\n *                  IF YOU NEED TO MODIFY THIS FILE.\n *\n * INTEL CONFIDENTIAL\n * Copyright ");
    // 28, 14
    {
      // 28, 14
      __jamon_innerUnit__copyright_year(jamonWriter, 2008 );
    }
    // 28, 55
    jamonWriter.write("  Intel Corporation. All Rights Reserved.\n *\n * The source code contained or described herein and all documents related\n * to the source code (\"Material\") are owned by Intel Corporation or its\n * suppliers or licensors. Title to the Material remains with Intel\n * Corporation or its suppliers and licensors. The Material contains trade\n * secrets and proprietary and confidential information of Intel or its\n * suppliers and licensors. The Material is protected by worldwide copyright\n * and trade secret laws and treaty provisions. No part of the Material may\n * be used, copied, reproduced, modified, published, uploaded, posted,\n * transmitted, distributed, or disclosed in any way without Intel's prior\n * express written permission.\n *\n * No license under any patent, copyright, trade secret or other intellectual\n * property right is granted to or conferred upon you by disclosure or\n * delivery of the Materials, either expressly, by implication, inducement,\n * estoppel or otherwise. Any license under such intellectual property rights\n * must be express and approved by Intel in writing.\n *****************************************************************************/\n\n#include \"fm_sdk_");
    // 49, 18
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(lcPrefix), jamonWriter);
    // 49, 32
    jamonWriter.write("_int.h\"\n\n#include \"debug/");
    // 51, 17
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(lcPrefix), jamonWriter);
    // 51, 31
    jamonWriter.write("/");
    // 51, 32
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(lcPrefix), jamonWriter);
    // 51, 46
    jamonWriter.write("_debug_regs_int.h\"\n\n\n/**********************************************************************\n * ");
    // 55, 4
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(ucPrefix), jamonWriter);
    // 55, 18
    jamonWriter.write(" Register Fields\n *\n *    !!!!! DO NOT EDIT THIS FILE BY HAND !!!!!\n *\n * This file is automatically generated from registerInfo.xml\n * using the fulcrum registers tool with the --c output option.\n **********************************************************************/\n\n\n/*****************************************************************************/\n/** ");
    // 65, 5
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(lcPrefix), jamonWriter);
    // 65, 19
    jamonWriter.write("DbgGetRegisterFields\n * \\ingroup intDiag\n *\n * \\desc            Return null-terminated fmRegisterField structure\n *                  containing all the fields of the given register.\n *\n * \\param[in]       registerName is the register name string, without the\n *                  ");
    // 72, 21
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(prefix), jamonWriter);
    // 72, 33
    jamonWriter.write(" prefix.\n *\n * \\return          Pointer to a null-terminated fmRegisterField structure,\n *                  or NULL if the register name does not match.\n *\n *****************************************************************************/\nconst fmRegisterField * ");
    // 78, 25
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(lcPrefix), jamonWriter);
    // 78, 39
    jamonWriter.write("DbgGetRegisterFields(fm_text registerName)\n{\n\n");
    // 81, 1
    for (Register r : regs )
    {
      // 81, 27
      jamonWriter.write("    if (strcmp(registerName, \"");
      // 82, 31
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(r.getName()), jamonWriter);
      // 82, 48
      jamonWriter.write("\") == 0)\n    {\n        static const fmRegisterField ");
      // 84, 38
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(r.getName()), jamonWriter);
      // 84, 55
      jamonWriter.write("[] =\n        {\n");
      // 86, 1
      for (RegisterField field : r.fields.values() )
      {
        // 86, 49
        jamonWriter.write("            { \"");
        // 87, 16
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.desc), jamonWriter);
        // 87, 32
        jamonWriter.write("\", ");
        // 87, 35
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.pos), jamonWriter);
        // 87, 50
        jamonWriter.write(", ");
        // 87, 52
        org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(field.len), jamonWriter);
        // 87, 67
        jamonWriter.write(" },\n");
      }
      // 88, 8
      jamonWriter.write("            { NULL, 0, 0 }\n        };\n        return ");
      // 91, 16
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(r.getName()), jamonWriter);
      // 91, 33
      jamonWriter.write(";\n    }\n");
    }
    // 93, 8
    jamonWriter.write("    return NULL;\n\n}   /* end ");
    // 96, 12
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(lcPrefix), jamonWriter);
    // 96, 26
    jamonWriter.write("DbgGetRegisterFields */\n");
  }
  
  
}
