// Autogenerated Jamon proxy
// /nfs/site/disks/wdisk.55/rliu68/reg-rrc-1/shared/java/src/./com/fulcrummicro/hw/verification/chip/mgmt/registers/templates/Specman.jamon

package com.fulcrummicro.hw.verification.chip.mgmt.registers.templates;

// 3, 1
import java.util.ArrayList;
// 4, 1
import java.util.Collection;
// 5, 1
import com.fulcrummicro.util.misc.Utility;
// 6, 1
import com.fulcrummicro.hw.verification.chip.mgmt.registers.*;
// 7, 1
import com.fulcrummicro.hw.verification.lib.bitarray.LittleEndianBitArray;

@org.jamon.annotations.Template(
  signature = "5AB38B46243570890540ADBC767E960E",
  inheritanceDepth = 1,
  requiredArguments = {
    @org.jamon.annotations.Argument(name = "bases", type = "Collection<RegisterBase>"),
    @org.jamon.annotations.Argument(name = "regs", type = "Collection<Register>"),
    @org.jamon.annotations.Argument(name = "chip", type = "String"),
    @org.jamon.annotations.Argument(name = "virtual", type = "boolean")},
  methods = {
    @org.jamon.annotations.Method(
      name = "timestamp"),
    @org.jamon.annotations.Method(
      name = "copyright_year",
      optionalArguments = {
        @org.jamon.annotations.Argument(name = "creationYear", type = "Integer")})})
public class Specman
  extends com.fulcrummicro.util.jamon.timestamp
{
  
  public Specman(org.jamon.TemplateManager p_manager)
  {
     super(p_manager);
  }
  
  protected Specman(String p_path)
  {
    super(p_path);
  }
  
  public Specman()
  {
     super("/com/fulcrummicro/hw/verification/chip/mgmt/registers/templates/Specman");
  }
  
  public interface Intf
    extends com.fulcrummicro.util.jamon.timestamp.Intf
  {
    
    void renderNoFlush(final java.io.Writer jamonWriter) throws java.io.IOException;
    
  }
  public static class ImplData
    extends com.fulcrummicro.util.jamon.timestamp.ImplData
  {
    // 117, 1
    public void setBases(Collection<RegisterBase> bases)
    {
      // 117, 1
      m_bases = bases;
    }
    public Collection<RegisterBase> getBases()
    {
      return m_bases;
    }
    private Collection<RegisterBase> m_bases;
    // 118, 1
    public void setRegs(Collection<Register> regs)
    {
      // 118, 1
      m_regs = regs;
    }
    public Collection<Register> getRegs()
    {
      return m_regs;
    }
    private Collection<Register> m_regs;
    // 119, 1
    public void setChip(String chip)
    {
      // 119, 1
      m_chip = chip;
    }
    public String getChip()
    {
      return m_chip;
    }
    private String m_chip;
    // 120, 1
    public void setVirtual(boolean virtual)
    {
      // 120, 1
      m_virtual = virtual;
    }
    public boolean getVirtual()
    {
      return m_virtual;
    }
    private boolean m_virtual;
  }
  @Override
  protected org.jamon.AbstractTemplateProxy.ImplData makeImplData()
  {
    return new ImplData();
  }
  @Override public ImplData getImplData()
  {
    return (ImplData) super.getImplData();
  }
  
  
  @Override
  public org.jamon.AbstractTemplateImpl constructImpl(Class<? extends org.jamon.AbstractTemplateImpl> p_class){
    try
    {
      return p_class
        .getConstructor(new Class [] { org.jamon.TemplateManager.class, ImplData.class })
        .newInstance(new Object [] { getTemplateManager(), getImplData()});
    }
    catch (RuntimeException e)
    {
      throw e;
    }
    catch (Exception e)
    {
      throw new RuntimeException(e);
    }
  }
  
  @Override
  protected org.jamon.AbstractTemplateImpl constructImpl(){
    return new SpecmanImpl(getTemplateManager(), getImplData());
  }
  public org.jamon.Renderer makeRenderer(final Collection<RegisterBase> bases, final Collection<Register> regs, final String chip, final boolean virtual)
  {
    return new org.jamon.AbstractRenderer() {
      @Override
      public void renderTo(final java.io.Writer jamonWriter)
        throws java.io.IOException
      {
        render(jamonWriter, bases, regs, chip, virtual);
      }
    };
  }
  
  public void render(final java.io.Writer jamonWriter, final Collection<RegisterBase> bases, final Collection<Register> regs, final String chip, final boolean virtual)
    throws java.io.IOException
  {
    renderNoFlush(jamonWriter, bases, regs, chip, virtual);
    jamonWriter.flush();
  }
  public void renderNoFlush(final java.io.Writer jamonWriter, final Collection<RegisterBase> bases, final Collection<Register> regs, final String chip, final boolean virtual)
    throws java.io.IOException
  {
    ImplData implData = getImplData();
    implData.setBases(bases);
    implData.setRegs(regs);
    implData.setChip(chip);
    implData.setVirtual(virtual);
    Intf instance = (Intf) getTemplateManager().constructImpl(this);
    instance.renderNoFlush(jamonWriter);
    reset();
  }
  
  public com.fulcrummicro.util.jamon.timestamp.ParentRenderer makeParentRenderer(final Collection<RegisterBase> bases, final Collection<Register> regs, final String chip, final boolean virtual)
  {
    return new com.fulcrummicro.util.jamon.timestamp.ParentRenderer() {
      @Override protected void renderChild(final java.io.Writer jamonWriter)
        throws java.io.IOException
      {
        Specman.this.renderNoFlush(jamonWriter, bases, regs, chip, virtual);
      }
    };
  }
  
}
