
import ("libm3")
import ("cit_util")
import ("parseparams")
import ("normaldev")

implementation ("Main")

module("Cloudbreak")
module("JBay")
interface("SvsTypes")
interface ("N7Tech")
interface ("N7PMRO")
interface ("PMRO")
interface ("Corner")

module ("Power")
interface ("ProgramSetter")

program("svspredict")
