INTERFACE Scale;

PROCEDURE LkgPwrByT(from, to : LONGREAL) : LONGREAL;

PROCEDURE LkgPwrByV(from, to : LONGREAL) : LONGREAL;

PROCEDURE DynPwrByT(<*UNUSED*>from, to : LONGREAL) : LONGREAL;

PROCEDURE DynPwrByV(from, to : LONGREAL) : LONGREAL;

END Scale.
