% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

/* $Id: m3makefile,v 1.17 2011/02/19 20:49:28 mika Exp $ */
import ("cit_util")
import ("libm3")
import ("parseparams")

implementation("Main")

program ("makekeywords")
