#!/bin/sh

# Copyright 2002 Fulcrum Microsystems.  All rights reserved.
# $Id$
# $DateTime$
# $Author$

# This script is deprecated, and may be removed soon.  The future is at
# //depot/sw/cad/external-tools-integration/cadence/virtuoso/main/script/sh/util/mk_instance.
# If you want to make substantive changes, modify that instead.

if [ `uname` != 'SunOS' ]; then
    echo "Please only run on a Solaris machine, since layoutPlus is required."
    exit
fi

if [ $# -ne 4 ]; then
    echo "Usage: $0 <lib> <cell> <outdir> <view>"
    exit
fi

lib=$1
cell=$2
outdir=$3
view=$4

[ -d $outdir ] || mkdir -p $outdir

if [ ! -d $outdir ]; then
    echo "Cannot write to $outdir."
fi

cat << EOF | layoutPlus -nograph
(load "/home/user/rliu/cadence/virtuoso/main/skill/layout/instancesfile/instance.il")
(WriteInstancesFile "$outdir" (dbOpenCellViewByType "$lib" "$cell" "$view"))
(exit)
EOF
