#!/usr/intel/bin/perl
my $date=`date`;
my $Tau=32e-12;
my $runName=shift(@ARGV);
my $ntpcNode=shift(@ARGV);
my $ntpcVal=shift(@ARGV);
my $Res_File=shift(@ARGV);
my $TDS_result=` /usr/local/cad/bin/trace $runName $ntpcNode | /usr/local/cad/bin/trig rise 0.6 5 1 10`;
open HANDLE1, ">>$Res_File";
if($TDS_result =~ /no trigger/)  {
  print HANDLE1 "$date $runName   $ntpcNode   $ntpcVal  $TDS_result";
}
else {
chomp($TDS_result);
my @Res=split/\s+/, $TDS_result;
my $ConcRes=$Res[2];
   @Res=split/=/, $ConcRes;
   $ConcRes=$Res[1];
   $ConcRes=~/([0-9\.]*)/;
my $SimFreq=$1;
my $ExpFreq=(1/($Tau*$ntpcVal*1e+6));
   if($SimFreq<$ExpFreq)  { 
     print HANDLE1 "$date Potential Problem Simulation Frequency less than Expected Frequency $runName $ntpcNode $ntpcVal $SimFreq   $ExpFreq\n";
   }
   else  {
     print HANDLE1 "$date Simulation Frequency greater than Expected Frequency  $runName $ntpcNode $ntpcVal $SimFreq   $ExpFreq\n";
   }
}
  close(HANDLE1);
