MODULE SpiceDecorate EXPORTS Main;
IMPORT ParseParams;
IMPORT Stdio;
IMPORT Debug;
IMPORT Params;
IMPORT Pathname;
IMPORT SpiceFormat;
IMPORT SpiceError;
IMPORT AL;
IMPORT Rd, FileRd;
IMPORT OSError;
FROM Fmt IMPORT F, Int, LongReal;
IMPORT SpiceCircuit;
IMPORT SpiceObject;
IMPORT Wr;
IMPORT FileWr;
IMPORT Thread;
IMPORT TextSetDef;
IMPORT Time;

<*FATAL Thread.Alerted*>

CONST
  Usage   = "";
  LR      = LongReal;

VAR
  Verbose := TRUE;

VAR
  emitted := NEW(TextSetDef.T).init();
  
PROCEDURE EnsureEmitted(typeNm : TEXT;
                        type   : SpiceCircuit.T) =
  BEGIN
    IF emitted.member(typeNm) THEN
      RETURN
    ELSE
      Debug.Out("Emitting " & Debug.UnNil(typeNm));

      Emit(typeNm, type);
      
      IF typeNm # NIL THEN
        EVAL emitted.insert(typeNm)
      END
    END
  END EnsureEmitted;

PROCEDURE EmitElem(elem : SpiceObject.T) =
  BEGIN
    Debug.Out("EmitElem " & elem.name);
    
    TYPECASE elem OF
      SpiceObject.R =>
    |
      SpiceObject.C =>
    |
      SpiceObject.X =>
    |
      SpiceObject.M =>
    |
      SpiceObject.D =>
    ELSE
      <*ASSERT FALSE*>
    END
  END EmitElem;

PROCEDURE FormatParams(type : SpiceCircuit.T) : TEXT =
  BEGIN
    RETURN ""
  END FormatParams;

PROCEDURE FormatBindings(type : SpiceCircuit.T) : TEXT =
  BEGIN
    RETURN ""
  END FormatBindings;
  
PROCEDURE Emit(typeNm : TEXT;
               type   : SpiceCircuit.T) =
  BEGIN
    <*ASSERT type # NIL*>
    <*ASSERT typeNm # NIL*>
    
    Wr.PutText(wr, F(".SUBCKT %s %s %s\n",
                     typeNm,
                     FormatParams(type),
                     FormatBindings(type)
    ));

    <*ASSERT type.elements # NIL*>
    FOR i := 0 TO type.elements.size() - 1 DO
      WITH elem = type.elements.get(i) DO
        EmitElem(elem)
      END
    END;
    Wr.PutText(wr, F(".ENDS %s\n\n", typeNm));
  END Emit;

PROCEDURE DoIt(ckt  : SpiceCircuit.T;
               path : TEXT) =
  VAR
    elems := ckt.elements;
    type : SpiceCircuit.T;
  BEGIN
    FOR i := 0 TO elems.size() - 1 DO
      
      WITH elem = elems.get(i) DO
        TYPECASE elem OF
          SpiceObject.X (x) =>

          IF Verbose AND FALSE THEN
            Debug.Out(F("X object nm %s type %s", x.name, x.type))
          END;

          WITH hadIt = spice.subCkts.get(x.type, type) DO
            <*ASSERT hadIt*>
          END;

          EnsureEmitted(x.type, type);
          
          DoIt(type, path & x.name & ".")
        |
          SpiceObject.C(c) =>
          <*ASSERT c # NIL*>
          <*ASSERT c.name # NIL*>
          <*ASSERT path # NIL*>
          
          WITH hnm = ckt.name & "/" & c.name DO
          END
        ELSE
          (* skip *)
        END
      END
    END
          
  END DoIt;
  
VAR
  pp                          := NEW(ParseParams.T).init(Stdio.stderr);
  spiceFn    : Pathname.T     ;
  spice      : SpiceFormat.T;
  rootType   : TEXT := NIL;
  rootCkt    : SpiceCircuit.T;
  sum        := 0.0d0;
  wr         := FileWr.Open("decorated.sp");
BEGIN
  Wr.PutText(wr, "* Generated by SpiceDecorate.m3 @ " & LR(Time.Now()));
  
  TRY
    IF pp.keywordPresent("-i") THEN
      spiceFn := pp.getNext()
    END;
    IF pp.keywordPresent("-root") THEN
      rootType := pp.getNext()
    END;
    pp.skipParsed();
    pp.finish()
  EXCEPT
    ParseParams.Error => Debug.Error("Can't parse command-line parameters\nUsage: " & Params.Get(0) & " " & Usage)
  END;

  TRY
    WITH spiceRd = FileRd.Open(spiceFn) DO
      spice := SpiceFormat.ParseSpice(spiceRd, ".", spiceFn);
      Rd.Close(spiceRd)
    END
  EXCEPT
    OSError.E(e) =>
    Debug.Error(F("Can't open top level file %s : OSError.E : %s",
                  spiceFn, AL.Format(e)))
  |
    SpiceError.E(e) =>
    Debug.Error(F("Parsing input : caught SpiceError.E : %s at line %s of file %s",
                  e.msg, Int(e.lNo), Debug.UnNil(e.fn)))
  END;
  
  IF rootType = NIL THEN
    rootCkt := spice.topCkt
  ELSE
    WITH hadIt = spice.subCkts.get(rootType, rootCkt) DO
      IF NOT hadIt THEN
        Debug.Error(F("Unknown root type %s", rootType))
      END
    END
  END;

  Debug.Out("Done parsing.");

  DoIt(rootCkt, "");

  EnsureEmitted(rootType, rootCkt);

  Wr.Close(wr)

END SpiceDecorate.
