MODULE StdfConstProc;

PROCEDURE P1() : CARDINAL = BEGIN RETURN 1 END P1;
  
PROCEDURE P2() : CARDINAL = BEGIN RETURN 2 END P2;
  
PROCEDURE P4() : CARDINAL = BEGIN RETURN 4 END P4;

BEGIN END StdfConstProc.
