import ("libm3")
import ("cit_util")
import ("parseparams")
import ("trie")
import ("recursiveparse")

_exec(["../../parsesupport/AMD64_LINUX/parsesupport","../src/enums.scm","exit"])

include ("../AMD64_LINUX/derived.m3m")

module ("DefFormat")
module ("DefLexer")

%interface ("ParseProc")
%interface ("ParseProcRec")
%interface ("ParseError")

%trie("CharCard", "Char", "Cardinal")
%trie("DefParse", "Char", "ParseProcRec")

module ("DefPoint")
sequence  ("DefPoint", "DefPoint")

module ("DefRoutingPoint")
sequence ("DefRoutingPoint", "DefRoutingPoint")

module ("DefNumbers")
interface ("DefInt")
interface ("DefCard")

module ("DefName")
module ("DefIdent")
module ("DefString")

implementation ("Main")

program ("testdef")
