LIBFILES_VARS_CHANGED_STACK :=$(LIBFILES_VARS_CHANGED) $(LIBFILES_VARS_CHANGED_STACK)
LIBFILES_VARS_CHANGED :=0


LIBFILES_LIBFILES_CUSTOM_MK := $(wildcard $(CURR_PROJECT_DIR)/libfiles-custom.mk)

ifneq ("$(strip $(LIBFILES_LIBFILES_CUSTOM_MK))","")

LIBFILES_PROJECT_LINK_FLAGS_TEMP := $(LIBFILES_PROJECT_LINK_FLAGS)
LIBFILES_LINKER_TEMP := $(LIBFILES_LINKER)

-include $(CURR_PROJECT_DIR)/libfiles-custom.mk

ifneq ("$(strip $(LIBFILES_PROJECT_LINK_FLAGS_TEMP))","$(strip $(LIBFILES_PROJECT_LINK_FLAGS))")
LIBFILES_VARS_CHANGED :=1
else
ifneq ("$(strip $(LIBFILES_LINKER_TEMP))","$(strip $(LIBFILES_LINKER_TEMP))")
LIBFILES_VARS_CHANGED :=1
endif
endif

ifeq ($(LIBFILES_VARS_CHANGED),1)

PUSH_SCOPED_VAR_VAR_NAME := LIBFILES_PROJECT_LINK_FLAGS
include $(BUILD_SYSTEM_ROOT)/include-functions/pushscopedvar.mk

PUSH_SCOPED_VAR_VAR_NAME := LIBFILES_LINKER
include $(BUILD_SYSTEM_ROOT)/include-functions/pushscopedvar.mk

endif

endif

LIBFILES_NON_LIB_DIRS := $(LIBFILES_NON_LIB_DIRS) CVS

LIBFILES_SUB_LIB_NAMES := $(filter-out $(LIBFILES_NON_LIB_DIRS), $(CURR_SUB_DIRS_NAMES))

LIBFILES_SUB_LIB_NAMES := $(filter-out $(CURR_NON_BUILD_DIRS), $(LIBFILES_SUB_LIB_NAMES))


LIBFILES_SUB_TARGET_OBJS := $(foreach subtarget, $(LIBFILES_SUB_LIB_NAMES), \
			    $(CURR_TARGET_DIR)/$(subtarget)/lib$(subtarget).o )

LIBFILES_DIR_LIB_OBJS := $(filter-out $(LIBFILES_DIR_LIB_EXCLUDE_OBJS), $(LIBFILES_TARGET_LD_OBJS))

LIBFILES_DIR_LIB_EXCLUDE_OBJS :=

libfiles_make_lib_rule :=1

ifeq ("","$(strip $(LIBFILES_DIR_LIB_OBJS))")
ifeq ("","$(strip $(LIBFILES_SUB_TARGET_OBJS))")
libfiles_make_lib_rule :=0
endif
endif

ifneq ("","$(strip $(CURR_PROJECT_NAME))")
ifeq ($(libfiles_make_lib_rule),1)
LIBFILES_TARGET_LIB := $(CURR_TARGET_DIR)/lib$(CURR_PROJECT_NAME).o


LIBFILES_LOCAL_CSTATIC_LINKER-$(CURR_TARGET_DIR) := $(LIBFILES_LINKER) $(LIBFILES_PROJECT_LINK_FLAGS)




$(LIBFILES_TARGET_LIB): $(LIBFILES_DIR_LIB_OBJS) $(LIBFILES_SUB_TARGET_OBJS)
	$(LIBFILES_LOCAL_CSTATIC_LINKER-$(strip $(@D))) -o $@ $^

CURR_RESULT_FILES := $(LIBFILES_TARGET_LIB) $(CURR_RESULT_FILES)
endif
endif








