%char [\[\]<>+\-*/;.()=,:|{}'#&\^]

%const ERROR

%const oAND
%const oANY
%const oARRAY
%const oAS
%const oBEGIN
%const oBITS
%const oBRANDED
%const oBY
%const oCASE
%const oCONST
%const oDIV
%const oDO
%const oDQUOTE
%const oELSE
%const oELSIF
%const oEND
%const oEVAL
%const oEXCEPT
%const oEXCEPTION
%const oEXIT
%const oEXPORTS
%const oFINALLY
%const oFOR
%const oFROM
%const oGENERIC
%const oIF
%const oIMPORT
%const oIN
%const oINTERFACE
%const oLOCK
%const oLOOP
%const oMETHODS
%const oMOD
%const oMODULE
%const oNOT
%const oOBJECT
%const oOF
%const oOR
%const oOVERRIDES
%const oPROCEDURE
%const oRAISE
%const oRAISES
%const oREADONLY
%const oRECORD
%const oREF
%const oREPEAT
%const oRETURN
%const oREVEAL
%const oROOT
%const oSET
%const oTHEN
%const oTO
%const oTRY
%const oTYPE
%const oTYPECASE
%const oUNSAFE
%const oUNTIL
%const oUNTRACED
%const oVALUE
%const oVAR
%const oWHILE
%const oWITH
%const oABS
%const oADDRESS
%const oADR
%const oADRSIZE
%const oBITSIZE
%const oBOOLEAN
%const oBYTESIZE
%const oCARDINAL
%const oCEILING
%const oCHAR
%const oDEC
%const oDISPOSE
%const oEXTENDED
%const oFALSE
%const oFIRST
%const oFLOAT
%const oFLOOR
%const oINC
%const oINTEGER
%const oISTYPE
%const oLAST
%const oLONGREAL
%const oLOOPHOLE
%const oMAX
%const oMIN
%const oMUTEX
%const oNARROW
%const oNEW
%const oNIL
%const oNULL
%const oNUMBERKEYWORD
%const oORD
%const oREAL
%const oREFANY
%const oROUND
%const oSUBARRAY
%const oTEXT
%const oTRUE
%const oTRUNC
%const oTYPECODE
%const oVAL

%const oGTOP
%const oLTOP
%const oLTEOP
%const oGTEOP
%const oLEFTBRACKET
%const oRIGHTBRACKET
%const oTWOPERIODS
%const oASSOP
%const oSUBTYPEOP
%const oARROWOP
%const oNEGATIVEOP
%const oPOSITIVEOP

%token oLITERAL
%token oCHARLITERAL
%token oTEXTLITERAL
%token oESCAPE
%token oPRINTINGCHAR
%token oID
%token oNUMBER
