(* $Id$ *)

GENERIC INTERFACE M2M3(M2);

PROCEDURE MulMV(READONLY a : M2.M; READONLY b : M2.V; VAR prod : M2.V);
PROCEDURE MulMC(READONLY a : M2.M; READONLY b : M2.M; VAR res : M2.V);
PROCEDURE MulMVC(READONLY a : M2.M; READONLY b : M2.V; VAR res : M2.M);

END M2M3.
