/* $Id$ */
import("libm3")
import("cit_util")
/* making a SetDef with Refanys can't work since we can't hash those */
/*mkSetDef("Ref","Refany")*/

Module("Quantity")
Module("Matrix")
Module("LU")
Module("Newton")

Library("matrix")
