/* $Id$ */
import("libm3")
import("cit_util")

Module("Quantity")
Module("Matrix")
Module("LU")
Module("SVD")
Module("Newton")
Module("Fortran")
Module("Tridiagonal")

implementation("MatrixM3")

/*

interface("MatrixF")	
implementation("MatrixFGlue") 
import_obj("muld.o")

*/

Library("matrix")
