#!/usr/bin/csh

echo $1

fulcrum --latest --pdk=$PDK --pdkhome=$TOOLHOME --toolhome=$TOOLHOME cast2cdl \
--process-dependent-name --cdl-mos-parameters=m \
--cast-path=$CAST_PATH --cadence-name \
--cell=$1 --output=hier.cdl

fulcrum --latest --pdk=$PDK --pdkhome=$TOOLHOME --toolhome=$TOOLHOME inliner \
--cdl=hier.cdl --library=hier.cdl > flat.cdl

#$SW_DIR/cad/scripts/spice2spice \
#--scaleM "34/42" --deltaL "20e-9-28e-9*34/42" flat.cdl 10nm.cdl

set out=`grep -w $1 $WD/laygen/script/N3_cells.config | cut -d " " -f1`
echo $out
$WD/laygen/script/cdl2snp.pl \
--length 20e-9 --gridW 34e-9 --maxNmosW 102e-9 --maxPmosW 102e-9 \
$1 flat.cdl $out.snp
