#!/usr/intel/bin/perl -w

my $LAYGENWARD="/nfs/site/disks/laygen_release_001/dev_rel/bhmiller/n3lib_may17";
my $COLLATERAL="$LAYGENWARD/collateral/arch/e08";
my $placements=100;
my $height=1;
my $area="min";

(@ARGV>=1) or die "USAGE: laygen_run fqcn [e08name]\n";
my $cell=$ARGV[0];
my $e08=$cell;
if (@ARGV>1) {
    $e08=$ARGV[1];
    if ($e08 =~ /d(....)$/) { $height=2; } # E08 naming convention
}

my $lsf =
    "set_architecture_file $COLLATERAL/e08.arch\n" .
    "set_rpg_file $COLLATERAL/e08_rpg_all.txt\n" .
    "set_tcl_container_file $COLLATERAL/e08_container.tcl\n" .
    "set_option layer_file $COLLATERAL/e08.layer\n" .
    "set_option fabric e08\n" .
    "set_option use_assumptions yes\n" .
    "set_option upperlayer m2\n" .
    "set_option max_num_cores 4\n" .
    "set_log_level status";

my $place="";
if (-e "${e08}.place") {
    $place="set_option Option name=manual_placement_file value=../../../${e08}.place\n";
}

my $rundir="${cell}.run";
system("mkdir -p $rundir");
chdir($rundir);
system("$ENV{FULCRUM} cast2cdl " . 
       "--process-dependent-name --cdl-mos-parameters=m " .
       "--cast-path=$ENV{CAST_PATH} --cadence-name " .
       "--cell=$cell --output=hier.cdl");
system("$ENV{FULCRUM} inliner " .
       "--cdl=hier.cdl --library=hier.cdl > flat.cdl");
system("$ENV{FULCRUM} cdl2snp " .
       "--length 20e-9 --gridW 34e-9 --maxNmosW 102e-9 --maxPmosW 102e-9 " .
       "$cell flat.cdl $e08.snp");
system("$LAYGENWARD/tcl/snp_to_lgf.tcl $e08.snp $e08.lgf");

my $lgf="$e08.lgf";

# place
print "PLACE: $lgf\n";
open OUT, ">place.lsh" or die;
print OUT <<EOF;
$lsf
set_option placement_result_idx $placements
set_option generate_snp yes
set_option run_hazel_placement_engine 1
set_option placement_effort 1
set_option target_area $area
set_option target_height $height
set_option option "Option name=plan_device_y value=1 push_out=0 push_devices_to_default=1,0"
set_option route no
set_netlist $lgf
run_main
exit
EOF
system("$LAYGENWARD/bin/laygen_shell -nogui -file place.lsh >& place.log");

# route all placements
my @files = split("\n",`ls out/*.lgf`);
foreach my $place_lgf (@files) {
    print "ROUTE: $place_lgf\n";
    my $routedir=$place_lgf;
    $routedir =~ s/\.lgf//;
    system("mkdir $routedir");
    open OUT, ">$routedir/route.lsh" or die;
    print OUT <<EOF;
$lsf
$place
set_option option "Option name=undesired_pattern_report_filename value=undesired_patterns.txt"
set_option option "Option name=dump_final_rpg_file value=0"
set_option option "Option name=show_invisible_layout value=0"
set_option route yes
set_netlist ../../$place_lgf
run_main
exit
EOF
    close OUT;
    system("cd $routedir; nbq $LAYGENWARD/bin/laygen_shell -nogui -file route.lsh >& route.log ");
}
