#!/usr/bin/csh

alias laygen_prep '$WD/laygen/script/laygen_prep'

laygen_prep lib.util.ctree.CTREE2.b0
laygen_prep lib.util.ctree.CTREE2.c0
laygen_prep lib.util.ctree.CTREE2.b1
laygen_prep lib.util.ctree.CTREE2.c1
laygen_prep lib.util.ctree.CTREE2.b2
laygen_prep lib.util.ctree.CTREE2.c2
laygen_prep lib.util.ctree.CTREE2.b3
laygen_prep lib.util.ctree.CTREE2.c3
laygen_prep lib.util.ctree.CTREE3.b0
laygen_prep lib.util.ctree.CTREE3.c0
laygen_prep lib.util.ctree.CTREE3.b1
laygen_prep lib.util.ctree.CTREE3.c1
laygen_prep lib.util.ctree.CTREE3.b2
laygen_prep lib.util.ctree.CTREE3.c2
laygen_prep lib.util.ctree.CTREE3.b3
laygen_prep lib.util.ctree.CTREE3.c3
laygen_prep lib.util.ctree.RHI_CTREE2.b1
laygen_prep lib.util.ctree.RHI_CTREE2.c1
laygen_prep lib.util.ctree.RLO_CTREE2.b1
laygen_prep lib.util.ctree.RLO_CTREE2.c1
laygen_prep lib.util.delay.tunable.WEAKENER.b0
laygen_prep lib.util.delay.tunable.WEAKENER.c0
laygen_prep lib.util.delay.tunable.WEAK_QUAD_INV.b0
laygen_prep lib.util.delay.tunable.WEAK_QUAD_INV.c0
laygen_prep lib.util.delay.tunable.WEAK_BUF.b0
laygen_prep lib.util.delay.tunable.WEAK_BUF.c0
laygen_prep lib.util.widget.XOR_LATCH.b0
laygen_prep lib.util.widget.XOR_LATCH.c0
laygen_prep lib.util.widget.ALTVERTER_LATCH.b0
laygen_prep lib.util.widget.ALTVERTER_LATCH.c0
laygen_prep lib.qdi.metastable.filter.HALF_FILTER.b0
laygen_prep lib.qdi.metastable.filter.HALF_FILTER.c0
laygen_prep core.noc.crossbar.datapath.TAIL_CONTROL_La.b0
laygen_prep core.noc.crossbar.datapath.TAIL_CONTROL_La.c0
laygen_prep core.noc.crossbar.datapath.TAIL_CONTROL_y.b0
laygen_prep core.noc.crossbar.datapath.TAIL_CONTROL_y.c0

rm *.cdl
tar -cvf N3lib.tar *.snp
