# standard setup
TOP = ..
SUBDIRS =
BIN_TARGETS = strip_redundant_def
MAN_TARGETS =
INSTALL_TARGETS = $(BIN_TARGETS)
include $(TOP)/Makefile.rules

strip_redundant_def: strip_redundant_def.o $(LIB_DIR)/castlib.a
