import ("libm3")
import ("cptr")
import ("set")
import ("cit_util")

/* the whole Bool deal */
c_source("misc") 
c_source("bool") 

Module("Bool") 
Module("Cbool") 
interface("CboolImpl")
Interface("BoolImpl") 
/* This is a bit tricky:  The use of CPtr (CPtr.T = Bool.T) in the BoolTextTbl
   allows BoolTextTbl to be imported by Bool.T! */
Table("BoolText", "CPtr", "Text")

Interface("BoolVector")
implementation("BoolVectorImpl")
implementation("BoolVector")

table("BoolRef", "Bool", "Refany")

MkSet("Bool", "CPtr")
MkSetDef("Bool", "CPtr")

library("bool")
