/*
 * Copyright 2002 Fulcrum Microsystems.  All rights reserved.
 * $Id$
 * $DateTime$
 * $Author$
 */

package com.avlsi.tools.cadencize;

import java.util.Map;
import java.util.Iterator;

import com.avlsi.tools.cadencize.CadenceDataInterface;
import com.avlsi.tools.cadencize.CadenceDataTreeMapImpl;
import com.avlsi.tools.cadencize.SubCellFile;

public final class CadencizeDataInterfaceActionHandler implements CadenceActionInterface {

    CadenceDataTreeMapImpl m_CadenceData;
    Map m_InstanceSubTypeMap;

    public CadencizeDataInterfaceActionHandler( final String unitName,
						final String subTypeName,
						Map InstanceSubTypeMap ){
	m_CadenceData = new CadenceDataTreeMapImpl();
	m_CadenceData.SetCellUnitName( unitName ) ;
	m_CadenceData.SetCellSubType( subTypeName );
	m_InstanceSubTypeMap = InstanceSubTypeMap;
    }

    public void doType( String typeName ){
	m_CadenceData.SetCellName( typeName );
    }

    public void doPort( String portName ){}

    public void doNet( String netName ){
      m_CadenceData.AddNet( SubCellFile.CononicalizeSubCellInstanceName(netName) );
    }

    public void doSubcell( String subcellName, String subcellType ){
	String RealSubCellName = SubCellFile.CononicalizeSubCellInstanceName( subcellName );
	String SubCellSubType = ( String ) m_InstanceSubTypeMap.get( RealSubCellName ) ;
	if ( SubCellSubType != null ) {
	    m_CadenceData.AddSubCell( RealSubCellName, subcellType, SubCellSubType ) ;
	}
	else{
	    System.out.print( "WARNING: Could not get subtype for \"" );
	    System.out.print( RealSubCellName );
	    System.out.print( "\" which is of type \"" );
	    System.out.print( subcellType );
	    System.out.print( "\".  Assumming subtype is \"" );
	    System.out.print( subcellType );
	    System.out.println( "\".  Your layout might use a subtype different");
	    System.out.print( "from \"" );
	    System.out.print( subcellType ) ;
	    System.out.print( ", which potentially will mean that the layout will differ from the CDL ");
	    System.out.println( "file generated by this program." );

	    m_CadenceData.AddSubCell( RealSubCellName, subcellType, subcellType ) ;
	}
    }

    public void doPortConnection( String netName, String portName ){
	m_CadenceData.AddPort( SubCellFile.CononicalizeSubCellInstanceName(netName), SubCellFile.CononicalizeSubCellInstanceName(portName) );
    }

    public void doSubcellConnection( String netName, 
				     String subcellName,
				     String subcellPortName, 
				     String subcellNetName ){
	m_CadenceData.AddSubCellConnection( SubCellFile.CononicalizeSubCellInstanceName(subcellName),
					    SubCellFile.CononicalizeSubCellInstanceName(subcellNetName),
					    SubCellFile.CononicalizeSubCellInstanceName(netName) ) ;
    }

    public void doAliases(final String netName, final Iterator aliases) {
	m_CadenceData.AddNetAliases( SubCellFile.CononicalizeSubCellInstanceName(netName), aliases );
    }

    public CadenceDataInterface getCadenceData( ) {
	return m_CadenceData;
    }

}
