#!/bin/sh
#
# This is a hook script to verify what is about to be committed.
# Called by git-commit with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# Disallow committing on a detached HEAD.
if ! git symbolic-ref -q HEAD > /dev/null 2>&1
then
    echo >&2 "Error: You must check out a branch ('git checkout <branch>') before
committing."
    exit 2
fi
