/* $Id$ */



if defined("pm3_version")
	option("optimization","") 
end


import("libm3")
import("cit_util")
import("mscheme")
import("schemesig")
import("modula3scheme")

implementation("Main")

program("mscheme")
