/* $Id$ */



if defined("pm3_version")
	option("optimization","") 
end


import("libm3")
import("cit_util")
import("mscheme")

interface("Csighandler")
c_source("sighandler")
implementation("Main")

program("mscheme")
