# Copyright 2003 Fulcrum Microsystems.  All rights reserved.
# $Id$
# $DateTime$
# $Author$

CFILES_COMPILER     := $(GCC) 
CFILES_PREPROCESSOR := $(CFILES_COMPILER) -E

ifeq ($(MAKEFILE_KERNEL_NAME),Linux)
  CFILES_C_COMPILE_FLAGS += -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
  PROGFILES_PROJECT_LIBS := m
endif
ifeq ($(MAKEFILE_KERNEL_NAME),SunOS)
  CFILES_C_COMPILE_FLAGS := -O3 -ggdb -m64 -Wall
  PROGFILES_PROJECT_LIBS := m
endif
ifeq ($(MAKEFILE_KERNEL_NAME),Darwin)
  CFILES_C_COMPILE_FLAGS := -O3 -Wall
  PROGFILES_PROJECT_LIBS := m
endif

CFILES_PROJECT_INCLUDE_DIRS := $(CURR_PROJECT_DIR)/aag $(CURR_PROJECT_DIR)/plot
