#!/usr/intel/bin/perl -w
use strict;
use warnings;

# default arguments
my $work_dir=".";
my $pdk_root;
my $cast_path=$ENV{CAST_PATH};
my $dfII_dir=$ENV{DFII_DIR};
my $output="cell.gds2";
my $view="layout";
my $cell;

# usage banner
sub usage {
    die("USAGE: ExportGDS\n" .
        " --work-dir=[$work_dir]\n" .
        " --cast-path=[$cast_path]\n" .
        " --dfII-dir=[$dfII_dir]\n" .
        " --output=[$output]\n" .
        " --view=[$view]\n" .
        " cellName\n");
}

# parse command-line arguments
my @args;
while (@ARGV) {
    if    ($ARGV[0] =~ /^--work-dir=(.*)/ ) { $work_dir =$1; }
    elsif ($ARGV[0] =~ /^--fulcrum-pdk-root=(.*)/) { $pdk_root=$1; }
    elsif ($ARGV[0] =~ /^--cast-path=(.*)/) { $cast_path=$1; }
    elsif ($ARGV[0] =~ /^--dfII-dir=(.*)/)  { $dfII_dir =$1; }
    elsif ($ARGV[0] =~ /^--output=(.*)/)    { $output   =$1; }
    elsif ($ARGV[0] =~ /^--view=(.*)/)      { $view    = $1; }
    else { $cell = $ARGV[0]; }
    shift @ARGV;
}
usage() unless defined($cell);

# create cdswd and write replay.il
my $cdswd = "${work_dir}/ExportGDS.cdswd";
system("mkdir -p $cdswd");
open  OUT, ">${cdswd}/replay.il" or die;
print OUT "(ExportGDS ?CV (ReadCV (GetCastLibName \"$cell\") \"$cell\" \"$view\"))\n";
close OUT;

# run mkcdswd and virtuoso (TODO: avoid $ENV{FULCRUM})
system("mkcdswd --fulcrum-pdk-root=$pdk_root --target-dir=\"$cdswd\" --dfII-dir=\"$dfII_dir\" --cast-path=\"$cast_path\" --force && " .
       "cd \"$cdswd\" && " .
       "$ENV{IC_SCRIPT} virtuoso -log CDS.log -replay replay.il -nograph && " .
       "mv temp/gds/$cell/*.gds \"$output\"");
