#!/usr/intel/bin/perl -w
use strict;
use warnings;

my $local=0;
my $block=0;
my $cds_lib;
while (@ARGV>0) {
    if    ($ARGV[0] eq "--local") { $local=1; shift; }
    elsif ($ARGV[0] eq "--block") { $block=1; shift; }
    elsif ($ARGV[0] =~ /--cds-lib=(\S+)/) { $cds_lib=$1; shift; }
    else { last; }
}

@ARGV>0 or die "USAGE: virtuoso_replay [[--local|--block]] [--cds-lib=?] 1.il 2.il ...\n";
my $count = 0;
foreach my $file (@ARGV) {
    (-r $file) or die "cannot read file $file\n";
    my $base = $file;
    $base =~ s/\.il$//g;
    if (-e "${base}.cdswd") { print STDERR "WARNING: ${base}.cdswd already exists, skipping\n"; next; }
    system("mkdir -p ${base}.cdswd");
    system("$ENV{FULCRUM} mkcdswd --target-dir=${base}.cdswd " .
           "--dfII-dir=$ENV{DFII_DIR} --cast-path=$ENV{CAST_PATH} " .
           "--force --p4-client=$ENV{HW_CLIENT}");
    if (defined($cds_lib)) { system("cp \"$cds_lib\" ${base}.cdswd"); }

    # Workaround for Xvnc server sharing
    # Valid Xvnc display range from [10..99] (excluding +)
    my $display = ($count % 90) + 10;
    $ENV{CDS_XVNC_TENBASE} = $display / 10;
    $ENV{CDS_XVNC_OFFSET} = $display % 10;

    # run locally or with netbatch
    print "Running $file\n";
    if ($block) {
        system("(cd ${base}.cdswd; " .
               "$ENV{FULCRUM} --cadence assura_oa,$ENV{ICV_VERSION} " .
               "virtuoso -log ${base}.log -replay $ENV{PWD}/${file} -nograph >& ${base}.out)");
    } elsif ($local) {
        system("(cd ${base}.cdswd; " .
               "$ENV{FULCRUM} --cadence assura_oa,$ENV{ICV_VERSION} " .
               "virtuoso -log ${base}.log -replay $ENV{PWD}/${file} -nograph >& ${base}.out) &");
    } else {
        system("(cd ${base}.cdswd; " .
               "nbjob run --log-file ${base}.out " .
               "$ENV{FULCRUM} --cadence assura_oa,$ENV{ICV_VERSION} " .
               "virtuoso -log ${base}.log -replay $ENV{PWD}/${file} -nograph)");
    }
    $count++;
}
