/* $Id: m3makefile,v 1.8 2005/11/20 07:11:13 mika Exp $ */
/*m3_option("-g") */
/*m3_option("-times") */

import("cit_util")
import("integrate")

Module("Spline")
Module("CubicSpline")
Module("ParametricSpline")
interface("ParametricSplineRep")

Generic_module("ParametricSplineImpl")
template("parametricspline")
ParametricSpline("CubicSpline","CubicSpline")

library("splines")
