/* $Id$ */
m3_option("-g")
m3_option("-times")

import("cit_util")

Interface("Spline")
Module("CubicSpline")
Interface("ParametricSpline")

Generic_module("ParametricSplineImpl")
template("parametricspline")
ParametricSpline("CubicSpline","CubicSpline")

library("splines")
