/* $Id$ */

import ("cit_util")
import ("parserlib")
import ("bdd")
import ("sop")
import ("modula3scheme")

Module   ("BoolArrayOps")

Table    ("BDDBDD", "BDD", "BDD")
Table    ("BDDBDDSeq", "BDD", "BDDSeq")

Module   ("BDDDepender")
Module   ("BDDOpsH")

Table    ("BDDBDDSet", "BDD", "BDDSet")

Table    ("BDDLongreal", "BDD", "LongrealType")
Table    ("BDDPairLongreal", "BDDPair", "LongrealType")

Generic_module("Causal")
template("causal")

Causal   ("BDDCausal", "BDD", "BDDPair", "BDDLongrealTbl", "BDDPairLongrealTbl", "BDDBDDSetTbl")

Module   ("TimeSearcher")

Generic_module("SetToList")
template("settolist")

Table    ("TextBDD", "Text", "BDD")
Table    ("BDDCard", "BDD", "Cardinal")
Table    ("BDDRefList", "BDD", "RefList")

Module   ("BDDDecompose")
Module   ("BDDScanner")
Module   ("BDDCanon")

SetToList("BDDSetToList", "BDD", "BDDSet")

library ("hbddops")