CURR_TARGET_TEX_FILES := $(wildcard $(CURR_PROJECT_DIR)/*.tex )


ifneq ("$(strip $(CURR_TARGET_TEX_FILES))","")

CURR_TARGET_DEPS := $(patsubst $(CURR_PROJECT_DIR)/%.tex, $(CURR_TARGET_DIR)/%.d, $(CURR_TARGET_TEX_FILES) ) $(CURR_TARGET_DEPS)

CURR_INTERMEDIATE_FILES := $(patsubst $(CURR_PROJECT_DIR)/%.tex, $(CURR_TARGET_DIR)/%.aux, $(CURR_TARGET_TEX_FILES) ) $(CURR_INTERMEDIATE_FILES)
CURR_RESULT_FILES := $(patsubst $(CURR_PROJECT_DIR)/%.tex, $(CURR_TARGET_DIR)/%.pdf, $(CURR_TARGET_TEX_FILES) ) $(CURR_RESULT_FILES)
CURR_RESULT_FILES := $(patsubst $(CURR_PROJECT_DIR)/%.tex, $(CURR_TARGET_DIR)/%.ps, $(CURR_TARGET_TEX_FILES) ) $(CURR_RESULT_FILES)
CURR_RESULT_FILES := $(patsubst $(CURR_PROJECT_DIR)/%.tex, $(CURR_TARGET_DIR)/%.preview.ps, $(CURR_TARGET_TEX_FILES) ) $(CURR_RESULT_FILES)
CURR_INTERMEDIATE_MAKE_FILES := $(patsubst $(CURR_PROJECT_DIR)/%.tex, $(CURR_TARGET_DIR)/%.tex, $(CURR_TARGET_TEX_FILES) ) \
                                $(CURR_INTERMEDIATE_MAKE_FILES)
CURR_INTERMEDIATE_FILES := $(patsubst $(CURR_PROJECT_DIR)/%.tex, $(CURR_TARGET_DIR)/%.log, $(CURR_TARGET_TEX_FILES) ) $(CURR_INTERMEDIATE_FILES)
CURR_INTERMEDIATE_FILES := $(patsubst $(CURR_PROJECT_DIR)/%.tex, $(CURR_TARGET_DIR)/%.dvi, $(CURR_TARGET_TEX_FILES) ) $(CURR_INTERMEDIATE_FILES)
CURR_TARGET_DIA_FILES := $(wildcard $(CURR_PROJECT_DIR)/*.dia )
CURR_INTERMEDIATE_FILES := $(patsubst $(CURR_PROJECT_DIR)/%.dia, $(CURR_TARGET_DIR)/%.eps, $(CURR_TARGET_DIA_FILES) ) $(CURR_INTERMEDIATE_FILES)

ALL_TEX_FILES := $(CURR_TARGET_TEX_FILES) $(ALL_TEX_FILES)
ALL_PDF_FILES := $(patsubst $(CURR_PROJECT_DIR)/%.tex,$(CURR_TARGET_DIR)/%.pdf,$(CURR_TARGET_TEX_FILES)) $(ALL_PDF_FILES)
ALL_PS_FILES := $(patsubst $(CURR_PROJECT_DIR)/%.tex,$(CURR_TARGET_DIR)/%.ps,$(CURR_TARGET_TEX_FILES)) $(ALL_PS_FILES)
ALL_PREVIEW_PS_FILES := $(patsubst $(CURR_PROJECT_DIR)/%.tex,$(CURR_TARGET_DIR)/%.preview.ps,$(CURR_TARGET_TEX_FILES)) $(ALL_PREVIEW_PS_FILES)



$(CURR_TARGET_DIR)/%.tex: $(CURR_PROJECT_DIR)/%.tex
	cp $< $@
	chmod u+w $@

$(CURR_TARGET_DIR)/%.eps: $(CURR_PROJECT_DIR)/%.dia
	$(DIA) -e $@ $<

$(CURR_TARGET_DIR)/%.d: $(CURR_TARGET_DIR)/%.tex $(BUILD)/filetypes/texfiles/texdep.zsh
	$(BUILD)/filetypes/texfiles/texdep.zsh $(call CONONICALIZE_PATH,$<) "$(patsubst %.tex, %.dvi, $< ) $(patsubst %.tex, %.aux, $< )" >$@

endif
