% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("wm_support")
import ("hlp")

_exec(["../../structgen/AMD64_LINUX/structgen","../src/structgen_shared.scm","../src/structgen_m3.scm","../src/structs_m3.scm", "../src/structs.scm"])

include ("../AMD64_LINUX/derived.m3m")

Interface("Byte")
Sequence("Byte","Byte")

Module ("NetTypes")

Module ("RdNet")
Module ("WrNet")
Module ("StructField")

%Module ("FmModelMessageHdr")

Interface ("NetError")
Interface ("NetContext")

Module("ServerPacket")
implementation("ServerPacketDbg")

library ("wm_net")
