import ("libm3")
import ("wm_support")
import ("hlp")

_exec(["../../structgen/AMD64_LINUX/structgen","../src/structs.scm"])

include ("../AMD64_LINUX/derived.m3m")

Interface("Byte")
Sequence("Byte","Byte")

Module ("NetTypes")

Module ("RdNet")
Module ("WrNet")
Module ("StructField")

%Module ("FmModelMessageHdr")

Interface ("NetError")
Interface ("NetContext")

Module("ServerPacket")
implementation("ServerPacketDbg")

library ("wm_net")
