#!/bin/bash
#
# TestPoint
#   - Perl object based TestPoint interface

attr_file="local_attributes.cfg"

# Prevent the --perl-debug argument from being passed to TestPoint.
perl -e '
if (grep {m/--perl-debug/} @ARGV)
{
    exit(0);
}
exit(1);
' -- $*
if [ $? -eq 0 ]; then 
    export PERL_DEBUG=-d
fi

# Parse all command line arguments for API attributes of the form
# --<attr>:<type>:<value>.
perl -e '
my $attr_file = shift(@ARGV);
unlink($attr_file);
while (my $arg = shift(@ARGV))
{
    if ($arg =~ m/--api(.*):(.*):(.*)/)
    {
        my ($attr, $type, $value) = ("api$1", $2, $3);
        system("echo $attr $type $value >> $attr_file");
    }
}
' -- $attr_file $*

export PERL5LIB="$(pwd):$(pwd)/../perl-lib:$(pwd)/../perl-lib/SDK:$PERL5LIB"
export LD_LIBRARY_PATH="$(pwd)/../lib:$(pwd)/../perl-lib:$LD_LIBRARY_PATH"

# Do not set the FM_API_ATTR_FILE environment variable unless the user has
# specified one or more API attributes.
if [ -f "$attr_file" ]; then
    export FM_API_ATTR_FILE="$attr_file"
fi

if [ "$PERL_PLATFORM" == "" ]; then
    if [ -e "SDKPlatform" ]; then
        export PERL_PLATFORM=`cat SDKPlatform`
    else
        export PERL_PLATFORM=fm85xxep
    fi
fi

perl $PERL_DEBUG -e '
our $progressChildPid;
our $loadStartTime;
our $loadTime;

# nifty little trick to have a progress indicator
BEGIN
{
    $| = 1;
    $loadStartTime = time();
    $progressChildPid = fork();

    # child process only
    if ($progressChildPid == 0)
    {
        my @symbols = ( "\\", "|", "/", "-");
        my $i = 0;
        printf("\n>> Loading TestPoint Module ");

        while(1)
        {
            printf("(%s)", $symbols[$i]);  
            $i = ++$i % scalar(@symbols);

            select(undef, undef, undef, 0.15);

            printf("\b\b\b");
        }
    }
}

use Applications::TestPoint;

# kill off the progress bar fork
system("kill $progressChildPid");

$loadTime = time() - $loadStartTime;
printf("\n");
printf(">> Module loaded in $loadTime seconds\n");

my $tp = new Applications::TestPoint(@ARGV);

$tp->run();
' $PERL_PLATFORM $*
