//                                                                             
// File:            mby_mesh_row_map_bios_settings.h                           
// Creator:         solson                                                     
// Time:            Tuesday Dec 11, 2018 [9:55:24 am]                          
//                                                                             
// Path:            /tmp/solson/nebulon_run/3588935889_2018-12-11.09:54:39     
// Arguments:       -sv_no_sai_checks -sverilog -xml -chdr -crif -ovm -input   
//                  mby/mby_mesh_row_map.rdl -timeout 60000 -out_dir           
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018/target/GenRTL/regflow/msh
//                  -rtlgencomp -log_file                                      
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018/target/GenRTL/regflow/msh/nebulon_sv_output.log
//                                                                             
// MRE:             5.2018.2                                                   
// Machine:         scci80131                                                  
// OS:              Linux 3.0.101-84-default                                   
// Nebulon version: d18ww24.4                                                  
// Description:                                                                
//                                                                             
// No Description Provided                                                     
//                                                                             
// Copyright (C) 2018 Intel Corp. All rights reserved                          
// THIS FILE IS AUTOMATICALLY GENERATED BY INTEL RDL GENERATOR, DO NOT EDIT    
//                                                                             


#ifndef MBY_MESH_ROW_MAP_BIOS_SETTINGS_HH
#define MBY_MESH_ROW_MAP_BIOS_SETTINGS_HH

#define MBY_MESH_ROW_MAP_MEMBAR_MAX -1

#define MBY_MESH_ROW_MAP_IOBAR_MAX -1

#endif // MBY_MESH_ROW_MAP_BIOS_SETTINGS_HH
