
CPPFILES_VARS_CHANGED_STACK :=$(CPPFILES_VARS_CHANGED) $(CPPFILES_VARS_CHANGED_STACK)
CPPFILES_VARS_CHANGED :=0

CPPFILES_CPPFILES_CUSTOM_MK := $(wildcard $(CURR_PROJECT_DIR)/cppfiles-custom.mk)

ifneq ("$(strip $(CPPFILES_CPPFILES_CUSTOM_MK))","")

CPPFILES_COMPILER_TEMP               := $(CPPFILES_COMPILER)
CPPFILES_PREPROCESSOR_TEMP           := $(CPPFILES_PREPROCESSOR)
CPPFILES_PRE_PROCESSOR_DEFINES_TEMP  := $(CPPFILES_PRE_PROCESSOR_DEFINES)
CPPFILES_PROJECT_INCLUDE_DIRS_TEMP   := $(CPPFILES_PROJECT_INCLUDE_DIRS)
CPPFILES_GENERATED_INCLUDE_DIRS_TEMP := $(CPPFILES_GENERATED_INCLUDE_DIRS)
CPPFILES_CPP_COMPILE_FLAGS_TEMP      := $(CPPFILES_CPP_COMPILE_FLAGS)

-include $(CURR_PROJECT_DIR)/cppfiles-custom.mk 


ifneq ("$(strip $(CPPFILES_COMPILER_TEMP))","$(strip $(CPPFILES_COMPILER))")
CPPFILES_VARS_CHANGED :=1
else
ifneq ("$(strip $(CPPFILES_PREPROCESSOR_TEMP))","$(strip $(CPPFILES_PREPROCESSOR))")
CPPFILES_VARS_CHANGED :=1
else
ifneq ("$(strip $(CPPFILES_PRE_PROCESSOR_DEFINES_TEMP))","$(strip $(CPPFILES_PRE_PROCESSOR_DEFINES))")
CPPFILES_VARS_CHANGED :=1
else
ifneq ("$(strip $(CPPFILES_PROJECT_INCLUDE_DIRS_TEMP))","$(strip $(CPPFILES_PROJECT_INCLUDE_DIRS))")
CPPFILES_VARS_CHANGED :=1
else
ifneq ("$(strip $(CPPFILES_GENERATED_INCLUDE_DIRS_TEMP))","$(strip $(CPPFILES_GENERATED_INCLUDE_DIRS))")
CPPFILES_VARS_CHANGED :=1
else
ifneq ("$(strip $(CPPFILES_CPP_COMPILE_FLAGS_TEMP))","$(strip $(CPPFILES_CPP_COMPILE_FLAGS))")
CPPFILES_VARS_CHANGED :=1
endif
endif
endif
endif
endif
endif

ifeq ($(CPPFILES_VARS_CHANGED),1)

PUSH_SCOPED_VAR_VAR_NAME := CPPFILES_COMPILER
include $(BUILD)/include-functions/pushscopedvar.mk

PUSH_SCOPED_VAR_VAR_NAME := CPPFILES_PREPROCESSOR
include $(BUILD)/include-functions/pushscopedvar.mk

PUSH_SCOPED_VAR_VAR_NAME := CPPFILES_PRE_PROCESSOR_DEFINES
include $(BUILD)/include-functions/pushscopedvar.mk

PUSH_SCOPED_VAR_VAR_NAME := CPPFILES_PROJECT_INCLUDE_DIRS
include $(BUILD)/include-functions/pushscopedvar.mk

PUSH_SCOPED_VAR_VAR_NAME := CPPFILES_GENERATED_INCLUDE_DIRS
include $(BUILD)/include-functions/pushscopedvar.mk

PUSH_SCOPED_VAR_VAR_NAME := CPPFILES_CPP_COMPILE_FLAGS
include $(BUILD)/include-functions/pushscopedvar.mk

endif

endif

CURR_TARGET_CPP_FILES     := $(wildcard $(CURR_PROJECT_DIR)/*.cpp )
CURR_TARGET_CC_FILES      := $(wildcard $(CURR_PROJECT_DIR)/*.cc )

ifneq ("$(strip $(CURR_TARGET_CPP_FILES) $(CURR_TARGET_CC_FILES))","")


CPPFILES_CURR_INCLUDE_DIRS          := $(CPPFILES_PROJECT_INCLUDE_DIRS) $(SYSTEM_INCLUDE_DIRS) $(CPPFILES_GENERATED_INCLUDE_DIRS)
CPPFILES_CURR_INCLUDE_PATH_SWITCHES := $(foreach dir, $(CPPFILES_CURR_INCLUDE_DIRS),-I$(dir))

CPPFILES_CURR_PRE_PROCESSOR_DEFINES          := $(CPPFILES_PRE_PROCESSOR_DEFINES) $(SYSTEM_DEFINES)
CPPFILES_CURR_PRE_PROCESSOR_DEFINES_SWITCHES := $(foreach def,$(CPPFILES_CURR_PRE_PROCESSOR_DEFINES),-D$(def))



CPPFILES_CURR_CC    := $(CPPFILES_COMPILER)                   \
                       $(CPPFILES_CPP_COMPILE_FLAGS)          \
                       $(CPPFILES_CURR_INCLUDE_PATH_SWITCHES) \
                       $(CPPFILES_CURR_PRE_PROCESSOR_DEFINES_SWITCHES)

CPPFILES_CURR_PRECC := $(CPPFILES_PREPROCESSOR) $(CPPFILES_CURR_INCLUDE_PATH_SWITCHES) \
                       $(CPPFILES_CURR_PRE_PROCESSOR_DEFINES_SWITCHES) \
                       -DFULCRUM_EXCLUDED_GENERATED_INCLUDES



CURR_TARGET_DEPS          := $(patsubst $(CURR_PROJECT_DIR)/%.cpp, $(CURR_TARGET_DIR)/%.d, $(CURR_TARGET_CPP_FILES) ) $(CURR_TARGET_DEPS)
CURR_TARGET_DEPS          := $(patsubst $(CURR_PROJECT_DIR)/%.cc, $(CURR_TARGET_DIR)/%.d, $(CURR_TARGET_CC_FILES) ) $(CURR_TARGET_DEPS)

CPPFILES_CPP_OBJS         := $(patsubst $(CURR_PROJECT_DIR)/%.cpp, $(CURR_TARGET_DIR)/%.o, $(CURR_TARGET_CPP_FILES) ) 

CPPFILES_CC_OBJS          := $(patsubst $(CURR_PROJECT_DIR)/%.cc, $(CURR_TARGET_DIR)/%.o, $(CURR_TARGET_CC_FILES) )

LIBFILES_TARGET_LD_OBJS     :=  $(CPPFILES_CPP_OBJS) $(CPPFILES_CC_OBJS) $(LIBFILES_TARGET_LD_OBJS)

CURR_INTERMEDIATE_FILES := $(CPPFILES_CPP_OBJS) $(CPPFILES_CC_OBJS) $(CURR_INTERMEDIATE_FILES)

CPPFILES_LOCAL_CC-$(CURR_TARGET_DIR) := $(CPPFILES_CURR_CC)

$(CURR_TARGET_DIR)/%.o: $(CURR_PROJECT_DIR)/%.cpp
	$(CPPFILES_LOCAL_CC-$(strip $(@D))) -c -o $@ $<

$(CURR_TARGET_DIR)/%.o: $(CURR_PROJECT_DIR)/%.cc
	$(CPPFILES_LOCAL_CC-$(strip $(@D))) -c -o $@ $<

CPPFILES_LOCAL_PRECC-$(CURR_TARGET_DIR) := $(CPPFILES_CURR_PRECC)

$(CURR_TARGET_DEPS): $(foreach dir, $(CPPFILES_GENERATED_INCLUDE_DIRS), $(dir)/.sometimesmakesucks)

$(CURR_TARGET_DIR)/%.d: $(CURR_PROJECT_DIR)/%.cpp
	$(CPPFILES_LOCAL_PRECC-$(strip $(@D))) -MM -MG $< | $(GNUSED) -e "s/.*\.o\:/$(subst /,\/,$(@D)/$(*F)).o:/" >$@

$(CURR_TARGET_DIR)/%.d: $(CURR_PROJECT_DIR)/%.cc
	$(CPPFILES_LOCAL_PRECC-$(strip $(@D))) -MM -MG $< | $(GNUSED) -e "s/.*\.o\:/$(subst /,\/,$(@D)/$(*F)).o:/" >$@



endif
