

OS_TYPE := $(shell uname -s)
UNAME   := $(shell uname)
CPPFILES_PRE_PROCESSOR_DEFINES_FRAME_SIZE  :=0
CPPFILES_PROJECT_INCLUDE_DIRS_FRAME_SIZE   :=0
CPPFILES_GENERATED_INCLUDE_DIRS_FRAME_SIZE :=0
CPPFILES_C_COMPILE_FLAGS_FRAME_SIZE        :=0
