import ("libm3")
import ("cit_util")
import ("parseparams")
import ("simpletoken")
import ("mscheme")
import ("modula3scheme")
import ("sstubgen")
import ("parseparams")
import ("cspgrammar")
import ("cspsimlib")

%if defined("CM3_VERSION")
%        m3_optimize("T")
%end

SchemeStubs ("CspExpression")
SchemeStubs ("CspExpressionPublic")
SchemeStubs ("CspExpressionSeq")

SchemeStubs ("CspStatement")
SchemeStubs ("CspStatementPublic")
SchemeStubs ("CspStatementSeq")

SchemeStubs ("CspType")
SchemeStubs ("CspTypePublic")
SchemeStubs ("CspStructMember")
SchemeStubs ("CspStructMemberSeq")

SchemeStubs ("CspAst")

SchemeStubs ("CspGuardedCommand")
SchemeStubs ("CspGuardedCommandSeq")

SchemeStubs ("CspDeclaration")
SchemeStubs ("CspDeclarationPublic")
SchemeStubs ("CspDeclarationSeq")

SchemeStubs ("CspDirection")
SchemeStubs ("CspRange")
SchemeStubs ("CspInterval")

SchemeStubs ("CspDeclarator")
SchemeStubs ("CspDeclaratorSeq")
SchemeStubs ("CspStructDeclarator")
SchemeStubs ("CspStructDeclaratorSeq")

SchemeStubs ("CspSyntax")

SchemeStubs ("FiniteInterval")
SchemeStubs ("VaryBits")

SchemeStubs ("DynamicInt")
SchemeStubs ("WideInt")
SchemeStubs ("NativeInt")
SchemeStubs ("Debug")
SchemeStubs ("BigInt")
SchemeStubs ("Math")
SchemeStubs ("TextWr")
SchemeStubs ("FileWr")
SchemeStubs ("Wr")
SchemeStubs ("FileRd")
SchemeStubs ("Rd")
SchemeStubs ("TextRd")
SchemeStubs ("SchemeEnvironment")
SchemeStubs ("SchemeUtils")
SchemeStubs ("Fmt")
SchemeStubs ("Atom")
SchemeStubs ("Word")
SchemeStubs ("Env")
SchemeStubs ("CitTextUtils")

ExportSchemeStubs ("cspc")
importSchemeStubs()

implementation ("Main")

program ("cspc")


