% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("cit_util")
import ("parseparams")
import ("varosc")
import ("techc")
import ("normaldev")

implementation ("Main")

KeyPair ("TextLR", "Text", "LongrealType")
Array_sort("TextLRPair", "TextLRPair")

program ("vary")
