#!/usr/intel/bin/zsh -x

echo $0 start at `date`

release_dir=$1
shift
if [[ $# -eq 0 ]]; then
    bundles=(base_ulvt dsbase_ulvt dsimain_ulvt dsseq_ulvt seq_ulvt base_lvt dsbase_lvt)
else
    bundles=("$@")
fi

for bundle in $bundles; do
    rm -rf $bundle/lib
    rm -rf $bundle/ndm
    mkdir -p $bundle/{lib,ndm}
    for subdir in $stdcell_dir/$bundle/*; do
        [[ -d $bundle/${subdir:t} ]] || ln -s $subdir $bundle
    done
    for lib in $stdcell_dir/$bundle/lib/*; do
        ln -sf $lib $bundle/lib
    done
    cp -a $release_dir/${fulllib}_${bundle}_*.{lib,ldb} $bundle/lib
    nbjob run --target ${NBPOOL} --qslot ${NBQSLOT} --mode interactive --class 'SLES12&&4G' gzip -f $bundle/lib/*.lib &
done

wait

for bundle in $bundles; do
    nbjob run --target ${NBPOOL} --qslot ${NBQSLOT} --mode interactive --class 'SLES12&&4G' cp -a $release_dir/$bundle/${fulllib}_${bundle}.ndm $bundle/ndm &
done

wait

for bundle in $bundles; do
    for f in $stdcell_dir/$bundle/ndm/*; do
        [[ -e $bundle/ndm/${f:t} ]] || ln -s $f $bundle/ndm
    done
done

echo $0 done at `date`
