import ("libm3")
import ("cit_util")
import ("spicelib")
import ("tracelib")
import ("regression")
import ("arithcode")

import ("rep16")

Module ("SpiceCompress")

Table ("TripleRef", "IntTriple", "Refany")


library ("spicecompress")
