% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("cit_util")
import ("spicelib")
import ("regression")
import ("arithcode")

m3_optimize("T")

import ("rep16")

Module ("SpiceCompress")

Table ("TripleRef", "IntTriple", "Refany")

library ("spicecompress")
