/* $Id: m3makefile,v 1.4 2009/11/27 09:24:46 mika Exp $ */

import("libm3")
import("cit_util")
import("mscheme")
import("schemesig")
import("m3readline")
import("modula3scheme")

Module("SchemeReadLine")
Module("SchemeInteraction")

library("schemereadline")
