/* $Id$ */
import ("cit_util")
import ("mscheme")
import ("modula3scheme")
import ("libm3")
import ("netobj")
import ("m3readline")
import ("schemereadline")
import ("sstubgen")
import ("traderulelib")

Module("Example")
Interface("Example2")
%Interface("Type")
%Interface("Value")
Module("Bubble")

SchemeStubs("Bubble")
SchemeStubs("Example")

SchemeStubs("Wr")
SchemeStubs("TextWr")
SchemeStubs("TextRd")
SchemeStubs("FileWr")
SchemeStubs("Rd")
SchemeStubs("FileRd")
SchemeStubs("Pickle")
SchemeStubs("MarketData")  % why doesnt THIS work

SchemeStubs("TextSet")
SchemeStubs("TextSetDef")

%SchemeStubs("TextRefTbl") % doesnt work yet

ExportSchemeStubs("stubexample") % export OUR scheme stubs

importSchemeStubs()              % import ALL scheme stubs

implementation("Main")

program ("stubexample")
