// Autogenerated Jamon proxy
// C:/Users/mhesseli/Documents/Perforce/rrc-4/reg-main/shared/java/src/./com/fulcrummicro/util/jamon/timestamp.jamon

package com.fulcrummicro.util.jamon;

// 8, 1
import java.text.SimpleDateFormat;
// 9, 1
import java.util.Calendar;
// 10, 1
import java.util.Locale;
// 11, 1
import java.util.TimeZone;

@org.jamon.annotations.Template(
  signature = "16641E4377F3F072614EBF98F7B441F9",
  methods = {
    @org.jamon.annotations.Method(
      name = "timestamp"),
    @org.jamon.annotations.Method(
      name = "copyright_year",
      optionalArguments = {
        @org.jamon.annotations.Argument(name = "creationYear", type = "Integer")})})
public abstract class timestamp
  extends org.jamon.AbstractTemplateProxy
{
  
  public timestamp(org.jamon.TemplateManager p_manager)
  {
     super(p_manager);
  }
  
  protected timestamp(String p_path)
  {
    super(p_path);
  }
  
  public interface Intf
    extends org.jamon.AbstractTemplateProxy.Intf
  {
    
  }
  public static class ImplData
    extends org.jamon.AbstractTemplateProxy.ImplData
  {
  }
  
  public abstract class ParentRenderer
  {
    protected ParentRenderer() {}
    public void render(final java.io.Writer jamonWriter)
      throws java.io.IOException{
      renderNoFlush(jamonWriter);
      jamonWriter.flush();
    }
    public void renderNoFlush(final java.io.Writer jamonWriter)
      throws java.io.IOException{
      renderChild(jamonWriter);
    }
    public org.jamon.Renderer makeRenderer()
    {
      return new org.jamon.AbstractRenderer() {
        @Override
        public void renderTo(final java.io.Writer jamonWriter)
          throws java.io.IOException
        {
          render(jamonWriter);
        }
      };
    }
    
    protected abstract void renderChild(final java.io.Writer jamonWriter)
      throws java.io.IOException;
  }
  
}
