% Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information.
% SPDX-License-Identifier: Apache-2.0

import ("libm3")
import ("set")
import ("parseparams")
import ("mscheme")

m3_optimize("T")

implementation ("UglyPrint")

program ("uglyprint")
