import ("libm3")
import ("cit_util")
import ("parseparams")
import ("simpletoken")
import ("mscheme")
import ("modula3scheme")
import ("sstubgen")
import ("parseparams")
import ("mpfr")
import ("minimize")

%if defined("CM3_VERSION")
%        m3_optimize("T")
%end

module ("YieldModel")

Table("LongrealMpfr", "LongReal", "Mpfr")
Sorted_table("LongrealMpfr", "LongReal", "Mpfr")

Module ("Polynomial")

Module ("FmtFrac")

SchemeStubs ("YieldModel")
SchemeStubs ("Math")
SchemeStubs ("Wr")
SchemeStubs ("Rd")
SchemeStubs ("Mpfr")
SchemeStubs ("Polynomial")
SchemeStubs ("SortedLongrealMpfrTbl")
SchemeStubs ("LongrealMpfrTbl")
SchemeStubs ("SchemeEnvironment")
SchemeStubs ("Fmt")
SchemeStubs ("LRFunction")
SchemeStubs ("Solve")
SchemeStubs ("FmtFrac")

ExportSchemeStubs ("diesplit")
importSchemeStubs()

implementation ("Main")

program ("diesplit")


