/* $Id: m3makefile,v 1.2 2005/04/18 20:54:42 mika Exp $ */

/*import("netobj")*/
import("tcp")
import("libm3")

Table ("Refany", "Text", "Refany")

Module("RdWrPipe")
Module("SimpleMsgRW")
Module("TeeWr")

Library("rdwr")
