//                                                                             
// File:            mby_ppe_trig_usage_map_regs.h                              
// Creator:         solson                                                     
// Time:            Wednesday Dec 12, 2018 [10:52:09 am]                       
//                                                                             
// Path:            /tmp/solson/nebulon_run/4706538284_2018-12-12.10:40:08     
// Arguments:       -I                                                         
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/tools/srdl
//                  -sv_no_sai_checks -sverilog -xml -chdr -crif -ovm -input   
//                  mby_top_map.rdl -timeout 60000 -out_dir                    
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/target/GenRTL/regflow/mby
//                  -rtlgencomp -log_file                                      
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/target/GenRTL/regflow/mby/nebulon_sv_output.log
//                                                                             
// MRE:             5.2018.2                                                   
// Machine:         scci79110                                                  
// OS:              Linux 3.0.101-108.13.1.14249.0.PTF-default                 
// Nebulon version: d18ww24.4                                                  
// Description:                                                                
//                                                                             
// No Description Provided                                                     
//                                                                             
// Copyright (C) 2018 Intel Corp. All rights reserved                          
// THIS FILE IS AUTOMATICALLY GENERATED BY INTEL RDL GENERATOR, DO NOT EDIT    
//                                                                             


#ifndef _MBY_PPE_TRIG_USAGE_MAP_REGS_H_
#define _MBY_PPE_TRIG_USAGE_MAP_REGS_H_

#define TRIG_USAGE_MSGPORT     0x0
#define TRIG_USAGE_TRIGGER_RATE_LIM_CFG_1_MSGREGADDR 0x0
#define TRIG_USAGE_TRIGGER_RATE_LIM_USAGE_MSGREGADDR 0x80

#ifndef MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_FLAG
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_FLAG
// TRIGGER_RATE_LIM_CFG_1 desc:  Configuration related to the trigger rate limiting action.
typedef union {
    struct {
        uint64_t  CAPACITY             :  12;    //  Capacity of rate limiter
                                                 // token bucket in 1024 byte
                                                 // units. (Maximum burst
                                                 // allowance is 4 MB, or 3.6MB
                                                 // for near-maximal rate limits.)
                                                 // This must not be set within
                                                 // refillAmount of the maximum:
                                                 // Capacity <= ((0xfff << 14) -
                                                 // ((RateMantissa) << (7-
                                                 // RateExponent))) >> 14
        uint64_t  RATE_MANTISSA        :  12;    //  Floating point mantissa of
                                                 // the token bucket's refill
                                                 // rate. Amount of refill is
                                                 // (RateMantissa) << (7-
                                                 // RateExponent) per 16 FH clock
                                                 // cycles, in units of 1/16th
                                                 // bytes.
        uint64_t  RATE_EXPONENT        :   3;    //  Floating point exponent of
                                                 // the token bucket's refill
                                                 // rate. Amount of refill is
                                                 // (RateMantissa) << (7-
                                                 // RateExponent) per 16 FH clock
                                                 // cycles, in units of 1/16th
                                                 // bytes.
        uint64_t  RSVD_0               :  37;    // Nebulon auto filled RSVD [63:27]

    }                                field;
    uint64_t                         val;
} MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_t;
#endif
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_OFFSET 0x00
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_SCOPE 0x01
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_SIZE 64
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_BITFIELD_COUNT 0x03
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_RESET 0x00000000

#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_CAPACITY_LSB 0x0000
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_CAPACITY_MSB 0x000b
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_CAPACITY_RANGE 0x000c
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_CAPACITY_MASK 0x00000fff
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_CAPACITY_RESET_VALUE 0x00000000

#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_RATE_MANTISSA_LSB 0x000c
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_RATE_MANTISSA_MSB 0x0017
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_RATE_MANTISSA_RANGE 0x000c
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_RATE_MANTISSA_MASK 0x00fff000
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_RATE_MANTISSA_RESET_VALUE 0x00000000

#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_RATE_EXPONENT_LSB 0x0018
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_RATE_EXPONENT_MSB 0x001a
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_RATE_EXPONENT_RANGE 0x0003
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_RATE_EXPONENT_MASK 0x07000000
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_RATE_EXPONENT_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

#ifndef MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_USAGE_FLAG
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_USAGE_FLAG
// TRIGGER_RATE_LIM_USAGE desc:  Tracks the trigger rate limiter's token-bucket level in units of
// 1/16th bytes.
typedef union {
    struct {
        uint64_t  LEVEL                :  27;    //  Current rate limiter token
                                                 // bucket level in units of
                                                 // 1/16th bytes. Value is signed
                                                 // two's complement notation.
        uint64_t  RSVD_0               :  37;    // Nebulon auto filled RSVD [63:27]

    }                                field;
    uint64_t                         val;
} MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_USAGE_t;
#endif
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_USAGE_OFFSET 0x80
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_USAGE_SCOPE 0x01
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_USAGE_SIZE 64
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_USAGE_BITFIELD_COUNT 0x01
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_USAGE_RESET 0x00000000

#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_USAGE_LEVEL_LSB 0x0000
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_USAGE_LEVEL_MSB 0x001a
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_USAGE_LEVEL_RANGE 0x001b
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_USAGE_LEVEL_MASK 0x07ffffff
#define MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_USAGE_LEVEL_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

// starting the array instantiation section
typedef struct {
    MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_CFG_1_t TRIGGER_RATE_LIM_CFG_1[16]; // offset 4'h0, width 64
    MBY_PPE_TRIG_USAGE_MAP_MSG_TRIGGER_RATE_LIM_USAGE_t TRIGGER_RATE_LIM_USAGE[16]; // offset 8'h80, width 64
} mby_ppe_trig_usage_map_t;                      // size:  12'h100


#endif // _MBY_PPE_TRIG_USAGE_MAP_REGS_H_

