//                                                                             
// File:            mby_mgp_top_map_top_regs.h                                 
// Creator:         solson                                                     
// Time:            Wednesday Dec 12, 2018 [10:52:09 am]                       
//                                                                             
// Path:            /tmp/solson/nebulon_run/4706538284_2018-12-12.10:40:08     
// Arguments:       -I                                                         
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/tools/srdl
//                  -sv_no_sai_checks -sverilog -xml -chdr -crif -ovm -input   
//                  mby_top_map.rdl -timeout 60000 -out_dir                    
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/target/GenRTL/regflow/mby
//                  -rtlgencomp -log_file                                      
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/target/GenRTL/regflow/mby/nebulon_sv_output.log
//                                                                             
// MRE:             5.2018.2                                                   
// Machine:         scci79110                                                  
// OS:              Linux 3.0.101-108.13.1.14249.0.PTF-default                 
// Nebulon version: d18ww24.4                                                  
// Description:                                                                
//                                                                             
// No Description Provided                                                     
//                                                                             
// Copyright (C) 2018 Intel Corp. All rights reserved                          
// THIS FILE IS AUTOMATICALLY GENERATED BY INTEL RDL GENERATOR, DO NOT EDIT    
//                                                                             



#include "mby_ppe_rx_top_map_top_regs.h"
#include "mby_rx_voq_map_regs.h"
#include "mby_rx_pb_map_regs.h"
#include "mby_ppe_tx_top_map_top_regs.h"
#include "mby_tx_voq_map_regs.h"
#include "mby_tx_pb_map_regs.h"


// begin top instantiation section
typedef struct {
  mby_ppe_rx_top_map_top      rx_ppe;
  mby_rx_voq_map_t      rx_voq;
  mby_rx_pb_map_t       rx_pb;
  mby_ppe_tx_top_map_top      tx_ppe;
  mby_tx_voq_map_t      tx_voq;
  mby_tx_pb_map_t       tx_pb;

} mby_mgp_top_map_top;    // size: 4'h0
