//                                                                             
// File:            mby_tx_voq_map_regs.h                                      
// Creator:         solson                                                     
// Time:            Wednesday Dec 12, 2018 [10:52:09 am]                       
//                                                                             
// Path:            /tmp/solson/nebulon_run/4706538284_2018-12-12.10:40:08     
// Arguments:       -I                                                         
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/tools/srdl
//                  -sv_no_sai_checks -sverilog -xml -chdr -crif -ovm -input   
//                  mby_top_map.rdl -timeout 60000 -out_dir                    
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/target/GenRTL/regflow/mby
//                  -rtlgencomp -log_file                                      
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/target/GenRTL/regflow/mby/nebulon_sv_output.log
//                                                                             
// MRE:             5.2018.2                                                   
// Machine:         scci79110                                                  
// OS:              Linux 3.0.101-108.13.1.14249.0.PTF-default                 
// Nebulon version: d18ww24.4                                                  
// Description:                                                                
//                                                                             
// No Description Provided                                                     
//                                                                             
// Copyright (C) 2018 Intel Corp. All rights reserved                          
// THIS FILE IS AUTOMATICALLY GENERATED BY INTEL RDL GENERATOR, DO NOT EDIT    
//                                                                             


#ifndef _MBY_TX_VOQ_MAP_REGS_H_
#define _MBY_TX_VOQ_MAP_REGS_H_

#define TX_VOQ_MSGPORT     0x0
#define TX_VOQ_TX_VOQ_PORT_CFG_MSGREGADDR 0x0

#ifndef MBY_TX_VOQ_MAP_MSG_TX_VOQ_PORT_CFG_FLAG
#define MBY_TX_VOQ_MAP_MSG_TX_VOQ_PORT_CFG_FLAG
// TX_VOQ_PORT_CFG desc:  Port configuration for the Tx VOQ. The head buffer allocation and
// scheduler time-slicing are derived from this configuration. The port
// index is N*4 + M. The port configuration values are: [list] [*] 0 =
// Disable this port. [*] 1 = This port is 100G, 50G, or 25G. [*] 2 =
// This port is 200G. Only port N.0 or N.2 can be 200G, and the next port
// must be disabled. [*] 3 = This port is 400G. Only port N.0 can be
// 400G, and the next 3 ports must be disabled. [/list]
typedef union {
    struct {
        uint64_t  PORT                 :  32;    //  Port configurations, the
                                                 // configuration for port i runs
                                                 // from bit 2*i to bit 2*i+1
        uint64_t  RSVD_0               :  32;    // Nebulon auto filled RSVD [63:32]

    }                                field;
    uint64_t                         val;
} MBY_TX_VOQ_MAP_MSG_TX_VOQ_PORT_CFG_t;
#endif
#define MBY_TX_VOQ_MAP_MSG_TX_VOQ_PORT_CFG_OFFSET 0x00
#define MBY_TX_VOQ_MAP_MSG_TX_VOQ_PORT_CFG_SCOPE 0x01
#define MBY_TX_VOQ_MAP_MSG_TX_VOQ_PORT_CFG_SIZE 64
#define MBY_TX_VOQ_MAP_MSG_TX_VOQ_PORT_CFG_BITFIELD_COUNT 0x01
#define MBY_TX_VOQ_MAP_MSG_TX_VOQ_PORT_CFG_RESET 0x00000000

#define MBY_TX_VOQ_MAP_MSG_TX_VOQ_PORT_CFG_PORT_LSB 0x0000
#define MBY_TX_VOQ_MAP_MSG_TX_VOQ_PORT_CFG_PORT_MSB 0x001f
#define MBY_TX_VOQ_MAP_MSG_TX_VOQ_PORT_CFG_PORT_RANGE 0x0020
#define MBY_TX_VOQ_MAP_MSG_TX_VOQ_PORT_CFG_PORT_MASK 0xffffffff
#define MBY_TX_VOQ_MAP_MSG_TX_VOQ_PORT_CFG_PORT_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

// starting the array instantiation section
typedef struct {
    MBY_TX_VOQ_MAP_MSG_TX_VOQ_PORT_CFG_t TX_VOQ_PORT_CFG;  // offset 4'h0, width 64
} mby_tx_voq_map_t;                              // size:  4'h8


#endif // _MBY_TX_VOQ_MAP_REGS_H_

