/* Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information. */
/* SPDX-License-Identifier: Apache-2.0 */

//                                                                             
// File:            mby_freepointer_fifo_map_regs.h                            
// Creator:         solson                                                     
// Time:            Wednesday Dec 12, 2018 [10:52:09 am]                       
//                                                                             
// Path:            /tmp/solson/nebulon_run/4706538284_2018-12-12.10:40:08     
// Arguments:       -I                                                         
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/tools/srdl
//                  -sv_no_sai_checks -sverilog -xml -chdr -crif -ovm -input   
//                  mby_top_map.rdl -timeout 60000 -out_dir                    
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/target/GenRTL/regflow/mby
//                  -rtlgencomp -log_file                                      
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/target/GenRTL/regflow/mby/nebulon_sv_output.log
//                                                                             
// MRE:             5.2018.2                                                   
// Machine:         scci79110                                                  
// OS:              Linux 3.0.101-108.13.1.14249.0.PTF-default                 
// Nebulon version: d18ww24.4                                                  
// Description:                                                                
//                                                                             
// No Description Provided                                                     
//                                                                             
// Copyright (C) 2018 Intel Corp. All rights reserved                          
// THIS FILE IS AUTOMATICALLY GENERATED BY INTEL RDL GENERATOR, DO NOT EDIT    
//                                                                             


#ifndef _MBY_FREEPOINTER_FIFO_MAP_REGS_H_
#define _MBY_FREEPOINTER_FIFO_MAP_REGS_H_

#define FIFO0_BASE 0x0
#define FIFO1_BASE 0x8000
#define FIFO2_BASE 0x10000
#define FIFO3_BASE 0x18000
#define FIFO4_BASE 0x20000
#define FIFO5_BASE 0x28000
#define FIFO6_BASE 0x30000
#define FIFO7_BASE 0x38000
#define FIFO8_BASE 0x40000
#define FIFO9_BASE 0x48000
#define FIFO10_BASE 0x50000
#define FIFO11_BASE 0x58000
#define FIFO12_BASE 0x60000
#define FIFO13_BASE 0x68000
#define FIFO14_BASE 0x70000
#define FIFO15_BASE 0x78000
#define FIFO16_BASE 0x80000
#define FIFO17_BASE 0x88000
#define FIFO18_BASE 0x90000
#define FIFO19_BASE 0x98000
#define FIFO20_BASE 0x0A0000
#define FIFO21_BASE 0x0A8000
#define FIFO22_BASE 0x0B0000
#define FIFO23_BASE 0x0B8000
#define FIFO24_BASE 0x0C0000
#define FIFO25_BASE 0x0C8000
#define FIFO26_BASE 0x0D0000
#define FIFO27_BASE 0x0D8000
#define FIFO28_BASE 0x0E0000
#define FIFO29_BASE 0x0E8000
#define FIFO30_BASE 0x0F0000
#define FIFO31_BASE 0x0F8000
#define FIFO32_BASE 0x100000
#define FIFO33_BASE 0x108000
#define FIFO34_BASE 0x110000
#define FIFO35_BASE 0x118000
#define FIFO36_BASE 0x120000
#define FIFO37_BASE 0x128000
#define FIFO38_BASE 0x130000
#define FIFO39_BASE 0x138000
#define FIFO40_BASE 0x140000
#define FIFO41_BASE 0x148000
#define FIFO42_BASE 0x150000
#define FIFO43_BASE 0x158000
#define FIFO44_BASE 0x160000
#define FIFO45_BASE 0x168000
#define FIFO46_BASE 0x170000
#define FIFO47_BASE 0x178000
#define FIFO48_BASE 0x180000
#define FIFO49_BASE 0x188000
#define FIFO50_BASE 0x190000
#define FIFO51_BASE 0x198000
#define FIFO52_BASE 0x1A0000
#define FIFO53_BASE 0x1A8000
#define FIFO54_BASE 0x1B0000
#define FIFO55_BASE 0x1B8000
#define FIFO56_BASE 0x1C0000
#define FIFO57_BASE 0x1C8000
#define FIFO58_BASE 0x1D0000
#define FIFO59_BASE 0x1D8000
#define FIFO60_BASE 0x1E0000
#define FIFO61_BASE 0x1E8000
#define FIFO62_BASE 0x1F0000
#define FIFO63_BASE 0x1F8000
#define FIFO64_BASE 0x200000
#define FIFO65_BASE 0x208000
#define FIFO66_BASE 0x210000
#define FIFO67_BASE 0x218000
#define FIFO68_BASE 0x220000
#define FIFO69_BASE 0x228000
#define FIFO70_BASE 0x230000
#define FIFO71_BASE 0x238000
#define FIFO72_BASE 0x240000
#define FIFO73_BASE 0x248000
#define FIFO74_BASE 0x250000
#define FIFO75_BASE 0x258000
#define FIFO76_BASE 0x260000
#define FIFO77_BASE 0x268000
#define FIFO78_BASE 0x270000
#define FIFO79_BASE 0x278000
#define FIFO80_BASE 0x280000
#define FIFO81_BASE 0x288000
#define FIFO82_BASE 0x290000
#define FIFO83_BASE 0x298000
#define FIFO84_BASE 0x2A0000
#define FIFO_MESH_FREEPOINTER_LOAD_ADDRESS_MMOFFSET 0x0

#ifndef MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_FLAG
#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_FLAG
// MESH_FREEPOINTER_LOAD_ADDRESS desc:  Writes two free pointer addresses (and correspondent RAW bits) into
// a FIFO. Register index indicates, first which free pointer fifo (65),
// and second which of the 3085 pairs of addresses (total of 6,169) are
// loaded into that free pointer fifo.
typedef union {
    struct {
        uint64_t  VALUE_1              :  24;    //  First free pointer address to
                                                 // loead.
        uint64_t  VALUE_2              :  24;    //  Second free pointer address
                                                 // to loead.
        uint64_t  RSVD_0               :  16;    // Nebulon auto filled RSVD [63:48]

    }                                field;
    uint64_t                         val;
} MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_t;
#endif
#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_OFFSET 0x00
#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_SCOPE 0x01
#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_SIZE 64
#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_BITFIELD_COUNT 0x02
#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_RESET 0x00000000

#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_VALUE_1_LSB 0x0000
#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_VALUE_1_MSB 0x0017
#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_VALUE_1_RANGE 0x0018
#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_VALUE_1_MASK 0x00ffffff
#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_VALUE_1_RESET_VALUE 0x00000000

#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_VALUE_2_LSB 0x0018
#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_VALUE_2_MSB 0x002f
#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_VALUE_2_RANGE 0x0018
#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_VALUE_2_MASK 0xffffff000000
#define MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_VALUE_2_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

// starting the array instantiation section
typedef struct {
    MBY_FREEPOINTER_FIFO_MAP_MEM_MESH_FREEPOINTER_LOAD_ADDRESS_t MESH_FREEPOINTER_LOAD_ADDRESS[3085]; // offset 4'h0, width 64
} mby_freepointer_fifo_map_t;                    // size:  16'h6068


#endif // _MBY_FREEPOINTER_FIFO_MAP_REGS_H_

