//                                                                             
// File:            mby_ppe_modify_map_regs.h                                  
// Creator:         solson                                                     
// Time:            Wednesday Dec 12, 2018 [10:52:09 am]                       
//                                                                             
// Path:            /tmp/solson/nebulon_run/4706538284_2018-12-12.10:40:08     
// Arguments:       -I                                                         
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/tools/srdl
//                  -sv_no_sai_checks -sverilog -xml -chdr -crif -ovm -input   
//                  mby_top_map.rdl -timeout 60000 -out_dir                    
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/target/GenRTL/regflow/mby
//                  -rtlgencomp -log_file                                      
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/target/GenRTL/regflow/mby/nebulon_sv_output.log
//                                                                             
// MRE:             5.2018.2                                                   
// Machine:         scci79110                                                  
// OS:              Linux 3.0.101-108.13.1.14249.0.PTF-default                 
// Nebulon version: d18ww24.4                                                  
// Description:                                                                
//                                                                             
// No Description Provided                                                     
//                                                                             
// Copyright (C) 2018 Intel Corp. All rights reserved                          
// THIS FILE IS AUTOMATICALLY GENERATED BY INTEL RDL GENERATOR, DO NOT EDIT    
//                                                                             


#ifndef _MBY_PPE_MODIFY_MAP_REGS_H_
#define _MBY_PPE_MODIFY_MAP_REGS_H_

#define MODIFY_MSGPORT     0x0
#define MODIFY_MOD_PROFILE_COMMAND_MSGREGADDR 0x0
#define MODIFY_MOD_PROFILE_FIELD_MSGREGADDR 0x2000
#define MODIFY_MOD_MAP_DUAL_MSGREGADDR 0x10000
#define MODIFY_MOD_MAP_MSGREGADDR 0x20000
#define MODIFY_MOD_PROFILE_GROUP_MSGREGADDR 0x24000
#define MODIFY_MOD_MIRROR_PROFILE_TABLE0_MSGREGADDR 0x24200
#define MODIFY_MOD_MIRROR_PROFILE_TABLE1_MSGREGADDR 0x24400
#define MODIFY_MOD_MIRROR_PROFILE_TABLE2_MSGREGADDR 0x24600
#define MODIFY_MOD_MAP_CFG_MSGREGADDR 0x24800
#define MODIFY_MOD_MAP_DUAL_CFG_MSGREGADDR 0x24820
#define MODIFY_MOD_CSUM_CFG1_MSGREGADDR 0x24828
#define MODIFY_MOD_CSUM_CFG2_MSGREGADDR 0x24830
#define MODIFY_MOD_CSUM_EN_CFG_MSGREGADDR 0x24838

#ifndef MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_FLAG
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_FLAG
// MOD_PROFILE_COMMAND desc:  Defines up to 4 24b commands to apply to a group. The i'th command
// for the j'th group is accessed at MOD_PROFILE_COMMAND[profile][(j*4 +
// i)/2].CMD_{i%2}.
typedef union {
    struct {
        uint64_t  CMD_0                :  24;    //  Indicates the 1st command.
                                                 // See the HAS for the encoding.
        uint64_t  CMD_1                :  24;    //  Indicates the 2nd command.
                                                 // See the HAS for the encoding.
        uint64_t  RSVD_0               :  16;    // Nebulon auto filled RSVD [63:48]

    }                                field;
    uint64_t                         val;
} MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_t;
#endif
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_OFFSET 0x00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_SCOPE 0x01
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_SIZE 64
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_BITFIELD_COUNT 0x02
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_RESET 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_CMD_0_LSB 0x0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_CMD_0_MSB 0x0017
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_CMD_0_RANGE 0x0018
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_CMD_0_MASK 0x00ffffff
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_CMD_0_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_CMD_1_LSB 0x0018
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_CMD_1_MSB 0x002f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_CMD_1_RANGE 0x0018
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_CMD_1_MASK 0xffffff000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_CMD_1_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

#ifndef MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_FLAG
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_FLAG
// MOD_PROFILE_FIELD desc:  Defines the 8b extraction for up to 24 fields. The i'th field
// settings is accessed at MOD_PROFILE_FIELD[profile][i/3].*_{i%3}.
typedef union {
    struct {
        uint64_t  PROTOCOL_ID_0        :   8;    //  Selects the protocol ID
                                                 // whose base offset is used to
                                                 // pick the field to extract.
                                                 // Values 0..222 indicate packet
                                                 // header protocols. A value of
                                                 // 223 refers to the internal
                                                 // parser pointer list. Values
                                                 // 224..254 indicate metadata
                                                 // types 0..30 respectively. A
                                                 // value of 255 is reserved.
        uint64_t  OFFSET_0             :   9;    //  Selects the extraction
                                                 // offset relative to the base
                                                 // offset of the given protocol
                                                 // ID.
        uint64_t  PROTOCOL_ID_1        :   8;    //  Selects the protocol ID
                                                 // whose base offset is used to
                                                 // pick the field to extract.
                                                 // Values 0..222 indicate packet
                                                 // header protocols. A value of
                                                 // 223 refers to the internal
                                                 // parser pointer list. Values
                                                 // 224..254 indicate metadata
                                                 // types 0..30 respectively. A
                                                 // value of 255 is reserved.
        uint64_t  OFFSET_1             :   9;    //  Selects the extraction
                                                 // offset relative to the base
                                                 // offset of the given protocol
                                                 // ID.
        uint64_t  PROTOCOL_ID_2        :   8;    //  Selects the protocol ID
                                                 // whose base offset is used to
                                                 // pick the field to extract.
                                                 // Values 0..222 indicate packet
                                                 // header protocols. A value of
                                                 // 223 refers to the internal
                                                 // parser pointer list. Values
                                                 // 224..254 indicate metadata
                                                 // types 0..30 respectively. A
                                                 // value of 255 is reserved.
        uint64_t  OFFSET_2             :   9;    //  Selects the extraction
                                                 // offset relative to the base
                                                 // offset of the given protocol
                                                 // ID.
        uint64_t  RSVD_0               :  13;    // Nebulon auto filled RSVD [63:51]

    }                                field;
    uint64_t                         val;
} MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_t;
#endif
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET 0x00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_SCOPE 0x01
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_SIZE 64
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_BITFIELD_COUNT 0x06
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_RESET 0x3fc01fe00ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_0_LSB 0x0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_0_MSB 0x0007
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_0_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_0_MASK 0x000000ff
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_0_RESET_VALUE 0x000000ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_0_LSB 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_0_MSB 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_0_RANGE 0x0009
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_0_MASK 0x0001ff00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_0_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_1_LSB 0x0011
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_1_MSB 0x0018
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_1_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_1_MASK 0x01fe0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_1_RESET_VALUE 0x000000ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_1_LSB 0x0019
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_1_MSB 0x0021
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_1_RANGE 0x0009
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_1_MASK 0x3fe000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_1_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_2_LSB 0x0022
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_2_MSB 0x0029
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_2_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_2_MASK 0x3fc00000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_PROTOCOL_ID_2_RESET_VALUE 0x000000ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_2_LSB 0x002a
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_2_MSB 0x0032
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_2_RANGE 0x0009
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_2_MASK 0x7fc0000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_OFFSET_2_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

#ifndef MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_FLAG
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_FLAG
// MOD_MAP_DUAL desc:  Provides 1K instances of 64 maps that produce a 1B value. The inner
// map i'th entry is located as MOD_MAP_DUAL[j][i/8].VALUE{i%8}. This
// LUT can be used to remap DSCP, VPRI or MPLS TC.
typedef union {
    struct {
        uint64_t  VALUE0               :   8;    //  The remapped value.
        uint64_t  VALUE1               :   8;    //  The remapped value.
        uint64_t  VALUE2               :   8;    //  The remapped value.
        uint64_t  VALUE3               :   8;    //  The remapped value.
        uint64_t  VALUE4               :   8;    //  The remapped value.
        uint64_t  VALUE5               :   8;    //  The remapped value.
        uint64_t  VALUE6               :   8;    //  The remapped value.
        uint64_t  VALUE7               :   8;    //  The remapped value.

    }                                field;
    uint64_t                         val;
} MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_t;
#endif
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_OFFSET 0x00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_SCOPE 0x01
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_SIZE 64
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_BITFIELD_COUNT 0x08
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_RESET 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE0_LSB 0x0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE0_MSB 0x0007
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE0_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE0_MASK 0x000000ff
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE0_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE1_LSB 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE1_MSB 0x000f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE1_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE1_MASK 0x0000ff00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE1_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE2_LSB 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE2_MSB 0x0017
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE2_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE2_MASK 0x00ff0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE2_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE3_LSB 0x0018
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE3_MSB 0x001f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE3_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE3_MASK 0xff000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE3_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE4_LSB 0x0020
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE4_MSB 0x0027
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE4_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE4_MASK 0xff00000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE4_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE5_LSB 0x0028
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE5_MSB 0x002f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE5_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE5_MASK 0xff0000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE5_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE6_LSB 0x0030
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE6_MSB 0x0037
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE6_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE6_MASK 0xff000000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE6_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE7_LSB 0x0038
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE7_MSB 0x003f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE7_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE7_MASK 0xff00000000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_VALUE7_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

#ifndef MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_FLAG
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_FLAG
// MOD_MAP desc:  Provides 2K maps that produce a 2B value. The i'th entry is located
// as MOD_MAP[*][i/4].VALUE{i%4}.
typedef union {
    struct {
        uint64_t  VALUE0               :  16;    //  The remapped value.
        uint64_t  VALUE1               :  16;    //  The remapped value.
        uint64_t  VALUE2               :  16;    //  The remapped value.
        uint64_t  VALUE3               :  16;    //  The remapped value.

    }                                field;
    uint64_t                         val;
} MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_t;
#endif
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_OFFSET 0x00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_SCOPE 0x01
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_SIZE 64
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_BITFIELD_COUNT 0x04
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_RESET 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE0_LSB 0x0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE0_MSB 0x000f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE0_RANGE 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE0_MASK 0x0000ffff
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE0_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE1_LSB 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE1_MSB 0x001f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE1_RANGE 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE1_MASK 0xffff0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE1_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE2_LSB 0x0020
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE2_MSB 0x002f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE2_RANGE 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE2_MASK 0xffff00000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE2_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE3_LSB 0x0030
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE3_MSB 0x003f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE3_RANGE 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE3_MASK 0xffff000000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_VALUE3_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

#ifndef MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_FLAG
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_FLAG
// MOD_PROFILE_GROUP desc:  Defines the mapping from the protocol headers to the modify
// transform groups. The first group, GROUP_0, is always assumed to
// start at byte 0 of the packet. The following 7 group values are
// provided, where the i'th value is a 9b encoding that either specifies
// an 8b protocol ID (when bit 8 is 0), or an 8b relative length offset
// into the last specified protocol ID (when bit 8 is 1). Use a value of
// 255 to indicate an unused group mapping.
typedef union {
    struct {
        uint64_t  GROUP_1              :   9;    //  See register description for
                                                 // field details.
        uint64_t  GROUP_2              :   9;    //  See register description for
                                                 // field details.
        uint64_t  GROUP_3              :   9;    //  See register description for
                                                 // field details.
        uint64_t  GROUP_4              :   9;    //  See register description for
                                                 // field details.
        uint64_t  GROUP_5              :   9;    //  See register description for
                                                 // field details.
        uint64_t  GROUP_6              :   9;    //  See register description for
                                                 // field details.
        uint64_t  GROUP_7              :   9;    //  See register description for
                                                 // field details.
        uint64_t  RSVD_0               :   1;    // Nebulon auto filled RSVD [63:63]

    }                                field;
    uint64_t                         val;
} MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_t;
#endif
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_OFFSET 0x00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_SCOPE 0x01
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_SIZE 64
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_BITFIELD_COUNT 0x07
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_RESET 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_1_LSB 0x0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_1_MSB 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_1_RANGE 0x0009
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_1_MASK 0x000001ff
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_1_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_2_LSB 0x0009
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_2_MSB 0x0011
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_2_RANGE 0x0009
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_2_MASK 0x0003fe00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_2_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_3_LSB 0x0012
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_3_MSB 0x001a
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_3_RANGE 0x0009
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_3_MASK 0x07fc0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_3_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_4_LSB 0x001b
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_4_MSB 0x0023
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_4_RANGE 0x0009
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_4_MASK 0xff8000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_4_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_5_LSB 0x0024
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_5_MSB 0x002c
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_5_RANGE 0x0009
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_5_MASK 0x1ff000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_5_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_6_LSB 0x002d
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_6_MSB 0x0035
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_6_RANGE 0x0009
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_6_MASK 0x3fe00000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_6_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_7_LSB 0x0036
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_7_MSB 0x003e
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_7_RANGE 0x0009
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_7_MASK 0x7fc0000000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_GROUP_7_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

#ifndef MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_FLAG
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_FLAG
// MOD_MIRROR_PROFILE_TABLE0 desc:  Defines mirror profiles in modify.
typedef union {
    struct {
        uint64_t  MIRROR_DST           :  12;    //  New Destination VSI/Port to
                                                 // use for mirrored or logged
                                                 // copies. The highest bit (bit
                                                 // 11) indicates that the
                                                 // destination type: *0: VSI
                                                 // *1: Physical Port 10:0
                                                 // Destination ID *if
                                                 // Destination Type = 0, valid
                                                 // from 0 to 1023, *if
                                                 // Destination Type = 1, valid
                                                 // from 0 to 7
        uint64_t  TRUNC                :   1;    //  Define whether mirror copies
                                                 // should be truncated or not.
        uint64_t  PRE_MOD              :   1;    //  Define whether mirror is
                                                 // Pre-Modify or not.
        uint64_t  RECIRCULATE          :   1;    //  Define whether the mirror
                                                 // copy should be recirculated
                                                 // back to FXP for additional
                                                 // processing.
        uint64_t  AUTO_LEARN           :   1;    //  Define whether this mirror
                                                 // packet is for auto-learn
                                                 // mirroring. When this bit is
                                                 // set, the RECIRCULATE bit must
                                                 // be set as well.
        uint64_t  METADATA_MASK0       :  16;    //  Mask value for the first
                                                 // update in Metadata. For each
                                                 // bit, set to 1 to apply new
                                                 // MetadataValue. Otherwise, set
                                                 // to 0 for no change.
        uint64_t  METADATA_VALUE0      :  16;    //  Value to be updated in the
                                                 // specified location in Metadata
                                                 // staring from the byte offset
                                                 // indicated above
        uint64_t  METADATA_BYTE_OFFSET0 :   8;    //  byte offset for starting
                                                 // byte for the first metadata
                                                 // update.
        uint64_t  METADATA_TYPE0       :   5;    //  Metadata Type for the first
                                                 // metadata update.
        uint64_t  STORE_VSI            :   1;    //  Store the original source
                                                 // VSI of the packet into PMD
        uint64_t  STORE_PORT           :   1;    //  Store the original source
                                                 // PORT of the packet into PMD
        uint64_t  RSVD_0               :   1;    // Nebulon auto filled RSVD [63:63]

    }                                field;
    uint64_t                         val;
} MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_t;
#endif
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_OFFSET 0x00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_SCOPE 0x01
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_SIZE 64
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_BITFIELD_COUNT 0x0b
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_RESET 0x1f00000000000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_MIRROR_DST_LSB 0x0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_MIRROR_DST_MSB 0x000b
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_MIRROR_DST_RANGE 0x000c
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_MIRROR_DST_MASK 0x00000fff
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_MIRROR_DST_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_TRUNC_LSB 0x000c
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_TRUNC_MSB 0x000c
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_TRUNC_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_TRUNC_MASK 0x00001000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_TRUNC_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_PRE_MOD_LSB 0x000d
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_PRE_MOD_MSB 0x000d
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_PRE_MOD_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_PRE_MOD_MASK 0x00002000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_PRE_MOD_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_RECIRCULATE_LSB 0x000e
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_RECIRCULATE_MSB 0x000e
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_RECIRCULATE_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_RECIRCULATE_MASK 0x00004000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_RECIRCULATE_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_AUTO_LEARN_LSB 0x000f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_AUTO_LEARN_MSB 0x000f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_AUTO_LEARN_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_AUTO_LEARN_MASK 0x00008000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_AUTO_LEARN_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_MASK0_LSB 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_MASK0_MSB 0x001f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_MASK0_RANGE 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_MASK0_MASK 0xffff0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_MASK0_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_VALUE0_LSB 0x0020
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_VALUE0_MSB 0x002f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_VALUE0_RANGE 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_VALUE0_MASK 0xffff00000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_VALUE0_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_BYTE_OFFSET0_LSB 0x0030
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_BYTE_OFFSET0_MSB 0x0037
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_BYTE_OFFSET0_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_BYTE_OFFSET0_MASK 0xff000000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_BYTE_OFFSET0_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_TYPE0_LSB 0x0038
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_TYPE0_MSB 0x003c
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_TYPE0_RANGE 0x0005
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_TYPE0_MASK 0x1f00000000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_METADATA_TYPE0_RESET_VALUE 0x0000001f

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_STORE_VSI_LSB 0x003d
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_STORE_VSI_MSB 0x003d
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_STORE_VSI_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_STORE_VSI_MASK 0x2000000000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_STORE_VSI_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_STORE_PORT_LSB 0x003e
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_STORE_PORT_MSB 0x003e
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_STORE_PORT_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_STORE_PORT_MASK 0x4000000000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_STORE_PORT_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

#ifndef MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_FLAG
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_FLAG
// MOD_MIRROR_PROFILE_TABLE1 desc:  Defines mirror profiles in modify.
typedef union {
    struct {
        uint64_t  METADATA_MASK1       :  16;    //  Mask value for the second
                                                 // update in Metadata. For each
                                                 // bit, set to 1 to apply new
                                                 // MetadataValue. Otherwise, set
                                                 // to 0 for no change.
        uint64_t  METADATA_VALUE1      :  16;    //  Value to be updated in the
                                                 // specified location in Metadata
                                                 // staring from the byte offset
                                                 // indicated above
        uint64_t  METADATA_BYTE_OFFSET1 :   8;    //  byte offset for starting
                                                 // byte for the second metadata
                                                 // update.
        uint64_t  METADATA_TYPE1       :   5;    //  Metadata Type for the second
                                                 // metadata update.
        uint64_t  RSVD_0               :  19;    // Nebulon auto filled RSVD [63:45]

    }                                field;
    uint64_t                         val;
} MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_t;
#endif
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_OFFSET 0x00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_SCOPE 0x01
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_SIZE 64
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_BITFIELD_COUNT 0x04
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_RESET 0x1f0000000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_MASK1_LSB 0x0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_MASK1_MSB 0x000f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_MASK1_RANGE 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_MASK1_MASK 0x0000ffff
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_MASK1_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_VALUE1_LSB 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_VALUE1_MSB 0x001f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_VALUE1_RANGE 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_VALUE1_MASK 0xffff0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_VALUE1_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_BYTE_OFFSET1_LSB 0x0020
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_BYTE_OFFSET1_MSB 0x0027
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_BYTE_OFFSET1_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_BYTE_OFFSET1_MASK 0xff00000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_BYTE_OFFSET1_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_TYPE1_LSB 0x0028
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_TYPE1_MSB 0x002c
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_TYPE1_RANGE 0x0005
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_TYPE1_MASK 0x1f0000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_METADATA_TYPE1_RESET_VALUE 0x0000001f


// --------------------------------------------------------------------------------------------------------------------------------

#ifndef MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FLAG
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FLAG
// MOD_MIRROR_PROFILE_TABLE2 desc:  Defines mirror profiles in modify.
typedef union {
    struct {
        uint64_t  FUNCTION_NUM         :  12;    //  Function Number
        uint64_t  FUNCTION_TYPE        :   2;    //  Function Type: *00: Virtual
                                                 // Function *01: Virtual
                                                 // Device/Virtual Machine *10:
                                                 // Physical Function *11:
                                                 // Managemeability (EMP)
        uint64_t  _RSVD0_              :   2;    //  Reserved bits
        uint64_t  PF_NUM               :   6;    //  Physical Function Number
        uint64_t  _RSVD1_              :   1;    //  Reserved bits
        uint64_t  FUNC_VALID           :   1;    //  Function Valid
        uint64_t  DST_Q                :  14;    //  Destination Queue. For
                                                 // Mirror Copy to Local Host
                                                 // (MIRROR_DST = VSI Type), the
                                                 // DST_Q will be used to update
                                                 // HostInfoRx.DST_Q or
                                                 // Common.Generic.
        uint64_t  RSVD_0               :  26;    // Nebulon auto filled RSVD [63:38]

    }                                field;
    uint64_t                         val;
} MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_t;
#endif
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_OFFSET 0x00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_SCOPE 0x01
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_SIZE 64
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_BITFIELD_COUNT 0x07
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_RESET 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNCTION_NUM_LSB 0x0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNCTION_NUM_MSB 0x000b
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNCTION_NUM_RANGE 0x000c
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNCTION_NUM_MASK 0x00000fff
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNCTION_NUM_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNCTION_TYPE_LSB 0x000c
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNCTION_TYPE_MSB 0x000d
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNCTION_TYPE_RANGE 0x0002
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNCTION_TYPE_MASK 0x00003000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNCTION_TYPE_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2__RSVD0__LSB 0x000e
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2__RSVD0__MSB 0x000f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2__RSVD0__RANGE 0x0002
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2__RSVD0__MASK 0x0000c000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2__RSVD0__RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_PF_NUM_LSB 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_PF_NUM_MSB 0x0015
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_PF_NUM_RANGE 0x0006
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_PF_NUM_MASK 0x003f0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_PF_NUM_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2__RSVD1__LSB 0x0016
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2__RSVD1__MSB 0x0016
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2__RSVD1__RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2__RSVD1__MASK 0x00400000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2__RSVD1__RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNC_VALID_LSB 0x0017
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNC_VALID_MSB 0x0017
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNC_VALID_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNC_VALID_MASK 0x00800000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_FUNC_VALID_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_DST_Q_LSB 0x0018
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_DST_Q_MSB 0x0025
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_DST_Q_RANGE 0x000e
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_DST_Q_MASK 0x3fff000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_DST_Q_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

#ifndef MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_FLAG
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_FLAG
// MOD_MAP_CFG desc:  Defines the mapping input configuration for corresponding MOD_MAP
// lookup table. In direct mode, the first 16b of field data is the
// starting IDX value. The IDX is first shifted and then masked, and the
// result is the final index. In relative mode, the first 16b is the
// IDX, and next 16b is the BASE. Separately, both fields are shifted
// and then masked. The final index is the sum of the masked BASE and
// masked IDX. Upper bits of the final index that exceed the input to
// the lookup table will be ignored.
typedef union {
    struct {
        uint64_t  IDX_SHIFT_RIGHT      :   4;    //  This field indicates the
                                                 // number of bits of the IDX
                                                 // field to shift right.
        uint64_t  IDX_MASK_LEN         :   4;    //  This field indicates the bit
                                                 // length of the mask, starting
                                                 // from bit 0, that is applied
                                                 // to the shifted IDX. Bits
                                                 // outside of the mask will be
                                                 // zeroed out.
        uint64_t  BASE_SHIFT_RIGHT     :   4;    //  This field indicates the
                                                 // number of bits of the BASE
                                                 // field to shift right.
        uint64_t  BASE_MASK_LEN        :   4;    //  This field indicates the bit
                                                 // length of the mask, starting
                                                 // from bit 0, that is applied
                                                 // to the shifted BASE. Bits
                                                 // outside of the mask will be
                                                 // zeroed out.
        uint64_t  OUTPUT_MASK          :  16;    //  This field represents the
                                                 // output bitmask for the lookup
                                                 // result. Only asserted bits
                                                 // will have the lookup result
                                                 // transferred to the packet.
        uint64_t  OUTPUT_SHIFT         :   4;    //  This field represents the
                                                 // output shift for the lookup
                                                 // result. The lookup result
                                                 // will be shifted left by this
                                                 // many bits before transferring
                                                 // into the packet.
        uint64_t  RSVD_0               :  28;    // Nebulon auto filled RSVD [63:36]

    }                                field;
    uint64_t                         val;
} MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_t;
#endif
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_OFFSET 0x00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_SCOPE 0x01
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_SIZE 64
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_BITFIELD_COUNT 0x06
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_RESET 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_IDX_SHIFT_RIGHT_LSB 0x0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_IDX_SHIFT_RIGHT_MSB 0x0003
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_IDX_SHIFT_RIGHT_RANGE 0x0004
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_IDX_SHIFT_RIGHT_MASK 0x0000000f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_IDX_SHIFT_RIGHT_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_IDX_MASK_LEN_LSB 0x0004
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_IDX_MASK_LEN_MSB 0x0007
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_IDX_MASK_LEN_RANGE 0x0004
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_IDX_MASK_LEN_MASK 0x000000f0
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_IDX_MASK_LEN_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_BASE_SHIFT_RIGHT_LSB 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_BASE_SHIFT_RIGHT_MSB 0x000b
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_BASE_SHIFT_RIGHT_RANGE 0x0004
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_BASE_SHIFT_RIGHT_MASK 0x00000f00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_BASE_SHIFT_RIGHT_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_BASE_MASK_LEN_LSB 0x000c
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_BASE_MASK_LEN_MSB 0x000f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_BASE_MASK_LEN_RANGE 0x0004
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_BASE_MASK_LEN_MASK 0x0000f000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_BASE_MASK_LEN_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_OUTPUT_MASK_LSB 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_OUTPUT_MASK_MSB 0x001f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_OUTPUT_MASK_RANGE 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_OUTPUT_MASK_MASK 0xffff0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_OUTPUT_MASK_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_OUTPUT_SHIFT_LSB 0x0020
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_OUTPUT_SHIFT_MSB 0x0023
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_OUTPUT_SHIFT_RANGE 0x0004
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_OUTPUT_SHIFT_MASK 0xf00000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_OUTPUT_SHIFT_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

#ifndef MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_FLAG
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_FLAG
// MOD_MAP_DUAL_CFG desc:  Defines the mapping input configuration for the MOD_MAP_DUAL lookup
// table. The first 16b of field data is the IDX0, and the next 8b is
// IDX1. After shifting and masking the indices, MOD_MAP_DUAL is
// accessed by [IDX0][IDX1]. Upper bits of the indices that exceed the
// inputs to the lookup tables will be ignored.
typedef union {
    struct {
        uint64_t  IDX0_SHIFT_RIGHT     :   4;    //  This field indicates the
                                                 // number of bits of the IDX0
                                                 // field to shift right.
        uint64_t  IDX0_MASK_LEN        :   4;    //  This field indicates the bit
                                                 // length of the mask, starting
                                                 // from bit 0, that is applied
                                                 // to the shifted IDX0. Bits
                                                 // outside of the mask will be
                                                 // zeroed out.
        uint64_t  IDX1_SHIFT_RIGHT     :   3;    //  This field indicates the
                                                 // number of bits of the IDX1
                                                 // field to shift right.
        uint64_t  IDX1_MASK_LEN        :   3;    //  This field indicates the bit
                                                 // length of the mask, starting
                                                 // from bit 0, that is applied
                                                 // to the shifted IDX1. Bits
                                                 // outside of the mask will be
                                                 // zeroed out.
        uint64_t  OUTPUT_MASK          :  16;    //  This field represents the
                                                 // output bitmask for the lookup
                                                 // result. Only asserted bits
                                                 // will have the lookup result
                                                 // transferred to the packet.
        uint64_t  OUTPUT_SHIFT         :   4;    //  This field represents the
                                                 // output shift for the lookup
                                                 // result. The lookup result
                                                 // will be shifted left by this
                                                 // many bits before transferring
                                                 // into the packet.
        uint64_t  RSVD_0               :  30;    // Nebulon auto filled RSVD [63:34]

    }                                field;
    uint64_t                         val;
} MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_t;
#endif
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_OFFSET 0x20
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_SCOPE 0x01
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_SIZE 64
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_BITFIELD_COUNT 0x06
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_RESET 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX0_SHIFT_RIGHT_LSB 0x0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX0_SHIFT_RIGHT_MSB 0x0003
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX0_SHIFT_RIGHT_RANGE 0x0004
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX0_SHIFT_RIGHT_MASK 0x0000000f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX0_SHIFT_RIGHT_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX0_MASK_LEN_LSB 0x0004
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX0_MASK_LEN_MSB 0x0007
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX0_MASK_LEN_RANGE 0x0004
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX0_MASK_LEN_MASK 0x000000f0
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX0_MASK_LEN_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX1_SHIFT_RIGHT_LSB 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX1_SHIFT_RIGHT_MSB 0x000a
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX1_SHIFT_RIGHT_RANGE 0x0003
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX1_SHIFT_RIGHT_MASK 0x00000700
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX1_SHIFT_RIGHT_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX1_MASK_LEN_LSB 0x000b
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX1_MASK_LEN_MSB 0x000d
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX1_MASK_LEN_RANGE 0x0003
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX1_MASK_LEN_MASK 0x00003800
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_IDX1_MASK_LEN_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_OUTPUT_MASK_LSB 0x000e
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_OUTPUT_MASK_MSB 0x001d
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_OUTPUT_MASK_RANGE 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_OUTPUT_MASK_MASK 0x3fffc000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_OUTPUT_MASK_RESET_VALUE 0x00000000

#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_OUTPUT_SHIFT_LSB 0x001e
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_OUTPUT_SHIFT_MSB 0x0021
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_OUTPUT_SHIFT_RANGE 0x0004
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_OUTPUT_SHIFT_MASK 0x3c0000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_OUTPUT_SHIFT_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

#ifndef MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_FLAG
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_FLAG
// MOD_CSUM_CFG1 desc: 
typedef union {
    struct {
        uint64_t  IPV4_0               :   8;    //  Protocol ID of the depth-0
                                                 // IPv4 header.
        uint64_t  IPV4_1               :   8;    //  Protocol ID of the depth-1
                                                 // IPv4 header.
        uint64_t  IPV4_2               :   8;    //  Protocol ID of the depth-2
                                                 // IPv4 header.
        uint64_t  IPV6_0               :   8;    //  Protocol ID of the depth-0
                                                 // IPv6 header.
        uint64_t  IPV6_1               :   8;    //  Protocol ID of the depth-1
                                                 // IPv6 header.
        uint64_t  IPV6_2               :   8;    //  Protocol ID of the depth-2
                                                 // IPv6 header.
        uint64_t  RSVD_0               :  16;    // Nebulon auto filled RSVD [63:48]

    }                                field;
    uint64_t                         val;
} MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_t;
#endif
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_OFFSET 0x28
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_SCOPE 0x01
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_SIZE 64
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_BITFIELD_COUNT 0x06
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_RESET 0xffffffffffff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_0_LSB 0x0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_0_MSB 0x0007
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_0_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_0_MASK 0x000000ff
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_0_RESET_VALUE 0x000000ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_1_LSB 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_1_MSB 0x000f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_1_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_1_MASK 0x0000ff00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_1_RESET_VALUE 0x000000ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_2_LSB 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_2_MSB 0x0017
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_2_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_2_MASK 0x00ff0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV4_2_RESET_VALUE 0x000000ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_0_LSB 0x0018
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_0_MSB 0x001f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_0_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_0_MASK 0xff000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_0_RESET_VALUE 0x000000ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_1_LSB 0x0020
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_1_MSB 0x0027
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_1_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_1_MASK 0xff00000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_1_RESET_VALUE 0x000000ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_2_LSB 0x0028
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_2_MSB 0x002f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_2_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_2_MASK 0xff0000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_IPV6_2_RESET_VALUE 0x000000ff


// --------------------------------------------------------------------------------------------------------------------------------

#ifndef MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_FLAG
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_FLAG
// MOD_CSUM_CFG2 desc: 
typedef union {
    struct {
        uint64_t  UDP_0                :   8;    //  Protocol ID of the depth-0
                                                 // UDP header.
        uint64_t  UDP_1                :   8;    //  Protocol ID of the depth-1
                                                 // UDP header.
        uint64_t  UDP_2                :   8;    //  Protocol ID of the depth-1
                                                 // UDP header.
        uint64_t  TCP_0                :   8;    //  Protocol ID of the depth-0
                                                 // TCP header.
        uint64_t  TCP_1                :   8;    //  Protocol ID of the depth-1
                                                 // TCP header.
        uint64_t  TCP_2                :   8;    //  Protocol ID of the depth-1
                                                 // TCP header.
        uint64_t  SCTP                 :   8;    //  Protocol ID of the SCTP
                                                 // header.
        uint64_t  RSVD_0               :   8;    // Nebulon auto filled RSVD [63:56]

    }                                field;
    uint64_t                         val;
} MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_t;
#endif
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_OFFSET 0x30
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_SCOPE 0x01
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_SIZE 64
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_BITFIELD_COUNT 0x07
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_RESET 0xffffffffffffff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_0_LSB 0x0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_0_MSB 0x0007
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_0_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_0_MASK 0x000000ff
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_0_RESET_VALUE 0x000000ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_1_LSB 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_1_MSB 0x000f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_1_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_1_MASK 0x0000ff00
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_1_RESET_VALUE 0x000000ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_2_LSB 0x0010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_2_MSB 0x0017
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_2_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_2_MASK 0x00ff0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_UDP_2_RESET_VALUE 0x000000ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_0_LSB 0x0018
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_0_MSB 0x001f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_0_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_0_MASK 0xff000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_0_RESET_VALUE 0x000000ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_1_LSB 0x0020
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_1_MSB 0x0027
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_1_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_1_MASK 0xff00000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_1_RESET_VALUE 0x000000ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_2_LSB 0x0028
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_2_MSB 0x002f
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_2_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_2_MASK 0xff0000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_TCP_2_RESET_VALUE 0x000000ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_SCTP_LSB 0x0030
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_SCTP_MSB 0x0037
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_SCTP_RANGE 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_SCTP_MASK 0xff000000000000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_SCTP_RESET_VALUE 0x000000ff


// --------------------------------------------------------------------------------------------------------------------------------

#ifndef MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_FLAG
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_FLAG
// MOD_CSUM_EN_CFG desc:  Provides Enable Config for Rx Checksum regneration
typedef union {
    struct {
        uint64_t  D0_IPV4_EN           :   1;    //  Checksum Computation Enable
                                                 // for the depth-0 IPV4 header.
        uint64_t  D1_IPV4_EN           :   1;    //  Checksum Computation Enable
                                                 // for the depth-1 IPV4 header.
        uint64_t  D2_IPV4_EN           :   1;    //  Checksum Computation Enable
                                                 // for the depth-2 IPV4 header.
        uint64_t  D0_IPV6_EN           :   1;    //  Checksum Computation Enable
                                                 // for the depth-0 IPV6 header.
        uint64_t  D1_IPV6_EN           :   1;    //  Checksum Computation Enable
                                                 // for the depth-1 IPV6 header.
        uint64_t  D2_IPV6_EN           :   1;    //  Checksum Computation Enable
                                                 // for the depth-2 IPV6 header.
        uint64_t  D0_UDP_EN            :   1;    //  Checksum Computation Enable
                                                 // for the depth-0 UDP.
        uint64_t  D1_UDP_EN            :   1;    //  Checksum Computation Enable
                                                 // for the depth-1 UDP.
        uint64_t  D0_TCP_EN            :   1;    //  Checksum Computation Enable
                                                 // for the Depth-0 TCP.
        uint64_t  D1_TCP_EN            :   1;    //  Checksum Computation Enable
                                                 // for the depth-1 TCP.
        uint64_t  SCTP_EN              :   1;    //  Checksum Computation Enable
                                                 // for the SCTP.
        uint64_t  RSVD_0               :  53;    // Nebulon auto filled RSVD [63:11]

    }                                field;
    uint64_t                         val;
} MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_t;
#endif
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_OFFSET 0x38
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_SCOPE 0x01
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_SIZE 64
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_BITFIELD_COUNT 0x0b
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_RESET 0x000007ff

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_IPV4_EN_LSB 0x0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_IPV4_EN_MSB 0x0000
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_IPV4_EN_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_IPV4_EN_MASK 0x00000001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_IPV4_EN_RESET_VALUE 0x00000001

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_IPV4_EN_LSB 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_IPV4_EN_MSB 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_IPV4_EN_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_IPV4_EN_MASK 0x00000002
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_IPV4_EN_RESET_VALUE 0x00000001

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D2_IPV4_EN_LSB 0x0002
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D2_IPV4_EN_MSB 0x0002
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D2_IPV4_EN_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D2_IPV4_EN_MASK 0x00000004
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D2_IPV4_EN_RESET_VALUE 0x00000001

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_IPV6_EN_LSB 0x0003
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_IPV6_EN_MSB 0x0003
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_IPV6_EN_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_IPV6_EN_MASK 0x00000008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_IPV6_EN_RESET_VALUE 0x00000001

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_IPV6_EN_LSB 0x0004
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_IPV6_EN_MSB 0x0004
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_IPV6_EN_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_IPV6_EN_MASK 0x00000010
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_IPV6_EN_RESET_VALUE 0x00000001

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D2_IPV6_EN_LSB 0x0005
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D2_IPV6_EN_MSB 0x0005
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D2_IPV6_EN_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D2_IPV6_EN_MASK 0x00000020
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D2_IPV6_EN_RESET_VALUE 0x00000001

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_UDP_EN_LSB 0x0006
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_UDP_EN_MSB 0x0006
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_UDP_EN_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_UDP_EN_MASK 0x00000040
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_UDP_EN_RESET_VALUE 0x00000001

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_UDP_EN_LSB 0x0007
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_UDP_EN_MSB 0x0007
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_UDP_EN_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_UDP_EN_MASK 0x00000080
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_UDP_EN_RESET_VALUE 0x00000001

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_TCP_EN_LSB 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_TCP_EN_MSB 0x0008
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_TCP_EN_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_TCP_EN_MASK 0x00000100
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D0_TCP_EN_RESET_VALUE 0x00000001

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_TCP_EN_LSB 0x0009
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_TCP_EN_MSB 0x0009
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_TCP_EN_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_TCP_EN_MASK 0x00000200
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_D1_TCP_EN_RESET_VALUE 0x00000001

#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_SCTP_EN_LSB 0x000a
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_SCTP_EN_MSB 0x000a
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_SCTP_EN_RANGE 0x0001
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_SCTP_EN_MASK 0x00000400
#define MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_SCTP_EN_RESET_VALUE 0x00000001


// --------------------------------------------------------------------------------------------------------------------------------

// starting the array instantiation section
typedef struct {
    // starting the regfile section
    struct {
        MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_COMMAND_t MOD_PROFILE_COMMAND[16]; // offset 4'h0, width 64
    } MOD_PROFILE_COMMAND[64];                   // offset 4'h0, size: 128
    // starting the regfile section
    struct {
        MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_FIELD_t MOD_PROFILE_FIELD[8]; // offset 4'h0, width 64
    } MOD_PROFILE_FIELD[64];                     // offset 16'h2000, size: 64
    uint8_t                    rsvd0[53248];
    // starting the regfile section
    struct {
        MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_t MOD_MAP_DUAL[8];  // offset 4'h0, width 64
    } MOD_MAP_DUAL[1024];                        // offset 20'h10000, size: 64
    // starting the regfile section
    struct {
        MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_t MOD_MAP[512];     // offset 4'h0, width 64
    } MOD_MAP[4];                                // offset 20'h20000, size: 4096
    MBY_PPE_MODIFY_MAP_MSG_MOD_PROFILE_GROUP_t MOD_PROFILE_GROUP[64]; // offset 20'h24000, width 64
    MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE0_t MOD_MIRROR_PROFILE_TABLE0[64]; // offset 20'h24200, width 64
    MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE1_t MOD_MIRROR_PROFILE_TABLE1[64]; // offset 20'h24400, width 64
    MBY_PPE_MODIFY_MAP_MSG_MOD_MIRROR_PROFILE_TABLE2_t MOD_MIRROR_PROFILE_TABLE2[64]; // offset 20'h24600, width 64
    MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_CFG_t MOD_MAP_CFG[4];   // offset 20'h24800, width 64
    MBY_PPE_MODIFY_MAP_MSG_MOD_MAP_DUAL_CFG_t MOD_MAP_DUAL_CFG; // offset 20'h24820, width 64
    MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG1_t MOD_CSUM_CFG1;    // offset 20'h24828, width 64
    MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_CFG2_t MOD_CSUM_CFG2;    // offset 20'h24830, width 64
    MBY_PPE_MODIFY_MAP_MSG_MOD_CSUM_EN_CFG_t MOD_CSUM_EN_CFG;  // offset 20'h24838, width 64
} mby_ppe_modify_map_t;                          // size:  20'h24840


#endif // _MBY_PPE_MODIFY_MAP_REGS_H_

