/* Copyright (c) 2025 Intel Corporation.  All rights reserved.  See the file COPYRIGHT for more information. */
/* SPDX-License-Identifier: Apache-2.0 */

//                                                                             
// File:            mby_rx_pb_map_regs.h                                       
// Creator:         solson                                                     
// Time:            Wednesday Dec 12, 2018 [10:52:09 am]                       
//                                                                             
// Path:            /tmp/solson/nebulon_run/4706538284_2018-12-12.10:40:08     
// Arguments:       -I                                                         
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/tools/srdl
//                  -sv_no_sai_checks -sverilog -xml -chdr -crif -ovm -input   
//                  mby_top_map.rdl -timeout 60000 -out_dir                    
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/target/GenRTL/regflow/mby
//                  -rtlgencomp -log_file                                      
//                  /nfs/site/disks/slx_1593/solson/mby/work_root/mby-mby-x0_WW5018a/MockTurnin/target/GenRTL/regflow/mby/nebulon_sv_output.log
//                                                                             
// MRE:             5.2018.2                                                   
// Machine:         scci79110                                                  
// OS:              Linux 3.0.101-108.13.1.14249.0.PTF-default                 
// Nebulon version: d18ww24.4                                                  
// Description:                                                                
//                                                                             
// No Description Provided                                                     
//                                                                             
// Copyright (C) 2018 Intel Corp. All rights reserved                          
// THIS FILE IS AUTOMATICALLY GENERATED BY INTEL RDL GENERATOR, DO NOT EDIT    
//                                                                             


#ifndef _MBY_RX_PB_MAP_REGS_H_
#define _MBY_RX_PB_MAP_REGS_H_

#define RX_PB_MSGPORT     0x0
#define RX_PB_RX_PB_PORT_CFG_MSGREGADDR 0x0
#define RX_PB_RX_PB_WM_MSGREGADDR 0x800

#ifndef MBY_RX_PB_MAP_MSG_RX_PB_PORT_CFG_FLAG
#define MBY_RX_PB_MAP_MSG_RX_PB_PORT_CFG_FLAG
// RX_PB_PORT_CFG desc:  Port configuration for the Rx Packet Buffer. Buffer allocation is
// derived from this configuration. The port index is N*4 + M. The port
// configuration values are: [list] [*] 0 = Disable this port. [*] 1 =
// This port is 100G, 50G, or 25G. [*] 2 = This port is 200G. Only port
// N.0 or N.2 can be 200G, and the next port must be disabled. [*] 3 =
// This port is 400G. Only port N.0 can be 400G, and the next 3 ports
// must be disabled. [/list]
typedef union {
    struct {
        uint64_t  PORT                 :  32;    //  Port configurations, the
                                                 // configuration for port i runs
                                                 // from bit 2*i to bit 2*i+1
        uint64_t  RSVD_0               :  32;    // Nebulon auto filled RSVD [63:32]

    }                                field;
    uint64_t                         val;
} MBY_RX_PB_MAP_MSG_RX_PB_PORT_CFG_t;
#endif
#define MBY_RX_PB_MAP_MSG_RX_PB_PORT_CFG_OFFSET 0x00
#define MBY_RX_PB_MAP_MSG_RX_PB_PORT_CFG_SCOPE 0x01
#define MBY_RX_PB_MAP_MSG_RX_PB_PORT_CFG_SIZE 64
#define MBY_RX_PB_MAP_MSG_RX_PB_PORT_CFG_BITFIELD_COUNT 0x01
#define MBY_RX_PB_MAP_MSG_RX_PB_PORT_CFG_RESET 0x00000000

#define MBY_RX_PB_MAP_MSG_RX_PB_PORT_CFG_PORT_LSB 0x0000
#define MBY_RX_PB_MAP_MSG_RX_PB_PORT_CFG_PORT_MSB 0x001f
#define MBY_RX_PB_MAP_MSG_RX_PB_PORT_CFG_PORT_RANGE 0x0020
#define MBY_RX_PB_MAP_MSG_RX_PB_PORT_CFG_PORT_MASK 0xffffffff
#define MBY_RX_PB_MAP_MSG_RX_PB_PORT_CFG_PORT_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

#ifndef MBY_RX_PB_MAP_MSG_RX_PB_WM_FLAG
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_FLAG
// RX_PB_WM desc:  Watermarks for pause and drop. First index is Rx logical port
// (0..17; includes virtual ports). Second index is Rx TC. The
// watermarks are compared against the total amount of header data that
// the port is using in the ingress packet buffer (data is not counted
// per TC, but each TC can have a different watermark value). If the
// port is configured to use PAUSE, then the port will be paused when any
// of its TCs is paused.
typedef union {
    struct {
        uint64_t  XOFF_OR_DROP         :  10;    //  XOFF or drop watermark. In
                                                 // lossless mode, defines total
                                                 // ingress buffer level above
                                                 // which the TC is paused. In
                                                 // lossy mode, defines total
                                                 // ingress buffer level above
                                                 // which packets are dropped. The
                                                 // value is 0..512 in units of
                                                 // 1KB.
        uint64_t  XON                  :  10;    //  Pause XON watermark. Defines
                                                 // total ingress buffer level
                                                 // below which the TC is
                                                 // unpaused. The value is 0..512
                                                 // in units of 1KB.
        uint64_t  LOSSLESS             :   1;    //  Set to indicate a lossless
                                                 // traffic class.
        uint64_t  RSVD_0               :  43;    // Nebulon auto filled RSVD [63:21]

    }                                field;
    uint64_t                         val;
} MBY_RX_PB_MAP_MSG_RX_PB_WM_t;
#endif
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_OFFSET 0x00
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_SCOPE 0x01
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_SIZE 64
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_BITFIELD_COUNT 0x03
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_RESET 0x00080200

#define MBY_RX_PB_MAP_MSG_RX_PB_WM_XOFF_OR_DROP_LSB 0x0000
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_XOFF_OR_DROP_MSB 0x0009
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_XOFF_OR_DROP_RANGE 0x000a
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_XOFF_OR_DROP_MASK 0x000003ff
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_XOFF_OR_DROP_RESET_VALUE 0x00000200

#define MBY_RX_PB_MAP_MSG_RX_PB_WM_XON_LSB 0x000a
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_XON_MSB 0x0013
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_XON_RANGE 0x000a
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_XON_MASK 0x000ffc00
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_XON_RESET_VALUE 0x00000200

#define MBY_RX_PB_MAP_MSG_RX_PB_WM_LOSSLESS_LSB 0x0014
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_LOSSLESS_MSB 0x0014
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_LOSSLESS_RANGE 0x0001
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_LOSSLESS_MASK 0x00100000
#define MBY_RX_PB_MAP_MSG_RX_PB_WM_LOSSLESS_RESET_VALUE 0x00000000


// --------------------------------------------------------------------------------------------------------------------------------

// starting the array instantiation section
typedef struct {
    MBY_RX_PB_MAP_MSG_RX_PB_PORT_CFG_t RX_PB_PORT_CFG;   // offset 4'h0, width 64
    uint8_t                    rsvd0[2040];
    // starting the regfile section
    struct {
        MBY_RX_PB_MAP_MSG_RX_PB_WM_t RX_PB_WM[8];      // offset 4'h0, width 64
    } RX_PB_WM[18];                              // offset 12'h800, size: 64
} mby_rx_pb_map_t;                               // size:  16'h0C80


#endif // _MBY_RX_PB_MAP_REGS_H_

